import type { SouthwellMinsterCopy } from "./southwellMinster"

/** fr copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_FR: SouthwellMinsterCopy = {
  "audioHint": "Là où vous voyez la commande audio ci-dessous, ainsi que dans chaque section où figure une icône audio, vous pouvez écouter le contenu tout en naviguant ou en vous déplaçant. Veuillez utiliser vos écouteurs ou vos oreillettes.",
  "eyebrow": "Nottinghamshire · Église d'Angleterre",
  "title": "Cathédrale de Southwell",
  "tagline": "La cathédrale et église paroissiale de la Bienheureuse Vierge Marie — un joyau normand des Midlands anglais, où l'on prie sans interruption depuis 627.",
  "meta": [
    "Fondée vers 627",
    "Reconstruction normande à partir de 1108",
    "Cathédrale depuis 1884"
  ],
  "welcome": {
    "invite": "Écouter le message de bienvenue du père Stephen",
    "videoUnsupported": "Votre navigateur ne prend pas en charge l'élément vidéo.",
    "placeholderLabel": "Vidéo de bienvenue — à venir",
    "role": "Le Très Révérend",
    "name": "Dr Stephen Evans",
    "title": "Doyen de la cathédrale de Southwell"
  },
  "toc": [
    {
      "href": "#history",
      "label": "Histoire"
    },
    {
      "href": "#treasures",
      "label": "Trésors et décoration d'intérieur"
    },
    {
      "href": "#officers",
      "label": "Principaux dirigeants"
    },
    {
      "href": "#music",
      "label": "Musique et chorales"
    },
    {
      "href": "#worship",
      "label": "Liturgie et offices"
    },
    {
      "href": "#visit",
      "label": "Horaires d'ouverture"
    },
    {
      "href": "#donate",
      "label": "Faire un don"
    },
    {
      "href": "#projects",
      "label": "Nos projets"
    },
    {
      "href": "#contact",
      "label": "Contact"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Un bref historique",
    "lede": "Une cathédrale se dresse à Southwell depuis bien plus de mille ans — ayant survécu aux Vikings, à la Réforme, à la guerre civile et aux incendies — et fait aujourd’hui office d’église mère du diocèse de Southwell et Nottingham.",
    "paragraphs": [
      "La tradition veut que <strong>Paulinus, premier archevêque d’York, ait fondé ici la toute première église en 627,</strong> alors qu’il baptisait des convertis dans la rivière Trent. En <strong>956,</strong> le roi Eadwig accorda des terres à Southwell à Oskytel, archevêque d’York, et une église minster saxonne y fut fondée ; le manoir fut décrit en détail dans le <em>Domesday Book</em> de 1086.",
      "La construction de l'actuelle <strong>cathédrale normande</strong> a débuté vers <strong>1108</strong>, sur les fondations anglo-saxonnes antérieures. La nef, les transepts, la tour centrale et les deux tours occidentales en forme de « pot à poivre » constituent aujourd’hui l’un des plus beaux exemples du style roman austère en Angleterre. Le <strong>chœur, de style anglo-primitif</strong>, fut reconstruit entre 1234 et 1251, et la célèbre <strong>salle capitulaire</strong> fut entamée en 1288.",
      "Supprimée par Henri VIII en <strong>1540</strong>, la collégiale fut refondée en 1543, perdit à nouveau son statut en 1548, puis fut finalement rétablie en 1557. Pendant la guerre civile, <strong>Charles Ier se rendit à Southwell en 1646</strong> après le siège de Newark. En <strong>1711,</strong> la foudre frappa la flèche sud-ouest et un incendie détruisit les toitures, les cloches, l’horloge et l’orgue ; les deux flèches furent démantelées en 1805 et ne furent reconstruites qu’entre 1879 et 1881, lors de la vaste restauration victorienne menée par Ewan Christian.",
      "La Minster est devenue une <strong>cathédrale en 1884</strong>, lors de la création du nouveau diocèse de Southwell, destiné à desservir le Nottinghamshire et le Derbyshire (Derby devenant un diocèse distinct en 1927). Elle reste dédiée à la Sainte Vierge Marie et, fait unique parmi les cathédrales anglaises, conserve son ancien titre de « <em>Minster</em> »."
    ],
    "figureAlt": "La grande fenêtre ouest de la cathédrale de Southwell, encadrée par les deux tours normandes en forme de « pot à poivre ».",
    "figureCaption": "La façade ouest de style normand, avec ses tours caractéristiques en forme de « poivrière » et le vitrail « L'Ange », réalisé en 1996 par Patrick Reyntiens.",
    "timelineLabel": "Chronologie de la cathédrale de Southwell",
    "timeline": [
      {
        "year": "627",
        "text": "Paulinus, premier archevêque d'York, à qui l'on attribue la fondation d'une église à Southwell."
      },
      {
        "year": "956",
        "text": "Le roi Eadwig accorde des terres à l'archevêque Oskytel ; une cathédrale saxonne est fondée."
      },
      {
        "year": "1108",
        "text": "La reconstruction de l'église normande a commencé à l'extrémité est ; la nef a été mise en chantier après 1120."
      },
      {
        "year": "1234–51",
        "text": "Le cahier de chants de l'époque anglo-normande a été reconstitué."
      },
      {
        "year": "1288",
        "text": "Début de la construction de la salle capitulaire octogonale."
      },
      {
        "year": "1320–40",
        "text": "Le grand « pulpitum » (cloître) en pierre est sculpté dans le style décoré."
      },
      {
        "year": "1540–57",
        "text": "Supprimée sous Henri VIII, rétablie sous Philippe et Marie."
      },
      {
        "year": "1646",
        "text": "Charles Ier se rend aux troupes presbytériennes écossaises à Southwell."
      },
      {
        "year": "1711",
        "text": "Un coup de foudre ; l'incendie détruit les toits, les cloches, l'horloge et l'orgue."
      },
      {
        "year": "1879–81",
        "text": "Restauration de l'église Ewan Christian ; les flèches ouest ont été remises en place."
      },
      {
        "year": "1884",
        "text": "La cathédrale de Southwell devient la cathédrale du nouveau diocèse."
      },
      {
        "year": "1996",
        "text": "La magnifique « Fenêtre des anges » de Patrick Reyntiens, installée à l'extrémité ouest."
      },
      {
        "year": "2021",
        "text": "La salle capitulaire rouvre ses portes après d'importants travaux de restauration, dotée d'un ascenseur en porte-à-faux garantissant une accessibilité totale."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Trésors et lieux d'intérêt",
    "lede": "Des plus belles sculptures médiévales sur bois d'Angleterre à un vitrail flamand du XVIe siècle donnant sur l'est, la cathédrale regorge d'éléments qui méritent qu'on s'y attarde.",
    "leavesHeading": "Les feuilles de Southwell",
    "leavesBody": "La <strong>salle capitulaire</strong> (dont la construction a débuté en 1288) est octogonale, dépourvue de pilier central, et ornée de sculptures végétales profondément creusées, connues sous <strong>le</strong> <strong>nom</strong> collectif <strong>de</strong> <strong>« Feuilles de Southwell ».</strong> On peut y distinguer différentes espèces — lierre, érable, chêne, houblon, aubépine —, entremêlées de « Green Men » et de figures mythologiques. Considérées comme les plus belles sculptures naturalistes du XIIIe siècle au Royaume-Uni, elles ont fait l’objet de la monographie classique de Nikolaus Pevsner publiée en 1945 et ont été élues « trésor de cathédrale préféré des Britanniques » lors d’un sondage public réalisé en 2023.",
    "figureAlt": "Sculptures naturalistes de feuilles datant du XIIIe siècle, ornant l'entrée de la salle capitulaire de la cathédrale de Southwell.",
    "figureCaption": "« Les Feuilles de Southwell » — des sculptures de feuillage datant du XIIIe siècle qui ornent le portail de la salle capitulaire, élues « trésor de cathédrale préféré des Britanniques » en 2023.",
    "features": [
      {
        "heading": "La nef normande",
        "body": "Sept travées soutenues par des colonnes courtes et circulaires aux chapiteaux festonnés ; une seule grande arche de triforium dans chaque travée ; de petites fenêtres de claire-voie en plein cintre et des ouvertures extérieures circulaires — l’un des plus remarquables exemples encore existants du style roman anglais austère."
      },
      {
        "heading": "Le tympan",
        "body": "Le tympan sculpté datant de la fin du XIe siècle, situé dans le transept nord, ainsi qu'un fragment de sol en mosaïque, constituent les seuls vestiges visibles de l'ancienne cathédrale anglo-saxonne."
      },
      {
        "heading": "Le pulpitum (cloison du chœur)",
        "body": "Une cloison de chœur en pierre finement sculptée, datant de 1320-1340, qui constitue un exemple remarquable du style décoré, avec deux rangées de niches à arc en ogive et des pignons ajourés encadrant l'entrée du chœur."
      },
      {
        "heading": "Le chœur Early English",
        "body": "Reconstruite entre 1234 et 1251 dans un style typiquement « Early English » : colonnes groupées, fenêtres en ogive jumelées à l’étage supérieur, voûte en pierres nervurées et une abside carrée éclairée par deux rangées de quatre fenêtres en ogive."
      },
      {
        "heading": "La fenêtre est",
        "body": "Quatre panneaux de la Renaissance en vitrail flamand du XVIe siècle, réalisés par Jean Chastellain d’après des dessins de Noël Bellemare, initialement destinés à l’église du Temple à Paris et offerts à la cathédrale en 1818 ; les quatre évangélistes représentés ci-dessus sont l’œuvre de Clayton & Bell (1876)."
      },
      {
        "heading": "La fenêtre des anges",
        "body": "Installé à l'extrémité ouest en <strong>1996</strong>, ce magnifique vitrail moderne signé <strong>Patrick Reyntiens</strong> — l'un des plus grands artistes britanniques spécialisés dans l'art du vitrail — constitue l'ajout récent le plus remarquable de la cathédrale."
      },
      {
        "heading": "Tombe de l'archevêque Sandys",
        "body": "Le plus beau des monuments commémoratifs de la cathédrale : le tombeau en albâtre d’<strong>Edwin Sandys, archevêque d’York (décédé en 1588)</strong>, dont la famille a longtemps possédé des domaines dans le Nottinghamshire."
      },
      {
        "heading": "Le pupitre de Newstead",
        "body": "Un lutrin médiéval en laiton en forme d'aigle, qui aurait été repêché dans le lac de l'abbaye de Newstead après la Dissolution et offert à la cathédrale par l'archidiacre Kaye en 1805."
      },
      {
        "heading": "La tour centrale normande",
        "body": "Deux niveaux décoratifs — des arcs entrecroisés en bas, des arcs simples en haut — placent cette tour de croisement parmi les plus hautes des tours normandes encore debout en Angleterre."
      },
      {
        "heading": "Chapelles de prière",
        "body": "Trois chapelles sont réservées à la prière privée, notamment <strong>la chapelle Saint-Oswald</strong> (où sont célébrées chaque jour la prière du matin et la Sainte Communion) et la <strong>chapelle des aviateurs</strong>, dédiée à la mémoire du Bomber Command de la RAF dans le Nottinghamshire."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Principaux dirigeants",
    "lede": "La cathédrale de Southwell est dirigée par son <strong>chapitre</strong>, présidé par le doyen, avec le soutien et sous la supervision du Conseil de la cathédrale et du Collège des chanoines dans son ensemble. Vous trouverez ci-dessous la liste des principaux responsables telle qu'elle est actuellement publiée par la cathédrale.",
    "people": [
      {
        "role": "Évêque de Southwell et Nottingham",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "Le doyen",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Chanoine chantre",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Membre du comité exécutif de la section locale",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Membre du comité exécutif de la section locale",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Membre non exécutif senior",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Rector Chori (directeur musical)",
        "name": "Paul Provost"
      },
      {
        "role": "Directeur adjoint de la musique",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Verger en chef",
        "name": "Andrew Todd"
      }
    ],
    "note": "Parmi les membres non exécutifs du Chapitre figurent également M. Andrew Corner, M. Nick Alexander, Mme Ann Carter-Gray, Mme Marion Oswald, M. David Walker et M. Jonathan Wheeler. La cathédrale emploie également un directeur des opérations et un directeur financier, ainsi qu’environ 32 employés et quelque 300 bénévoles."
  },
  "music": {
    "num": "IV.",
    "heading": "Fondation musicale et chorales",
    "lede": "Une chorale chante à Southwell depuis plus de neuf cents ans — une tradition ininterrompue de culte choral qui s'étend des « Vicars Choral » du Moyen Âge à la chorale actuelle de la cathédrale, composée de jeunes choristes, de choristes professionnels laïcs et de la chorale bénévole « Minster Chorale ».",
    "songHeading": "Neuf siècles de chanson",
    "songParagraphs": [
      "La vie musicale de la cathédrale a débuté avec un collège de <strong>vicaires choraux</strong>, qui résidaient dans les bâtiments situés à l'emplacement de l'actuelle Vicars' Court. Un ou deux d’entre eux étaient désignés sous le titre de « <strong>Rector Chori</strong> » — « chef de chœur » —, un titre mentionné pour la première fois officiellement à Southwell en <strong>1499</strong> et qui désigne encore aujourd’hui le directeur musical. Des enfants de chœur vinrent s’ajouter aux vicaires choraux, et ces derniers furent progressivement remplacés par des chanteurs laïcs — les « <strong>Lay Clerks</strong> » —, donnant ainsi au chœur la forme qu’il a essentiellement conservée jusqu’à aujourd’hui.",
      "En <strong>2005,</strong> une chorale de filles a été fondée par le directeur musical adjoint de l’époque. Elle a été pleinement intégrée à la chorale de la cathédrale en <strong>2019</strong> ; aujourd’hui, les choristes, garçons et filles, jouissent <strong>d’une parité totale</strong> : ils partagent les offices, les vêtements liturgiques (soutane et surplis), les tranches d’âge et le titre — tous sont simplement appelés « choristes de la cathédrale ». En <strong>2021,</strong> Southwell a nommé sa <strong>toute première chef de chœur féminine</strong> en mille ans d’histoire de la cathédrale, et en 2025, celle-ci a célébré le vingtième anniversaire de la chorale de jeunes filles."
    ],
    "figureAlt": "La chaire médiévale en pierre de la cathédrale de Southwell, surmontée de l'orgue Nicholson.",
    "figureCaption": "Le pulpitum surmonté de l'orgue principal Nicholson, dans son buffet Caröe.",
    "choirsHeading": "Les chorales aujourd'hui",
    "features": [
      {
        "heading": "Chœur de jeunes garçons",
        "body": "La ligne des aigus traditionnelle, issue de l'école The Minster School. Les garçons chantent généralement seuls lors des vêpres du lundi et du mardi, puis se joignent aux Lay Clerks du jeudi au dimanche pendant la période scolaire, en alternance avec les filles."
      },
      {
        "heading": "Chanteuses de chorale",
        "body": "Fondé en 2005, ce chœur compte désormais des partenaires à part entière au sein de la chorale de la cathédrale — environ 18 filles à l'heure actuelle, qui partagent toutes les tâches de choristes, les répétitions, les tournées et les enregistrements sur un pied d'égalité avec les garçons."
      },
      {
        "heading": "Laïcs",
        "body": "Six choristes laïcs professionnels et six choristes laïcs auxiliaires — les voix d'alto, de ténor et de basse adultes, descendants directs des vicaires choraux du Moyen Âge. Ils chantent avec les choristes du jeudi au dimanche ainsi que les jours de fête."
      },
      {
        "heading": "La chorale de la cathédrale",
        "body": "Fondée en <strong>1994</strong>, cette chorale bénévole d'adultes, composée de trente chanteurs au maximum sélectionnés sur audition, est dirigée par le directeur musical adjoint. Elle intervient lors des offices lorsque la chorale de la cathédrale est en congé, ainsi que lors des matines dominicales mensuelles."
      },
      {
        "heading": "L'école Minster",
        "body": "Tous les choristes sont scolarisés à <strong>la Minster School</strong>, une académie de l'Église d'Angleterre dotée d'un cycle élémentaire (de la 3e à la 6e année) spécialisé dans la musique et membre de l'Association des écoles de chorale."
      },
      {
        "heading": "Société chorale de Southwell",
        "body": "Une chorale communautaire ouverte à tous, sans audition préalable, qui existe depuis plus de soixante ans et se répète chaque semaine à la cathédrale pendant la période scolaire — la communauté musicale au sens large qui se rassemble autour de la fondation."
      }
    ],
    "organsHeading": "Les orgues",
    "organsBody": "L’orgue principal de la cathédrale trône sur le « pulpitum » médiéval, dans un buffet en chêne conçu par <strong>W. D. Caröe</strong>. L’orgue de chœur actuel a été reconstruit au cours des années 1990 par d’éminents facteurs d’orgues (sous la direction de John Norman, Stephen Bicknell et Ian Bell), le buffet de Caröe ayant été conservé pour des raisons historiques. Un <strong>orgue de nef</strong> distinct, dont l’origine remonte à un instrument de 1662 fabriqué par « M. Derbie » et réparé après le grand incendie de 1711, accompagne les chants de l’assemblée à l’extrémité ouest, tandis qu’un bel <strong>orgue de chambre</strong> est utilisé pour le continuo et les liturgies de moindre envergure. Un livret illustré de 72 pages, intitulé <em>*The Organs of Southwell Minster*</em> et rédigé par l’ancien recteur de chœur Paul Hale, est disponible à la boutique de la cathédrale."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturgie et offices quotidiens",
    "lede": "Le programme quotidien de prières de la cathédrale suit le modèle du « Common Worship » de l’Église d’Angleterre, animé pendant l’année scolaire par l’une des fondations de musique cathédrale les plus prestigieuses du pays.",
    "paragraphs": [
      "Southwell observe l'<strong>office quotidien</strong> complet <strong>d'une cathédrale anglicane</strong> : la prière du matin, la Sainte Communion (l'Eucharistie) et la prière du soir ou « Evensong » sont célébrées chaque jour. La plupart des jours, pendant les périodes scolaires, les offices choraux sont chantés par le <strong>chœur de la cathédrale</strong> — composé des enfants de chœur, des choristes et des chantres laïcs — qui, à eux tous, assurent l’accompagnement musical de huit offices choraux par semaine. Le dimanche, les choristes, garçons et filles, chantent l’Eucharistie et les Vêpres en alternance avec les chantres laïcs. D’autres offices sont assurés par la <strong>Minster Chorale</strong>, un chœur de chambre comptant jusqu’à trente chanteurs bénévoles, fondé en 1994.",
      "<strong>La messe dominicale à la cathédrale (10 h)</strong> et <strong>les vêpres dominicales (15 h 30)</strong> sont diffusées en direct et restent disponibles en ligne pendant respectivement une semaine et un jour. Les visiteurs de toutes confessions sont chaleureusement les bienvenus ; l’entrée est gratuite."
    ],
    "figureAlt": "Le chœur de la cathédrale de Southwell, vu vers l'est, montrant les stalles médiévales et la voûte en pierre.",
    "figureCaption": "La chapelle Early English, où sont chantés les vêpres en chœur presque tous les jours pendant le trimestre.",
    "weekdayHeading": "Rythme des jours de la semaine",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Prière du matin — <em>Chapelle Saint-Oswald</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Sainte Communion — <em>Église Saint-Oswald / Chapelle des aviateurs</em> <br /><small>(les samedis à 9 h)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Vêpres chorales — <em>The Quire</em><br /> <small>(récitées le mercredi ; chantées les lundis, mardis, jeudis, vendredis et samedis pendant la période scolaire)</small>"
      }
    ],
    "sundayHeading": "Programme du dimanche",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Sainte Communion (Livre de prières commun, célébrée)"
      },
      {
        "clock": "10.00am",
        "detail": "Eucharistie chantée à la cathédrale — <em>diffusée en direct</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Vêpres chorales — <em>diffusées en direct</em>"
      }
    ],
    "timesNote": "<em>Les horaires des offices peuvent varier les jours de fête et pendant les vacances scolaires — veuillez consulter le calendrier des offices sur le site Internet de la cathédrale avant de vous y rendre.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Horaires d'ouverture",
    "lede": "La cathédrale est ouverte aux visiteurs tous les jours de l'année, gratuitement. Les dons destinés à son entretien sont les bienvenus.",
    "cards": [
      {
        "heading": "La cathédrale",
        "rows": [
          {
            "days": "Du lundi au samedi",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "dimanche",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Les agents d'accueil sont généralement en service de 10 h 30 à 17 h (du lundi au samedi) et de 11 h à 17 h le dimanche. Des fermetures ponctuelles liées à des services ou à des événements peuvent survenir à court terme."
      },
      {
        "heading": "Bureau du ministre",
        "rows": [
          {
            "days": "Du lundi au vendredi",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "Le Minster Centre abrite les bureaux, l'équipe pédagogique et l'office de tourisme."
      },
      {
        "heading": "Réfectoire",
        "rows": [
          {
            "days": "Du lundi au samedi",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "dimanche",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Boutique de la cathédrale",
        "rows": [
          {
            "days": "Du lundi au samedi",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "dimanche",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Palais archiépiscopal et jardins",
        "rows": [
          {
            "days": "Quotidien",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Entrée gratuite aux ruines du palais médiéval et aux jardins sensoriels situés à proximité de la cathédrale."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Faire un don",
    "paragraphs": [
      "La pierre qui se dresse au-dessus de vous a été érigée en 1108. C'est la plus belle nef normande encore debout en Angleterre — une succession d'arcs en plein cintre, taillés par des hommes qui savaient qu'ils ne vivraient pas assez longtemps pour voir le toit se refermer au-dessus d'eux.",
      "Et marchez vers l'est, jusqu'à la salle capitulaire. Là, sculptées dans la pierre il y a huit cents ans, se trouvent les feuilles emblématiques de ce comté. L’aubépine, le chêne, l’érable, le renoncule et la vigne. Celui qui les a sculptées s’était manifestement promené dans les bois et avait observé — <strong>vraiment</strong> observé — un être vivant, pour ensuite l’immortaliser. Elles ne se sont pas fanées en sept siècles.",
      "Ce n'est pas un musée. C'est un lieu de culte en activité, où l'on célèbre encore la messe, où l'on chante encore, où l'on allume encore des cierges ; un lieu qui procure chaleur et réconfort spirituels.",
      "Il faut plus de cinq mille livres par jour rien que pour maintenir ces portes ouvertes : le chauffage, les vitraux, les tissus, les choristes, la liturgie.",
      "L'entrée est gratuite. Elle l'a toujours été, et notre section veillera à ce qu'il en reste ainsi. Vous pouvez toutefois jouer un rôle important en contribuant à cette mission. L'année dernière, chaque visiteur a donné en moyenne une livre et quatre-vingt-huit pence.",
      "Nous aimerions vous demander un don de cinq livres.",
      "Si cet endroit vous a offert un moment de sérénité aujourd’hui et a enrichi votre journée, n’hésitez pas à le soutenir en cliquant sur le bouton « Faire un don maintenant » : cochez la case « Gift Aid » si vous êtes contribuable au Royaume-Uni : pour chaque tranche de 5 £, 1,25 £ supplémentaire sera versé, sans que cela ne vous coûte rien de plus."
    ],
    "button": "Faites un don dès maintenant",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "Mais surtout, sachez que vous quittez cet endroit sans aucune obligation. Ne donnez que dans la mesure de vos moyens. Ne donnez pas ce que vous ne pouvez pas vous permettre. Vous repartez toujours avec la bénédiction du Seigneur.",
    "close": "Ces feuilles ont traversé huit cents ans. Quant à savoir si elles en traverseront encore huit cents, cela dépend, sans qu'on en parle beaucoup, de nous."
  },
  "projects": {
    "num": "VIII.",
    "heading": "Nos projets",
    "lede": "Projets en cours et à venir à la cathédrale de Southwell — le contenu de cette rubrique sera publié prochainement.",
    "placeholderLabel": "Nos projets — à venir",
    "placeholderBody": "Espace réservé aux résumés de projets, aux images et aux mises à jour. Ajoutez les fiches de projet individuelles dès qu'elles seront prêtes."
  },
  "contact": {
    "num": "IX.",
    "heading": "Contact et comment nous trouver",
    "minsterHeading": "Cathédrale de Southwell",
    "addressLabel": "Adresse",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Téléphone",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Siège social)",
    "emailLabel": "E-mail",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Site web",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Prêtres recherchés d'urgence",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Boutique",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Comment s'y rendre",
    "gettingHere": [
      "Southwell est une petite ville de marché située au cœur du Nottinghamshire, à sept miles de l'A1 et à environ 30 minutes de route de Nottingham par l'A612. La cathédrale se trouve sur Church Street, au centre-ville, à quelques pas de la place où se tient le marché du samedi.",
      "<strong>Les visites guidées</strong> peuvent être réservées à l'avance auprès du bureau de la cathédrale ; <strong>les visites scolaires</strong> s'organisent séparément au <a href=\"tel:+441636817287\">01636 817287</a>.",
      "<strong>Célébrations en ligne :</strong> l'Eucharistie du dimanche et les vêpres sont diffusées en direct sur le site web de la cathédrale et restent disponibles en différé pendant la semaine suivante."
    ],
    "socialPrefix": "Réseaux sociaux :",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Guide concis destiné aux visiteurs, élaboré à partir des publications de la cathédrale, de celles de l'Association des cathédrales anglaises et de Wikipédia. Il ne s'agit pas d'une publication officielle de la cathédrale.",
    "photos": "Photographies : façade ouest, vitrail ouest, chœur, portail de la salle capitulaire et pulpitum avec orgue — Wikimedia Commons (Diliff et contributeurs de Geograph), CC BY-SA."
  }
}
