import type { SouthwellMinsterCopy } from "./southwellMinster"

/** de copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_DE: SouthwellMinsterCopy = {
  "audioHint": "Dort, wo Sie unten die Audiosteuerung sehen, sowie in jedem Abschnitt, in dem ein Audio-Symbol angezeigt wird, können Sie sich den Ton anhören, während Sie durch die Seite navigieren oder sich darin bewegen. Bitte verwenden Sie dazu Ihre Kopfhörer oder Ohrhörer.",
  "eyebrow": "Nottinghamshire · Anglikanische Kirche",
  "title": "Southwell Minster",
  "tagline": "Die Kathedrale und Pfarrkirche der Heiligen Jungfrau Maria – ein normannisches Juwel in den englischen Midlands, in dem seit dem Jahr 627 ununterbrochen gebetet wird.",
  "meta": [
    "Gegründet um 627",
    "Der Wiederaufbau durch die Normannen ab 1108",
    "Dom seit 1884"
  ],
  "welcome": {
    "invite": "Eine Begrüßungsbotschaft von Pater Stephen abspielen",
    "videoUnsupported": "Ihr Browser unterstützt das Video-Element nicht.",
    "placeholderLabel": "Begrüßungsvideo – in Kürze verfügbar",
    "role": "Der Hochwürden",
    "name": "Dr Stephen Evans",
    "title": "Dekan der Southwell Minster"
  },
  "toc": [
    {
      "href": "#history",
      "label": "Geschichte"
    },
    {
      "href": "#treasures",
      "label": "Schätze & Inneneinrichtung"
    },
    {
      "href": "#officers",
      "label": "Führungskräfte"
    },
    {
      "href": "#music",
      "label": "Musik & Chöre"
    },
    {
      "href": "#worship",
      "label": "Liturgie und Gottesdienste"
    },
    {
      "href": "#visit",
      "label": "Öffnungszeiten"
    },
    {
      "href": "#donate",
      "label": "Spenden"
    },
    {
      "href": "#projects",
      "label": "Unsere Projekte"
    },
    {
      "href": "#contact",
      "label": "Kontakt"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Ein kurzer Rückblick",
    "lede": "In Southwell steht seit weit über tausend Jahren eine Minsterkirche – sie hat die Zeit der Wikinger, die Reformation, den Bürgerkrieg und einen Brand überstanden – und dient heute als Mutterkirche der Diözese Southwell & Nottingham.",
    "paragraphs": [
      "Der Überlieferung zufolge <strong>gründete Paulinus, der erste Erzbischof von York, im Jahr 627 hier die älteste Kirche,</strong> während er Bekehrte im Fluss Trent taufte. Im Jahr <strong>956</strong> schenkte König Eadwig dem Erzbischof von York, Oskytel, Ländereien in Southwell, woraufhin eine sächsische Minsterkirche errichtet wurde; das Gut wurde im <em>„Domesday Book“</em> von 1086 ausführlich beschrieben.",
      "Der Bau <strong>der</strong> heutigen <strong>normannischen Minster</strong> wurde um <strong>1108</strong> begonnen; sie wurde auf den früheren angelsächsischen Fundamenten wiedererrichtet. Das Langhaus, die Querschiffe, der Mittelturm und die beiden westlichen „Pepperpot“-Türme sind als eines der schönsten Beispiele für strenge romanische Architektur in England erhalten geblieben. Der <strong>im frühenglischen Stil erbaute Chor</strong> wurde zwischen 1234 und 1251 umgebaut, und mit dem Bau <strong>des</strong> berühmten <strong>Kapitelsaals</strong> wurde 1288 begonnen.",
      "Die Stiftskirche, die <strong>1540</strong> von Heinrich VIII. aufgelöst worden war, wurde 1543 wiedergegründet, verlor 1548 erneut ihren Status und wurde schließlich 1557 wiederhergestellt. Während des Bürgerkriegs <strong>ergab sich Karl I. 1646</strong> nach der Belagerung von Newark <strong>in Southwell</strong>. Im Jahr <strong>1711</strong> schlug ein Blitz in den südwestlichen Turm ein, und ein Brand zerstörte die Dächer, die Glocken, die Uhr und die Orgel; beide Türme wurden 1805 abgetragen und erst 1879–81 im Rahmen der umfassenden viktorianischen Restaurierung durch Ewan Christian wieder aufgebaut.",
      "Die Minster wurde <strong>1884</strong> zur <strong>Kathedrale</strong>, als die neue Diözese Southwell gegründet wurde, um Nottinghamshire und Derbyshire zu betreuen (Derby wurde 1927 zu einer eigenständigen Diözese). Sie ist nach wie vor der Heiligen Jungfrau Maria geweiht und behält – als einzige unter den englischen Kathedralen – ihren alten Titel <em>„Minster“</em> bei."
    ],
    "figureAlt": "Das große Westfenster der Southwell Minster, eingerahmt von den beiden normannischen „Pepperpot“-Türmen.",
    "figureCaption": "Die normannische Westfassade mit ihren charakteristischen „Pfeffermühlen“-Türmen und dem 1996 von Patrick Reyntiens geschaffenen „Engelfenster“.",
    "timelineLabel": "Chronologie der Southwell Minster",
    "timeline": [
      {
        "year": "627",
        "text": "Paulinus, der erste Erzbischof von York, dem die Gründung einer Kirche in Southwell zugeschrieben wird."
      },
      {
        "year": "956",
        "text": "König Eadwig schenkt Erzbischof Oskytel Ländereien; eine sächsische Stiftskirche wird gegründet."
      },
      {
        "year": "1108",
        "text": "Der Wiederaufbau der normannischen Kirche begann am östlichen Ende; mit dem Langhaus wurde nach 1120 begonnen."
      },
      {
        "year": "1234–51",
        "text": "Der frühenglische Gesangszug wurde wieder aufgebaut."
      },
      {
        "year": "1288",
        "text": "Der Bau des achteckigen Kapitelsaals beginnt."
      },
      {
        "year": "1320–40",
        "text": "Das große steinerne Pulpitum (Chorwand) ist im „Decorated“-Stil geschnitzt."
      },
      {
        "year": "1540–57",
        "text": "Unter Heinrich VIII. abgeschafft, unter Philipp und Maria wieder eingeführt."
      },
      {
        "year": "1646",
        "text": "Karl I. ergibt sich in Southwell den schottischen presbyterianischen Truppen."
      },
      {
        "year": "1711",
        "text": "Blitzschlag; ein Brand zerstört die Dächer, die Glocken, die Uhr und die Orgel."
      },
      {
        "year": "1879–81",
        "text": "Die Restaurierung der Ewan Christian-Kirche; die westlichen Türme werden wieder aufgerichtet."
      },
      {
        "year": "1884",
        "text": "Die Southwell Minster wird zur Kathedrale der neuen Diözese."
      },
      {
        "year": "1996",
        "text": "Patrick Reyntiens’ großartiges „Engelfenster“ am westlichen Ende."
      },
      {
        "year": "2021",
        "text": "Das Chapter House wird nach umfangreichen Restaurierungsarbeiten wiedereröffnet – mit einem freitragenden Aufzug für uneingeschränkte Barrierefreiheit."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Schätze und Sehenswürdigkeiten",
    "lede": "Von den schönsten mittelalterlichen Blattschnitzereien Englands bis hin zu einem flämischen Ostfenster aus dem 16. Jahrhundert – die Minster bietet eine außergewöhnliche Fülle an Sehenswürdigkeiten, bei denen es sich lohnt, einen Moment innezuhalten.",
    "leavesHeading": "Die Blätter von Southwell",
    "leavesBody": "Der <strong>Kapitelsaal</strong> (Baubeginn 1288) ist achteckig, hat keine Mittelsäule und ist mit tief eingearbeiteten Blattwerk-Schnitzereien verziert, die unter dem Namen <strong>„The Leaves of Southwell“</strong> bekannt sind<strong>.</strong> Einzelne Pflanzenarten – Efeu, Ahorn, Eiche, Hopfen, Weißdorn – sind alle erkennbar und werden von „Green Men“ und mythologischen Figuren durchsetzt. Sie gelten als die schönsten naturalistischen Schnitzereien des 13. Jahrhunderts im Vereinigten Königreich, waren Gegenstand von Nikolaus Pevsners klassischer Monografie aus dem Jahr 1945 und wurden 2023 in einer öffentlichen Umfrage zum beliebtesten Domschatz Großbritanniens gewählt.",
    "figureAlt": "Naturalistische Blattschnitzereien aus dem 13. Jahrhundert rund um den Eingang zum Kapitelsaal der Southwell Minster.",
    "figureCaption": "„The Leaves of Southwell“ – Laubwerk-Schnitzereien aus dem 13. Jahrhundert rund um das Portal des Kapitelsaals, die 2023 zum beliebtesten Schatz der Kathedrale des Landes gewählt wurden.",
    "features": [
      {
        "heading": "Das normannische Kirchenschiff",
        "body": "Sieben Joche mit kurzen, runden Säulen und muschelförmigen Kapitellen; in jedem Joch ein einzelner großer Triforiumbogen; kleine Rundbogenfenster im Oberlicht und runde Außenöffnungen – eines der herausragenden erhaltenen Beispiele der strengen englischen Romanik."
      },
      {
        "heading": "Das Tympanon",
        "body": "Das geschnitzte Tympanon aus dem späten 11. Jahrhundert im nördlichen Querschiff sowie ein Fragment des Mosaikbodens sind die einzigen sichtbaren Überreste der früheren angelsächsischen Stiftskirche."
      },
      {
        "heading": "Das Pulpitum (Chorgitter)",
        "body": "Ein kunstvoll geschnitztes Chorgitter aus Stein aus den Jahren 1320–1340, ein herausragendes Beispiel für den dekorativen Stil, mit zwei Stockwerken aus Nischen mit Ogee-Bögen und durchbrochenen Giebeln, die den Eingang zum Chor einrahmen."
      },
      {
        "heading": "Der frühe englische Gesangbuchheft",
        "body": "Zwischen 1234 und 1251 im reinsten frühenglischen Stil wieder aufgebaut: Säulengruppen, doppelte Spitzbogenfenster im Obergeschoss, ein geripptes Steingewölbe und ein quadratischer Ostbau, der durch zwei Reihen mit je vier Spitzbogenfenstern beleuchtet wird."
      },
      {
        "heading": "Das Ostfenster",
        "body": "Vier Renaissance-Glasmalereien aus flämischem Glas des 16. Jahrhunderts von Jean Chastellain nach Entwürfen von Noël Bellemare, die ursprünglich für die Temple Church in Paris angefertigt und 1818 dem Minster geschenkt wurden; die vier Evangelisten darüber stammen von Clayton & Bell (1876)."
      },
      {
        "heading": "Das Engelsfenster",
        "body": "Dieses großartige moderne Fenster von <strong>Patrick Reyntiens</strong> – einem der bedeutendsten britischen Glasmaler –, das <strong>1996</strong> am westlichen Ende eingebaut wurde, ist die auffälligste Neuerung der Minster in jüngerer Zeit."
      },
      {
        "heading": "Grabstätte von Erzbischof Sandys",
        "body": "Das prächtigste aller Gedenkdenkmäler der Minster: das Alabastergrabmal von <strong>Edwin Sandys, Erzbischof von York (gest. 1588)</strong>, dessen Familie lange Zeit Ländereien in Nottinghamshire besaß."
      },
      {
        "heading": "Das Newstead-Rednerpult",
        "body": "Ein mittelalterliches Rednerpult aus Messing in Form eines Adlers, das vermutlich nach der Auflösung der Klöster aus dem See der Newstead Abbey geborgen und 1805 von Erzdiakon Kaye der Minster geschenkt wurde."
      },
      {
        "heading": "Der zentrale normannische Turm",
        "body": "Zwei ornamentale Etagen – unten sich kreuzende Bögen, oben schlichte Bögen – machen den Vierungsturm zu einem der höchsten noch erhaltenen normannischen Türme Englands."
      },
      {
        "heading": "Gebetskapellen",
        "body": "Drei Kapellen sind für das private Gebet vorgesehen, darunter <strong>die St.-Oswald-Kapelle</strong> (in der täglich das Morgengebet und die Heilige Kommunion stattfinden) und die <strong>Fliegerkapelle</strong>, <strong>die</strong> an das RAF Bomber Command in Nottinghamshire erinnert."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Führungskräfte",
    "lede": "Die Southwell Minster wird von ihrem <strong>Domkapitel</strong> unter dem Vorsitz des Dekans geleitet, das vom Domrat und dem gesamten Domkapitel unterstützt und beaufsichtigt wird. Nachstehend sind die wichtigsten Amtsträger aufgeführt, wie sie derzeit von der Minster angegeben werden.",
    "people": [
      {
        "role": "Bischof von Southwell und Nottingham",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "Der Dekan",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Kanoniker und Kantor",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Vorstandsmitglied des Ortsverbands",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Vorstandsmitglied des Ortsverbands",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Leitendes nicht geschäftsführendes Mitglied",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Rektor Chori (Musikdirektor)",
        "name": "Paul Provost"
      },
      {
        "role": "Stellvertretender Musikdirektor",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Leitender Kirchenvorsteher",
        "name": "Andrew Todd"
      }
    ],
    "note": "Zu den nicht geschäftsführenden Mitgliedern des Kapitels gehören außerdem Herr Andrew Corner, Herr Nick Alexander, Frau Ann Carter-Gray, Frau Marion Oswald, Herr David Walker und Herr Jonathan Wheeler. Die Kathedrale beschäftigt außerdem einen Chief Operating Officer und einen Chief Finance Officer sowie etwa 32 Mitarbeiter und rund 300 ehrenamtliche Helfer."
  },
  "music": {
    "num": "IV.",
    "heading": "Musikstiftung & Chöre",
    "lede": "Seit mehr als neunhundert Jahren singt in Southwell ein Chor – eine ununterbrochene Tradition des chorischen Gottesdienstes, die von den mittelalterlichen „Vicars Choral“ bis zum heutigen Domchor reicht, der sich aus Knaben- und Mädchenstimmen, professionellen Laienchoristen und dem ehrenamtlichen „Minster Chorale“ zusammensetzt.",
    "songHeading": "Neun Jahrhunderte Musik",
    "songParagraphs": [
      "Das musikalische Leben der Minster begann mit einem <strong>Chorvikar</strong>-Kollegium, das in den Gebäuden untergebracht war, die sich an der Stelle des heutigen „Vicars’ Court“ befanden. Ein oder zwei von ihnen wurden <strong>zum</strong> <strong>„Rector Chori“</strong> – „Leiter des Chors“ – ernannt, ein Titel, der erstmals <strong>1499</strong> in Southwell urkundlich erwähnt wurde und bis heute für den Musikdirektor verwendet wird. Zu den Chorvikaren kamen Knabenchoristen hinzu, und die Vikare wurden nach und nach durch Laiensänger – die <strong>„Lay Clerks“</strong> – ersetzt, wodurch der Chor im Wesentlichen seine heutige Form erhielt.",
      "Im Jahr <strong>2005</strong> wurde vom damaligen stellvertretenden Musikdirektor ein Mädchenchor gegründet. Dieser wurde <strong>2019</strong> vollständig in den Domchor integriert; heute sind Jungen und Mädchen im Chor <strong>völlig gleichberechtigt</strong> und teilen sich Gottesdienste, Gewänder (Soutane und Albe), Altersgruppen und Titel – alle sind einfach „Domchorsänger“. Im Jahr <strong>2021</strong> ernannte Southwell in der tausendjährigen Geschichte der Minster die <strong>erste weibliche Chorleiterin überhaupt</strong>, und im Jahr 2025 feierte die Minster das zwanzigjährige Jubiläum des Mädchenchors."
    ],
    "figureAlt": "Die mittelalterliche Steinkanzel der Southwell Minster mit der darüber angebrachten Nicholson-Orgel.",
    "figureCaption": "Das Pulpitum mit der darüber montierten Nicholson-Hauptorgel in ihrem Caröe-Gehäuse.",
    "choirsHeading": "Die Chöre heute",
    "features": [
      {
        "heading": "Knabenchorsänger",
        "body": "Der traditionelle Sopranchor, der aus der Minster School hervorgegangen ist. Die Jungen singen während des Schuljahres in der Regel montags und dienstags bei der Abendandacht allein und schließen sich von Donnerstag bis Sonntag den Lay Clerks an, wobei sie sich mit den Mädchen abwechseln."
      },
      {
        "heading": "Mädchen im Chor",
        "body": "Gegründet im Jahr 2005 und mittlerweile vollwertige Partnerinnen im Domchor – derzeit sind es etwa 18 Mädchen, die alle Aufgaben als Chorsängerinnen, Proben, Tourneen und Aufnahmen auf Augenhöhe mit den Jungen wahrnehmen."
      },
      {
        "heading": "Laienbeamte",
        "body": "Sechs professionelle Laienchoristen und sechs Hilfschoristen – die Erwachsenenstimmen im Alt-, Tenor- und Bassbereich, direkte Nachfolger der mittelalterlichen „Vicars Choral“. Sie singen von Donnerstag bis Sonntag sowie an Feiertagen gemeinsam mit den Chorkindern."
      },
      {
        "heading": "Der Minster-Chor",
        "body": "Der <strong>1994</strong> gegründete, aus ausgewählten Mitgliedern bestehende ehrenamtliche Erwachsenenchor mit bis zu dreißig Sängern steht unter der Leitung des stellvertretenden Musikdirektors. Er singt bei Gottesdiensten, wenn der Domchor nicht zur Verfügung steht, sowie bei den monatlichen Sonntagsmatthins."
      },
      {
        "heading": "Die Minster-Schule",
        "body": "Alle Chormitglieder besuchen <strong>die Minster School</strong>, eine Akademie der Church of England mit einer auf Musik spezialisierten Unterstufe (Jahrgangsstufen 3–6), die Mitglied der „Choir Schools’ Association“ ist."
      },
      {
        "heading": "Southwell-Chorverein",
        "body": "Ein seit über sechzig Jahren bestehender Gemeinschaftschor ohne Vorsingen, der während des Semesters wöchentlich in der Minster probt – die breitere Musikgemeinschaft, die sich um die Stiftung versammelt."
      }
    ],
    "organsHeading": "Die Orgeln",
    "organsBody": "Das Hauptinstrument der Minster steht auf dem mittelalterlichen Pulpitum in einem von <strong>W. D. Caröe</strong> entworfenen Eichenprospekt. Die heutige Screen-Orgel wurde in den 1990er Jahren von führenden Orgelbauern (unter Beratung von John Norman, Stephen Bicknell und Ian Bell) umgebaut, wobei der Caröe-Prospekt aus historischen Gründen erhalten blieb. Eine separate <strong>Kirchenschifforgel</strong>, deren Geschichte auf ein Instrument von „Mr. Derbie“ aus dem Jahr 1662 und Reparaturen nach dem großen Brand von 1711 zurückgeht, begleitet den Gemeindegesang am westlichen Ende, und eine schöne <strong>Kammerorgel</strong> wird für den Continuo-Begleitung und kleinere Gottesdienste genutzt. Eine 72-seitige, illustrierte Broschüre mit <em>dem Titel „The Organs of Southwell Minster</em>“ des ehemaligen Rector Chori Paul Hale ist im Kathedralenladen erhältlich."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturgie und tägliche Gottesdienste",
    "lede": "Der tägliche Gebetsablauf des Dompropstes folgt dem „Common Worship“-Modell der Church of England und wird während des Semesters von einer der renommiertesten Stiftungen für Dommusik des Landes unterstützt.",
    "paragraphs": [
      "In Southwell wird das vollständige <strong>anglikanische Kathedral-Tagesgebet</strong> abgehalten: Jeden Tag finden das Morgengebet, die Heilige Kommunion (die Eucharistie) und das Abendgebet bzw. die Abendandacht statt. Während der Schulzeit werden an den meisten Tagen Chorgottesdienste vom <strong>Domchor</strong> – den Knaben- und Mädchenchorsängern sowie den Laienkantoren – gesungen, die gemeinsam acht Chorgottesdienste pro Woche musikalisch gestalten. Sonntags singen die Mädchen- und Knabenchorsänger abwechselnd mit den Laienchoristen die Eucharistiefeier und die Evensong. Weitere Gottesdienste werden vom <strong>„Minster Chorale“</strong> gesungen, einem 1994 gegründeten Kammerchor mit bis zu dreißig ehrenamtlichen Sängern.",
      "Die <strong>Sonntagsmesse in der Kathedrale (10.00 Uhr)</strong> und <strong>der Sonntagsvespergottesdienst (15.30 Uhr)</strong> werden live übertragen und bleiben jeweils eine Woche bzw. einen Tag lang online verfügbar. Besucher aller Glaubensrichtungen sind herzlich willkommen; der Eintritt ist frei."
    ],
    "figureAlt": "Der Chorraum der Southwell Minster mit Blick nach Osten, zu sehen sind die mittelalterlichen Chorgestühle und das Steingewölbe.",
    "figureCaption": "Der „Early English“-Chorraum, in dem während des Semesters an den meisten Tagen die Abendandacht mit Chorgesang stattfindet.",
    "weekdayHeading": "Wochentagsrhythmus",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Morgengebet – St<em>.-Oswald-Kapelle</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Heilige Kommunion – <em>St. Oswald’s / Airmen’s Chapel</em><br /> <small>(samstags: 9.00 Uhr)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Choral-Vesper – <em>The Quire</em> <br /><small>(mittwochs gesprochenes Abendgebet; montags, dienstags, donnerstags, freitags und samstags während des Semesters gesungen)</small>"
      }
    ],
    "sundayHeading": "Sonntagsmuster",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Heilige Kommunion (BCP, gesprochen)"
      },
      {
        "clock": "10.00am",
        "detail": "Gesungene Kathedral-Eucharistiefeier – <em>per Live-Stream übertragen</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Choral-Vesper — <em>per Live-Stream</em>"
      }
    ],
    "timesNote": "<em>Die Gottesdienstzeiten können an Feiertagen und während der Schulferien variieren – bitte informieren Sie sich vor Ihrer Anreise im Gottesdienstkalender auf der Website der Minster.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Öffnungszeiten",
    "lede": "Die Minster ist das ganze Jahr über täglich für Besucher geöffnet, der Eintritt ist kostenlos. Spenden für den Unterhalt der Minster sind herzlich willkommen.",
    "cards": [
      {
        "heading": "Die Kathedrale",
        "rows": [
          {
            "days": "Montag – Samstag",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "Sonntag",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Die Ordner sind in der Regel montags bis samstags von 10:30 bis 17:00 Uhr und sonntags von 11:00 bis 17:00 Uhr im Einsatz. Gelegentlich kann es kurzfristig zu Schließungen aufgrund von Veranstaltungen oder anderen Anlässen kommen."
      },
      {
        "heading": "Ministerbüro",
        "rows": [
          {
            "days": "Montag – Freitag",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "Im Minster Centre sind die Geschäftsstelle, das Bildungsteam und die Touristeninformation untergebracht."
      },
      {
        "heading": "Speisesaal",
        "rows": [
          {
            "days": "Mo – Sa",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "Sonntag",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Dom-Shop",
        "rows": [
          {
            "days": "Mo – Sa",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "Sonntag",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Erzbischofspalast und Gärten",
        "rows": [
          {
            "days": "Täglich",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Freier Eintritt zur mittelalterlichen Palasruine und zu den Sinnesgärten neben dem Minster."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Spenden",
    "paragraphs": [
      "Der Stein über euch wurde im Jahr 1108 errichtet. Es ist das schönste noch erhaltene normannische Kirchenschiff in England – ein Rundbogen folgt dem nächsten, gemeißelt von Männern, die wussten, dass sie den Tag, an dem das Dach über ihnen geschlossen würde, nicht mehr erleben würden.",
      "Und gehen Sie nach Osten, in den Kapitelsaal. Dort sind vor achthundert Jahren in den Stein gemeißelt die Blätter dieses Landkreises zu sehen. Weißdorn, Eiche, Ahorn, Hahnenfuß und Weinrebe. Wer auch immer sie gemeißelt hat, war offensichtlich in den Wald gegangen und hatte ein Lebewesen betrachtet – <strong>wirklich</strong> betrachtet – und es für die Ewigkeit festgehalten. Sie sind in sieben Jahrhunderten nicht verwelkt.",
      "All das ist kein Museum. Es ist ein aktiver Ort der Andacht, an dem noch immer Gottesdienste abgehalten, noch immer gesungen und noch immer Licht angezündet wird; ein Ort geistiger Wärme und Trost.",
      "Allein um diese Türen offen zu halten, kostet es mehr als fünftausend Pfund pro Tag – die Heizung, das Glas, die Stoffe, die Chorsänger, die Liturgie.",
      "Der Eintritt ist kostenlos. Das war schon immer so, und der Ortsverband wird dies auch weiterhin so handhaben. Sie können jedoch einen wichtigen Beitrag zur Erfüllung dieser Aufgabe leisten. Im vergangenen Jahr spendete ein Besucher im Durchschnitt ein Pfund und achtundachtzig Pence.",
      "Wir möchten Sie um eine Spende in Höhe von fünf Pfund bitten.",
      "Wenn Ihnen dieser Ort heute einen Moment der Ruhe geschenkt und Ihren Tag bereichert hat, unterstützen Sie ihn bitte – indem Sie auf die Schaltfläche „Jetzt spenden“ klicken: Aktivieren Sie „Gift Aid“, wenn Sie in Großbritannien steuerpflichtig sind: Pro 5 £ kommt so zusätzlich 1,25 £ hinzu, ohne dass Ihnen dadurch zusätzliche Kosten entstehen."
    ],
    "button": "Jetzt spenden",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "Bitte beachten Sie vor allem, dass Sie diesen Ort ohne jegliche Verpflichtung verlassen. Geben Sie bitte nur im Rahmen Ihrer Möglichkeiten. Geben Sie nichts, was Sie sich nicht leisten können. Sie verlassen diesen Ort stets mit dem Segen des Herrn.",
    "close": "Die Blätter haben achthundert Jahre überdauert. Ob sie noch weitere achthundert Jahre überdauern, liegt – ganz still und leise – an uns."
  },
  "projects": {
    "num": "VIII.",
    "heading": "Unsere Projekte",
    "lede": "Laufende und geplante Projekte in der Southwell Minster – Inhalte zu diesem Abschnitt folgen in Kürze.",
    "placeholderLabel": "Unsere Projekte – in Kürze",
    "placeholderBody": "Platzhalter für Projektzusammenfassungen, Bilder und Aktualisierungen. Fügen Sie einzelne Projekteinträge hinzu, sobald diese fertig sind."
  },
  "contact": {
    "num": "IX.",
    "heading": "Kontakt & Anfahrt",
    "minsterHeading": "Southwell Minster",
    "addressLabel": "Adresse",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Telefon",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Hauptsitz)",
    "emailLabel": "E-Mail",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Website",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Dringender Bedarf an Geistlichen",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Shop",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Anreise",
    "gettingHere": [
      "Southwell ist eine kleine Marktstadt im Zentrum von Nottinghamshire, sieben Meilen von der A1 entfernt und über die A612 in etwa 30 Minuten mit dem Auto von Nottingham aus zu erreichen. Die Minster befindet sich in der Church Street im Stadtzentrum, nur einen kurzen Fußweg vom Samstagsmarktplatz entfernt.",
      "<strong>Führungen</strong> können im Büro der Minster im Voraus gebucht werden; <strong>Schulbesuche</strong> werden separat unter der Telefonnummer <a href=\"tel:+441636817287\">01636 817287</a> vereinbart.",
      "<strong>Online-Gottesdienste:</strong> Die Sonntagsmesse und die Abendandacht werden live auf der Website der Minster übertragen und stehen in der darauffolgenden Woche als Aufzeichnung zur Verfügung."
    ],
    "socialPrefix": "Soziale Medien:",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Ein kurzer Besucherleitfaden, zusammengestellt aus den eigenen Veröffentlichungen der Minster, den Veröffentlichungen der Association of English Cathedrals und Wikipedia. Keine offizielle Veröffentlichung der Minster.",
    "photos": "Fotos: Westfassade, Westfenster, Chorraum, Portal des Kapitelsaals und Pulpitum mit Orgel – Wikimedia Commons (Diliff und Geograph-Mitwirkende), CC BY-SA."
  }
}
