import type { SouthwellMinsterCopy } from "./southwellMinster"

/** pt copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_PT: SouthwellMinsterCopy = {
  "audioHint": "Nos locais em que você vir o controle de áudio abaixo e em cada seção em que houver um ícone de áudio, você poderá ouvir enquanto navega ou se desloca pelo site. Use seus fones de ouvido ou earbuds.",
  "eyebrow": "Nottinghamshire · Igreja da Inglaterra",
  "title": "Catedral de Southwell",
  "tagline": "A Catedral e Igreja Paroquial da Santíssima Virgem Maria — uma joia normanda da região de Midlands, na Inglaterra, em oração ininterrupta desde 627.",
  "meta": [
    "Fundada por volta de 627",
    "Reconstrução normanda a partir de 1108",
    "Catedral desde 1884"
  ],
  "welcome": {
    "invite": "Reproduza uma mensagem de boas-vindas do padre Stephen",
    "videoUnsupported": "Seu navegador não suporta o elemento de vídeo.",
    "placeholderLabel": "Vídeo de boas-vindas — em breve",
    "role": "O Reverendíssimo",
    "name": "Dr Stephen Evans",
    "title": "Decano da Catedral de Southwell"
  },
  "toc": [
    {
      "href": "#history",
      "label": "História"
    },
    {
      "href": "#treasures",
      "label": "Tesouros e decoração de interiores"
    },
    {
      "href": "#officers",
      "label": "Principais dirigentes"
    },
    {
      "href": "#music",
      "label": "Música e corais"
    },
    {
      "href": "#worship",
      "label": "Liturgia e celebrações"
    },
    {
      "href": "#visit",
      "label": "Horário de funcionamento"
    },
    {
      "href": "#donate",
      "label": "Faça uma doação"
    },
    {
      "href": "#projects",
      "label": "Nossos projetos"
    },
    {
      "href": "#contact",
      "label": "Contato"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Uma breve história",
    "lede": "Há bem mais de mil anos existe uma catedral em Southwell — que resistiu aos vikings, à Reforma, à guerra civil e a incêndios — e que hoje funciona como igreja-mãe da Diocese de Southwell e Nottingham.",
    "paragraphs": [
      "Reza a tradição que <strong>Paulino, o primeiro arcebispo de York, fundou a primeira igreja neste local em 627,</strong> enquanto batizava convertidos no rio Trent. Em <strong>956,</strong> o rei Eadwig concedeu terras em Southwell a Oskytel, arcebispo de York, e uma igreja minster saxônica foi erguida; a propriedade foi registrada em detalhes no <em>Domesday Book</em> de 1086.",
      "A atual <strong>catedral normanda</strong> teve sua construção iniciada por volta de <strong>1108</strong>, tendo sido reconstruída sobre as antigas fundações anglo-saxônicas. A nave, os transeptos, a torre central e as duas torres ocidentais em forma de “pimentão” permanecem como um dos melhores exemplos do austero estilo românico na Inglaterra. O <strong>coro, em estilo inglês primitivo</strong>, foi reconstruído entre 1234 e 1251, e a famosa <strong>Sala do Capítulo</strong> teve suas obras iniciadas em 1288.",
      "Suprimida por Henrique VIII em <strong>1540</strong>, a igreja colegiada foi refundada em 1543, perdeu seu status novamente em 1548 e foi finalmente restaurada em 1557. Durante a Guerra Civil, <strong>Carlos I se rendeu em Southwell em 1646</strong>, após o cerco de Newark. Em <strong>1711,</strong> um raio atingiu a torre sul-oeste e um incêndio destruiu os telhados, os sinos, o relógio e o órgão; ambas as torres foram removidas em 1805 e só foram reconstruídas entre 1879 e 1881, durante a extensa restauração vitoriana conduzida por Ewan Christian.",
      "A Minster tornou-se <strong>catedral em 1884</strong>, quando foi criada a nova Diocese de Southwell para atender Nottinghamshire e Derbyshire (Derby tornou-se uma diocese independente em 1927). Ela continua dedicada à Santíssima Virgem Maria e, de forma única entre as catedrais inglesas, mantém seu antigo título de <em>“Minster</em>”."
    ],
    "figureAlt": "A grande janela ocidental da Catedral de Southwell, emoldurada pelas duas torres normandas em forma de “pote de pimenta”.",
    "figureCaption": "A fachada oeste normanda, com suas características torres em forma de “pimentão” e a Janela do Anjo, de 1996, obra de Patrick Reyntiens.",
    "timelineLabel": "Cronologia da Catedral de Southwell",
    "timeline": [
      {
        "year": "627",
        "text": "Paulinus, primeiro arcebispo de York, a quem se atribui a fundação de uma igreja em Southwell."
      },
      {
        "year": "956",
        "text": "O rei Eadwig concede terras ao arcebispo Oskytel; é fundada uma catedral saxônica."
      },
      {
        "year": "1108",
        "text": "A reconstrução da catedral de Norman teve início na extremidade leste; a construção da nave começou após 1120."
      },
      {
        "year": "1234–51",
        "text": "O caderno de partitura da música inglesa antiga foi reconstruído."
      },
      {
        "year": "1288",
        "text": "Começa a construção da Sala Capitular octogonal."
      },
      {
        "year": "1320–40",
        "text": "O grande pulpitum (coro) de pedra é esculpido no estilo Decorado."
      },
      {
        "year": "1540–57",
        "text": "Suprimida durante o reinado de Henrique VIII, restabelecida durante o reinado de Filipe e Maria."
      },
      {
        "year": "1646",
        "text": "Carlos I se rende às tropas presbiterianas escocesas em Southwell."
      },
      {
        "year": "1711",
        "text": "Um raio atingiu o local; o incêndio destruiu os telhados, os sinos, o relógio e o órgão."
      },
      {
        "year": "1879–81",
        "text": "Restauração da igreja de Ewan Christian; as torres ocidentais foram reconstruídas."
      },
      {
        "year": "1884",
        "text": "A Minster de Southwell passa a ser a catedral da nova diocese."
      },
      {
        "year": "1996",
        "text": "A magnífica “Janela dos Anjos”, de Patrick Reyntiens, instalada na extremidade oeste."
      },
      {
        "year": "2021",
        "text": "A Sala Capitular reabre após uma grande restauração, com um elevador em balanço para garantir acesso total."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Tesouros e pontos turísticos",
    "lede": "Desde as mais belas entalhadas medievais da Inglaterra até uma janela oriental flamenga do século XVI, a Catedral é excepcionalmente rica em elementos que merecem uma parada para serem apreciados.",
    "leavesHeading": "As Folhas de Southwell",
    "leavesBody": "A <strong>Sala Capitular</strong> (iniciada em 1288) é octogonal, não possui pilar central e é decorada com entalhes de folhagem profundamente recortados, conhecidos coletivamente como <strong>“As Folhas de Southwell”.</strong> Espécies individuais — hera, bordo, carvalho, lúpulo, espinheiro — são todas identificáveis, intercaladas com “Homens Verdes” e figuras mitológicas. Consideradas as melhores esculturas naturalistas do século XIII no Reino Unido, elas foram tema da clássica monografia de Nikolaus Pevsner, de 1945, e foram eleitas o tesouro catedralício favorito da Grã-Bretanha em uma pesquisa pública realizada em 2023.",
    "figureAlt": "Entalhes naturalistas de folhas do século XIII ao redor da porta de entrada da Sala do Capítulo da Catedral de Southwell.",
    "figureCaption": "“As Folhas de Southwell” — entalhes de folhagem do século XIII ao redor do portal da Sala Capitular, eleitos o tesouro catedralício favorito do país em 2023.",
    "features": [
      {
        "heading": "A nave normanda",
        "body": "Sete vãos com colunas curtas e circulares com capitéis recortados; um único arco grande de trifório em cada vão; pequenas janelas de claraboia com arco redondo e aberturas externas circulares — um dos exemplos mais notáveis que ainda sobrevivem do rigoroso estilo românico inglês."
      },
      {
        "heading": "O tímpano",
        "body": "O tímpano esculpido do final do século XI, localizado no transepto norte, juntamente com um fragmento do piso em mosaico, são os únicos vestígios visíveis da antiga catedral anglo-saxônica."
      },
      {
        "heading": "O pulpitum (biombo do coro)",
        "body": "Uma tela de coro em pedra, ricamente esculpida, datada de 1320–40, um exemplo notável do estilo Decorado, com dois andares de nichos com arcos ogivais e frontões com aberturas que emolduram a entrada do coro."
      },
      {
        "heading": "O caderno de partitura da música inglesa antiga",
        "body": "Reconstruída entre 1234 e 1251 em puro estilo inglês primitivo: colunas agrupadas, janelas góticas duplas no andar superior, abóbada de pedra com nervuras e uma fachada oriental quadrada iluminada por duas fileiras de quatro janelas góticas."
      },
      {
        "heading": "A janela do lado leste",
        "body": "Quatro painéis renascentistas de vitrais flamengos do século XVI, de Jean Chastellain, baseados em desenhos de Noël Bellemare, originalmente criados para a Igreja do Templo, em Paris, e doados à Catedral em 1818; os quatro evangelistas acima são de autoria de Clayton & Bell (1876)."
      },
      {
        "heading": "A Janela do Anjo",
        "body": "Instalado na extremidade oeste em <strong>1996</strong>, este magnífico vitral moderno de <strong>Patrick Reyntiens</strong> — um dos mais renomados artistas britânicos especializados em vitrais — é a adição recente mais marcante da Catedral."
      },
      {
        "heading": "Túmulo do Arcebispo Sandys",
        "body": "O mais belo dos memoriais da Catedral: o túmulo de alabastro de <strong>Edwin Sandys, arcebispo de York (falecido em 1588)</strong>, cuja família possuía propriedades em Nottinghamshire há muito tempo."
      },
      {
        "heading": "O púlpito de Newstead",
        "body": "Um púlpito medieval em forma de águia, feito de latão, que se acredita ter sido recuperado do lago da Abadia de Newstead após a Dissolução e doado à Catedral pelo arquidiácono Kaye em 1805."
      },
      {
        "heading": "A torre normanda central",
        "body": "Dois níveis ornamentais — arcos entrecruzados na parte inferior e arcos simples na parte superior — colocam a torre da cruzada entre as mais altas das torres normandas que ainda se conservam na Inglaterra."
      },
      {
        "heading": "Capelas para oração",
        "body": "Três capelas são destinadas à oração particular, incluindo <strong>a Capela de São Oswald</strong> (utilizada diariamente para a Oração da Manhã e a Santa Comunhão) e a <strong>Capela dos Aviadores</strong>, em homenagem ao Comando de Bombardeiros da RAF em Nottinghamshire."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Principais dirigentes",
    "lede": "A Catedral de Southwell é administrada por seu <strong>Capítulo</strong>, presidido pelo Decano, com o apoio e a supervisão do Conselho da Catedral e do Colégio de Cônegos em geral. Abaixo estão os principais titulares de cargos, conforme listados atualmente pela Catedral.",
    "people": [
      {
        "role": "Bispo de Southwell e Nottingham",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "O Reitor",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Cantor-mor",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Membro da Diretoria do Capítulo",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Membro Executivo da Seção",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Membro Sênior Não Executivo",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Reitor Chori (Diretor de Música)",
        "name": "Paul Provost"
      },
      {
        "role": "Diretor-adjunto de Música",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Chefe dos Sacristães",
        "name": "Andrew Todd"
      }
    ],
    "note": "Entre os membros não executivos do Capítulo estão também o Sr. Andrew Corner, o Sr. Nick Alexander, a Sra. Ann Carter-Gray, a Sra. Marion Oswald, o Sr. David Walker e o Sr. Jonathan Wheeler. A Catedral também conta com um Diretor de Operações e um Diretor Financeiro, além de cerca de 32 funcionários e aproximadamente 300 voluntários."
  },
  "music": {
    "num": "IV.",
    "heading": "Fundação de Música e corais",
    "lede": "Há mais de novecentos anos que um coro canta em Southwell — uma tradição ininterrupta de adoração coral que se estende desde os “Vicars Choral” medievais até o atual Coro da Catedral, composto por meninos e meninas, cantores leigos profissionais e o Minster Chorale, formado por voluntários.",
    "songHeading": "Nove séculos de música",
    "songParagraphs": [
      "A vida musical da Catedral teve início com um corpo de <strong>vigários corais</strong>, que residia nos edifícios que se erguiam no local onde hoje fica o Vicars’ Court. Um ou dois deles eram designados como <strong>Rector Chori</strong> — “Governante do Coro” —, um título registrado formalmente pela primeira vez em Southwell em <strong>1499</strong> e ainda hoje utilizado para designar o diretor musical. Meninos coristas foram incorporados aos vigários corais, e os vigários foram gradualmente substituídos por cantores leigos — os <strong>“Lay Clerks”</strong> —, conferindo ao coro, em grande parte, a forma que ele tem hoje.",
      "Em <strong>2005,</strong> um Coro de Meninas foi fundado pelo então Diretor Assistente de Música. Ele foi totalmente integrado ao Coro da Catedral em <strong>2019</strong>; hoje, os coristas meninos e meninas desfrutam de <strong>total paridade</strong>, compartilhando as celebrações, as vestimentas (batina e sobrepeliz), as faixas etárias e o título — todos são simplesmente Coristas da Catedral. Em <strong>2021</strong>, Southwell nomeou sua <strong>primeira corista-chefe mulher</strong> na história milenar da Catedral, e em 2025 a Catedral comemorou o vigésimo aniversário do Coro de Meninas."
    ],
    "figureAlt": "O púlpito medieval de pedra da Catedral de Southwell, com o órgão Nicholson instalado acima dele.",
    "figureCaption": "O púlpito com o órgão principal Nicholson instalado acima, em sua caixa Caröe.",
    "choirsHeading": "Os corais de hoje",
    "features": [
      {
        "heading": "Meninos do coro",
        "body": "O tradicional coro de vozes agudas, proveniente da The Minster School. Os meninos costumam cantar sozinhos nas Vésperas de segunda e terça-feira e se juntam aos Lay Clerks de quinta a domingo durante o período letivo, alternando-se com as meninas."
      },
      {
        "heading": "Meninas do coro",
        "body": "Fundado em 2005, o grupo é hoje composto por parceiras em plena igualdade no Coro da Catedral — atualmente, cerca de 18 meninas, que compartilham todas as funções de coristas, ensaios, turnês e gravações em pé de igualdade com os meninos."
      },
      {
        "heading": "Leigos",
        "body": "Seis coristas leigos profissionais e seis coristas leigos auxiliares — as vozes adultas de contralto, tenor e baixo, descendentes diretos dos vicários corais medievais. Eles cantam com os coristas de quinta a domingo e nos dias de festa."
      },
      {
        "heading": "O Coro da Catedral",
        "body": "Fundado em <strong>1994</strong>, é um coro voluntário de adultos, com até trinta cantores selecionados por meio de audições, dirigido pelo Diretor Assistente de Música. Canta nas celebrações quando o Coro da Catedral está de folga, além das matinas dominicais mensais."
      },
      {
        "heading": "A Escola Minster",
        "body": "Todos os coristas estudam na <strong>The Minster School</strong>, uma academia da Igreja da Inglaterra que possui um Departamento de Ensino Fundamental (3º ao 6º ano) especializado em música e é membro da Associação das Escolas de Corais."
      },
      {
        "heading": "Sociedade Coral de Southwell",
        "body": "Um coro comunitário sem seleção por audição, com mais de sessenta anos de história, que ensaia semanalmente na Catedral durante o período letivo — a comunidade musical mais ampla que se reúne em torno da fundação."
      }
    ],
    "organsHeading": "Os órgãos",
    "organsBody": "O órgão principal da catedral está instalado no púlpito medieval, em um gabinete de carvalho projetado por <strong>W. D. Caröe</strong>. O atual órgão de tela foi reconstruído ao longo da década de 1990 por renomados construtores de órgãos (assessorados por John Norman, Stephen Bicknell e Ian Bell), tendo o gabinete de Caröe sido preservado por motivos históricos. Um <strong>órgão</strong> separado <strong>da nave</strong>, cuja linhagem remonta a um instrumento de 1662 construído por “Sr. Derbie” e que passou por reparos após o grande incêndio de 1711, acompanha o canto da congregação na extremidade oeste, e um belo <strong>órgão de câmara</strong> é utilizado para o continuo e para liturgias em menor escala. Um livreto ilustrado de 72 páginas, intitulado <em>*The Organs of Southwell Minster*</em>, de autoria do ex-reitor do coro Paul Hale, está disponível na loja da catedral."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturgia e celebrações diárias",
    "lede": "A rotina diária de orações do Reitor segue o modelo do “Common Worship” da Igreja da Inglaterra, mantida durante o período letivo por uma das mais renomadas fundações de música catedral do país.",
    "paragraphs": [
      "Southwell mantém um <strong>ofício diário</strong> completo <strong>da catedral anglicana</strong>: a Oração da Manhã, a Santa Comunhão (a Eucaristia) e a Oração da Tarde ou Véspera são celebradas todos os dias. A maioria dos dias, durante o período letivo, as celebrações com coro são entoadas pelo <strong>Coro</strong> da <strong>Catedral</strong> — composto pelos meninos e meninas do coro e pelos coristas leigos —, que, juntos, proporcionam a música para oito celebrações com coro por semana. Aos domingos, os meninos e meninas do coro cantam a Eucaristia e a Véspera em rodízio com os cantores leigos. Outras celebrações são cantadas pelo <strong>Minster Chorale</strong>, um coro de câmara com até trinta cantores voluntários, fundado em 1994.",
      "<strong>A Eucaristia dominical na Catedral (10h)</strong> e <strong>as Vésperas dominicais (15h30)</strong> são transmitidas ao vivo e permanecem disponíveis online por uma semana e um dia, respectivamente. Visitantes de todas as tradições são calorosamente bem-vindos; a entrada é gratuita."
    ],
    "figureAlt": "O coro da Catedral de Southwell, visto do lado leste, mostrando os bancos medievais e as abóbadas de pedra.",
    "figureCaption": "A capela Early English, onde a oração vespertina coral é entoada quase todos os dias durante o período letivo.",
    "weekdayHeading": "Padrão dos dias da semana",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Oração da Manhã — <em>Capela de São Oswaldo</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Santa Comunhão — <em>Igreja de São Oswald / Capela dos Aviadores</em> <br /><small>(sábados: 9h)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Vésperas Corais — <em>O Coro</em> <br /><small>(recitadas às quartas-feiras; cantadas às segundas, terças, quintas, sextas e sábados durante o período letivo)</small>"
      }
    ],
    "sundayHeading": "Padrão de domingo",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Santa Ceia (BCP, celebrada)"
      },
      {
        "clock": "10.00am",
        "detail": "Eucaristia cantada na Catedral — <em>transmitida ao vivo</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Vésperas Corais — <em>transmitidas ao vivo</em>"
      }
    ],
    "timesNote": "<em>Os horários das missas podem variar em dias de festa religiosa e durante as férias escolares — verifique o Calendário de Missas no site da Catedral antes de viajar.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Horário de funcionamento",
    "lede": "A Catedral está aberta aos visitantes todos os dias do ano, sem cobrança de entrada. Doações para sua manutenção são muito bem-vindas.",
    "cards": [
      {
        "heading": "A Catedral",
        "rows": [
          {
            "days": "Segunda-feira a sábado",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "Domingo",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Os atendentes normalmente estão de plantão das 10h30 às 17h (de segunda a sábado) e das 11h às 17h aos domingos. O serviço pode ser suspenso ou o local fechado ocasionalmente para eventos, com aviso prévio de última hora."
      },
      {
        "heading": "Gabinete do Ministro",
        "rows": [
          {
            "days": "Segunda a sexta-feira",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "O Minster Centre abriga o escritório, a equipe de educação e o ponto de informações turísticas."
      },
      {
        "heading": "Refeitório",
        "rows": [
          {
            "days": "Seg. – Sáb.",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "Domingo",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Loja da Catedral",
        "rows": [
          {
            "days": "Seg. – Sáb.",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "Domingo",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Palácio e Jardins do Arcebispo",
        "rows": [
          {
            "days": "Diário",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Entrada gratuita nas ruínas do palácio medieval e nos jardins sensoriais adjacentes à Catedral."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Faça uma doação",
    "paragraphs": [
      "A pedra acima de vocês foi erguida em 1108. É a melhor nave normanda ainda de pé na Inglaterra — arco redondo após arco redondo, esculpida por homens que sabiam que nunca viveriam para ver o telhado fechado sobre eles.",
      "E caminhe para o leste, em direção à Sala do Capítulo. Lá, esculpidas na pedra há oitocentos anos, estão as folhas deste condado. Espinheiro; carvalho; bordo; botão-de-ouro e videira. Quem quer que as tenha esculpido claramente havia caminhado pela floresta e observado — <strong>realmente</strong> observado — um ser vivo, e o transformou em algo permanente. Elas não murcharam em sete séculos.",
      "Nada disso é um museu. É um local de culto ativo, onde ainda se realizam cerimônias, ainda se canta e ainda se acende a luz; um lugar de calor espiritual e conforto.",
      "Custa mais de cinco mil libras por dia apenas para manter essas portas abertas — o aquecimento, os vitrais, os tecidos, os coristas, a liturgia.",
      "A entrada é gratuita. Sempre foi assim, e a Seção vai continuar mantendo assim. Você pode, no entanto, desempenhar um papel importante ao ajudar nessa missão. No ano passado, cada visitante doou, em média, uma libra e oitenta e oito pence.",
      "Gostaríamos de pedir a você uma doação de cinco libras.",
      "Se este lugar proporcionou a você um momento de tranquilidade hoje e enriqueceu o seu dia, por favor, ajude-nos — clicando no botão “Doar agora”: marque a opção “Gift Aid” se você for contribuinte no Reino Unido: para cada £5, serão acrescentados £1,25 a mais, e isso não lhe custará nada a mais."
    ],
    "button": "Faça uma doação agora",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "Acima de tudo, por favor, saibam que vocês saem deste lugar sem nenhuma obrigação. Por favor, contribuam apenas de acordo com suas possibilidades. Não doem o que não podem arcar. Vocês sempre partem com a bênção do Senhor.",
    "close": "As folhas já duram oitocentos anos. Se vão durar mais oitocentos, isso, de certa forma, depende de nós."
  },
  "projects": {
    "num": "VIII.",
    "heading": "Nossos projetos",
    "lede": "Projetos em andamento e planejados na Catedral de Southwell — o conteúdo desta seção será publicado em breve.",
    "placeholderLabel": "Nossos projetos — em breve",
    "placeholderBody": "Espaço reservado para resumos, imagens e atualizações dos projetos. Adicione entradas individuais dos projetos quando estiver pronto."
  },
  "contact": {
    "num": "IX.",
    "heading": "Contato e como chegar até nós",
    "minsterHeading": "Catedral de Southwell",
    "addressLabel": "Endereço",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Telefone",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Sede)",
    "emailLabel": "E-mail",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Site",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Clérigos urgentes",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Loja",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Como chegar",
    "gettingHere": [
      "Southwell é uma pequena cidade mercantil na região central de Nottinghamshire, a sete milhas da A1 e a cerca de 30 minutos de carro de Nottingham pela A612. A catedral fica na Church Street, no centro da cidade, a uma curta caminhada da praça do mercado de sábado.",
      "<strong>As visitas guiadas</strong> podem ser agendadas com antecedência pelo escritório da catedral; <strong>as visitas educacionais</strong> são organizadas separadamente pelo telefone <a href=\"tel:+441636817287\">01636 817287</a>.",
      "<strong>Culto online:</strong> a Eucaristia dominical e a Véspera são transmitidas ao vivo pelo site da Catedral e permanecem disponíveis para assistir na semana seguinte."
    ],
    "socialPrefix": "Redes sociais:",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Guia conciso para visitantes, elaborado a partir de publicações da própria Catedral, da Associação das Catedrais Inglesas e da Wikipédia. Não se trata de uma publicação oficial da Catedral.",
    "photos": "Fotografias: fachada oeste, janela oeste, coro, portal da Sala Capitular e púlpito com órgão — Wikimedia Commons (colaboradores Diliff e Geograph), CC BY-SA."
  }
}
