import type { SouthwellMinsterCopy } from "./southwellMinster"

/** it copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_IT: SouthwellMinsterCopy = {
  "audioHint": "Lì dove vedi il controllo dell'audio qui sotto, e in ogni sezione in cui è presente l'icona dell'audio, puoi ascoltare mentre navighi o ti sposti all'interno del sito. Ti preghiamo di utilizzare le cuffie o gli auricolari.",
  "eyebrow": "Nottinghamshire · Chiesa d'Inghilterra",
  "title": "Cattedrale di Southwell",
  "tagline": "La Cattedrale e Chiesa Parrocchiale della Beata Vergine Maria — un gioiello normanno delle Midlands inglesi, luogo di preghiera ininterrotta dal 627.",
  "meta": [
    "Fondata intorno al 627",
    "Ricostruzione di Norman a partire dal 1108",
    "Cattedrale dal 1884"
  ],
  "welcome": {
    "invite": "Ascolta il messaggio di benvenuto di padre Stephen",
    "videoUnsupported": "Il tuo browser non supporta l'elemento video.",
    "placeholderLabel": "Video di benvenuto — in arrivo",
    "role": "Il Molto Reverendo",
    "name": "Dr Stephen Evans",
    "title": "Decano della Cattedrale di Southwell"
  },
  "toc": [
    {
      "href": "#history",
      "label": "Storia"
    },
    {
      "href": "#treasures",
      "label": "Tesori e interni"
    },
    {
      "href": "#officers",
      "label": "Dirigenti principali"
    },
    {
      "href": "#music",
      "label": "Musica e cori"
    },
    {
      "href": "#worship",
      "label": "Liturgia e funzioni religiose"
    },
    {
      "href": "#visit",
      "label": "Orari di apertura"
    },
    {
      "href": "#donate",
      "label": "Fai una donazione"
    },
    {
      "href": "#projects",
      "label": "I nostri progetti"
    },
    {
      "href": "#contact",
      "label": "Contatti"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Una breve storia",
    "lede": "A Southwell sorge una cattedrale da ben oltre mille anni — che è sopravvissuta ai Vichinghi, alla Riforma, alla guerra civile e a un incendio — e oggi funge da chiesa madre della diocesi di Southwell e Nottingham.",
    "paragraphs": [
      "La tradizione vuole che <strong>Paolino, primo arcivescovo di York, fondò qui la prima chiesa nel 627,</strong> mentre battezzava i convertiti nel fiume Trent. Nel <strong>956</strong> il re Eadwig concesse un appezzamento di terreno a Southwell a Oskytel, arcivescovo di York, e vi fu fondata una chiesa minster sassone; il feudo fu descritto in dettaglio nel <em>Domesday Book</em> del 1086.",
      "L'attuale <strong>cattedrale normanna</strong> fu iniziata intorno <strong>al 1108</strong>, ricostruita sulle precedenti fondamenta anglosassoni. La navata, i transetti, la torre centrale e le due torri occidentali a forma di “pepperpot” sono giunti fino a noi come uno dei migliori esempi di austero stile romanico in Inghilterra. Il <strong>coro in stile primo inglese</strong> fu ricostruito tra il 1234 e il 1251, mentre la celebre <strong>Sala Capitolare</strong> fu iniziata nel 1288.",
      "Soppressa da Enrico VIII nel <strong>1540</strong>, la chiesa collegiata fu rifondata nel 1543, perse nuovamente il proprio status nel 1548 e fu infine ripristinata nel 1557. Durante la guerra civile, <strong>Carlo I si arrese a Southwell nel 1646</strong> dopo l’assedio di Newark. Nel <strong>1711</strong> un fulmine colpì la guglia sud-occidentale e un incendio distrusse i tetti, le campane, l’orologio e l’organo; entrambe le guglie furono rimosse nel 1805 e ricostruite solo nel 1879–81 durante l’ampio restauro vittoriano curato da Ewan Christian.",
      "Il Minster divenne <strong>cattedrale nel 1884</strong>, quando fu istituita la nuova diocesi di Southwell per servire il Nottinghamshire e il Derbyshire (Derby divenne una diocesi a sé stante nel 1927). È tuttora dedicata alla Beata Vergine Maria e, caso unico tra le cattedrali inglesi, conserva il suo antico titolo di <em>«Minster</em>»."
    ],
    "figureAlt": "La grande finestra occidentale della cattedrale di Southwell, incorniciata dalle due torri normanne a forma di “pepperpot”.",
    "figureCaption": "La facciata occidentale in stile normanno, con le sue caratteristiche torri a “pepperpot” e la “Finestra dell’Angelo” realizzata nel 1996 da Patrick Reyntiens.",
    "timelineLabel": "Cronologia della Cattedrale di Southwell",
    "timeline": [
      {
        "year": "627",
        "text": "Paolino, primo arcivescovo di York, a cui si attribuisce la fondazione di una chiesa a Southwell."
      },
      {
        "year": "956",
        "text": "Il re Eadwig concede dei terreni all'arcivescovo Oskytel; viene fondata una chiesa sassone."
      },
      {
        "year": "1108",
        "text": "La ricostruzione in stile normanno iniziò dall'estremità orientale; la navata centrale fu avviata dopo il 1120."
      },
      {
        "year": "1234–51",
        "text": "Il fascicolo del primo inglese è stato ricostruito."
      },
      {
        "year": "1288",
        "text": "Inizia la costruzione della Sala Capitolare ottagonale."
      },
      {
        "year": "1320–40",
        "text": "Il grande “pulpitum” (tribuna del coro) in pietra è scolpito in stile decorato."
      },
      {
        "year": "1540–57",
        "text": "Soppressa sotto Enrico VIII, ripristinata sotto Filippo e Maria."
      },
      {
        "year": "1646",
        "text": "Carlo I si arrende alle truppe presbiteriane scozzesi a Southwell."
      },
      {
        "year": "1711",
        "text": "Un fulmine; l'incendio distrugge i tetti, le campane, l'orologio e l'organo."
      },
      {
        "year": "1879–81",
        "text": "Restauro della chiesa di Ewan Christian; le guglie occidentali vengono ricostruite."
      },
      {
        "year": "1884",
        "text": "La cattedrale di Southwell diventa la sede della nuova diocesi."
      },
      {
        "year": "1996",
        "text": "La magnifica “Finestra degli Angeli” di Patrick Reyntiens, installata all’estremità occidentale."
      },
      {
        "year": "2021",
        "text": "La Sala Capitolare riapre dopo un importante intervento di restauro, dotata di un ascensore a sbalzo che garantisce piena accessibilità."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Tesori e luoghi di interesse",
    "lede": "Dalle più belle intagliature medievali inglesi raffiguranti foglie a una finestra orientale fiamminga del XVI secolo, la cattedrale è straordinariamente ricca di elementi che meritano una sosta.",
    "leavesHeading": "Le foglie di Southwell",
    "leavesBody": "La <strong>Sala Capitolare</strong> (iniziata nel 1288) è ottagonale, priva di pilastro centrale ed è decorata con intagli di fogliame profondamente incisi, noti collettivamente come <strong>“Le Foglie di Southwell”.</strong> Le singole specie — edera, acero, quercia, luppolo, biancospino — sono tutte riconoscibili, intervallate da «Uomini Verdi» e figure mitologiche. Considerate le più belle sculture naturalistiche del XIII secolo nel Regno Unito, sono state oggetto della classica monografia di Nikolaus Pevsner del 1945 e sono state votate come il tesoro cattedrale preferito dai britannici in un sondaggio pubblico del 2023.",
    "figureAlt": "Intagli naturalistici su foglia risalenti al XIII secolo che adornano l’arco d’ingresso della Sala Capitolare della Cattedrale di Southwell.",
    "figureCaption": "“Le foglie di Southwell” — intagli di fogliame del XIII secolo che adornano il portale della Sala Capitolare, eletti nel 2023 tesoro della cattedrale preferito dalla nazione.",
    "features": [
      {
        "heading": "La navata normanna",
        "body": "Sette campate con colonne corte e circolari dai capitelli smerlati; un unico grande arco di triforio in ciascuna campata; piccole finestre a tutto sesto nel cleristorio e aperture esterne circolari — uno dei più straordinari esempi giunti fino a noi del rigoroso stile romanico inglese."
      },
      {
        "heading": "Il timpano",
        "body": "Il timpano scolpito risalente alla fine dell'XI secolo, situato nel transetto nord, insieme a un frammento di pavimento a mosaico, costituisce l'unico resto visibile dell'antica cattedrale anglosassone."
      },
      {
        "heading": "Il pulpito (trave trasversale)",
        "body": "Una transenna del coro in pietra finemente scolpita, risalente al 1320–40, esempio eccezionale dello stile decorato, con due file di nicchie ad arco ogivale e frontoni traforati che incorniciano l’ingresso al coro."
      },
      {
        "heading": "Il fascicolo inglese antico",
        "body": "Ricostruita tra il 1234 e il 1251 in puro stile inglese primitivo: colonne raggruppate, finestre a lancetta doppie al piano superiore, volta a costoloni in pietra e una facciata orientale quadrata illuminata da due file di quattro finestre a lancetta."
      },
      {
        "heading": "La finestra a est",
        "body": "Quattro pannelli rinascimentali in vetro fiammingo del XVI secolo realizzati da Jean Chastellain, su disegno di Noël Bellemare, originariamente destinati alla Temple Church di Parigi e donati alla Cattedrale nel 1818; i quattro evangelisti raffigurati in alto sono opera di Clayton & Bell (1876)."
      },
      {
        "heading": "La finestra dell’angelo",
        "body": "Installata nell'ala ovest nel <strong>1996</strong>, questa splendida vetrata moderna opera di <strong>Patrick Reyntiens</strong> — uno dei più importanti artisti britannici specializzati in vetrate artistiche — è l'aggiunta più suggestiva apportata di recente alla cattedrale."
      },
      {
        "heading": "Tomba dell'arcivescovo Sandys",
        "body": "Il più bello tra i monumenti commemorativi della cattedrale: la tomba in alabastro di <strong>Edwin Sandys, arcivescovo di York (morto nel 1588)</strong>, la cui famiglia possedeva da tempo delle tenute nel Nottinghamshire."
      },
      {
        "heading": "Il leggio di Newstead",
        "body": "Un leggio medievale a forma di aquila in ottone, che si ritiene sia stato recuperato dal lago dell’Abbazia di Newstead dopo la Dissoluzione e donato alla Cattedrale dall’arcidiacono Kaye nel 1805."
      },
      {
        "heading": "La torre centrale normanna",
        "body": "Due livelli decorativi — archi intrecciati nella parte inferiore, archi semplici in quella superiore — collocano la torre di incrocio ai vertici tra le torri normanne ancora esistenti in Inghilterra."
      },
      {
        "heading": "Cappelle per la preghiera",
        "body": "Tre cappelle sono riservate alla preghiera privata, tra cui <strong>la Cappella di Sant’Oswald</strong> (utilizzata quotidianamente per la preghiera del mattino e la Santa Comunione) e la <strong>Cappella degli aviatori</strong>, dedicata alla memoria del Bomber Command della RAF nel Nottinghamshire."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Dirigenti principali",
    "lede": "La Cattedrale di Southwell è amministrata dal proprio <strong>Capitolo</strong>, presieduto dal Decano, con il sostegno e la supervisione del Consiglio della Cattedrale e del più ampio Collegio dei Canonici. Di seguito sono elencati i principali titolari di cariche, secondo l’elenco attualmente fornito dalla Cattedrale.",
    "people": [
      {
        "role": "Vescovo di Southwell e Nottingham",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "Il Preside",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Cantore principale",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Membro esecutivo della sezione locale",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Membro esecutivo della sezione locale",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Membro senior non esecutivo",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Rettore Chori (Direttore musicale)",
        "name": "Paul Provost"
      },
      {
        "role": "Vicedirettore musicale",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Capo sacrestano",
        "name": "Andrew Todd"
      }
    ],
    "note": "Tra i membri non esecutivi del Capitolo figurano anche il sig. Andrew Corner, il sig. Nick Alexander, la sig.ra Ann Carter-Gray, la sig.ra Marion Oswald, il sig. David Walker e il sig. Jonathan Wheeler. La Cattedrale impiega inoltre un direttore operativo e un direttore finanziario, oltre a circa 32 dipendenti e circa 300 volontari."
  },
  "music": {
    "num": "IV.",
    "heading": "Fondazione musicale e cori",
    "lede": "A Southwell un coro canta da oltre novecento anni: una tradizione ininterrotta di culto corale che va dai “Vicari Corali” medievali all’odierno Coro della Cattedrale, composto da coristi e coriste, da cantori laici professionisti e dal coro volontario “Minster Chorale”.",
    "songHeading": "Nove secoli di musica",
    "songParagraphs": [
      "La vita musicale della cattedrale ebbe inizio con un collegio di <strong>vicari corali</strong>, che risiedeva negli edifici che sorgevano dove oggi si trova la Vicars’ Court. Uno o due di loro venivano designati come <strong>Rector Chori</strong> — “Capo del coro” — un titolo registrato formalmente per la prima volta a Southwell nel <strong>1499</strong> e ancora oggi utilizzato per indicare il direttore musicale. Ai vicari corali si aggiunsero i coristi fanciulli, e i vicari furono gradualmente sostituiti da cantori laici — i <strong>Lay Clerks</strong> — conferendo al coro sostanzialmente la forma che ha oggi.",
      "Nel <strong>2005</strong> l’allora vicedirettore musicale fondò un coro femminile. Nel <strong>2019</strong> esso è stato pienamente integrato nel coro della cattedrale; oggi i coristi e le coriste godono di <strong>piena parità</strong>, condividendo le funzioni, le vesti liturgiche (sottoveste e cotta), le fasce d’età e il titolo: tutti sono semplicemente “coristi della cattedrale”. Nel <strong>2021</strong> Southwell ha nominato <strong>la</strong> sua <strong>prima capocoro donna</strong> in mille anni di storia della Cattedrale, e nel 2025 la Cattedrale ha celebrato il ventesimo anniversario del coro delle ragazze."
    ],
    "figureAlt": "Il pulpito medievale in pietra della Cattedrale di Southwell, con l’organo Nicholson installato nella parte superiore.",
    "figureCaption": "Il pulpitum con l'organo principale Nicholson montato sopra, nella sua cassa Caröe.",
    "choirsHeading": "I cori di oggi",
    "features": [
      {
        "heading": "Ragazzi del coro",
        "body": "La tradizionale linea dei soprani, proveniente dalla Minster School. I ragazzi cantano solitamente da soli durante i vespri del lunedì e del martedì e si uniscono ai Lay Clerks dal giovedì alla domenica durante il periodo scolastico, alternandosi con le ragazze."
      },
      {
        "heading": "Ragazze del coro",
        "body": "Fondato nel 2005, oggi i suoi membri sono partner a pieno titolo del Coro della Cattedrale — attualmente composto da circa 18 ragazze, che condividono tutti i compiti dei coristi, le prove, le tournée e le registrazioni alla pari dei ragazzi."
      },
      {
        "heading": "Laici addetti all’amministrazione",
        "body": "Sei coristi laici professionisti e sei coristi laici ausiliari — le parti di contralto, tenore e basso degli adulti, diretti discendenti dei vicari corali medievali. Cantano insieme ai coristi dal giovedì alla domenica e nei giorni di festa."
      },
      {
        "heading": "Il coro della cattedrale",
        "body": "Fondato nel <strong>1994</strong>, è un coro amatoriale per adulti composto da un massimo di trenta cantanti selezionati tramite audizione e diretto dal vicedirettore musicale. Si esibisce durante le funzioni quando il coro della cattedrale è in congedo, oltre che durante le funzioni domenicali del Mattutino."
      },
      {
        "heading": "La Minster School",
        "body": "Tutti i coristi frequentano <strong>la Minster School</strong>, un’accademia della Chiesa d’Inghilterra dotata di un dipartimento junior (anni 3–6) specializzato in musica e membro della Choir Schools’ Association."
      },
      {
        "heading": "Società Corale di Southwell",
        "body": "Un coro comunitario senza audizioni, attivo da oltre sessant’anni, che si riunisce settimanalmente nella cattedrale durante il periodo scolastico: la più ampia comunità musicale che ruota attorno alla fondazione."
      }
    ],
    "organsHeading": "Gli organi",
    "organsBody": "Lo strumento principale della cattedrale è collocato sul pulpito medievale, all’interno di una cassa in quercia progettata da <strong>W. D. Caröe</strong>. L’attuale organo da transenna è stato ricostruito nel corso degli anni ’90 da importanti costruttori di organi (con la consulenza di John Norman, Stephen Bicknell e Ian Bell), conservando la cassa di Caröe per motivi storici. Un <strong>organo</strong> separato <strong>della navata</strong>, la cui discendenza risale a uno strumento del 1662 realizzato da “Mr Derbie” e sottoposto a riparazioni dopo il grande incendio del 1711, accompagna il canto della congregazione nell’ala occidentale, mentre un raffinato <strong>organo da camera</strong> viene utilizzato per il basso continuo e le liturgie su scala più ridotta. Un opuscolo illustrato di 72 pagine, intitolato <em>*The Organs of Southwell Minster*</em> e redatto dall’ex Rettore del Coro Paul Hale, è disponibile presso il negozio della cattedrale."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturgia e funzioni quotidiane",
    "lede": "Il programma quotidiano di preghiera del ministro segue lo schema del “Common Worship” della Chiesa d’Inghilterra, sostenuto durante il periodo scolastico da una delle più prestigiose fondazioni di musica cattedrale del Paese.",
    "paragraphs": [
      "A Southwell si celebra integralmente l’<strong>ufficio quotidiano della cattedrale anglicana</strong>: ogni giorno vengono celebrate la preghiera del mattino, la Santa Comunione (l’Eucaristia) e la preghiera della sera o Evensong. Durante i periodi scolastici, la maggior parte dei giorni le funzioni corali sono cantate dal <strong>Coro</strong> <strong>della</strong> <strong>Cattedrale</strong> — composto dai coristi maschi, dalle coriste e dai cantori laici — che, insieme, assicurano l’accompagnamento musicale per otto funzioni corali alla settimana. La domenica i coristi e le coriste cantano l’Eucaristia e l’Evensong a rotazione con i cantori laici. Ulteriori funzioni sono cantate dal <strong>Minster Chorale</strong>, un coro da camera composto da un massimo di trenta cantori volontari fondato nel 1994.",
      "<strong>La Messa domenicale in cattedrale (ore 10.00)</strong> e <strong>il Vespro domenicale (ore 15.30)</strong> vengono trasmessi in diretta streaming e rimangono disponibili online rispettivamente per una settimana e un giorno. I visitatori di ogni tradizione sono i benvenuti; l’ingresso è gratuito."
    ],
    "figureAlt": "Il coro della Cattedrale di Southwell visto verso est, con i banchi medievali e le volte in pietra.",
    "figureCaption": "La cappella Early English, dove quasi tutti i giorni durante il semestre si canta il vespro corale.",
    "weekdayHeading": "Andamento nei giorni feriali",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Preghiera del mattino — <em>Cappella di Sant’Osvaldo</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Santa Comunione — <em>Cappella di Sant’Oswaldo / Cappella degli aviatori</em> <br /><small>(sabato: ore 9.00)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Vespri corali — <em>Il coro</em> <br /><small>(recitati il mercoledì; cantati lunedì, martedì, giovedì, venerdì e sabato durante il periodo scolastico)</small>"
      }
    ],
    "sundayHeading": "Schema della domenica",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Santa Comunione (BCP, recitata)"
      },
      {
        "clock": "10.00am",
        "detail": "Eucaristia celebrata nella Cattedrale di Sung — <em>trasmessa in diretta streaming</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Vespri corali — <em>in diretta streaming</em>"
      }
    ],
    "timesNote": "<em>Gli orari delle funzioni possono variare nei giorni di festa e durante le vacanze scolastiche: si prega di consultare il calendario delle funzioni sul sito web della Cattedrale prima di mettersi in viaggio.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Orari di apertura",
    "lede": "La cattedrale è aperta ai visitatori tutti i giorni dell'anno, gratuitamente. Si accettano con gratitudine donazioni a sostegno della sua manutenzione.",
    "cards": [
      {
        "heading": "La cattedrale",
        "rows": [
          {
            "days": "Dal lunedì al sabato",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "Domenica",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Il personale di assistenza è normalmente in servizio dalle 10.30 alle 17.00 (dal lunedì al sabato) e dalle 11.00 alle 17.00 la domenica. Potrebbero verificarsi chiusure occasionali del servizio o in occasione di eventi con breve preavviso."
      },
      {
        "heading": "Ufficio del ministro",
        "rows": [
          {
            "days": "Dal lunedì al venerdì",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "Il Minster Centre ospita gli uffici, il team didattico e il punto informazioni turistiche."
      },
      {
        "heading": "Sala da pranzo",
        "rows": [
          {
            "days": "Lun – Sab",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "Domenica",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Negozio della cattedrale",
        "rows": [
          {
            "days": "Lun – Sab",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "Domenica",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Palazzo Arcivescovile e Giardini",
        "rows": [
          {
            "days": "Quotidiano",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Ingresso gratuito alle rovine del palazzo medievale e ai giardini sensoriali adiacenti alla cattedrale."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Fai una donazione",
    "paragraphs": [
      "La pietra che si trova sopra di voi fu eretta nel 1108. È la navata normanna meglio conservata di tutta l’Inghilterra: un arco a tutto sesto dopo l’altro, scolpiti da uomini che sapevano che non sarebbero mai vissuti abbastanza a lungo da vedere il tetto chiudersi sopra di loro.",
      "E cammina verso est, fino alla Sala Capitolare. Lì, scolpite nella pietra ottocento anni fa, ci sono le foglie simbolo di questa contea. Biancospino, quercia, acero, ranuncolo e vite. Chiunque le abbia scolpite si era chiaramente addentrato nei boschi e aveva osservato — osservato <strong>davvero</strong> — un essere vivente, rendendolo immortale. Non sono appassite in sette secoli.",
      "Niente di tutto questo è un museo. È un luogo di culto attivo, dove si celebrano ancora le funzioni, si canta ancora e si accendono ancora le luci; un luogo di calore spirituale e conforto.",
      "Ci vogliono più di cinquemila sterline al giorno solo per tenere aperte queste porte: il riscaldamento, i vetri, i tessuti, i coristi, la liturgia.",
      "L’ingresso è gratuito. Lo è sempre stato e la Sezione farà in modo che continui ad esserlo. Potete però dare un contributo importante a questa missione. L’anno scorso ogni visitatore ha donato in media una sterlina e ottantotto pence.",
      "Vorremmo chiedervi una donazione di cinque sterline.",
      "Se oggi questo posto ti ha regalato un momento di tranquillità e ha arricchito la tua giornata, ti invitiamo a sostenerlo cliccando sul pulsante “Dona ora”: se sei un contribuente del Regno Unito, seleziona l’opzione “Gift Aid”: per ogni 5 sterline donate, ne verranno aggiunte altre 1,25, senza alcun costo aggiuntivo per te."
    ],
    "button": "Dona ora",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "Soprattutto, vi preghiamo di tenere presente che quando lasciate questo luogo non avete alcun obbligo. Vi preghiamo di donare solo secondo le vostre possibilità. Non donate ciò che non potete permettervi. Partite sempre con la benedizione del Signore.",
    "close": "Le foglie sono sopravvissute per ottocento anni. Che ne sopravvivano altri ottocento dipende, in modo piuttosto discreto, da noi."
  },
  "projects": {
    "num": "VIII.",
    "heading": "I nostri progetti",
    "lede": "Progetti in corso e in programma alla Cattedrale di Southwell — i contenuti di questa sezione saranno pubblicati a breve.",
    "placeholderLabel": "I nostri progetti — in arrivo",
    "placeholderBody": "Spazio riservato alle descrizioni dei progetti, alle immagini e agli aggiornamenti. Aggiungere le singole voci relative ai progetti quando saranno pronte."
  },
  "contact": {
    "num": "IX.",
    "heading": "Contatti e come raggiungerci",
    "minsterHeading": "Cattedrale di Southwell",
    "addressLabel": "Indirizzo",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Telefono",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Sede centrale)",
    "emailLabel": "E-mail",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Sito web",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Clero urgente",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Negozio",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Come arrivare",
    "gettingHere": [
      "Southwell è una piccola cittadina di mercato situata nel cuore del Nottinghamshire, a sette miglia dall’A1 e a circa 30 minuti di auto da Nottingham lungo la A612. La cattedrale sorge in Church Street, nel centro della città, a pochi passi dalla piazza del mercato del sabato.",
      "È possibile prenotare in anticipo <strong>le visite guidate</strong> presso l'ufficio della cattedrale; <strong>le visite didattiche</strong> vanno concordate separatamente al numero <a href=\"tel:+441636817287\">01636 817287</a>.",
      "<strong>Celebrazioni online:</strong> l’Eucaristia domenicale e il Vespro vengono trasmessi in diretta streaming dal sito web della Cattedrale e rimangono disponibili per la visione in differita durante la settimana successiva."
    ],
    "socialPrefix": "Social media:",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Guida sintetica per i visitatori redatta attingendo alle pubblicazioni della stessa Cattedrale, all’Associazione delle Cattedrali Inglesi e a Wikipedia. Non si tratta di una pubblicazione ufficiale della Cattedrale.",
    "photos": "Fotografie: facciata occidentale, finestra occidentale, coro, portale della Sala Capitolare e pulpito con organo — Wikimedia Commons (contributori Diliff e Geograph), CC BY-SA."
  }
}
