import type { SouthwellMinsterCopy } from "./southwellMinster"

/** tr copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_TR: SouthwellMinsterCopy = {
  "audioHint": "Aşağıda ses kontrolünü gördüğünüz yerde ve ses simgesinin bulunduğu her bölümde, sayfada gezinirken veya başka bir yere geçerken ses dinleyebilirsiniz. Lütfen kulaklıklarınızı veya kulak içi kulaklıklarınızı kullanın.",
  "eyebrow": "Nottinghamshire · İngiltere Kilisesi",
  "title": "Southwell Katedrali",
  "tagline": "Kutsal Meryem Ana Katedrali ve Cemaat Kilisesi — İngiliz Midlands bölgesinin Norman mimari şaheseri; 627 yılından beri kesintisiz bir dua ortamıdır.",
  "meta": [
    "Yaklaşık 627 yılında kuruldu",
    "1108'den itibaren Normanların yeniden inşası",
    "1884'ten beri katedral"
  ],
  "welcome": {
    "invite": "Peder Stephen’ın hoş geldiniz mesajını dinleyin",
    "videoUnsupported": "Tarayıcınız video öğesini desteklemiyor.",
    "placeholderLabel": "Tanıtım videosu — yakında yayınlanacak",
    "role": "Çok Saygıdeğer",
    "name": "Dr Stephen Evans",
    "title": "Southwell Minster Başrahibi"
  },
  "toc": [
    {
      "href": "#history",
      "label": "Tarihçe"
    },
    {
      "href": "#treasures",
      "label": "Hazineler ve iç mekan"
    },
    {
      "href": "#officers",
      "label": "Üst düzey yetkililer"
    },
    {
      "href": "#music",
      "label": "Müzik ve korolar"
    },
    {
      "href": "#worship",
      "label": "Ayin ve ibadetler"
    },
    {
      "href": "#visit",
      "label": "Çalışma saatleri"
    },
    {
      "href": "#donate",
      "label": "Bağış Yap"
    },
    {
      "href": "#projects",
      "label": "Projelerimiz"
    },
    {
      "href": "#contact",
      "label": "İletişim"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Kısa bir tarihçe",
    "lede": "Southwell’de bin yıldan da fazla bir süredir ayakta duran bir katedral kilisesi — Vikingler, Reformasyon, iç savaş ve yangınları atlatarak günümüze kadar gelmiştir — ve bugün Southwell & Nottingham Piskoposluğu’nun ana kilisesi olarak hizmet vermektedir.",
    "paragraphs": [
      "Geleneklere göre, <strong>York’un ilk başpiskoposu Paulinus, 627 yılında</strong> Trent Nehri’nde din değiştiren kişilere vaftiz verirken <strong>buradaki en eski kiliseyi kurmuştur</strong>. <strong>956</strong> yılında Kral Eadwig, York Başpiskoposu Oskytel’e Southwell’de bir arazi bağışladı ve burada bir Sakson minster kilisesi kuruldu; bu malikâne, 1086 tarihli <em>Domesday </em>Kitabı’nda ayrıntılı olarak kaydedilmiştir.",
      "Günümüzdeki <strong>Norman Minster’ın</strong> inşasına yaklaşık <strong>1108 yılında</strong> başlanmış ve yapı, daha önceki Anglosakson temellerin üzerine yeniden inşa edilmiştir. Ana nef, transeptler, merkez kule ve batıdaki iki “biberlik” kule, İngiltere’deki sade Romanesk mimarinin en güzel örneklerinden biri olarak günümüze ulaşmıştır. <strong>Erken İngiliz tarzındaki koro bölümü</strong> 1234 ile 1251 yılları arasında yeniden inşa edilmiş, ünlü <strong>Bölüm Salonu</strong>’nun inşasına ise 1288 yılında başlanmıştır.",
      "<strong>1540</strong> yılında VIII. Henry tarafından kapatılan bu koleji kilisesi, 1543’te yeniden kuruldu, 1548’de statüsünü tekrar kaybetti ve nihayet 1557’de eski haline getirildi. İç Savaş sırasında <strong>I. Charles</strong>, Newark kuşatmasının ardından <strong>1646’da Southwell’de teslim oldu</strong>. <strong>1711</strong> yılında güneybatı kulesine yıldırım düştü ve çıkan yangın çatılar, çanlar, saat ve orgı tahrip etti; her iki kule de 1805 yılında yıkıldı ve ancak 1879–81 yıllarında Ewan Christian’ın kapsamlı Viktorya dönemi restorasyonu sırasında yeniden inşa edildi.",
      "Minster, <strong>1884 yılında</strong> Nottinghamshire ve Derbyshire’a hizmet etmek üzere yeni Southwell Piskoposluğu’nun kurulmasıyla <strong>katedral</strong> statüsüne kavuştu (Derby ise 1927’de ayrı bir piskoposluk haline geldi). Hâlâ Kutsal Meryem Ana’ya adanmış durumda olan bu yapı, İngiliz katedralleri arasında benzersiz bir şekilde, eski <em>“Minster”</em> unvanını korumaktadır."
    ],
    "figureAlt": "İki Norman tarzı “biberlik” kule ile çerçevelenmiş Southwell Minster’ın büyük batı penceresi.",
    "figureCaption": "Kendine özgü “biberlik” kuleleriyle ve Patrick Reyntiens’in 1996 tarihli Melek Penceresi’yle dikkat çeken Norman tarzı batı cephesi.",
    "timelineLabel": "Southwell Katedrali’nin Tarihçesi",
    "timeline": [
      {
        "year": "627",
        "text": "York’un ilk Başpiskoposu Paulinus, Southwell’de bir kilise kurmuş olarak bilinir."
      },
      {
        "year": "956",
        "text": "Kral Eadwig, Başpiskopos Oskytel’e toprak bağışlar; bir Sakson kilisesi kurulur."
      },
      {
        "year": "1108",
        "text": "Norman tarzındaki yeniden inşa çalışmaları doğu ucundan başladı; ana nef ise 1120’den sonra inşa edilmeye başlandı."
      },
      {
        "year": "1234–51",
        "text": "Erken dönem İngiliz ilahi defteri yeniden oluşturuldu."
      },
      {
        "year": "1288",
        "text": "Sekizgen Şapel Salonu’nun inşasına başlanır."
      },
      {
        "year": "1320–40",
        "text": "Büyük taş pulpitum (koro perdesi), Süslemeli tarzda oyulmuştur."
      },
      {
        "year": "1540–57",
        "text": "VIII. Henry döneminde yasaklanmış, Philip ve Mary döneminde yeniden yürürlüğe konmuştur."
      },
      {
        "year": "1646",
        "text": "I. Charles, Southwell'de İskoç Presbiteryen birliklerine teslim olur."
      },
      {
        "year": "1711",
        "text": "Yıldırım çarpması; çıkan yangın çatılar, çanlar, saat ve orgı tahrip etti."
      },
      {
        "year": "1879–81",
        "text": "Ewan Christian’ın restorasyon çalışması; batıdaki kuleler yeniden dikildi."
      },
      {
        "year": "1884",
        "text": "Southwell Minster, yeni piskoposluğun katedrali haline gelir."
      },
      {
        "year": "1996",
        "text": "Batı ucuna yerleştirilmiş Patrick Reyntiens’in muhteşem “Melek Penceresi” eseri."
      },
      {
        "year": "2021",
        "text": "Chapter House, kapsamlı bir restorasyonun ardından, tam erişim imkânı sağlayan konsol asansörüyle yeniden açıldı."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Hazineler ve ilgi çekici yerler",
    "lede": "İngiltere’nin en güzel ortaçağ yaprak oymalarından 16. yüzyıl Flaman tarzı doğu penceresine kadar, Minster, üzerinde durmaya değer unsurlar açısından olağanüstü bir zenginlik barındırmaktadır.",
    "leavesHeading": "Southwell’in Yaprakları",
    "leavesBody": "<strong>Chapter House</strong> (inşasına 1288’de başlanmıştır), sekizgen bir yapıdır; ortasında herhangi bir sütun bulunmamaktadır ve genel olarak <strong>“Southwell Yaprakları”</strong> olarak bilinen<strong>,</strong> derin oyma yaprak motifleriyle süslenmiştir<strong>.</strong> Sarmaşık, akçaağaç, meşe, şerbetçiotu, alıç gibi tek tek bitki türleri kolayca ayırt edilebilir ve aralarına “Yeşil Adamlar” ile mitolojik figürler serpiştirilmiştir. Birleşik Krallık’taki en güzel 13. yüzyıl natüralist oymaları olarak kabul edilen bu eserler, Nikolaus Pevsner’in 1945 tarihli klasik monografisinin konusuydu ve 2023 yılında yapılan bir kamuoyu anketinde Britanya’nın en sevilen katedral hazinesi seçildi.",
    "figureAlt": "Southwell Minster’ın Bölüm Salonu’nun giriş kapısı çevresinde yer alan, 13. yüzyıldan kalma doğal tarzda yaprak oymaları.",
    "figureCaption": "“Southwell’in Yaprakları” — 13. yüzyıldan kalma, Bölüm Salonu’nun giriş kapısı çevresindeki bitki motifli oymalar; 2023 yılında ülkenin en sevilen katedral hazinesi seçildi.",
    "features": [
      {
        "heading": "Norman ana nef",
        "body": "Dalgalı başlıklı kısa, dairesel sütunlardan oluşan yedi bölme; her bölmede tek bir büyük triforium kemeri; küçük yuvarlak kemerli clerestory pencereleri ve dairesel dış açıklıklar — sade İngiliz Romanesk mimarisinin günümüze ulaşan en seçkin örneklerinden biri."
      },
      {
        "heading": "Timpanum",
        "body": "Kuzey transeptte bulunan 11. yüzyıl sonlarına ait oyma timpanum ile mozaik zemin parçası, eski Anglosakson katedralinin günümüze ulaşan tek kalıntılarıdır."
      },
      {
        "heading": "Pulpitum (mihrap perdesi)",
        "body": "1320–40 yıllarına ait, Süslü Tarz’ın olağanüstü bir örneği olan, özenle oyulmuş taş koro perdesi; iki katlı ogee kemerli nişler ve koro bölümünün girişini çevreleyen delikli çatı uçlarından oluşmaktadır."
      },
      {
        "heading": "Erken Dönem İngiliz kitap yapımı",
        "body": "1234–51 yılları arasında saf Erken İngiliz mimari tarzında yeniden inşa edilmiştir: kümelenmiş sütunlar, üst katta ikiz lancet pencereler, nervürlü taş tonoz ve iki sıra halinde dörter lancet pencereden ışık alan kare şeklindeki doğu cephesi."
      },
      {
        "heading": "Doğu penceresi",
        "body": "Jean Chastellain tarafından, Noël Bellemare’nin tasarımlarına göre yapılmış, 16. yüzyıl Flaman camından dört Rönesans paneli; bu eserler aslen Paris’teki Temple Kilisesi için yapılmış ve 1818 yılında Minster’a bağışlanmıştır; yukarıdaki dört İncil yazarı figürü ise Clayton & Bell tarafından yapılmıştır (1876)."
      },
      {
        "heading": "Melek Penceresi",
        "body": "<strong>1996</strong> yılında batı ucuna yerleştirilen, İngiltere’nin önde gelen vitray sanatçılarından biri olan <strong>Patrick Reyntiens’in</strong> imzasını taşıyan bu muhteşem modern pencere, katedralin son dönemdeki en dikkat çekici eklemesidir."
      },
      {
        "heading": "Başpiskopos Sandys’in Mezarı",
        "body": "Katedralin en güzel anıtlarından biri: Ailesi uzun süre Nottinghamshire’da mülkler sahibi olan <strong>York Başpiskoposu Edwin Sandys’</strong>in <strong>(ö. 1588)</strong> alabaster mezarı."
      },
      {
        "heading": "Newstead kürsüsü",
        "body": "Orta Çağ’a ait pirinçten yapılmış bir kartal şekilli kürsü; bu kürsünün, Manastırların Dağılması’ndan sonra Newstead Manastırı’ndaki gölden çıkarıldığına ve 1805 yılında Başdiyakoz Kaye tarafından Minster’a bağışlandığına inanılmaktadır."
      },
      {
        "heading": "Norman tarzındaki merkezi kule",
        "body": "Aşağıda kesişen kemerler, yukarıda ise sade kemerlerden oluşan iki süsleme kademesi, bu kavşak kulesini İngiltere’de günümüze ulaşmış Norman kuleleri arasında en yükseklerden biri haline getirmektedir."
      },
      {
        "heading": "Dua için şapeller",
        "body": "Özel dua için ayrılmış üç şapel bulunmaktadır; bunlara, her gün Sabah Duası ve Kutsal Komünyon için kullanılan <strong>Aziz Oswald Şapeli</strong> ile Nottinghamshire’daki Kraliyet Hava Kuvvetleri Bombardıman Komutanlığı’nı anan <strong>Havacılar Şapeli</strong> de dahildir."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Üst düzey yetkililer",
    "lede": "Southwell Minster, Dekan’ın başkanlık ettiği Katedral <strong>Meclisi</strong> tarafından yönetilmekte olup, Katedral Konseyi ve daha geniş kapsamlı Kanonlar Kurulu’ndan destek ve denetim almaktadır. Aşağıda, Minster tarafından şu anda listelenen başlıca görevliler yer almaktadır.",
    "people": [
      {
        "role": "Southwell ve Nottingham Piskoposu",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "Dekan",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Baş Koro Şefi",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Şube Yönetim Kurulu Üyesi",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Şube Yönetim Kurulu Üyesi",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Üst Düzey İcrai Olmayan Üye",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Rektör Chori (Müzik Direktörü)",
        "name": "Paul Provost"
      },
      {
        "role": "Müzik Direktör Yardımcısı",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Baş Kilise Görevlisi",
        "name": "Andrew Todd"
      }
    ],
    "note": "Bölümün icracı olmayan üyeleri arasında ayrıca Bay Andrew Corner, Bay Nick Alexander, Bayan Ann Carter-Gray, Bayan Marion Oswald, Bay David Walker ve Bay Jonathan Wheeler yer almaktadır. Katedralde ayrıca bir Operasyon Direktörü ve bir Finans Direktörü ile birlikte yaklaşık 32 personel ve 300 civarında gönüllü görev yapmaktadır."
  },
  "music": {
    "num": "IV.",
    "heading": "Müzik vakfı ve korolar",
    "lede": "Southwell’de dokuz yüz yılı aşkın bir süredir bir koro şarkı söylüyor — bu, Orta Çağ’daki “Vicars Choral”dan günümüzün erkek ve kız koro üyeleri, profesyonel “Lay Clerks” ve gönüllü “Minster Chorale”den oluşan Katedral Korosu’na uzanan kesintisiz bir koro ibadet geleneğidir.",
    "songHeading": "Dokuz yüzyıllık şarkı geleneği",
    "songParagraphs": [
      "Minster’ın müzik hayatı, bugünkü Vicars’ Court’un bulunduğu yerde yer alan binalarda ikamet eden bir <strong>koro papazları</strong> topluluğuyla başladı. Bu grubun üyelerinden bir veya ikisi <strong>“Rector Chori</strong>” — “Koro Başkanı” — olarak atanırdı; bu unvan ilk kez <strong>1499</strong> yılında Southwell’de resmi olarak kaydedilmiş olup, günümüzde de Müzik Direktörü için kullanılmaktadır. Vicars Choral’a çocuk koro üyeleri de eklendi ve rahipler yavaş yavaş rahip olmayan şarkıcılar — <strong>Lay Clerks</strong> — ile yer değiştirdi; bu da koroya büyük ölçüde bugünkü şeklini kazandırdı.",
      "<strong>2005</strong> yılında, dönemin Müzik Müdür Yardımcısı tarafından bir Kız Korosu kuruldu. Bu koro, <strong>2019</strong> yılında Katedral Korosu’na tamamen entegre edildi; günümüzde erkek ve kız koro üyeleri <strong>tam bir eşitlik</strong> içinde, ayinleri, cüppeleri (kasok ve surplice), yaş gruplarını ve unvanlarını paylaşıyorlar — hepsi sadece “Katedral Korosu Üyesi” olarak anılıyor. <strong>2021</strong> yılında Southwell, Katedral’in bin yıllık tarihinde <strong>ilk kez </strong>bir <strong>kadın baş koro üyesini</strong> atadı ve 2025 yılında Katedral, Kız Korosu’nun yirminci yıl dönümünü kutladı."
    ],
    "figureAlt": "Üzerine Nicholson orgunun monte edildiği Southwell Minster’ın ortaçağ dönemine ait taş vaaz kürsüsü.",
    "figureCaption": "Üzerine monte edilmiş ana Nicholson orgunun bulunduğu pulpitum, Caröe kasası içinde.",
    "choirsHeading": "Bugünün koroları",
    "features": [
      {
        "heading": "Erkek Koro Üyeleri",
        "body": "The Minster School’dan geleneksel üç sesli koro. Erkek öğrenciler genellikle dönem boyunca pazartesi ve salı günleri akşam ayinlerinde tek başlarına şarkı söylerler; perşembe ile pazar günleri arasında ise kız öğrencilerle dönüşümlü olarak Lay Clerks’e katılırlar."
      },
      {
        "heading": "Kız Koro Üyeleri",
        "body": "2005 yılında kurulan ve şu anda Katedral Korosu’nda tam anlamıyla eşit ortaklar olan bu grup — şu anda yaklaşık 18 kızdan oluşuyor ve erkeklerle aynı şartlarda tüm koro görevlerini, provaları, turneleri ve kayıtları paylaşıyor."
      },
      {
        "heading": "Laik Memurlar",
        "body": "Altı profesyonel ve altı yardımcı amatör koro üyesi — yetişkin alto, tenor ve bas ses grupları; bunlar, Orta Çağ’daki “Vicars Choral”ın doğrudan mirasçılarıdır. Perşembe’den Pazar’a kadar ve bayram günlerinde koro üyeleriyle birlikte şarkı söylerler."
      },
      {
        "heading": "Minster Korosu",
        "body": "<strong>1994</strong> yılında kurulan, seçmeler yoluyla oluşturulan ve en fazla otuz şarkıcıdan oluşan, Müzik Müdür Yardımcısı tarafından yönetilen gönüllü yetişkin korosu. Katedral Korosu izinli olduğunda ayinlerde şarkı söyler; ayrıca her ay Pazar sabahı yapılan sabah ayinlerinde de şarkı söyler."
      },
      {
        "heading": "Minster Okulu",
        "body": "Tüm koro üyeleri, müzik üzerine uzmanlaşmış bir İlköğretim Bölümü’ne (3.–6. sınıflar) sahip olan ve Koro Okulları Birliği’ne üye bir İngiltere Kilisesi akademisi olan <strong>The Minster School</strong>’da eğitim görmektedir."
      },
      {
        "heading": "Southwell Koro Derneği",
        "body": "Altmış yılı aşkın bir geçmişe sahip, seçme yapılmayan bir topluluk korosu; dönem boyunca her hafta Minster’da prova yapıyor — vakfın etrafında bir araya gelen geniş müzik camiası."
      }
    ],
    "organsHeading": "Organlar",
    "organsBody": "Katedralin ana enstrümanı, <strong>W. D. Caröe</strong> tarafından tasarlanan meşe ahşap bir kasa içinde, ortaçağdan kalma pulpitum üzerinde yer almaktadır. Mevcut Ekran Org, 1990’lar boyunca önde gelen org yapımcıları tarafından (John Norman, Stephen Bicknell ve Ian Bell’in danışmanlığında) yeniden inşa edilmiş olup, Caröe’nin kasası tarihi değerleri nedeniyle korunmuştur. Kökeni “Bay Derbie” tarafından 1662 yılında yapılan enstrümana ve 1711’deki büyük yangının ardından yapılan onarımlara dayanan ayrı bir <strong>Nef Org’</strong>u, batı ucunda cemaatin ilahilerini desteklerken, continuo ve daha küçük ölçekli ayinler için ise güzel bir <strong>oda org’</strong>u kullanılmaktadır. Eski Koro Reçörü Paul Hale tarafından yazılan 72 sayfalık resimli kitapçık <em>The Organs of Southwell Minster</em>, Katedral Mağazasından temin edilebilir."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturji ve günlük ibadetler",
    "lede": "Minster’ın günlük dua programı, İngiltere Kilisesi’nin “Common Worship” düzenine göre yürütülür ve bu program, eğitim dönemi boyunca ülkenin en saygın katedral müzik vakıflarından biri tarafından sürdürülür.",
    "paragraphs": [
      "Southwell’de <strong>her gün</strong> tam bir <strong>Anglikan katedral ibadet programı</strong> uygulanmaktadır: Sabah Duası, Kutsal Komünyon (Eucharist) ve Akşam Duası ya da Evensong her gün icra edilmektedir. Okul dönemi boyunca çoğu gün, <strong>Katedral Korosu</strong> — Erkek Koristler, Kız Koristler ve Lay Clerks — tarafından koro ayinleri seslendirilir; bu gruplar haftada sekiz koro ayininin müziğini sağlar. Pazar günleri, kız ve erkek koro üyeleri, lay clerks ile dönüşümlü olarak Eucharist ve Evensong ayinlerinde şarkı söyler. Ek ayinler ise 1994 yılında kurulan ve en fazla otuz gönüllü şarkıcıdan oluşan bir oda korosu olan <strong>Minster Chorale</strong> tarafından seslendirilir.",
      "<strong>Pazar</strong> <strong>günü Katedral’de düzenlenen Ayin (saat 10.00)</strong> ve <strong>Pazar Akşam Duası (saat 15.30)</strong>, canlı olarak yayınlanmaktadır ve sırasıyla bir hafta ve bir gün boyunca çevrimiçi olarak izlenebilir. Her türlü inanç geleneklerinden gelen ziyaretçiler sıcak bir şekilde karşılanır; giriş ücreti alınmamaktadır."
    ],
    "figureAlt": "Southwell Minster’ın doğuya bakan korosu; Orta Çağ’dan kalma kilise sıraları ve taş tonozları görülüyor.",
    "figureCaption": "Erken Dönem İngiliz tarzı ilahi kitabı; sömestr boyunca çoğu gün burada koro eşliğinde Akşam Duası söylenir.",
    "weekdayHeading": "Hafta içi düzeni",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Sabah Duası — <em>St Oswald Şapeli</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Kutsal Komünyon — <em>St Oswald’s / Havacılar Şapeli</em><br /> <small>(Cumartesi günleri: 09.00)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Koro Akşam Duası — <em>Koro</em> <br /><small>(Çarşamba günleri okunur; öğretim dönemi boyunca Pazartesi, Salı, Perşembe, Cuma ve Cumartesi günleri ilahi olarak seslendirilir)</small>"
      }
    ],
    "sundayHeading": "Pazar günü düzeni",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Kutsal Komünyon (BCP, okunarak)"
      },
      {
        "clock": "10.00am",
        "detail": "Sung Katedrali'nde düzenlenen Ayin — <em>canlı yayın</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Koro Akşam Duası — <em>canlı yayın</em>"
      }
    ],
    "timesNote": "<em>Bayram günlerinde ve okul tatillerinde ayin saatleri değişiklik gösterebilir — yola çıkmadan önce lütfen Minster web sitesindeki Ayin Takvimi’ni kontrol ediniz.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Çalışma saatleri",
    "lede": "Katedral, yılın her günü ziyaretçilere ücretsiz olarak açıktır. Bakım masraflarına yönelik bağışlar memnuniyetle kabul edilmektedir.",
    "cards": [
      {
        "heading": "Katedral",
        "rows": [
          {
            "days": "Pazartesi – Cumartesi",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "Pazar",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Görevliler genellikle Pazartesi–Cumartesi günleri saat 10.30–17.00 arasında, Pazar günleri ise saat 11.00–17.00 arasında görev yapmaktadır. Bazı durumlarda, kısa süreli bildirimle hizmet veya etkinlik nedeniyle kapanışlar söz konusu olabilir."
      },
      {
        "heading": "Bakanlık Ofisi",
        "rows": [
          {
            "days": "Pazartesi – Cuma",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "Minster Merkezi’nde ofis, eğitim ekibi ve turizm danışma noktası yer almaktadır."
      },
      {
        "heading": "Yemekhane",
        "rows": [
          {
            "days": "Pzt – Cts",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "Pazar",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Katedral Mağazası",
        "rows": [
          {
            "days": "Pzt – Cts",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "Pazar",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Başpiskopos Sarayı ve Bahçeleri",
        "rows": [
          {
            "days": "Günlük",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Minster’ın bitişiğindeki ortaçağ saray kalıntılarına ve duyusal bahçelere giriş ücretsizdir."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Bağış Yap",
    "paragraphs": [
      "Üstünüzdeki taş, 1108 yılında dikilmiştir. Bu, İngiltere’de ayakta kalan en güzel Norman tarzı ana nefidir — yuvarlak kemerler arka arkaya sıralanmış; bu kemerleri yontan ustalar, çatılarının üzerlerine kapanışını asla göremeyeceklerini biliyorlardı.",
      "Ve doğuya doğru yürüyün, Bölüm Salonu’na girin. Orada, sekiz yüz yıl önce taşa oyulmuş olarak bu ilçenin yaprakları yer alıyor. Alıç; meşe; akçaağaç; düğünçiçeği ve asma. Bunları oyan kişi, açıkça ormana çıkmış ve bir canlıyı — <strong>gerçekten</strong> dikkatle — incelemiş, sonra da onu kalıcı hale getirmiş. Yedi yüzyıl boyunca hiç solmadılar.",
      "Buranın hiçbiri müze değildir. Burası hâlâ ibadet edilen, hâlâ ilahilerin söylendiği, hâlâ ışıkların yandığı aktif bir ibadet yeridir; manevi sıcaklık ve huzur dolu bir yerdir.",
      "Sadece bu kapıları açık tutmak bile günde beş bin pounddan fazla maliyete mal oluyor — ısıtma, camlar, kumaşlar, koro üyeleri, ayin.",
      "Giriş ücreti alınmamaktadır. Hiçbir zaman alınmadı ve Şubemiz de bu durumu böyle sürdürecektir. Ancak, bu misyona katkıda bulunarak önemli bir rol oynayabilirsiniz. Geçen yıl, ziyaretçiler ortalama olarak bir pound ve seksen sekiz peni bağışta bulundular.",
      "Sizden beş pound tutarında bir bağış rica etmek istiyoruz.",
      "Eğer bu yer bugün size bir anlık huzur vermiş ve gününüzü zenginleştirmişse, lütfen “Şimdi bağış yap” düğmesini kullanarak destek olun: Birleşik Krallık vergi mükellefiyseniz “Gift Aid” seçeneğini işaretleyin; her 5 £ için 1,25 £ daha eklenir ve size hiçbir ek maliyet getirmez."
    ],
    "button": "Şimdi bağış yapın",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "En önemlisi, buradan hiçbir yükümlülük altına girmeden ayrıldığınızı lütfen unutmayın. Lütfen sadece imkânlarınız ölçüsünde bağışta bulunun. Karşılayamayacağınız miktarda bağış yapmayın. Buradan her zaman Rab’bin bereketiyle ayrılırsınız.",
    "close": "Yapraklar sekiz yüz yıl dayandı. Bir sekiz yüz yıl daha dayanıp dayanmayacakları ise, pek de göze çarpmadan, bize bağlı."
  },
  "projects": {
    "num": "VIII.",
    "heading": "Projelerimiz",
    "lede": "Southwell Minster’daki mevcut ve planlanan projeler — bu bölümün içeriği daha sonra eklenecektir.",
    "placeholderLabel": "Projelerimiz — yakında",
    "placeholderBody": "Proje özetleri, görseller ve güncellemeler için yer tutucu. Hazır olduğunda tek tek proje girişlerini ekleyin."
  },
  "contact": {
    "num": "IX.",
    "heading": "İletişim ve bize nasıl ulaşabilirsiniz",
    "minsterHeading": "Southwell Katedrali",
    "addressLabel": "Adres",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Telefon",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Merkez Ofis)",
    "emailLabel": "E-posta",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Web sitesi",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Acil din görevlileri",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Mağaza",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Buraya ulaşım",
    "gettingHere": [
      "Southwell, Nottinghamshire’ın merkezinde yer alan küçük bir pazar kasabasıdır; A1 otoyoluna yedi mil uzaklıkta ve A612 karayolu üzerinden Nottingham’a arabayla yaklaşık 30 dakika mesafededir. Minster, kasabanın merkezindeki Church Street üzerinde, Cumartesi pazarı meydanına kısa bir yürüyüş mesafesinde yer almaktadır.",
      "<strong>Rehberli turlar,</strong> Minster Ofisi aracılığıyla önceden rezerve edilebilir; <strong>eğitim amaçlı ziyaretler</strong> ise <a href=\"tel:+441636817287\">01636 817287 numaralı</a> telefondan ayrı olarak düzenlenir.",
      "<strong>Çevrimiçi ibadet:</strong> Pazar günü kutlanan Efkaristiya ve Akşam Duası, Minster’ın web sitesinden canlı olarak yayınlanmaktadır ve bir hafta boyunca tekrar izlenebilir."
    ],
    "socialPrefix": "Sosyal medya:",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Bu kısa ziyaretçi rehberi, Minster’ın kendi yayınlarından, İngiliz Katedraller Birliği’nden ve Wikipedia’dan derlenmiştir. Bu, Minster’ın resmi bir yayını değildir.",
    "photos": "Fotoğraflar: batı cephesi, batı penceresi, koro bölümü, Bölüm Salonu girişi ve org bulunan pulpitum — Wikimedia Commons (Diliff ve Geograph katkıcıları), CC BY-SA."
  }
}
