import type { SouthwellMinsterCopy } from "./southwellMinster"

/** es copy — generated by scripts/translate-southwell.mjs (review before publishing). */
export const SOUTHWELL_MINSTER_ES: SouthwellMinsterCopy = {
  "audioHint": "Donde ves el control de audio a continuación, y en cada sección en la que veas un icono de audio, puedes escuchar mientras navegas o te desplazas. Utiliza tus auriculares o tus cascos.",
  "eyebrow": "Nottinghamshire · Iglesia de Inglaterra",
  "title": "Catedral de Southwell",
  "tagline": "La catedral y iglesia parroquial de la Santísima Virgen María: una joya normanda de la región de Midlands, en Inglaterra, donde se reza sin interrupción desde el año 627.",
  "meta": [
    "Fundada hacia el año 627",
    "Reconstrucción normanda a partir de 1108",
    "Catedral desde 1884"
  ],
  "welcome": {
    "invite": "Escucha el mensaje de bienvenida del padre Stephen",
    "videoUnsupported": "Tu navegador no es compatible con el elemento de vídeo.",
    "placeholderLabel": "Vídeo de bienvenida — próximamente",
    "role": "El Muy Reverendo",
    "name": "Dr Stephen Evans",
    "title": "Decano de la catedral de Southwell"
  },
  "toc": [
    {
      "href": "#history",
      "label": "Historia"
    },
    {
      "href": "#treasures",
      "label": "Tesoros e interiorismo"
    },
    {
      "href": "#officers",
      "label": "Miembros principales de la dirección"
    },
    {
      "href": "#music",
      "label": "Música y coros"
    },
    {
      "href": "#worship",
      "label": "Liturgia y servicios religiosos"
    },
    {
      "href": "#visit",
      "label": "Horario de apertura"
    },
    {
      "href": "#donate",
      "label": "Donar"
    },
    {
      "href": "#projects",
      "label": "Nuestros proyectos"
    },
    {
      "href": "#contact",
      "label": "Contacto"
    }
  ],
  "history": {
    "num": "I.",
    "heading": "Una breve historia",
    "lede": "En Southwell se alza una catedral desde hace más de mil años —que ha sobrevivido a los vikingos, a la Reforma, a la guerra civil y a los incendios— y que hoy en día es la iglesia madre de la Diócesis de Southwell y Nottingham.",
    "paragraphs": [
      "Según la tradición, <strong>Paulino, el primer arzobispo de York, fundó aquí la primera iglesia en el año 627,</strong> mientras bautizaba a los conversos en el río Trent. En el año <strong>956,</strong> el rey Eadwig concedió unas tierras en Southwell a Oskytel, arzobispo de York, y se fundó allí una iglesia minster sajona; la finca quedó registrada con todo detalle en el <em>Domesday Book</em> de 1086.",
      "La actual <strong>catedral normanda</strong> se comenzó a construir hacia <strong>el año 1108</strong>, sobre los cimientos anglosajones anteriores. La nave, los transeptos, la torre central y las dos torres occidentales en forma de «pimentero» se conservan como uno de los mejores ejemplos del austero estilo románico en Inglaterra. El <strong>coro, de estilo inglés temprano</strong>, se reconstruyó entre 1234 y 1251, y la célebre <strong>sala capitular</strong> se comenzó a construir en 1288.",
      "Suprimida por Enrique VIII en <strong>1540</strong>, la iglesia colegiata fue refundada en 1543, volvió a perder su estatus en 1548 y fue finalmente restablecida en 1557. Durante la Guerra Civil, <strong>Carlos I se rindió en Southwell en 1646</strong> tras el asedio de Newark. En <strong>1711,</strong> un rayo alcanzó la aguja suroeste y un incendio destruyó los tejados, las campanas, el reloj y el órgano; ambas agujas se retiraron en 1805 y no se reconstruyeron hasta 1879-1881, durante la amplia restauración victoriana llevada a cabo por Ewan Christian.",
      "La Minster pasó a ser <strong>catedral en 1884</strong>, cuando se creó la nueva diócesis de Southwell para abarcar Nottinghamshire y Derbyshire (Derby se convirtió en una diócesis independiente en 1927). Sigue estando dedicada a la Santísima Virgen María y, a diferencia de todas las demás catedrales inglesas, conserva su antiguo título de <em>«Minster</em>»."
    ],
    "figureAlt": "La gran ventana occidental de la catedral de Southwell, enmarcada por las dos torres normandas en forma de «pimentero».",
    "figureCaption": "La fachada occidental normanda, con sus características torres en forma de «pimentero» y la «Ventana del Ángel», obra de Patrick Reyntiens de 1996.",
    "timelineLabel": "Cronología de la catedral de Southwell",
    "timeline": [
      {
        "year": "627",
        "text": "Paolino, primer arzobispo de York, a quien se le atribuye la fundación de una iglesia en Southwell."
      },
      {
        "year": "956",
        "text": "El rey Eadwig concede tierras al arzobispo Oskytel; se funda una catedral sajona."
      },
      {
        "year": "1108",
        "text": "La reconstrucción normanda comienza en el extremo este; la nave se empezó a construir después de 1120."
      },
      {
        "year": "1234–51",
        "text": "Se ha reconstruido el cuaderno de partitura de inglés antiguo."
      },
      {
        "year": "1288",
        "text": "Comienza la construcción de la sala capitular octogonal."
      },
      {
        "year": "1320–40",
        "text": "El gran «pulpitum» (celosía del coro) de piedra está tallado en estilo Decorado."
      },
      {
        "year": "1540–57",
        "text": "Suprimida bajo el reinado de Enrique VIII, restablecida bajo el de Felipe y María."
      },
      {
        "year": "1646",
        "text": "Carlos I se rinde ante las tropas presbiterianas escocesas en Southwell."
      },
      {
        "year": "1711",
        "text": "Un rayo; el incendio destruye los tejados, las campanas, el reloj y el órgano."
      },
      {
        "year": "1879–81",
        "text": "Restauración de la iglesia de Ewan Christian; se vuelven a levantar las agujas occidentales."
      },
      {
        "year": "1884",
        "text": "La catedral de Southwell pasa a ser la catedral de la nueva diócesis."
      },
      {
        "year": "1996",
        "text": "La magnífica «Ventana de los Ángeles» de Patrick Reyntiens, instalada en el extremo oeste."
      },
      {
        "year": "2021",
        "text": "La Sala Capitular reabre sus puertas tras una importante restauración, con un ascensor en voladizo que garantiza la accesibilidad total."
      }
    ]
  },
  "treasures": {
    "num": "II.",
    "heading": "Tesoros y lugares de interés",
    "lede": "Desde las mejores tallas medievales de hojas de Inglaterra hasta una ventana oriental flamenca del siglo XVI, la catedral cuenta con una riqueza excepcional de elementos que merecen una parada para contemplarlos.",
    "leavesHeading": "Las hojas de Southwell",
    "leavesBody": "La <strong>Sala Capitular</strong> (iniciada en 1288) es octogonal, carece de pilar central y está decorada con tallas de follaje de gran profundidad, conocidas colectivamente como <strong>«Las hojas de Southwell».</strong> Se pueden identificar especies concretas —hiedra, arce, roble, lúpulo y espino— entremezcladas con «Hombres Verdes» y figuras mitológicas. Consideradas las mejores tallas naturalistas del siglo XIII del Reino Unido, fueron objeto de la clásica monografía de Nikolaus Pevsner de 1945 y fueron elegidas como el tesoro catedralicio favorito de Gran Bretaña en una encuesta pública realizada en 2023.",
    "figureAlt": "Tallados naturalistas de hojas del siglo XIII que rodean la puerta de la Sala Capitular de la catedral de Southwell.",
    "figureCaption": "«Las hojas de Southwell»: tallas de follaje del siglo XIII que rodean el pórtico de la Sala Capitular, elegidas como el tesoro catedralicio favorito del país en 2023.",
    "features": [
      {
        "heading": "La nave normanda",
        "body": "Siete tramos de columnas cortas y circulares con capiteles festoneados; un único arco de triforio de gran tamaño en cada tramo; pequeñas ventanas de claraboya de arco de medio punto y aberturas exteriores circulares: uno de los ejemplos más destacados que se conservan del austero románico inglés."
      },
      {
        "heading": "El tímpano",
        "body": "El tímpano tallado de finales del siglo XI que se encuentra en el transepto norte, junto con un fragmento de suelo de mosaico, son los únicos restos visibles de la antigua catedral anglosajona."
      },
      {
        "heading": "El púlpito (traba)",
        "body": "Una mampara del coro de piedra, elaboradamente tallada, que data de los años 1320-1340, un ejemplo excepcional del estilo Decorado, con dos hileras de nichos con arcos de ogiva y frontones calados que enmarcan la entrada al coro."
      },
      {
        "heading": "El cuaderno de la Edad Media inglesa",
        "body": "Reconstruida entre 1234 y 1251 en puro estilo inglés primitivo: columnas agrupadas, ventanas geminadas en la planta superior, bóveda de piedra con nervaduras y un ábside cuadrado iluminado por dos hileras de cuatro ventanas geminadas."
      },
      {
        "heading": "La ventana del este",
        "body": "Cuatro paneles renacentistas de vidrio flamenco del siglo XVI, obra de Jean Chastellain, según diseños de Noël Bellemare, realizados originalmente para la iglesia del Temple de París y donados a la catedral en 1818; los cuatro evangelistas que se ven arriba son obra de Clayton & Bell (1876)."
      },
      {
        "heading": "La Ventana del Ángel",
        "body": "Instalada en el extremo oeste en <strong>1996</strong>, esta magnífica vidriera moderna, obra de <strong>Patrick Reyntiens</strong> —uno de los artistas británicos más destacados en el ámbito del vitral—, es la incorporación reciente más llamativa de la catedral."
      },
      {
        "heading": "Tumba del arzobispo Sandys",
        "body": "El más bello de los monumentos conmemorativos de la catedral: la tumba de alabastro de <strong>Edwin Sandys, arzobispo de York (fallecido en 1588)</strong>, cuya familia poseyó durante mucho tiempo propiedades en Nottinghamshire."
      },
      {
        "heading": "El atril de Newstead",
        "body": "Un atril medieval de latón con forma de águila, que se cree que fue rescatado del lago de la abadía de Newstead tras la Disolución y que el archidiácono Kaye donó a la catedral en 1805."
      },
      {
        "heading": "La torre normanda central",
        "body": "Dos niveles decorativos —arcos entrecruzados en la parte inferior y arcos lisos en la superior— sitúan a la torre del crucero entre las más altas de las torres normandas que aún se conservan en Inglaterra."
      },
      {
        "heading": "Capillas para la oración",
        "body": "Hay tres capillas destinadas a la oración privada, entre ellas <strong>la capilla de San Oswald</strong> (que se utiliza a diario para la oración matutina y la Santa Comunión) y la <strong>capilla de los aviadores</strong>, en memoria del Mando de Bombarderos de la RAF en Nottinghamshire."
      }
    ]
  },
  "officers": {
    "num": "III.",
    "heading": "Miembros principales del equipo directivo",
    "lede": "La catedral de Southwell está dirigida por su <strong>Capítulo</strong>, presidido por el deán, con el apoyo y la supervisión del Consejo de la Catedral y del Colegio de Canónigos en su conjunto. A continuación se enumeran los principales cargos, tal y como los recoge actualmente la catedral.",
    "people": [
      {
        "role": "Obispo de Southwell y Nottingham",
        "name": "The Rt Revd Paul Williams"
      },
      {
        "role": "El decano",
        "name": "The Very Revd Dr Stephen Evans"
      },
      {
        "role": "Canónigo precentor",
        "name": "The Revd Canon Dr Richard Frith"
      },
      {
        "role": "Miembro ejecutivo de la sección",
        "name": "The Revd Canon Dr Stephen Hippisley-Cox"
      },
      {
        "role": "Miembro ejecutivo de la sección",
        "name": "The Revd Amanda Lees"
      },
      {
        "role": "Miembro no ejecutivo de alto rango",
        "name": "Mrs Jan Richardson MBE DL"
      },
      {
        "role": "Rector Chori (director musical)",
        "name": "Paul Provost"
      },
      {
        "role": "Subdirector musical",
        "name": "Jonathan Allsopp"
      },
      {
        "role": "Jefe de sacristanes",
        "name": "Andrew Todd"
      }
    ],
    "note": "Entre los miembros no ejecutivos del Capítulo se encuentran también el Sr. Andrew Corner, el Sr. Nick Alexander, la Sra. Ann Carter-Gray, la Sra. Marion Oswald, el Sr. David Walker y el Sr. Jonathan Wheeler. La catedral cuenta además con un director de operaciones y un director financiero, además de unos 32 empleados y unos 300 voluntarios."
  },
  "music": {
    "num": "IV.",
    "heading": "Fundación musical y coros",
    "lede": "En Southwell lleva más de novecientos años cantando un coro: una tradición ininterrumpida de culto coral que se remonta desde los vicarios corales de la Edad Media hasta el actual Coro de la Catedral, formado por niños y niñas, cantores laicos profesionales y el coro voluntario Minster Chorale.",
    "songHeading": "Nueve siglos de canciones",
    "songParagraphs": [
      "La vida musical de la catedral comenzó con un colegio de <strong>vicarios corales</strong>, que residían en los edificios que se alzaban en el lugar que hoy ocupa Vicars’ Court. Uno o dos de entre ellos eran designados <strong>Rector Chori</strong> —«gobernante del coro»—, un título que se registró oficialmente por primera vez en Southwell en <strong>1499</strong> y que todavía hoy se utiliza para referirse al director musical. A los vicarios corales se les incorporaron niños cantores, y los vicarios fueron sustituidos gradualmente por cantantes laicos —los <strong>«Lay Clerks»</strong>—, lo que dio al coro, en lo esencial, la forma que tiene hoy en día.",
      "En <strong>2005</strong>, el entonces director adjunto de música fundó un coro de niñas. Este se integró plenamente en el coro de la catedral en <strong>2019</strong>; hoy en día, los niños y las niñas del coro disfrutan de <strong>plena paridad</strong>, compartiendo servicios, vestimentas (sotana y sobrepelliz), rangos de edad y título: todos son, sencillamente, coristas de la catedral. En <strong>2021,</strong> Southwell nombró a su <strong>primera directora de coro femenina</strong> en los mil años de historia de la catedral, y en 2025 la catedral celebró el vigésimo aniversario del coro de niñas."
    ],
    "figureAlt": "El púlpito medieval de piedra de la catedral de Southwell, con el órgano Nicholson instalado en su parte superior.",
    "figureCaption": "El púlpito con el órgano principal de Nicholson instalado en su parte superior, en su caja de Caröe.",
    "choirsHeading": "Los coros de hoy",
    "features": [
      {
        "heading": "Niños de coro",
        "body": "La línea de voces agudas tradicional, procedente de The Minster School. Los chicos suelen cantar solos en las vísperas de los lunes y martes, y se unen a los Lay Clerks de jueves a domingo durante el curso, alternándose con las chicas."
      },
      {
        "heading": "Niñas del coro",
        "body": "Fundado en 2005, sus integrantes son ahora socios de pleno derecho en el Coro de la Catedral —actualmente unas 18 chicas— y comparten todas las tareas propias de los coristas, los ensayos, las giras y las grabaciones en igualdad de condiciones con los chicos."
      },
      {
        "heading": "Secretarios laicos",
        "body": "Seis coristas laicos profesionales y seis coristas laicos auxiliares: las voces adultas de contralto, tenor y bajo, descendientes directos de los vicarios corales medievales. Cantan junto a los niños del coro de jueves a domingo y en los días festivos."
      },
      {
        "heading": "La Coral de la Catedral",
        "body": "Fundado en <strong>1994</strong>, es un coro voluntario de adultos, cuyos miembros son seleccionados mediante audición, compuesto por un máximo de treinta cantantes y dirigido por el subdirector musical. Canta en los oficios religiosos cuando el coro de la catedral está de permiso, además de en las matinas dominicales mensuales."
      },
      {
        "heading": "El colegio Minster",
        "body": "Todos los miembros del coro estudian en <strong>The Minster School</strong>, una academia de la Iglesia de Inglaterra que cuenta con un departamento de primaria (cursos 3.º a 6.º) especializado en música y que forma parte de la Asociación de Escuelas de Coros."
      },
      {
        "heading": "Sociedad Coral de Southwell",
        "body": "Un coro comunitario sin audición de admisión, con más de sesenta años de historia, que ensaya semanalmente en la catedral durante el curso académico: la comunidad musical más amplia que se reúne en torno a la fundación."
      }
    ],
    "organsHeading": "Los órganos",
    "organsBody": "El órgano principal de la catedral se encuentra sobre el púlpito medieval, en una caja de roble diseñada por <strong>W. D. Caröe</strong>. El actual órgano de pantalla fue reconstruido a lo largo de la década de 1990 por destacados constructores de órganos (con el asesoramiento de John Norman, Stephen Bicknell e Ian Bell), conservándose la caja de Caröe por motivos históricos. Un <strong>órgano</strong> independiente <strong>de la nave</strong>, cuyo linaje se remonta a un instrumento de 1662 del «Sr. Derbie» y a las reparaciones realizadas tras el gran incendio de 1711, acompaña el canto de la congregación en el extremo oeste, mientras que un magnífico <strong>órgano de cámara</strong> se utiliza para el continuo y las liturgias a menor escala. En la tienda de la catedral se puede adquirir un folleto ilustrado de 72 páginas, titulado <em>*The Organs of Southwell Minster*</em>, escrito por el antiguo rector del coro, Paul Hale."
  },
  "worship": {
    "num": "V.",
    "heading": "Liturgia y oficios diarios",
    "lede": "La rutina diaria de oración del canónigo sigue el modelo de «Common Worship» de la Iglesia de Inglaterra, que durante el curso académico cuenta con el apoyo de una de las fundaciones de música catedralicia más prestigiosas del país.",
    "paragraphs": [
      "Southwell celebra <strong>diariamente </strong>el <strong>oficio</strong> completo <strong>de la catedral anglicana</strong>: cada día se celebran la Oración de la Mañana, la Santa Comunión (la Eucaristía) y la Oración de la Tarde o Vísperas. Durante el curso escolar, el <strong>coro de la catedral</strong> —integrado por los niños y niñas del coro y los cantores laicos— interpreta los oficios corales casi todos los días, lo que supone un total de ocho oficios corales a la semana. Los domingos, los niños y niñas del coro cantan la Eucaristía y las Vísperas alternándose con los cantores laicos. Los oficios adicionales los interpreta la <strong>Minster Chorale</strong>, un coro de cámara formado por hasta treinta cantantes voluntarios y fundado en 1994.",
      "<strong>La eucaristía dominical en la catedral (10:00 h)</strong> y <strong>las vísperas dominicales (15:30 h)</strong> se retransmiten en directo y permanecen disponibles en línea durante una semana y un día, respectivamente. Los visitantes de todas las tradiciones son bienvenidos; la entrada es gratuita."
    ],
    "figureAlt": "El coro de la catedral de Southwell, visto desde el este, en el que se aprecian los bancos medievales y las bóvedas de piedra.",
    "figureCaption": "La capilla de Early English, donde se cantan las vísperas corales casi todos los días durante el curso.",
    "weekdayHeading": "Horario de los días laborables",
    "weekdayRows": [
      {
        "clock": "8.30am",
        "detail": "Oración matutina — <em>Capilla de San Oswald</em>"
      },
      {
        "clock": "12.15pm",
        "detail": "Santa Comunión — <em>Iglesia de San Oswald / Capilla de los Aviadores</em> <br /><small>(sábados: 9:00 h)</small>"
      },
      {
        "clock": "5.30pm",
        "detail": "Vísperas corales — <em>El coro</em> <br /><small>(recitadas los miércoles; cantadas los lunes, martes, jueves, viernes y sábados durante el curso académico)</small>"
      }
    ],
    "sundayHeading": "Horario de los domingos",
    "sundayRows": [
      {
        "clock": "8.00am",
        "detail": "Santa Comunión (Libro de Oración Común, recitada)"
      },
      {
        "clock": "10.00am",
        "detail": "Eucaristía cantada en la catedral — <em>retransmitida en directo</em>"
      },
      {
        "clock": "3.30pm",
        "detail": "Vísperas corales — <em>retransmitidas en directo</em>"
      }
    ],
    "timesNote": "<em>Los horarios de los oficios pueden variar en días festivos y durante las vacaciones escolares; te recomendamos que consultes el calendario de oficios en la página web de la catedral antes de venir.</em>"
  },
  "visit": {
    "num": "VI.",
    "heading": "Horario de apertura",
    "lede": "La catedral está abierta al público todos los días del año y la entrada es gratuita. Se agradecen las donaciones destinadas a su mantenimiento.",
    "cards": [
      {
        "heading": "La catedral",
        "rows": [
          {
            "days": "De lunes a sábado",
            "clock": "10.00am – 6.30pm"
          },
          {
            "days": "Domingo",
            "clock": "10.00am – 4.30pm"
          }
        ],
        "note": "Los encargados suelen estar de servicio de 10:30 a 17:00 (de lunes a sábado) y de 11:00 a 17:00 los domingos. En ocasiones, el servicio o el recinto pueden cerrar con poca antelación debido a algún evento."
      },
      {
        "heading": "Oficina del ministro",
        "rows": [
          {
            "days": "De lunes a viernes",
            "clock": "10.00am – 1.00pm"
          }
        ],
        "note": "El Minster Centre alberga la oficina, el equipo educativo y el punto de información turística."
      },
      {
        "heading": "Comedor",
        "rows": [
          {
            "days": "De lunes a sábado",
            "clock": "9.30am – 4.00pm"
          },
          {
            "days": "Domingo",
            "clock": "10.00am – 4.00pm"
          }
        ]
      },
      {
        "heading": "Tienda de la catedral",
        "rows": [
          {
            "days": "De lunes a sábado",
            "clock": "10.00am – 4.00pm"
          },
          {
            "days": "Domingo",
            "clock": "11.30am – 3.30pm"
          }
        ]
      },
      {
        "heading": "Palacio Arzobispal y Jardines",
        "rows": [
          {
            "days": "Diario",
            "clock": "9.00am – 5.00pm"
          }
        ],
        "note": "Entrada gratuita a las ruinas del palacio medieval y a los jardines sensoriales contiguos a la catedral."
      }
    ]
  },
  "donate": {
    "num": "VII.",
    "heading": "Donar",
    "paragraphs": [
      "La piedra que tienes sobre tu cabeza se erigió en el año 1108. Es la nave normanda mejor conservada que queda en Inglaterra: arco redondo tras arco redondo, tallados por hombres que sabían que nunca vivirían para ver cómo se cerraba el techo sobre ellos.",
      "Y camina hacia el este, hasta la Sala Capitular. Allí, talladas en la piedra hace ochocientos años, se encuentran las hojas de este condado: espino, roble, arce, ranúnculo y parra. Quienquiera que las tallara, sin duda se había adentrado en el bosque y había observado —observado <strong>de</strong> verdad— un ser vivo, y lo había inmortalizado. No se han marchitado en siete siglos.",
      "Nada de esto es un museo. Es un lugar de culto activo, donde todavía se celebran misas, se canta y se enciende la luz; un lugar que transmite calidez y consuelo espirituales.",
      "Solo mantener estas puertas abiertas cuesta más de cinco mil libras al día: la calefacción, los vitrales, los tejidos, los coristas, la liturgia.",
      "La entrada es gratuita. Siempre lo ha sido, y la Delegación se asegurará de que siga siendo así. No obstante, tú puedes desempeñar un papel importante a la hora de colaborar con esta misión. El año pasado, cada visitante aportó de media una libra y ochenta y ocho peniques.",
      "Nos gustaría pedirte una donación de cinco libras.",
      "Si este sitio te ha regalado hoy un momento de tranquilidad y ha enriquecido tu día, te agradeceríamos que lo apoyaras haciendo clic en el botón «Donar ahora»: marca la casilla «Gift Aid» si eres contribuyente en el Reino Unido; por cada 5 £, se añade 1,25 £ extra, y a ti no te supone ningún coste adicional."
    ],
    "button": "Haz una donación ahora",
    "donateHref": "https://southwellminster.churchsuite.com/donate/fund/qx2ayo61",
    "after": "Y, sobre todo, tened presente que os marcháis de aquí sin ningún compromiso. Por favor, dad solo según vuestras posibilidades. No deis lo que no podáis permitirvos. Os marcháis siempre con la bendición del Señor.",
    "close": "Las hojas han perdurado ochocientos años. Que perduren otros ochocientos más depende, sin que se le dé mucha importancia, de nosotros."
  },
  "projects": {
    "num": "VIII.",
    "heading": "Nuestros proyectos",
    "lede": "Proyectos actuales y previstos en la catedral de Southwell — el contenido de esta sección se publicará próximamente.",
    "placeholderLabel": "Nuestros proyectos — próximamente",
    "placeholderBody": "Espacio reservado para resúmenes de proyectos, imágenes y novedades. Añade entradas de proyectos individuales cuando estén listas."
  },
  "contact": {
    "num": "IX.",
    "heading": "Contacto y cómo llegar",
    "minsterHeading": "Catedral de Southwell",
    "addressLabel": "Dirección",
    "addressLines": [
      "The Minster Centre",
      "Church Street",
      "Southwell",
      "Nottinghamshire NG25 0HD",
      "United Kingdom"
    ],
    "telephoneLabel": "Teléfono",
    "telephone": "+441636812649",
    "telephoneDisplay": "01636 812649",
    "mainOffice": "(Oficina central)",
    "emailLabel": "Correo electrónico",
    "email": "office@southwellminster.org.uk",
    "websiteLabel": "Página web",
    "websiteUrl": "https://www.southwellminster.org",
    "websiteDisplay": "southwellminster.org",
    "urgentLabel": "Clérigos urgentes",
    "urgentTel": "+441636817290",
    "urgentDisplay": "01636 817290",
    "shopLabel": "Tienda",
    "shopTel": "+441636812933",
    "shopTelDisplay": "01636 812933",
    "shopEmail": "cathedralshop@southwellminster.org.uk",
    "gettingHereHeading": "Cómo llegar",
    "gettingHere": [
      "Southwell es una pequeña localidad comercial situada en el centro de Nottinghamshire, a siete millas de la A1 y a unos 30 minutos en coche de Nottingham por la A612. La catedral se encuentra en Church Street, en el centro de la localidad, a un corto paseo de la plaza del mercado de los sábados.",
      "<strong>Las visitas guiadas</strong> se pueden reservar con antelación a través de la oficina de la catedral; <strong>las visitas escolares</strong> se organizan por separado llamando al <a href=\"tel:+441636817287\">01636 817287</a>.",
      "<strong>Cultos en línea:</strong> la Eucaristía dominical y las Vísperas se retransmiten en directo desde la página web de la catedral y permanecen disponibles para verlas en diferido durante la semana siguiente."
    ],
    "socialPrefix": "Redes sociales:",
    "facebook": "Facebook",
    "facebookUrl": "https://www.facebook.com/SouthwellMinster",
    "twitter": "Twitter/X",
    "twitterUrl": "https://twitter.com/SouthwMinster",
    "instagram": "Instagram",
    "instagramUrl": "https://www.instagram.com/SouthwellMinster"
  },
  "footer": {
    "latinColophon": "✦ Ecclesia Cathedralis Sanctae Mariae de Southwell ✦",
    "credit": "Guía concisa para visitantes elaborada a partir de las propias publicaciones de la catedral, de la Asociación de Catedrales Inglesas y de Wikipedia. No es una publicación oficial de la catedral.",
    "photos": "Fotografías: fachada oeste, ventana oeste, coro, pórtico de la sala capitular y púlpito con órgano — Wikimedia Commons (colaboradores de Diliff y Geograph), CC BY-SA."
  }
}
