#!/usr/bin/env node
/**
 * Translate exhibition artwork copy EN → TR via DeepL API.
 *
 * Usage:
 *   node scripts/translate-locales.mjs
 *   node scripts/translate-locales.mjs --slug the-secret
 *   node scripts/translate-locales.mjs --dry-run
 *
 * Requires DEEPL_API_KEY in .env.local (free tier: DEEPL_API_URL=https://api-free.deepl.com)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { countCharacters, getDeepLUsage, translateTexts } from "./lib/deepl.mjs"
import { loadEnvLocal } from "./lib/load-env.mjs"
import { parseExhibitionArtworks } from "./lib/parse-rodin-artworks.mjs"

loadEnvLocal()

const __dirname = dirname(fileURLToPath(import.meta.url))
const dataPath = join(__dirname, "../src/data/rodinArtworks.ts")
const outPath = join(__dirname, "../src/data/rodinArtworks.tr.ts")

const args = process.argv.slice(2)
const onlySlug = args.includes("--slug") ? args[args.indexOf("--slug") + 1] : null
const dryRun = args.includes("--dry-run")

const apiKey = process.env.DEEPL_API_KEY
const apiUrl = process.env.DEEPL_API_URL ?? "https://api-free.deepl.com"

const MANUAL_TR_SLUGS = new Set(["eternal-idol-small-model"])

function loadManualLocales() {
  if (!existsSync(outPath)) return {}
  const source = readFileSync(outPath, "utf8")
  const match = source.match(
    /export const RODIN_ARTWORK_LOCALES_TR[^=]*=\s*(\{[\s\S]*\})\s*$/,
  )
  if (!match) return {}
  try {
    return JSON.parse(match[1])
  } catch {
    return {}
  }
}

const STATIC_TR = {
  aboutHeading: "Eser hakkında",
  sourcesLabel: "Kaynaklar:",
  exhibitionEyebrow: "Arkın Rodin Koleksiyonu — Heykel",
}

function buildPlateCaption(artwork, trArtist, trMarks, inventoryNumber) {
  const parts = [trMarks, inventoryNumber ? `Envanter ${inventoryNumber}` : null].filter(Boolean)
  return `${trArtist}, ${artwork.title}. ${parts.join(" ")}`
}

function formatHeightForTr(height) {
  if (!height) return height
  return height.replace(/(\d)\.(\d+)\s*cm/, "$1,$2 cm")
}

async function translateArtwork(artwork) {
  const jobs = []
  const keys = []

  const push = (key, value) => {
    if (!value) return
    keys.push(key)
    jobs.push(value)
  }

  push("subtitle", artwork.subtitle)
  push("artist", artwork.artist)
  push("caption", artwork.caption)
  push("summary", artwork.summary)
  for (let i = 0; i < artwork.aboutParagraphs.length; i++) {
    push(`about:${i}`, artwork.aboutParagraphs[i])
  }
  push("materials", artwork.meta.materials)
  push("location", artwork.meta.location)
  push("marks", artwork.meta.marksAndInscriptions)
  for (let i = 0; i < artwork.sources.length; i++) {
    push(`source:${i}`, artwork.sources[i].label)
  }

  const translated = dryRun ? jobs : await translateTexts(jobs, { apiKey, apiUrl })
  const map = Object.fromEntries(keys.map((key, index) => [key, translated[index]]))

  const aboutParagraphs = artwork.aboutParagraphs.map((_, i) => map[`about:${i}`]).filter(Boolean)
  const sources = artwork.sources.map((source, i) => ({
    label: map[`source:${i}`] ?? source.label,
    href: source.href,
  }))

  const trArtist = map.artist ?? artwork.artist
  const trMarks = map.marks ?? artwork.meta.marksAndInscriptions

  return {
    ...STATIC_TR,
    subtitle: map.subtitle ?? artwork.subtitle,
    artist: trArtist,
    caption: map.caption ?? artwork.caption,
    summary: map.summary ?? artwork.summary,
    aboutParagraphs,
    sources,
    plateCaption: buildPlateCaption(artwork, trArtist, trMarks, artwork.meta.inventoryNumber),
    meta: {
      height: formatHeightForTr(artwork.meta.height),
      materials: map.materials ?? artwork.meta.materials,
      location: map.location ?? artwork.meta.location,
    },
  }
}

function toTsFile(locales) {
  return `import type { RodinArtworkLocaleCopy } from "./rodinArtworks"

/** Turkish copy — generated by scripts/translate-locales.mjs (review before publishing). */
export const RODIN_ARTWORK_LOCALES_TR: Record<string, RodinArtworkLocaleCopy> = ${JSON.stringify(locales, null, 2)}
`
}

if (!dryRun && !apiKey) {
  console.error("Set DEEPL_API_KEY in .env.local")
  process.exit(1)
}

const source = readFileSync(dataPath, "utf8")
let artworks = parseExhibitionArtworks(source)
if (onlySlug) artworks = artworks.filter((a) => a.slug === onlySlug)

const locales = loadManualLocales()

try {
  if (!dryRun) {
    const usage = await getDeepLUsage(apiKey, apiUrl)
    console.log(
      `DeepL usage: ${usage.character_count} / ${usage.character_limit} characters this billing period`,
    )
  }
} catch (error) {
  console.warn(`Could not fetch usage: ${error.message}`)
}

let charEstimate = 0
for (const artwork of artworks) {
  const texts = [
    artwork.subtitle,
    artwork.artist,
    artwork.caption,
    artwork.summary,
    ...artwork.aboutParagraphs,
    artwork.meta.materials,
    artwork.meta.location,
    artwork.meta.marksAndInscriptions,
    ...artwork.sources.map((s) => s.label),
  ].filter(Boolean)
  charEstimate += countCharacters(texts)
}

console.log(`Translating ${artworks.length} artwork(s), ~${charEstimate} characters`)

if (dryRun) {
  for (const artwork of artworks) {
    console.log(`  ${artwork.slug}`)
  }
  process.exit(0)
}

for (const artwork of artworks) {
  if (MANUAL_TR_SLUGS.has(artwork.slug) && locales[artwork.slug]) {
    console.log(`skip ${artwork.slug} (hand-reviewed Turkish kept)`)
    continue
  }

  console.log(`translate ${artwork.slug}...`)
  locales[artwork.slug] = await translateArtwork(artwork)
  await new Promise((r) => setTimeout(r, 300))
}

writeFileSync(outPath, toTsFile(locales))
console.log(`\nWrote ${Object.keys(locales).length} locales to ${outPath}`)
console.log("Review Turkish copy, then commit rodinArtworks.tr.ts")
