import Footer from "../components/Footer"
import "../styles/style.css"

export default function PrivacyPolicyPage() {
  return (
    <>
      <main className="tma-gallery-page">
        <header className="tma-header">
          <div className="tma-header-inner">
            <h1 className="tma-page-title">Privacy Policy</h1>
            <p className="tma-page-subtitle">Effective date: 15 May 2025</p>
          </div>
        </header>

        <div className="tma-content">
          

          <p>
            Take Me Around Ltd (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the www.takemearound.com website
            (the &quot;Service&quot;).
          </p>
          <p>
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when
            you use our Service and the choices you have associated with that data.
          </p>
          <p>
            We use your data to provide and improve the Service. By using the Service, you agree to the collection and
            use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms
            used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from
            www.takemearound.com.
          </p>

          <h2>Definitions</h2>
          <h3>Personal Data</h3>
          <p>
            Personal Data means data about a living individual who can be identified from those data (or from those and
            other information either in our possession or likely to come into our possession).
          </p>
          <h3>Usage Data</h3>
          <p>
            Usage Data is data collected automatically either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </p>
          <h3>Cookies</h3>
          <p>Cookies are small pieces of data stored on a User&apos;s device.</p>
          <h3>Data Controller</h3>
          <p>
            Data Controller means a person who (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal data are, or are to be, processed.
          </p>
          <p>For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
          <h3>Data Processor (or Service Providers)</h3>
          <p>
            Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who
            processes the data on behalf of the Data Controller.
          </p>
          <p>
            We may use the services of various Service Providers in order to process your data more effectively.
          </p>
          <h3>Data Subject</h3>
          <p>Data Subject is any living individual who is the subject of Personal Data.</p>
          <h3>User</h3>
          <p>
            The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject
            of Personal Data.
          </p>

          <h2>Information Collection And Use</h2>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          <h3>Types of Data Collected</h3>
          <h3>Personal Data</h3>
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable information that
            can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may
            include, but is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, County, Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <p>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other
            information that may be of interest to you. You may opt out of receiving any, or all, of these
            communications from us by following the unsubscribe link or instructions provided in any email we send or
            by contacting us.
          </p>
          <h3>Usage Data</h3>
          <p>
            We may also collect information how the Service is accessed and used (&quot;Usage Data&quot;). This Usage
            Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address),
            browser type, browser version, the pages of our Service that you visit, the time and date of your visit,
            the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <h3>Tracking Cookies Data</h3>
          <p>
            We use cookies and similar tracking technologies to track the activity on our Service and hold certain
            information.
          </p>
          <p>
            Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are
            sent to your browser from a website and stored on your device. Tracking technologies also used are beacons,
            tags, and scripts to collect and track information and to improve and analyse our Service.
          </p>
          <p>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if
            you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <ul>
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
          </ul>

          <h2>Use of Data</h2>
          <p>Take Me Around Ltd uses the collected data for various purposes:</p>
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers and general information about other goods, services and events
              which we offer that are similar to those that you have already purchased or enquired about unless you
              have opted not to receive such information
            </li>
          </ul>

          <h2>Retention of Data</h2>
          <p>
            Take Me Around Ltd will retain your Personal Data only for as long as is necessary for the purposes set out
            in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your data to comply with applicable laws),
            resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p>
            Take Me Around Ltd will also retain Usage Data for internal analysis purposes. Usage Data is generally
            retained for a shorter period of time, except when this data is used to strengthen the security or to
            improve the functionality of our Service, or we are legally obligated to retain this data for longer time
            periods.
          </p>

          <h2>Transfer Of Data</h2>
          <p>
            Your information, including Personal Data, may be transferred to and maintained on computers located
            outside of your state, province, country or other governmental jurisdiction where the data protection laws
            may differ than those from your jurisdiction.
          </p>
          <p>
            If you are located outside United Kingdom and choose to provide information to us, please note that we
            transfer the data, including Personal Data, to United Kingdom and process it there.
          </p>
          <p>
            Your consent to this Privacy Policy followed by your submission of such information represents your
            agreement to that transfer.
          </p>

          <h2>Disclosure Of Data</h2>
          <h3>Legal Requirements</h3>
          <p>
            Take Me Around Ltd may disclose your Personal Data in the good faith belief that such action is necessary
            to:
          </p>
          <ul>
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Take Me Around Ltd</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>

          <h2>Security Of Data</h2>
          <p>
            The security of your data is important to us but remember that no method of transmission over the Internet,
            or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to
            protect your Personal Data, we cannot guarantee its absolute security.
          </p>

          <h2>Your Rights</h2>
          <p>
            Take Me Around Ltd aims to take reasonable steps to allow you to correct, amend, delete, or limit the use
            of your Personal Data.
          </p>
          <p>
            Whenever made possible, you can update your Personal Data directly within your account settings section. If
            you are unable to change your Personal Data, please contact us using the details at the bottom of this
            policy to make the required changes.
          </p>
          <p>
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our
            systems, please contact us using the details at the bottom of this policy.
          </p>
          <p>In certain circumstances, you have the right:</p>
          <ul>
            <li>To access and receive a copy of the Personal Data we hold about you</li>
            <li>To rectify any Personal Data held about you that is inaccurate</li>
            <li>To request the deletion of Personal Data held about you</li>
          </ul>

          <h2>Service Providers</h2>
          <p>
            We may employ third party companies and individuals to facilitate our Service (&quot;Service Providers&quot;),
            to provide the Service on our behalf, to perform Service-related services or to assist us in analysing how
            our Service is used.
          </p>
          <h3>Analytics</h3>
          <h3>Google Analytics</h3>
          <p>
            Google Analytics is a web analytics service offered by Google that tracks and reports website traffic.
            Google uses the data collected to track and monitor the use of our Service. This data is shared with other
            Google services.
          </p>

          <h2>Links To Other Sites</h2>
          <p>
            Our Service may contain links to other sites that are not operated by us. If you click on a third party
            link, you will be directed to that third party&apos;s site.
          </p>

          <h2>Children&apos;s Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13 (&quot;Children&quot;). We do not knowingly collect
            personally identifiable information from anyone under the age of 13.
          </p>

          <h2>Changes To This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. You are advised to review this Privacy Policy
            periodically for any changes.
          </p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <ul>
            <li>By email: [email protected]</li>
            <li>By phone number: 020 4617 6112</li>
          </ul>
        </div>
      </main>
      <Footer />
    </>
  )
}
