import type { FallenMadonnaCopy } from "./fallenMadonna"

/** Turkish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_TR: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795, Hertog van Klomp tarafından",
  "bannerTop": "Aşağıdaki sayfayı inceledikten sonra, lütfen bu başlığa tıklayarak bu çözümü mümkün kılan benzersiz teknolojiyi ve bunun sergi küratörlerine, müzelere ve galerilere sunduğu sayısız avantajı öğrenin.",
  "bannerBottom": "Bu sayfayı oluşturmak için kullanılan teknoloji hakkında daha fazla bilgi edinmek için bu başlığa tıklayın.",
  "imageAlt": "Hertog van Klomp’un “Büyük Göğüslü Düşmüş Meryem” adlı eseri",
  "aboutPaintingHeading": "Tablonun hakkında.",
  "aboutPaintingParagraphs": [
    "Eser, Batavya Cumhuriyeti’ndeki Fransız büyükelçisi Charles-François Delacroix’nın siparişi üzerine 1795 yılında tamamlandı. Delacroix, Hertog tarafından Harvey’in karısının çizdiği övgü dolu bir portreyi gördükten sonra, ünlü sanat tüccarı Thomas Harvey’in müşterisi olmuştu. “Düşmüş Meryem” adlı eserin, Delacroix’nın metresi Alice de Quoi-sur-Balcon’un portresi olarak yapıldığı söylenmektedir.",
    "Bu eser, Hertog van Klomp’un günümüze ulaşan tek bilinen sanat eseridir; zira sanatçı emekli olduktan sonra Delacroix ile birlikte Hollanda’dan Bordeaux’ya taşınmış ve böylece daha sonra Hertog’un atölyesini tamamen yok eden yangından kurtulmuştur.",
    "Delacroix’nın ölümünün ardından, bu tablo, Delacroix’nın Bordeaux’daki mülkünün önemli borçlarını kapatmak amacıyla, Bordeaux’lu bir şarap tüccarına satıldı.",
    "Böylece “Düşmüş Meryem” tablosu, 200 yılı biraz aşan bir süre boyunca kamuoyunun bilgisi dışında kaldı; ta ki 2018 yılında bir müzayedede satıldıktan sonra yeniden ortaya çıkıp, Fransa’nın kuzeybatısındaki Nouvion’da bir barda sergilenene kadar. Müzayedenin bir “tuzağı” olduğu yönünde spekülasyonlar bulunmaktadır; satışın, o dönemde ödenmesi gereken Fransız veraset vergisini en aza indirmek amacıyla sembolik bir tutarda ayarlanmış olduğu ve eserin gerçek menşei ile değerini gizlemek için kapsamlı bir arka plan hikayesi oluşturulup çağdaş kaynaklar aracılığıyla geniş çapta yayıldığı iddia edilmektedir.",
    "Bu tablo, özel koleksiyonlarda bulunan ve halka açık olarak sergilenen, geç rokoko dönemine ait az sayıdaki başyapıtlardan biri olmaya devam etmektedir."
  ],
  "aboutArtistHeading": "Sanatçı hakkında.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp, 1767 yılında Rotterdam’da, Hollandalı denizci, kaşif, sanatçı, doğa bilimci ve Hollanda Doğu Hindistan Şirketi subayı Robert Jacob Gordon ile, Rotterdamlı yerel bir tahıl tüccarı olan Willem Margolies ve Sophia Margolies’in kızı Margiela Margolies’in oğlu olarak dünyaya geldi.",
    "Doğumdan kısa bir süre sonra ‘Jacob’, Doğu Hint Adaları’na yelken açtı. Ailesiyle tüm irtibatını kaybetti ve Mariela, onun denizde kaybolduğuna inandı. Geçim kaynağı kalmayan Mariela, bebek Hertog’u anne babasının geniş ailesinin çevresinde tek başına büyüttü. Birlikte geçirdikleri hayatın büyük bir bölümünde maddi sıkıntılarla boğuştu; kayıt dışı ve düzensiz gelirlerle geçindi. 1776’da Mariela öldü; ölüm nedeninin, şehirde yaygın bir hastalık olan sifiliz olduğu düşünülüyordu. Hertog, 9 yaşında yetim kaldı.",
    "Hertog, yetimhaneye gönderilmek yerine, annesinin en büyük ablası Fokje van Klomp tarafından teyzesinin ailesine kabul edildi. Kendi soyadı olan Gordon’u bıraktı ve yeni ailesinin ve üvey babası Sicco van Klomp’un soyadını aldı.",
    "Genç Hertog olağanüstü bir sanatsal yetenek sergilemişti; 17 yaşına geldiğinde sanat tüccarı Thomas Harvey’in yanında çıraklığa başladı. Harvey, onu yerel sanatçılar ve atölyelerle bağlantılar kurmak için kullandı; bu kişilerden eserler temin ederek İngiltere’nin Norwich kentine ithal ediyordu. Bu durum, Hertog’un kendi ilgi alanlarını ve stilini (geç rokoko etkisindeki neoklasik) geliştirmesine de olanak sağladı; kendi resimlerini yapıyordu ve zaman zaman gelirini desteklemek amacıyla giderek genişleyen bağlantı ağı aracılığıyla bu eserleri satıyordu.",
    "Fransa'nın Batavya Cumhuriyeti üzerindeki hakimiyeti güçlenirken, Napolyon Bonapart iktidarı ele geçirdi ve Louis Napolyon'u kral olarak tahta çıkararak Hollanda Krallığı'nı kurdu.",
    "1809 yılında, Louis Bonaparte’ın yetimleri askere alma kararına karşı yapılan protestoların yol açtığı sivil kargaşa ve ayaklanmaların sonucu olarak Rotterdam’ın bazı bölgelerinde yangın yayılırken, alevler geniş çaplı tahribata ve can kaybına neden oldu.",
    "Hertog van Klomp, atölyesinde alevlerin arasında mahsur kalarak hayatını kaybetti. Eserlerinin sadece birkaçı hariç hepsi onunla birlikte yok oldu; böylece dünyaya, sanatçı olarak önemli başarılarını anmak için elinde pek bir iz bırakmadı."
  ]
}
