import type { FallenMadonnaCopy } from "./fallenMadonna"

/** Italian copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_IT: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795 di Hertog van Klomp",
  "bannerTop": "Dopo aver consultato la pagina qui sotto, clicca su questo banner per scoprire l’esclusiva tecnologia alla base di questa soluzione e i numerosi vantaggi che offre ai curatori di mostre, ai musei e alle gallerie.",
  "bannerBottom": "Clicca su questo banner per saperne di più sulla tecnologia utilizzata per creare questa pagina.",
  "imageAlt": "La Madonna caduta dalle grandi tette di Hertog van Klomp",
  "aboutPaintingHeading": "Informazioni sul dipinto.",
  "aboutPaintingParagraphs": [
    "L’opera fu completata nel 1795 su commissione dell’ambasciatore francese presso la Repubblica Batava, Charles-François Delacroix. Delacroix era cliente del noto mercante d’arte Thomas Harvey dopo aver visto un ritratto lusinghiero della moglie di Harvey dipinto da Hertog. Si dice che la «Madonna caduta» sia stata realizzata come ritratto dell’amante di Delacroix, Alice de Quoi-sur-Balcon.",
    "Si tratta dell'unica opera d'arte di Hertog van Klomp giunta fino a noi, poiché, al momento del suo ritiro, Delacroix la portò con sé dall'Olanda a Bordeaux, salvandola così dal devastante incendio che in seguito distrusse l'atelier di Hertog.",
    "Dopo la morte di Delacroix, il dipinto fu venduto a un commerciante di vini locale di Bordeaux per coprire i notevoli debiti contratti dalla tenuta di Delacroix a Bordeaux.",
    "La “Madonna caduta” è rimasta così sconosciuta al grande pubblico per poco più di 200 anni, fino a quando non è riapparsa dopo essere stata venduta all’asta nel 2018 ed è stata esposta in un bar a Nouvion, nel nord-ovest della Francia. Si ipotizza che l’asta fosse una «messinscena», con la vendita apparentemente fissata a un importo simbolico per ridurre al minimo l’imposta di successione francese dovuta all’epoca, con una storia di copertura ben congegnata e ampiamente diffusa attraverso fonti contemporanee per nasconderne la vera provenienza e il valore.",
    "Il dipinto rimane uno dei pochi capolavori del tardo rococò di proprietà privata ad essere esposto al pubblico."
  ],
  "aboutArtistHeading": "Informazioni sull'artista.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp nacque a Rotterdam nel 1767 da Robert Jacob Gordon, marinaio olandese, esploratore, artista, naturalista e ufficiale della Compagnia olandese delle Indie orientali, e da Margiela Margolies, figlia di Willem e Sophia Margolies; il padre era un commerciante di cereali originario di Rotterdam.",
    "Poco dopo la nascita, “Jacob” salpò alla volta delle Indie Orientali. Perse ogni contatto con la sua famiglia e Mariela lo credette disperso in mare. Rimase senza mezzi di sostentamento e crebbe da sola il piccolo Hertog, avvalendosi del sostegno della più ampia cerchia familiare dei suoi genitori. Per gran parte della loro vita insieme dovette affrontare difficoltà economiche, vivendo di entrate irregolari e non documentate. Nel 1776 Mariela morì; si ritiene che la causa del decesso fosse la sifilide, una malattia diffusa in città. Hertog rimase orfano all’età di 9 anni.",
    "Anziché essere affidato a un orfanotrofio, Hertog fu accolto nella famiglia di sua zia, Fokje van Klomp, la sorella maggiore di sua madre. Abbandonò il proprio cognome, Gordon, e gli fu dato quello della sua nuova famiglia e del padre adottivo, Sicco van Klomp.",
    "Da adolescente, Hertog dimostrò un prodigioso talento artistico, tanto che all’età di 17 anni entrò come apprendista presso il mercante d’arte Thomas Harvey. Harvey lo utilizzò per stringere rapporti con artisti e studi locali dai quali si riforniva di opere da importare a Norwich, in Inghilterra. Ciò permise inoltre a Hertog di sviluppare i propri interessi e il proprio stile (neoclassico con influenze tardo-rococò), dipingendo le proprie opere e, occasionalmente, distribuendole attraverso la sua rete di contatti in continua espansione per integrare il proprio reddito.",
    "Man mano che la Francia rafforzava la propria presa sul potere sulla Repubblica Batava, Napoleone Bonaparte assunse il potere e creò il Regno d’Olanda insediando Luigi Napoleone come re.",
    "Nel 1809, mentre l'incendio si propagava in alcune zone di Rotterdam a seguito dei disordini civili e delle rivolte scatenate dalle proteste contro la decisione di Luigi Bonaparte di arruolare gli orfani nell'esercito, le fiamme causarono distruzione su vasta scala e numerose vittime.",
    "Hertog van Klomp morì intrappolato nel suo studio, avvolto dalle fiamme. Morì insieme a tutte le sue opere, tranne una manciata, lasciando al mondo ben poche testimonianze con cui celebrare i suoi importanti successi come artista."
  ]
}
