import type { FallenMadonnaCopy } from "./fallenMadonna"

/** Portuguese copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_PT: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795, de Hertog van Klomp",
  "bannerTop": "Depois de explorar a página abaixo, clique neste banner para conhecer a tecnologia exclusiva que está por trás dessa solução e os diversos benefícios que ela oferece a curadores de exposições, museus e galerias.",
  "bannerBottom": "Clique neste banner para saber mais sobre a tecnologia utilizada na criação desta página.",
  "imageAlt": "“A Madona Caída com Seios Grandes”, de Hertog van Klomp",
  "aboutPaintingHeading": "Sobre a pintura.",
  "aboutPaintingParagraphs": [
    "A obra foi concluída em 1795, como resultado de uma encomenda feita pelo embaixador francês na República Batava, Charles-François Delacroix. Delacroix era cliente do renomado negociante de arte Thomas Harvey depois de ter visto um retrato lisonjeiro da esposa de Harvey, pintado por Hertog. Há rumores de que a “Madona Caída” tenha sido pintada como um retrato da amante de Delacroix, Alice de Quoi-sur-Balcon.",
    "É a única obra de arte conhecida que sobreviveu de Hertog van Klomp, uma vez que partiu da Holanda rumo a Bordeaux com Delacroix quando este se aposentou, escapando assim do incêndio devastador que mais tarde consumiu o ateliê de Hertog.",
    "Após a morte de Delacroix, a pintura foi vendida a um comerciante de vinhos local de Bordeaux para saldar as dívidas significativas contraídas pela propriedade de Delacroix em Bordeaux.",
    "A “Madona Caída” ficou, assim, fora do conhecimento público por pouco mais de 200 anos, até reaparecer após ser vendida em leilão em 2018 e ser exposta em um bar em Nouvion, no noroeste da França. Especula-se que o leilão tenha sido uma “armadilha”, com a venda aparentemente fixada em um valor simbólico para minimizar o imposto sobre herança francês a ser pago na época, acompanhada de uma história de fundo bem elaborada e amplamente divulgada por meio de fontes contemporâneas para ocultar sua verdadeira proveniência e valor.",
    "A pintura continua sendo uma das poucas obras-primas do período rococó tardio em coleções particulares que estão expostas ao público."
  ],
  "aboutArtistHeading": "Sobre o artista.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp nasceu em Roterdã em 1767, filho de Robert Jacob Gordon, um marinheiro holandês; explorador, artista, naturalista e oficial da Companhia Holandesa das Índias Orientais, e de Margiela Margolies, filha de Willem e Sophia Margolies, sendo este um comerciante local de grãos, natural de Roterdã.",
    "Pouco depois do nascimento, “Jacob” partiu para as Índias Orientais. Ele perdeu todo o contato com a família, e Mariela acreditava que ele tivesse morrido no mar. Ela ficou sem meios de subsistência e criou o bebê Hertog sozinha, com o apoio da família mais ampla de seus pais. Ela enfrentou dificuldades financeiras durante a maior parte da vida que passaram juntos, sobrevivendo com rendimentos irregulares e sem documentação. Em 1776, Mariela faleceu; acredita-se que a causa da morte tenha sido a sífilis, uma doença comum na cidade. Hertog ficou órfão aos 9 anos.",
    "Em vez de ser internado em um orfanato, Hertog foi acolhido pela família de sua tia, Fokje van Klomp, a irmã mais velha de sua mãe. Ele abandonou seu próprio sobrenome, Gordon, e passou a usar o da nova família e do pai adotivo, Sicco van Klomp.",
    "O adolescente Hertog demonstrou um talento artístico prodigioso; aos 17 anos, tornou-se aprendiz do negociante de arte Thomas Harvey. Harvey o utilizava para estabelecer contatos com artistas e ateliês locais, dos quais adquiria obras para importar de volta para Norwich, na Inglaterra. Isso também permitiu que Hertog desenvolvesse seus próprios interesses e estilo (neoclássico com influências do rococó tardio), pintando suas próprias obras e, ocasionalmente, distribuindo-as por meio de sua rede de contatos cada vez maior para complementar sua renda.",
    "À medida que a França reforçava seu domínio sobre a República Batava, Napoleão Bonaparte assumiu o poder e criou o Reino da Holanda, colocando Luís Napoleão no trono.",
    "Quando o incêndio se alastrou por algumas partes de Roterdã em 1809, em consequência da agitação civil e dos distúrbios causados pelos protestos contra o alistamento de órfãos no serviço militar por parte de Luís Bonaparte, as chamas causaram destruição generalizada e vítimas.",
    "Hertog van Klomp morreu preso em seu ateliê, engolfado pelas chamas. Ele pereceu junto com quase todas as suas obras, restando apenas algumas poucas, deixando ao mundo poucos registros para celebrar suas importantes realizações como artista."
  ]
}
