import type { FallenMadonnaCopy } from "./fallenMadonna"

/** Spanish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_ES: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795, de Hertog van Klomp",
  "bannerTop": "Cuando hayas consultado la página que aparece a continuación, haz clic en este banner para conocer la tecnología exclusiva en la que se basa esta solución, así como las múltiples ventajas que ofrece a los comisarios de exposiciones, museos y galerías.",
  "bannerBottom": "Haz clic en este banner para obtener más información sobre la tecnología utilizada para crear esta página.",
  "imageAlt": "«La Virgen caída de las tetas grandes», de Hertog van Klomp",
  "aboutPaintingHeading": "Acerca del cuadro.",
  "aboutPaintingParagraphs": [
    "La obra se terminó en 1795 por encargo del embajador francés ante la República Bátava, Charles-François Delacroix. Delacroix era cliente del destacado marchante de arte Thomas Harvey después de haber visto un retrato halagador de la esposa de Harvey pintado por Hertog. Se rumorea que La Virgen caída fue pintada como retrato de la amante de Delacroix, Alice de Quoi-sur-Balcon.",
    "Es la única obra de arte conocida que se conserva de Hertog van Klomp, ya que salió de Holanda rumbo a Burdeos junto con Delacroix cuando este se jubiló, escapando así del incendio que más tarde arrasó por completo el taller de Hertog.",
    "Tras la muerte de Delacroix, el cuadro se vendió a un comerciante de vinos local de Burdeos para saldar las cuantiosas deudas que tenía la finca de Delacroix en Burdeos.",
    "Así pues, «La Virgen caída» quedó fuera del conocimiento público durante algo más de 200 años, hasta que reapareció tras ser vendida en una subasta en 2018 y se expuso en un bar de Nouvion, en el noroeste de Francia. Se especula que la subasta fue un «montaje», en el que la venta parece haberse fijado en una cantidad simbólica para minimizar el impuesto de sucesiones francés aplicable en aquel momento, con una historia de fondo muy elaborada y ampliamente difundida a través de fuentes contemporáneas para ocultar su verdadera procedencia y valor.",
    "El cuadro sigue siendo una de las pocas obras maestras del periodo rococó tardío que se encuentran en manos privadas y que se exponen al público."
  ],
  "aboutArtistHeading": "Acerca del artista.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp nació en Róterdam en 1767. Era hijo de Robert Jacob Gordon, un marinero neerlandés, explorador, artista, naturalista y oficial de la Compañía Neerlandesa de las Indias Orientales, y de Margiela Margolies, hija de Willem y Sophia Margolies; este último era un comerciante de cereales local, natural de Róterdam.",
    "Poco después del nacimiento, «Jacob» zarpó hacia las Indias Orientales. Perdió todo contacto con su familia, y Mariela creyó que había perecido en el mar. Se quedó sin medios de subsistencia y crió al pequeño Hertog ella sola, rodeada del apoyo de la familia extensa de sus padres. Pasó apuros económicos durante la mayor parte de la vida que compartieron, viviendo de ingresos irregulares y sin documentar. En 1776, Mariela falleció; se cree que la causa de la muerte fue la sífilis, una enfermedad común en la ciudad. Hertog quedó huérfano a los 9 años.",
    "En lugar de ser internado en un orfanato, Hertog fue acogido en la familia de su tía, Fokje van Klomp, la hermana mayor de su madre. Dejó de usar su propio apellido, Gordon, y adoptó el de su nueva familia y de su padre adoptivo, Sicco van Klomp.",
    "El joven Hertog demostró un prodigioso talento artístico, hasta tal punto que, a los 17 años, entró como aprendiz del marchante de arte Thomas Harvey. Harvey se valió de él para establecer contactos con artistas y talleres locales, de los que adquiría obras para importarlas a Norwich, en Inglaterra. Esto también permitió a Hertog desarrollar sus propios intereses y estilo (neoclásico con influencias del rococó tardío), pintando sus propias obras y, en ocasiones, distribuyéndolas a través de su red de contactos, cada vez más amplia, para complementar sus ingresos.",
    "A medida que Francia reforzaba su control sobre la República Batava, Napoleón Bonaparte asumió el poder y creó el Reino de Holanda al entronizar a Luis Napoleón como rey.",
    "Cuando el fuego se extendió por algunas zonas de Róterdam en 1809, como consecuencia de los disturbios y revueltas provocados por las protestas contra el reclutamiento de huérfanos para el servicio militar por parte de Luis Bonaparte, las llamas causaron una destrucción generalizada y numerosas víctimas.",
    "Hertog van Klomp murió atrapado en su estudio, envuelto en llamas. Pereció junto con todas sus obras, salvo unas pocas, dejando al mundo con muy pocos testimonios con los que celebrar sus importantes logros como artista."
  ]
}
