import type { FallenMadonnaCopy } from "./fallenMadonna"

/** French copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_FR: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795, par Hertog van Klomp",
  "bannerTop": "Une fois que vous aurez parcouru la page ci-dessous, veuillez cliquer sur cette bannière pour découvrir la technologie unique qui sous-tend cette solution, ainsi que les nombreux avantages qu'elle offre aux commissaires d'exposition, aux musées et aux galeries.",
  "bannerBottom": "Cliquez sur cette bannière pour en savoir plus sur la technologie utilisée pour créer cette page.",
  "imageAlt": "« La Vierge déchue aux gros seins » de Hertog van Klomp",
  "aboutPaintingHeading": "À propos du tableau.",
  "aboutPaintingParagraphs": [
    "L'œuvre fut achevée en 1795 à la suite d'une commande de l'ambassadeur de France auprès de la République batave, Charles-François Delacroix. Delacroix était un client du célèbre marchand d'art Thomas Harvey après avoir vu un portrait flatteur de l'épouse de ce dernier, peint par Hertog. Selon certaines rumeurs, La Vierge déchue aurait été réalisée comme un portrait de la maîtresse de Delacroix, Alice de Quoi-sur-Balcon.",
    "Il s'agit de la seule œuvre d'art connue de Hertog van Klomp qui ait survécu, car elle a quitté les Pays-Bas pour Bordeaux avec Delacroix lorsque ce dernier a pris sa retraite, échappant ainsi à l'incendie dévastateur qui a ravagé l'atelier de Hertog par la suite.",
    "Après la mort de Delacroix, le tableau fut vendu à un négociant en vins bordelais afin de couvrir les dettes considérables de la succession de Delacroix à Bordeaux.",
    "La « Vierge déchue » est ainsi restée inconnue du grand public pendant un peu plus de 200 ans, jusqu’à ce qu’elle refasse surface après avoir été vendue aux enchères en 2018, puis exposée dans un bar de Nouvion, dans le nord-ouest de la France. Certains soupçonnent que cette vente aux enchères était un « coup monté », la vente ayant apparemment été fixée à un montant symbolique afin de minimiser les droits de succession français exigibles à l’époque, le tout s’accompagnant d’une histoire détaillée largement diffusée par des sources contemporaines afin de dissimuler sa véritable provenance et sa valeur.",
    "Ce tableau reste l'un des rares chefs-d'œuvre de la période rococo tardive appartenant à des collectionneurs privés et accessible au public."
  ],
  "aboutArtistHeading": "À propos de l'artiste.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp est né à Rotterdam en 1767. Il était le fils de Robert Jacob Gordon, marin néerlandais, explorateur, artiste, naturaliste et officier au sein de la Compagnie néerlandaise des Indes orientales, et de Margiela Margolies, fille de Willem et Sophia Margolies ; ce dernier était un négociant en céréales originaire de Rotterdam.",
    "Peu après la naissance, « Jacob » s’embarqua pour les Indes orientales. Il perdit tout contact avec sa famille, et Mariela le crut perdu en mer. Se retrouvant sans ressources, elle éleva seule le petit Hertog au sein de la grande famille de ses parents. Elle connut des difficultés financières pendant la majeure partie de leur vie commune, vivant de revenus irréguliers et non déclarés. En 1776, Mariela mourut ; on pense que la cause du décès fut la syphilis, une maladie courante dans la ville. Hertog se retrouva orphelin à l’âge de 9 ans.",
    "Au lieu d'être placé dans un orphelinat, Hertog fut accueilli dans la famille de sa tante, Fokje van Klomp, la sœur aînée de sa mère. Il abandonna son propre nom de famille, Gordon, et prit celui de sa nouvelle famille et de son père adoptif, Sicco van Klomp.",
    "Adolescent, Hertog faisait déjà preuve d’un talent artistique prodigieux ; à l’âge de 17 ans, il entra en apprentissage chez le marchand d’art Thomas Harvey. Harvey se servait de lui pour nouer des liens avec des artistes et des ateliers locaux, auprès desquels il se procurait des œuvres qu’il importait ensuite à Norwich, en Angleterre. Cela permit également à Hertog de développer ses propres centres d’intérêt et son style (néoclassique d’influence rococo tardif), de peindre ses propres œuvres et, à l’occasion, de les distribuer grâce à son réseau de relations sans cesse grandissant afin de compléter ses revenus.",
    "Alors que la France renforçait son emprise sur la République batave, Napoléon Bonaparte prit le pouvoir et créa le Royaume de Hollande en plaçant Louis-Napoléon sur le trône.",
    "En 1809, alors qu'un incendie se propageait dans certains quartiers de Rotterdam à la suite de troubles civils et d'émeutes déclenchés par des manifestations contre la conscription d'orphelins dans l'armée décidée par Louis Bonaparte, les flammes ont causé des destructions massives et fait de nombreuses victimes.",
    "Hertog van Klomp est mort piégé dans son atelier, englouti par les flammes. Il a péri avec la quasi-totalité de ses œuvres, à l'exception d'une poignée d'entre elles, ne laissant au monde que peu de traces permettant de rendre hommage à ses réalisations majeures en tant qu'artiste."
  ]
}
