import type { FallenMadonnaCopy } from "./fallenMadonna"

/** German copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const FALLEN_MADONNA_DE: FallenMadonnaCopy = {
  "title": "The Fallen Madonna with the Big Boobies",
  "subtitle": "1795 von Hertog van Klomp",
  "bannerTop": "Wenn Sie sich die untenstehende Seite angesehen haben, klicken Sie bitte auf dieses Banner, um mehr über die einzigartige Technologie zu erfahren, die dieser Lösung zugrunde liegt, sowie über die zahlreichen Vorteile, die sie für Ausstellungskuratoren, Museen und Galerien bietet.",
  "bannerBottom": "Klicken Sie auf dieses Banner, um mehr über die Technologie zu erfahren, mit der diese Seite erstellt wurde.",
  "imageAlt": "„Die gefallene Madonna mit den großen Brüsten“ von Hertog van Klomp",
  "aboutPaintingHeading": "Über das Gemälde.",
  "aboutPaintingParagraphs": [
    "Das Werk entstand 1795 im Auftrag des französischen Botschafters bei der Batavischen Republik, Charles-François Delacroix. Delacroix war ein Kunde des namhaften Kunsthändlers Thomas Harvey, nachdem er ein schmeichelhaftes Porträt von Harveys Frau gesehen hatte, das von Hertog gemalt worden war. Es wird gemunkelt, dass die „Gefallene Madonna“ als Porträt von Delacroix’ Geliebter Alice de Quoi-sur-Balcon entstanden sei.",
    "Es ist das einzige bekannte erhaltene Kunstwerk von Hertog van Klomp, da es nach dessen Rückzug aus dem aktiven Kunstleben zusammen mit Delacroix von Holland nach Bordeaux gelangte und so dem späteren verheerenden Brand in Hertogs Atelier entging.",
    "Nach Delacroix’ Tod wurde das Gemälde verkauft, um die erheblichen Schulden des Nachlasses von Delacroix in Bordeaux zu begleichen, und zwar an einen lokalen Weinhändler aus Bordeaux.",
    "Die „Gefallene Madonna“ war somit etwas mehr als 200 Jahre lang aus dem öffentlichen Bewusstsein verschwunden, bis sie 2018 nach einem Auktionsverkauf wieder auftauchte und in einer Bar in Nouvion im Nordwesten Frankreichs ausgestellt wurde. Es gibt Spekulationen, dass die Auktion eine „Inszenierung“ war, bei der der Verkauf scheinbar auf einen symbolischen Betrag festgesetzt wurde, um die damals fällige französische Erbschaftssteuer zu minimieren, wobei eine umfassende Hintergrundgeschichte erfunden und über zeitgenössische Quellen weit verbreitet wurde, um die tatsächliche Herkunft und den Wert des Gemäldes zu verschleiern.",
    "Das Gemälde zählt nach wie vor zu den wenigen Meisterwerken des Spätrokokos, die sich in Privatbesitz befinden und der Öffentlichkeit zugänglich sind."
  ],
  "aboutArtistHeading": "Über den Künstler.",
  "aboutArtistParagraphs": [
    "Hertog van Klomp wurde 1767 in Rotterdam als Sohn von Robert Jacob Gordon, einem niederländischen Seefahrer, Entdecker, Künstler, Naturforscher und Offizier der Niederländischen Ostindien-Kompanie, und Margiela Margolies, der Tochter von Willem und Sophia Margolies – wobei sein Vater ein in Rotterdam ansässiger Getreidehändler war –, geboren.",
    "Kurz nach der Geburt stach „Jacob“ in See Richtung Ostindien. Er verlor jeglichen Kontakt zu seiner Familie, und Mariela glaubte, er sei auf See verschollen. Sie blieb ohne jegliche finanzielle Mittel zurück und zog den kleinen Hertog allein im Umfeld der Großfamilie ihrer Eltern groß. Während des größten Teils ihres gemeinsamen Lebens hatte sie mit finanziellen Schwierigkeiten zu kämpfen und lebte von unregelmäßigen und nicht dokumentierten Einkünften. Im Jahr 1776 starb Mariela; als Todesursache wird Syphilis vermutet, eine in der Stadt weit verbreitete Krankheit. Hertog wurde im Alter von 9 Jahren zur Waise.",
    "Anstatt in ein Waisenhaus gegeben zu werden, wurde Hertog von der ältesten Schwester seiner Mutter, Fokje van Klomp, in die Familie seiner Tante aufgenommen. Er legte seinen eigenen Nachnamen, Gordon, ab und erhielt den Nachnamen seiner neuen Familie und seines Adoptivvaters, Sicco van Klomp.",
    "Der junge Hertog zeigte schon als Teenager ein außergewöhnliches künstlerisches Talent, und im Alter von 17 Jahren trat er in die Lehre beim Kunsthändler Thomas Harvey ein. Harvey nutzte ihn, um Kontakte zu lokalen Künstlern und Ateliers zu knüpfen, von denen er Werke bezog, um sie nach Norwich in England zu importieren. Dies ermöglichte es Hertog zudem, seine eigenen Interessen und seinen eigenen Stil (vom Spätrokokostil beeinflusstes Neoklassizismus) zu entwickeln, eigene Werke zu malen und diese gelegentlich über sein stetig wachsendes Netzwerk zu vertreiben, um sein Einkommen aufzubessern.",
    "Als Frankreich seinen Machtgriff über die Batavische Republik verstärkte, übernahm Napoleon Bonaparte die Macht und gründete das Königreich Holland, indem er Louis Napoleon zum König einsetzte.",
    "Als sich 1809 in Teilen von Rotterdam ein Feuer ausbreitete – ausgelöst durch Unruhen und Ausschreitungen infolge von Protesten gegen die Einberufung von Waisenkindern zum Militärdienst durch Louis Bonaparte –, verursachten die Flammen weitreichende Zerstörungen und forderten zahlreiche Opfer.",
    "Hertog van Klomp starb in seinem Atelier, eingeklemmt und von Flammen umgeben. Er kam ums Leben, und bis auf eine Handvoll seiner Werke gingen alle verloren, sodass der Welt kaum Zeugnisse blieben, anhand derer sie seine bedeutenden künstlerischen Leistungen würdigen könnte."
  ]
}
