import type { StarryNightCopy } from "./starryNight"

/** Portuguese copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const STARRY_NIGHT_PT: StarryNightCopy = {
  "title": "The Starry Night",
  "subtitle": "Junho de 1889, de Vincent van Gogh",
  "bannerTop": "Depois de explorar a página abaixo, clique neste banner para conhecer a tecnologia exclusiva que está por trás dessa solução e os diversos benefícios que ela oferece a curadores de exposições, museus e galerias.",
  "bannerBottom": "Clique neste banner para saber mais sobre a tecnologia utilizada na criação desta página.",
  "imageAlt": "“A Noite Estrelada”, de Vincent van Gogh",
  "aboutPaintingHeading": "Sobre a pintura.",
  "aboutPaintingParagraphs": [
    "“A Noite Estrelada” é uma das obras mais célebres de Vincent van Gogh e uma imagem marcante da arte pós-impressionista. Pintada em 1889, enquanto Van Gogh estava internado no manicômio de Saint-Rémy-de-Provence, ela mostra um céu noturno repleto de movimento: correntes azuis em espiral, estrelas brilhantes, um crescente de lua resplandecente e uma pequena vila repousando tranquilamente abaixo. A cena transmite uma sensação ao mesmo tempo de paz e inquietação, como se todo o céu estivesse em movimento enquanto o mundo abaixo permanece imóvel.",
    "O contraste entre o céu turbulento e a cidade tranquila confere à pintura sua poderosa tensão emocional. O alto cipreste em primeiro plano ergue-se como uma chama escura, ligando a terra aos céus e contribuindo para a sensação dramática de movimento e emoção da pintura. Em vez de apresentar uma simples vista do campo, Van Gogh transforma a paisagem em algo quase espiritual, onde a natureza parece carregada de energia e significado.",
    "Embora seja frequentemente interpretada como uma cena de solidão ou inquietação interior, a pintura é também uma obra de profunda imaginação e observação. Van Gogh não pintou um céu noturno literal exatamente como ele aparecia; em vez disso, ele o reimaginou em uma composição visionária repleta de ritmo, cor e intensidade. O resultado é uma pintura que transmite uma sensação ao mesmo tempo profundamente pessoal e universalmente comovente, capturando admiração, beleza e força emocional, tudo de uma só vez."
  ],
  "aboutArtistHeading": "Sobre o artista.",
  "aboutArtistParagraphs": [
    "Vincent van Gogh foi um pintor pós-impressionista holandês que criou uma vasta obra de grande intensidade emocional em pouco mais de uma década, e suas cores ousadas e pinceladas espiraladas ajudaram a abrir caminho para movimentos artísticos modernos, como o expressionismo. Nascido em 30 de março de 1853, em Zundert, na Holanda, ele vinha de uma família protestante e exerceu diversas profissões, incluindo a de negociante de arte e pregador, antes de se dedicar à pintura aos 27 anos.",
    "O que distingue van Gogh é seu estilo cru e pessoal, que capturava sentimentos íntimos por meio de cores vivas, pinceladas espessas e formas dramáticas. Ele produziu mais de 2.000 obras, incluindo cerca de 860 pinturas a óleo, muitas vezes em surtos intensos, apesar das lutas contínuas contra a doença mental e a pobreza. Suas primeiras obras, como “Os Comedores de Batata”, focavam nos camponeses rurais em tons escuros e terrosos, mas suas obras posteriores explodiram em matizes brilhantes depois que ele se mudou para a França.",
    "Como pintor, van Gogh criou algumas das imagens mais reconhecidas da história da arte, como “A Noite Estrelada”, “Os Girassóis”, “O Quarto” e “Campo de Trigo com Ciprestes”. Ele experimentou técnicas como pinceladas pesadas e pigmentos instáveis, o que conferiu textura e energia às suas telas, mas, às vezes, causou alterações de cor com o passar do tempo. Ele pintava autorretratos obsessivamente, usando-os para explorar seu próprio conflito interior, e se inspirava fortemente na natureza e em cenas do cotidiano.",
    "Van Gogh também enfrentou grandes dificuldades pessoais. Com o apoio de seu irmão Theo, ele morou na Holanda, depois em Arles e em Saint-Rémy, na França, onde cortou parte da orelha em 1888, durante um surto de depressão. Ele passou um tempo em um manicômio, mas continuou pintando prolificamente, criando mais de 150 obras lá; morreu em 1890, aos 37 anos, vítima de um tiro autoinfligido em Auvers-sur-Oise.",
    "Em resumo, Vincent van Gogh foi um gênio atormentado cuja obra, não reconhecida em vida, hoje influencia artistas em todo o mundo por seu poder emocional e inovação visual."
  ]
}
