import type { StarryNightCopy } from "./starryNight"

/** Spanish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const STARRY_NIGHT_ES: StarryNightCopy = {
  "title": "The Starry Night",
  "subtitle": "Junio de 1889, de Vincent van Gogh",
  "bannerTop": "Cuando hayas consultado la página que aparece a continuación, haz clic en este banner para conocer la tecnología exclusiva en la que se basa esta solución, así como las múltiples ventajas que ofrece a los comisarios de exposiciones, museos y galerías.",
  "bannerBottom": "Haz clic en este banner para obtener más información sobre la tecnología utilizada para crear esta página.",
  "imageAlt": "«La noche estrellada», de Vincent van Gogh",
  "aboutPaintingHeading": "Acerca del cuadro.",
  "aboutPaintingParagraphs": [
    "«La noche estrellada» es una de las obras más famosas de Vincent van Gogh y una imagen emblemática del arte posimpresionista. Pintada en 1889, mientras Van Gogh se encontraba ingresado en el manicomio de Saint-Rémy-de-Provence, muestra un cielo nocturno lleno de movimiento: corrientes azules que se arremolinan, estrellas resplandecientes, una brillante luna creciente y un pequeño pueblo que descansa tranquilamente a sus pies. La escena transmite a la vez una sensación de paz y de inquietud, como si todo el cielo estuviera en movimiento mientras el mundo que hay debajo permanece inmóvil.",
    "El contraste entre el cielo tormentoso y la tranquilidad del pueblo confiere al cuadro su intensa tensión emocional. El alto ciprés del primer plano se eleva como una llama oscura, uniendo la tierra con el cielo y contribuyendo a la dramática sensación de movimiento y emoción del cuadro. En lugar de presentar una simple vista del campo, Van Gogh transforma el paisaje en algo casi espiritual, donde la naturaleza parece cargada de energía y significado.",
    "Aunque a menudo se interpreta como una escena de soledad o inquietud interior, el cuadro es también una obra de profunda imaginación y observación. Van Gogh no pintó un cielo nocturno literal tal y como se veía; en cambio, lo reimaginó para convertirlo en una composición visionaria llena de ritmo, color e intensidad. El resultado es un cuadro que resulta a la vez profundamente personal y universalmente conmovedor, capaz de capturar el asombro, la belleza y la fuerza emocional, todo al mismo tiempo."
  ],
  "aboutArtistHeading": "Acerca del artista.",
  "aboutArtistParagraphs": [
    "Vincent van Gogh fue un pintor posimpresionista neerlandés que creó una amplia obra de gran intensidad emocional en poco más de una década, y sus colores vivos y sus pinceladas arremolinadas contribuyeron a allanar el camino para movimientos artísticos modernos como el expresionismo. Nacido el 30 de marzo de 1853 en Zundert, Países Bajos, procedía de una familia protestante y desempeñó diversos oficios, entre ellos el de marchante de arte y predicador, antes de dedicarse a la pintura a los 27 años.",
    "Lo que distingue a Van Gogh es su estilo crudo y personal, capaz de plasmar sentimientos íntimos a través de colores vivos, una pintura de impasto espeso y formas dramáticas. Creó más de 2.000 obras, entre ellas unas 860 pinturas al óleo, a menudo en intensas rachas creativas a pesar de sus continuas luchas contra la enfermedad mental y la pobreza. Sus primeras obras, como «Los comedores de patatas», se centraban en los campesinos rurales en tonos oscuros y terrosos, pero sus obras posteriores rebosaban de tonos vivos tras su traslado a Francia.",
    "Como pintor, Van Gogh creó algunas de las imágenes más reconocidas de la historia del arte, como «La noche estrellada», «Los girasoles», «El dormitorio» y «Campo de trigo con cipreses». Experimentó con técnicas como la pincelada gruesa y los pigmentos inestables, lo que dotaba a sus lienzos de textura y energía, aunque a veces provocaba cambios de color con el paso del tiempo. Pintaba autorretratos de forma obsesiva, utilizándolos para explorar su propia agitación interior, y se inspiraba en gran medida en la naturaleza y en escenas cotidianas.",
    "Van Gogh también tuvo que hacer frente a grandes dificultades personales. Con el apoyo de su hermano Theo, vivió en los Países Bajos y, posteriormente, en Arlés y Saint-Rémy, en Francia, donde se cortó parte de la oreja en 1888 durante una crisis nerviosa. Pasó un tiempo en un manicomio, pero siguió pintando de forma prolífica, creando allí más de 150 obras; murió en 1890, a los 37 años, a causa de una herida de bala autoinfligida en Auvers-sur-Oise.",
    "En resumen, Vincent van Gogh fue un genio atormentado cuya obra, que no fue reconocida en vida, influye hoy en día en artistas de todo el mundo por su fuerza emocional y su innovación visual."
  ]
}
