import type { StarryNightCopy } from "./starryNight"

/** Turkish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const STARRY_NIGHT_TR: StarryNightCopy = {
  "title": "The Starry Night",
  "subtitle": "Haziran 1889, Vincent van Gogh",
  "bannerTop": "Aşağıdaki sayfayı inceledikten sonra, lütfen bu başlığa tıklayarak bu çözümü mümkün kılan benzersiz teknolojiyi ve bunun sergi küratörlerine, müzelere ve galerilere sunduğu sayısız avantajı öğrenin.",
  "bannerBottom": "Bu sayfayı oluşturmak için kullanılan teknoloji hakkında daha fazla bilgi edinmek için bu başlığa tıklayın.",
  "imageAlt": "Vincent van Gogh’un “Yıldızlı Gece” adlı eseri",
  "aboutPaintingHeading": "Tablonun hakkında.",
  "aboutPaintingParagraphs": [
    "“Yıldızlı Gece”, Vincent van Gogh’un en ünlü eserlerinden biri ve post-empresyonist sanatın simgesel bir görüntüsüdür. Van Gogh'un Saint-Rémy-de-Provence'daki akıl hastanesinde kaldığı dönemde, 1889 yılında resmedilen bu eser, hareketle dolu bir gece gökyüzünü yansıtıyor: kıvrılan mavi akıntılar, parıldayan yıldızlar, parlak bir hilal ve aşağıda sessizce uzanan küçük bir köy. Bu sahne, sanki tüm gökyüzü hareket halindeyken altındaki dünya sabit kalmış gibi, hem huzurlu hem de huzursuz bir his uyandırır.",
    "Fırtınalı gökyüzü ile sakin kasaba arasındaki zıtlık, resme güçlü bir duygusal gerilim katmaktadır. Ön plandaki uzun selvi ağacı, karanlık bir alev gibi yükselerek yeryüzünü gökyüzüne bağlar ve resmin dramatik hareket ve duygu hissini pekiştirir. Van Gogh, kırsalın basit bir manzarasını sunmak yerine, manzarayı doğanın enerji ve anlamla yüklü olduğu, neredeyse ruhani bir şeye dönüştürür.",
    "Her ne kadar genellikle bir yalnızlık ya da içsel huzursuzluk sahnesi olarak yorumlansa da, bu tablo aynı zamanda derin bir hayal gücü ve gözlemin ürünü bir eserdir. Van Gogh, gece gökyüzünü tam olarak göründüğü haliyle resmetmemiştir; bunun yerine onu ritim, renk ve yoğunlukla dolu vizyoner bir kompozisyona dönüştürmüştür. Sonuçta ortaya, hem son derece kişisel hem de evrensel olarak dokunaklı hissettiren, hayranlık, güzellik ve duygusal gücü aynı anda yakalayan bir tablo çıkmıştır."
  ],
  "aboutArtistHeading": "Sanatçı hakkında.",
  "aboutArtistParagraphs": [
    "Vincent van Gogh, on yıldan biraz fazla bir sürede duygusal açıdan yoğun çok sayıda eser ortaya koyan Hollandalı bir Post-Empresyonist ressamdı; cesur renkleri ve girdaplı fırça darbeleri, Ekspresyonizm gibi modern sanat akımlarının önünü açmaya katkıda bulundu. 30 Mart 1853’te Hollanda’nın Zundert kentinde dünyaya gelen Van Gogh, Protestan bir aileden geliyordu ve 27 yaşında resme yönelmeden önce sanat tüccarlığı ve vaizlik gibi çeşitli mesleklerde çalıştı.",
    "Van Gogh’u diğerlerinden ayıran şey, canlı renkler, kalın impasto boya tekniği ve dramatik formlar aracılığıyla içsel duyguları yansıtan ham ve kişisel üslubudur. Ruhsal hastalık ve yoksullukla süregelen mücadelesine rağmen, genellikle yoğun ataklar halinde yaklaşık 860 yağlı boya tablosu da dahil olmak üzere 2.000’den fazla eser üretmiştir. “Patates Yiyenler” gibi erken dönem eserleri, koyu ve toprak tonlarında kırsal kesimdeki köylüleri konu alırken, Fransa’ya taşındıktan sonra ürettiği eserlerde parlak renkler ön plana çıktı.",
    "Bir ressam olarak van Gogh, “Yıldızlı Gece”, “Ayçiçekleri”, “Yatak Odası” ve “Selvi Ağaçlı Buğday Tarlası” gibi sanat tarihinin en tanınmış eserlerinden bazılarını yarattı. Kalın fırça darbeleri ve dengesiz pigmentler gibi tekniklerle denemeler yaptı; bu teknikler tuvallere doku ve enerji kattı, ancak zamanla renk değişikliklerine neden oldu. Kendi içsel çalkantılarını keşfetmek amacıyla takıntılı bir şekilde otoportreler çizdi ve eserlerinde doğadan ve gündelik sahnelerden yoğun bir şekilde ilham aldı.",
    "Van Gogh ayrıca büyük kişisel zorluklarla da karşı karşıya kaldı. Kardeşi Theo’nun desteğiyle önce Hollanda’da, ardından Fransa’nın Arles ve Saint-Rémy kentlerinde yaşadı; 1888’de yaşadığı bir sinir krizi sırasında kulağının bir kısmını kesti. Bir akıl hastanesinde bir süre kaldı ancak bu süre boyunca da üretken bir şekilde resim yapmaya devam etti ve orada 150'den fazla eser yarattı; 1890 yılında, 37 yaşında, Auvers-sur-Oise'da kendi kendine ateş ettiği bir silah yarası sonucu hayatını kaybetti.",
    "Kısacası, Vincent van Gogh, hayatı boyunca eserleri takdir görmemiş, ancak duygusal gücü ve görsel yenilikçiliğiyle günümüzde dünya çapında sanatçılara ilham veren, acı çeken bir dahiydi."
  ]
}
