import type { StarryNightCopy } from "./starryNight"

/** Italian copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const STARRY_NIGHT_IT: StarryNightCopy = {
  "title": "The Starry Night",
  "subtitle": "Giugno 1889, di Vincent van Gogh",
  "bannerTop": "Dopo aver consultato la pagina qui sotto, clicca su questo banner per scoprire l’esclusiva tecnologia alla base di questa soluzione e i numerosi vantaggi che offre ai curatori di mostre, ai musei e alle gallerie.",
  "bannerBottom": "Clicca su questo banner per saperne di più sulla tecnologia utilizzata per creare questa pagina.",
  "imageAlt": "\"La notte stellata\" di Vincent van Gogh",
  "aboutPaintingHeading": "Informazioni sul dipinto.",
  "aboutPaintingParagraphs": [
    "“La notte stellata” è una delle opere più celebri di Vincent van Gogh e un’immagine simbolo dell’arte post-impressionista. Dipinta nel 1889 mentre Van Gogh era ricoverato nel manicomio di Saint-Rémy-de-Provence, raffigura un cielo notturno animato dal movimento: vorticosi flussi blu, stelle luminose, una mezzaluna splendente e un piccolo villaggio che riposa tranquillamente ai suoi piedi. La scena trasmette una sensazione al tempo stesso pacifica e inquieta, come se l’intero cielo fosse in movimento mentre il mondo sottostante rimane immobile.",
    "Il contrasto tra il cielo turbolento e la calma della cittadina conferisce al dipinto una forte tensione emotiva. L'alto cipresso in primo piano si erge come una fiamma scura, collegando la terra al cielo e contribuendo al senso drammatico di movimento e di emozione del dipinto. Anziché presentare una semplice veduta di campagna, Van Gogh trasforma il paesaggio in qualcosa di quasi spirituale, dove la natura sembra carica di energia e significato.",
    "Sebbene venga spesso interpretato come una scena di solitudine o di inquietudine interiore, il dipinto è anche un’opera di profonda immaginazione e osservazione. Van Gogh non ha dipinto un cielo notturno letterale esattamente come appariva; lo ha invece reinterpretato in una composizione visionaria ricca di ritmo, colore e intensità. Il risultato è un dipinto che appare al tempo stesso profondamente personale e universalmente commovente, capace di catturare allo stesso tempo stupore, bellezza e forza emotiva."
  ],
  "aboutArtistHeading": "Informazioni sull'artista.",
  "aboutArtistParagraphs": [
    "Vincent van Gogh è stato un pittore post-impressionista olandese che, in poco più di un decennio, ha creato una vasta produzione di opere di grande intensità emotiva; i suoi colori audaci e le sue pennellate vorticose hanno contribuito a spianare la strada a movimenti artistici moderni come l’espressionismo. Nato il 30 marzo 1853 a Zundert, nei Paesi Bassi, proveniva da una famiglia protestante e svolse diversi lavori, tra cui quello di mercante d’arte e predicatore, prima di dedicarsi alla pittura all’età di 27 anni.",
    "Ciò che contraddistingue van Gogh è il suo stile grezzo e personale, capace di catturare i sentimenti più intimi attraverso colori vivaci, impasti di pittura spessi e forme drammatiche. Realizzò oltre 2.000 opere, tra cui circa 860 dipinti a olio, spesso in intensi periodi di produzione nonostante le continue difficoltà legate alla malattia mentale e alla povertà. Le sue prime opere, come *I mangiatori di patate*, erano incentrate sui contadini rurali e caratterizzate da toni scuri e terrosi, mentre i lavori successivi, realizzati dopo il suo trasferimento in Francia, esplodevano in tonalità vivaci.",
    "Come pittore, van Gogh ha creato alcune delle immagini più famose della storia dell’arte, come *La notte stellata*, *I girasoli*, *La camera da letto* e *Campo di grano con cipressi*. Ha sperimentato tecniche come la pennellata marcata e l’uso di pigmenti instabili, che hanno conferito alle sue tele consistenza ed energia, ma che talvolta hanno causato alterazioni cromatiche nel corso del tempo. Dipingeva autoritratti in modo ossessivo, utilizzandoli per esplorare il proprio tumulto interiore, e traeva grande ispirazione dalla natura e dalle scene di vita quotidiana.",
    "Van Gogh dovette affrontare anche grandi difficoltà personali. Sostenuto dal fratello Theo, visse nei Paesi Bassi, poi ad Arles e a Saint-Rémy in Francia, dove nel 1888, durante un crollo nervoso, si tagliò parte dell’orecchio. Trascorse un periodo in un manicomio, ma continuò a dipingere con grande prolificità, realizzando lì oltre 150 opere; morì nel 1890 all’età di 37 anni per una ferita da arma da fuoco autoinflitta ad Auvers-sur-Oise.",
    "In breve, Vincent van Gogh era un genio tormentato le cui opere, non apprezzate quando era in vita, influenzano oggi gli artisti di tutto il mondo grazie alla loro forza emotiva e alla loro innovazione visiva."
  ]
}
