import type { TheKissCopy } from "./theKiss"

/** French copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_FR: TheKissCopy = {
  "banner": "Découvrez comment fonctionne cette expérience",
  "eyebrowParts": [
    "Belvédère, Vienne",
    "Belvédère supérieur",
    "Vienne, 1900"
  ],
  "title": "Le baiser",
  "titleEm": "(Amoureux)",
  "subtitle": "Gustav Klimt · L'apogée de la période dorée, 1908/09",
  "imageAlt": "Gustav Klimt, « Le Baiser » (Les Amants), 1908/09, huile et feuille d'or sur toile, Belvédère, Vienne",
  "figcaption": "Deux amants sont agenouillés dans une prairie fleurie, enveloppés d'un seul et même manteau doré ; le titre de l'exposition était « Liebespaar », « Amants ».",
  "credit": "Belvédère, Vienne · N° d'inv. 912",
  "facts": [
    {
      "k": "Artiste",
      "v": "Gustav Klimt (1862-1918)"
    },
    {
      "k": "Date",
      "v": "1908, achevé en 1909"
    },
    {
      "k": "Moyen",
      "v": "Huile, feuille d'or et feuille d'argent sur toile"
    },
    {
      "k": "Taille",
      "v": "180 × 180 cm (carré)"
    },
    {
      "k": "N° d'inventaire",
      "v": "Belvédère 912"
    },
    {
      "k": "Diffusé pour la première fois",
      "v": "Kunstschau, Vienne, 1908"
    },
    {
      "k": "Acquis",
      "v": "Moderne Galerie, 1908 · 25 000 couronnes"
    },
    {
      "k": "À l'affiche",
      "v": "Belvédère supérieur, galerie Klimt"
    }
  ],
  "lede": "Agenouillés sur une petite prairie de fleurs sauvages, au bord de ce qui semble être une falaise, deux amants sont enveloppés dans un seul et même manteau doré. L’homme se penche vers elle ; la femme lève le visage pour être embrassée, les yeux fermés, la main serrée autour de la sienne. Derrière eux, il n’y a ni espace ni paysage — seulement un champ doré scintillant. *Le Baiser* est le tableau le plus célèbre du mouvement « Vienne 1900 », et l’une des très rares œuvres de l’histoire de l’art occidental qui parvient à être à la fois follement ornementale et véritablement tendre.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "La période dorée de Klimt",
      "paragraphs": [
        "En 1907, Gustav Klimt était le peintre le plus célèbre — et le plus controversé — de Vienne. Ses plafonds allégoriques destinés à l’université avaient été rejetés pour obscénité, il avait cofondé puis quitté la Sécession, et il vivait avec sa compagne Emilie Flöge au-dessus de son atelier-jardin situé en banlieue. Deux expériences l’ont poussé vers l’or. Tout d’abord, un voyage à Ravenne en 1903, où les mosaïques byzantines de San Vitale — Justinien et Théodora se détachant sur un mur d’or chatoyant — lui ont montré comment détacher les figures de l’espace et les transformer en icônes. Ensuite, le métier de son père : Ernst Klimt avait été graveur sur or. Entre 1903 et 1909, Klimt a créé une série de « tableaux dorés » — la Frise de Beethoven, Judith I, le Portrait d’Adele Bloch-Bauer I et enfin Le Baiser — en posant directement sur la toile de véritables feuilles d’or et d’argent."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Interpréter l'image",
      "paragraphs": [
        "La composition est plus rigoureuse qu’il n’y paraît à première vue. Les amants forment une seule et même forme dorée — une silhouette arrondie et phallique — qui se dresse sur un étroit rebord de fleurs et se détache sur un fond doré mat. Seules la peau visible (son cou, son visage, ses bras et ses pieds) et la prairie sont peintes selon les règles de l'illusionnisme ; le reste n'est qu'ornement. Klimt répartit cet ornement de manière très nette selon des critères de genre, une idée qu'il développait depuis la Frise de Beethoven."
      ],
      "motifs": [
        {
          "label": "Sa robe.",
          "text": "Des rectangles et des carrés noirs, blancs et argentés — austères, architecturaux, « masculins »."
        },
        {
          "label": "Sa robe.",
          "text": "Des ovales et des cercles concentriques dans des tons dorés, roses et violets — doux, organiques, « féminins »."
        },
        {
          "label": "La prairie.",
          "text": "De vraies fleurs sauvages — coquelicots, marguerites, lierre — : le seul élément naturaliste de l'image."
        },
        {
          "label": "Le bord de la falaise.",
          "text": "Ses orteils se recroquevillent au bord d'un petit précipice : l'extase en équilibre au bord du vide."
        },
        {
          "label": "Sa main.",
          "text": "Les doigts de sa main droite serrent les siens ; les tendons sont dessinés avec une grande précision anatomique."
        },
        {
          "label": "Le fond doré.",
          "text": "Ni le ciel, ni un mur : le champ intemporel d’un peintre d’icônes, inspiré de Ravenne."
        }
      ],
      "quote": "Tout art est érotique.",
      "quoteCite": "— Gustav Klimt, remarque adressée à Berta Zuckerkandl, vers 1905"
    },
    {
      "id": "kunstschau-1908",
      "heading": "La Kunstschau de 1908",
      "paragraphs": [
        "Klimt a dévoilé ce tableau lors de la Kunstschau de 1908 à Vienne, une exposition gigantesque qu’il avait organisée avec un groupe d’artistes dissidents sur un terrain vague où se dresse aujourd’hui le Konzerthaus. Il trônait au cœur de la « salle Klimt » sous le titre plus discret de *Liebespaar* — « Les Amants ». L’État autrichien, par l’intermédiaire de sa Moderne Galerie nouvellement fondée au Belvédère inférieur, acheta le tableau directement sur le mur pour 25 000 couronnes avant même qu’il ne soit achevé. C’était un prix stupéfiant pour une œuvre autrichienne contemporaine, qui fit la réputation du jeune musée du jour au lendemain."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Le Belvédère vu de près",
      "paragraphs": [
        "Depuis lors, le tableau est exposé au Belvédère — depuis 1953 au Belvédère Supérieur, où la collection « Vienne 1900 » est disposée autour de la Salle de Marbre, à l'étage supérieur. Elle partage sa salle d’exposition avec Judith I, plusieurs paysages de l’Attersee et le double portrait de Fritza Riedler ; La Mort et la Jeune Fille d’Egon Schiele se trouve juste à côté. En reproduction, le tableau a toujours l’aspect du papier ; en réalité, l’or est du métal véritable — on le voit capter la lumière et passer du bronze au jaune citron lorsqu’on se déplace latéralement. Essayez de vous tenir à environ deux ou trois mètres de recul pour que l’ensemble du carré apparaisse comme une forme unique, puis avancez pour observer la prairie et les mains."
      ],
      "visitLabel": "Le trouver.",
      "visitBody": "Belvédère supérieur (Oberes Belvedere), Prinz-Eugen-Straße 27, 1030 Vienne. Prenez le tramway D jusqu'à Schloss Belvedere. Entrez dans le palais, montez l'escalier d'apparat jusqu'à l'étage supérieur, traversez la Salle de marbre et tournez vers la galerie Klimt — « Le Baiser » se trouve sur le mur du fond. Ouvert tous les jours de 9 h à 18 h (le vendredi jusqu'à 21 h). Allez-y dès l'ouverture ou dans la dernière heure ; la salle est petite et se remplit rapidement."
    }
  ],
  "colophonLeft": "Galerie autrichienne du Belvédère · Prinz-Eugen-Straße 27, Vienne",
  "colophonRight": "N° d'inventaire 912 · Collection Klimt"
}
