import type { TheKissCopy } from "./theKiss"

/** German copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_DE: TheKissCopy = {
  "banner": "Erfahren Sie, wie dieses Erlebnis funktioniert",
  "eyebrowParts": [
    "Belvedere, Wien",
    "Oberes Belvedere",
    "Wien 1900"
  ],
  "title": "Der Kuss",
  "titleEm": "(Liebende)",
  "subtitle": "Gustav Klimt · Der Höhepunkt der Goldenen Periode, 1908/09",
  "imageAlt": "Gustav Klimt, „Der Kuss“ (Die Liebenden), 1908/09, Öl und Blattgold auf Leinwand, Belvedere, Wien",
  "figcaption": "Zwei Liebende knien auf einer blühenden Wiese, in einen einzigen goldenen Mantel gehüllt; der Titel der Ausstellung lautete „Liebespaar“.",
  "credit": "Belvedere, Wien · Inv.-Nr. 912",
  "facts": [
    {
      "k": "Künstler",
      "v": "Gustav Klimt (1862–1918)"
    },
    {
      "k": "Datum",
      "v": "1908, fertiggestellt 1909"
    },
    {
      "k": "Mittel",
      "v": "Öl, Gold- und Silberblatt auf Leinwand"
    },
    {
      "k": "Größe",
      "v": "180 × 180 cm (quadratisch)"
    },
    {
      "k": "Inv.-Nr.",
      "v": "Belvedere 912"
    },
    {
      "k": "Erstmals gezeigt",
      "v": "Kunstschau, Wien, 1908"
    },
    {
      "k": "Erworben",
      "v": "Moderne Galerie, 1908 · 25.000 Kronen"
    },
    {
      "k": "Zu sehen",
      "v": "Oberes Belvedere, Klimt-Galerie"
    }
  ],
  "lede": "Auf einer kleinen Wiese voller Wildblumen, am Rande einer Art Klippe, knien zwei Liebende, in einen einzigen goldenen Mantel gehüllt. Der Mann beugt sich vor; die Frau hebt ihr Gesicht, um geküsst zu werden, die Augen geschlossen, ihre Hand um seine geschlungen. Hinter ihnen gibt es weder Raum noch Landschaft – nur ein schimmerndes Feld aus Gold. „Der Kuss“ ist das berühmteste Gemälde der Wiener Secession von 1900 und eines der wenigen Bilder in der Geschichte der westlichen Kunst, das es schafft, zugleich wild ornamental und aufrichtig zärtlich zu sein.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "Klimts Goldene Periode",
      "paragraphs": [
        "Im Jahr 1907 war Gustav Klimt Wiens berühmtester – und umstrittenster – Maler. Seine allegorischen Deckenmalereien für die Universität waren als obszön abgelehnt worden, er hatte die Secession mitbegründet und war dann aus ihr ausgetreten, und er lebte mit seiner Lebensgefährtin Emilie Flöge über seinem Gartenatelier in einem Vorort. Zwei Erlebnisse brachten ihn auf die Spur des Goldes. Erstens eine Reise im Jahr 1903 nach Ravenna, wo ihm die byzantinischen Mosaike von San Vitale – Justinian und Theodora vor einer Wand aus schimmerndem Gold – einen Weg aufzeigten, Figuren aus dem Raum herauszulösen und sie in Ikonen zu verwandeln. Zweitens das Handwerk seines Vaters: Ernst Klimt war Goldgraveur gewesen. Zwischen 1903 und 1909 schuf Klimt eine Reihe von „Goldbildern“ – den Beethoven-Fries, Judith I., das Porträt von Adele Bloch-Bauer I. und schließlich „Der Kuss“ –, bei denen er echtes Blattgold und Blattsilber direkt auf die Leinwand auftrug."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Das Bild interpretieren",
      "paragraphs": [
        "Die Komposition ist strenger, als es auf den ersten Blick erscheint. Die Liebenden bilden eine einzige goldene Gestalt – eine abgerundete, phallische Silhouette –, die auf einem schmalen Blumenvorsprung steht und vor einem mattgoldenen Hintergrund schwebt. Nur die sichtbare Haut (sein Hals, ihr Gesicht, ihre Arme und Füße) und die Wiese sind illusionistisch gemalt; der Rest ist Ornament. Klimt unterteilt dieses Ornament scharf nach geschlechtsspezifischen Gesichtspunkten – eine Idee, an der er bereits seit dem Beethoven-Fries gearbeitet hatte."
      ],
      "motifs": [
        {
          "label": "Seine Robe.",
          "text": "Rechtecke und Quadrate in Schwarz, Weiß und Silber – streng, architektonisch, „männlich“."
        },
        {
          "label": "Ihr Morgenmantel.",
          "text": "Ovale und konzentrische Kreise in Gold, Rosa und Violett – sanft, organisch, „feminin“."
        },
        {
          "label": "Die Wiese.",
          "text": "Echte Wildblumen – Mohnblumen, Gänseblümchen, Efeu – der einzige naturalistische Abschnitt im Bild."
        },
        {
          "label": "Der Rand der Klippe.",
          "text": "Ihre Zehen krümmen sich über einem kleinen Abgrund: Ekstase, die am Rande der Leere balanciert."
        },
        {
          "label": "Ihre Hand.",
          "text": "Die Finger ihrer rechten Hand umschließen seine; die Sehnen sind mit anatomischer Genauigkeit gezeichnet."
        },
        {
          "label": "Der goldene Hintergrund.",
          "text": "Weder Himmel noch Wand – das zeitlose Feld eines Ikonenmalers, inspiriert von Ravenna."
        }
      ],
      "quote": "Jede Kunst ist erotisch.",
      "quoteCite": "— Gustav Klimt, Bemerkung gegenüber Berta Zuckerkandl, um 1905"
    },
    {
      "id": "kunstschau-1908",
      "heading": "Die Kunstschau von 1908",
      "paragraphs": [
        "Klimt stellte das Gemälde 1908 auf der Kunstschau in Wien vor, einer gigantischen Ausstellung, die er gemeinsam mit einer abtrünnigen Künstlergruppe auf einem unbebauten Grundstück organisiert hatte, auf dem heute das Konzerthaus steht. Es hing als Herzstück des „Klimt-Raums“ unter dem eher zurückhaltenden Titel „Liebespaar“. Der österreichische Staat erwarb das Bild über seine neu gegründete Moderne Galerie im Unteren Belvedere direkt von der Wand für 25.000 Kronen, noch bevor es überhaupt fertiggestellt war. Das war ein erstaunlicher Preis für ein zeitgenössisches österreichisches Werk und machte das junge Museum über Nacht berühmt."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Ein genauer Blick auf das Belvedere",
      "paragraphs": [
        "Das Gemälde hängt seitdem im Belvedere – seit 1953 im Oberen Belvedere, wo die Sammlung „Wien 1900“ rund um den Marmorsaal im Obergeschoss angeordnet ist. Es teilt sich den Ausstellungsraum mit „Judith I“, mehreren Attersee-Landschaften und dem Doppelporträt von Fritza Riedler; Egon Schieles „Tod und das Mädchen“ befindet sich direkt nebenan. In Reproduktionen sieht das Bild immer aus wie Papier; vor Ort ist das Gold echtes Metall – man sieht, wie es das Licht einfängt und sich von Bronze zu Zitronengelb wandelt, wenn man sich seitlich bewegt. Versuchen Sie, etwa zwei bis drei Meter Abstand zu halten, damit sich das gesamte Quadrat als eine einzige Form darstellt, und treten Sie dann näher heran, um die Wiese und die Hände zu betrachten."
      ],
      "visitLabel": "Es finden.",
      "visitBody": "Oberes Belvedere, Prinz-Eugen-Straße 27, 1030 Wien. Nehmen Sie die Straßenbahnlinie D bis zur Haltestelle Schloss Belvedere. Betreten Sie das Schloss, steigen Sie die Prunktreppe hinauf in das Obergeschoss, durchqueren Sie den Marmorsaal und biegen Sie in die Klimt-Galerie ein – „Der Kuss“ befindet sich an der Stirnwand. Täglich von 09:00 bis 18:00 Uhr geöffnet (freitags bis 21:00 Uhr). Gehen Sie gleich zu Beginn oder in der letzten Stunde hin; der Raum ist klein und schnell überfüllt."
    }
  ],
  "colophonLeft": "Österreichische Galerie Belvedere · Prinz-Eugen-Straße 27, Wien",
  "colophonRight": "Inv.-Nr. 912 · Klimt-Sammlung"
}
