import type { TheKissCopy } from "./theKiss"

/** Spanish copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_ES: TheKissCopy = {
  "banner": "Descubre cómo funciona esta experiencia",
  "eyebrowParts": [
    "Belvedere, Viena",
    "Belvedere Superior",
    "Viena, 1900"
  ],
  "title": "El beso",
  "titleEm": "(Amantes)",
  "subtitle": "Gustav Klimt · El apogeo del Período Dorado, 1908/09",
  "imageAlt": "Gustav Klimt, «El beso» (Los amantes), 1908/09, óleo y pan de oro sobre lienzo, Belvedere, Viena",
  "figcaption": "Dos amantes están arrodillados en un prado en flor, envueltos en un único manto dorado; el título de la exposición era «Liebespaar», «Amantes».",
  "credit": "Belvedere, Viena · N.º de inventario 912",
  "facts": [
    {
      "k": "Artista",
      "v": "Gustav Klimt (1862-1918)"
    },
    {
      "k": "Fecha",
      "v": "1908, finalizada en 1909"
    },
    {
      "k": "Medio",
      "v": "Óleo, pan de oro y pan de plata sobre lienzo"
    },
    {
      "k": "Tamaño",
      "v": "180 × 180 cm (cuadrado)"
    },
    {
      "k": "N.º de inventario",
      "v": "Belvedere 912"
    },
    {
      "k": "Estreno",
      "v": "Kunstschau, Viena, 1908"
    },
    {
      "k": "Adquirido",
      "v": "Moderne Galerie, 1908 · 25 000 coronas"
    },
    {
      "k": "En exposición",
      "v": "Belvedere Superior, galería de Klimt"
    }
  ],
  "lede": "Arrodillados en una pequeña pradera de flores silvestres, al borde de lo que parece un acantilado, dos amantes están envueltos en un único manto dorado. El hombre se inclina hacia ella; la mujer levanta el rostro para que la bese, con los ojos cerrados y la mano entrelazada con la de él. Detrás de ellos no hay espacio ni paisaje, solo un campo dorado y resplandeciente. «El beso» es el cuadro más famoso del movimiento «Viena 1900» y una de las muy pocas obras de la historia del arte occidental que consigue ser a la vez tremendamente ornamental y genuinamente tierna.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "El periodo dorado de Klimt",
      "paragraphs": [
        "En 1907, Gustav Klimt era el pintor más célebre —y más polémico— de Viena. Sus techos alegóricos para la Universidad habían sido rechazados por obscenos, había cofundado la Secesión y luego la había abandonado, y vivía con su compañera Emilie Flöge en el piso situado encima de su estudio con jardín en las afueras. Dos experiencias le llevaron a decantarse por el oro. En primer lugar, un viaje en 1903 a Rávena, donde los mosaicos bizantinos de San Vitale —Justiniano y Teodora frente a una pared de oro resplandeciente— le mostraron la forma de separar las figuras del espacio y convertirlas en iconos. En segundo lugar, el oficio de su padre: Ernst Klimt había sido grabador de oro. Entre 1903 y 1909, Klimt creó una serie de «cuadros dorados» —el Friso de Beethoven, Judith I, el Retrato de Adele Bloch-Bauer I y, por último, El beso— aplicando pan de oro y pan de plata auténticos directamente sobre el lienzo."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Interpretar la imagen",
      "paragraphs": [
        "La composición es más rigurosa de lo que parece a primera vista. Los amantes forman una única figura dorada —una silueta redondeada y fálica— que se alza sobre una estrecha cornisa de flores y flota sobre un fondo dorado mate. Solo la piel visible (el cuello de él, el rostro, los brazos y los pies de ella) y la pradera están pintadas de forma ilusionista; el resto es ornamentación. Klimt divide esa ornamentación de forma nítida según criterios de género, una idea en la que llevaba trabajando desde el Friso de Beethoven."
      ],
      "motifs": [
        {
          "label": "Su túnica.",
          "text": "Rectángulos y cuadrados en negro, blanco y plateado: austeros, arquitectónicos, «masculinos»."
        },
        {
          "label": "Su bata.",
          "text": "Óvalos y círculos concéntricos en tonos dorados, rosados y violetas: suaves, orgánicos, «femeninos»."
        },
        {
          "label": "El prado.",
          "text": "Flores silvestres de verdad —amapolas, margaritas, hiedra—: el único elemento naturalista de la imagen."
        },
        {
          "label": "El borde del acantilado.",
          "text": "Sus dedos de los pies se curvan al borde de un pequeño precipicio: el éxtasis, en equilibrio al borde del vacío."
        },
        {
          "label": "Su mano.",
          "text": "Los dedos de su mano derecha le agarran la de él; los tendones están dibujados con precisión anatómica."
        },
        {
          "label": "El fondo dorado.",
          "text": "Ni el cielo, ni la pared: el escenario atemporal de un pintor de iconos, tomado de Rávena."
        }
      ],
      "quote": "Todo el arte es erótico.",
      "quoteCite": "— Gustav Klimt, comentario dirigido a Berta Zuckerkandl, hacia 1905"
    },
    {
      "id": "kunstschau-1908",
      "heading": "La Kunstschau de 1908",
      "paragraphs": [
        "Klimt presentó el cuadro en la Kunstschau de 1908 en Viena, una gigantesca exposición que había organizado junto con un grupo de artistas disidentes en un terreno baldío donde hoy se encuentra el Konzerthaus. El cuadro se expuso como pieza central de la «Sala Klimt» bajo el título más discreto de *Liebespaar* («Amantes»). El Estado austriaco, a través de su recién fundada Moderne Galerie en el Belvedere Inferior, compró el cuadro directamente de la pared por 25 000 coronas antes incluso de que estuviera terminado. Fue un precio asombroso para una obra austriaca contemporánea y catapultó la reputación del joven museo de la noche a la mañana."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Una mirada detallada al Belvedere",
      "paragraphs": [
        "El cuadro ha estado expuesto en el Belvedere desde entonces —desde 1953 en el Belvedere Superior, donde la colección «Viena 1900» se distribuye alrededor de la Sala de Mármol, en la planta superior—. Comparte galería con «Judith I», varios paisajes del Attersee y el doble retrato de Fritza Riedler; «La muerte y la doncella», de Egon Schiele, se encuentra justo al lado. En las reproducciones, el cuadro siempre parece de papel; en persona, el oro es metal auténtico: se ve cómo refleja la luz y pasa del bronce al amarillo limón al moverse lateralmente. Intenta situarte a unos dos o tres metros de distancia para que todo el cuadrado se perciba como una sola forma, y luego acércate para observar la pradera y las manos."
      ],
      "visitLabel": "Encontrarlo.",
      "visitBody": "Belvedere Superior (Oberes Belvedere), Prinz-Eugen-Straße 27, 1030 Viena. Coge el tranvía D hasta Schloss Belvedere. Entra en el palacio, sube por la escalera de gala hasta la planta superior, cruza el Salón de Mármol y gira hacia la galería de Klimt: «El beso» se encuentra en la pared del fondo. Abierto todos los días de 09:00 a 18:00 (los viernes hasta las 21:00). Ve a primera hora o en la última hora; la sala es pequeña y se llena rápidamente."
    }
  ],
  "colophonLeft": "Galería Austriaca del Belvedere · Prinz-Eugen-Straße 27, Viena",
  "colophonRight": "N.º de inventario 912 · Colección Klimt"
}
