import type { TheKissCopy } from "./theKiss"

/** Italian copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_IT: TheKissCopy = {
  "banner": "Scopri come funziona questa esperienza",
  "eyebrowParts": [
    "Belvedere, Vienna",
    "Belvedere Superiore",
    "Vienna 1900"
  ],
  "title": "Il bacio",
  "titleEm": "(Innamorati)",
  "subtitle": "Gustav Klimt · L’apice del Periodo d’oro, 1908/09",
  "imageAlt": "Gustav Klimt, Il bacio (Gli amanti), 1908/09, olio e foglia d’oro su tela, Belvedere, Vienna",
  "figcaption": "Due amanti sono inginocchiati su un prato fiorito, avvolti in un unico mantello dorato; il titolo della mostra era *Liebespaar*, “Amanti”.",
  "credit": "Belvedere, Vienna · N. inv. 912",
  "facts": [
    {
      "k": "Artista",
      "v": "Gustav Klimt (1862–1918)"
    },
    {
      "k": "Data",
      "v": "1908, completato nel 1909"
    },
    {
      "k": "Medio",
      "v": "Olio, foglia d'oro e foglia d'argento su tela"
    },
    {
      "k": "Dimensioni",
      "v": "180 × 180 cm (quadrato)"
    },
    {
      "k": "N. inv.",
      "v": "Belvedere 912"
    },
    {
      "k": "Presentato per la prima volta",
      "v": "Kunstschau, Vienna, 1908"
    },
    {
      "k": "Acquisito",
      "v": "Moderne Galerie, 1908 · 25.000 corone"
    },
    {
      "k": "In mostra",
      "v": "Belvedere Superiore, Galleria Klimt"
    }
  ],
  "lede": "In ginocchio su un piccolo prato di fiori selvatici, ai margini di quella che sembra una scarpata, due amanti sono avvolti in un unico mantello dorato. L’uomo si china verso di lei; la donna solleva il viso per farsi baciare, con gli occhi chiusi e la mano stretta attorno a quella di lui. Dietro di loro non c’è spazio né paesaggio — solo un campo dorato e scintillante. *Il bacio* è il dipinto più famoso del movimento Vienna 1900 e uno dei pochissimi quadri nella storia dell’arte occidentale che riesca a essere al tempo stesso selvaggiamente ornamentale e genuinamente tenero.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "Il periodo d'oro di Klimt",
      "paragraphs": [
        "Nel 1907 Gustav Klimt era il pittore più celebre — e più controverso — di Vienna. I suoi soffitti allegorici per l’Università erano stati respinti perché ritenuti osceni, aveva cofondato e poi abbandonato la Secessione, e viveva con la sua compagna Emilie Flöge sopra il suo studio con giardino in periferia. Due esperienze lo spinsero verso l’oro. Innanzitutto, un viaggio nel 1903 a Ravenna, dove i mosaici bizantini di San Vitale — Giustiniano e Teodora su uno sfondo di oro scintillante — gli mostrarono come staccare le figure dallo spazio e trasformarle in icone. In secondo luogo, il mestiere di suo padre: Ernst Klimt era stato un incisore d’oro. Tra il 1903 e il 1909 Klimt realizzò una serie di «quadri d’oro» — il Fregio di Beethoven, Giuditta I, il Ritratto di Adele Bloch-Bauer I e infine Il bacio — applicando foglia d’oro e d’argento vera direttamente sulla tela."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Leggere l'immagine",
      "paragraphs": [
        "La composizione è più rigorosa di quanto sembri a prima vista. Gli amanti formano un’unica figura dorata — una sagoma arrotondata e fallica — che poggia su una stretta sporgenza di fiori e si staglia su uno sfondo dorato opaco. Solo la pelle visibile (il collo di lui, il viso, le braccia e i piedi di lei) e il prato sono dipinti in modo illusionistico; il resto è ornamento. Klimt divide nettamente tale ornamento secondo criteri di genere, un’idea che stava elaborando fin dai tempi del Fregio di Beethoven."
      ],
      "motifs": [
        {
          "label": "La sua tunica.",
          "text": "Rettangoli e quadrati in nero, bianco e argento — rigidi, architettonici, “maschili”."
        },
        {
          "label": "La sua vestaglia.",
          "text": "Oval e cerchi concentrici nei toni dell’oro, del rosa e del viola: morbidi, organici, “femminili”."
        },
        {
          "label": "Il prato.",
          "text": "Veri fiori selvatici — papaveri, margherite, edera — l’unico elemento naturalistico dell’immagine."
        },
        {
          "label": "Il bordo della scogliera.",
          "text": "Le sue dita dei piedi si arricciano sull’orlo di un piccolo precipizio: l’estasi in bilico sull’orlo del vuoto."
        },
        {
          "label": "La sua mano.",
          "text": "Le dita della sua mano destra stringono quelle di lui; i tendini sono disegnati con precisione anatomica."
        },
        {
          "label": "Lo sfondo dorato.",
          "text": "Né cielo, né muro: lo spazio senza tempo di un pittore di icone, preso in prestito da Ravenna."
        }
      ],
      "quote": "Tutta l'arte è erotica.",
      "quoteCite": "— Gustav Klimt, commento rivolto a Berta Zuckerkandl, 1905 circa"
    },
    {
      "id": "kunstschau-1908",
      "heading": "La Kunstschau del 1908",
      "paragraphs": [
        "Klimt presentò il dipinto alla Kunstschau del 1908 a Vienna, una gigantesca mostra che aveva organizzato insieme a un gruppo di artisti dissidenti su un terreno incolto dove oggi sorge il Konzerthaus. L’opera era esposta come pezzo forte della “Sala Klimt” con il titolo più discreto di *Liebespaar* — “Amanti”. Lo Stato austriaco, attraverso la sua Moderne Galerie appena fondata nel Belvedere Inferiore, acquistò il quadro direttamente dalla parete per 25.000 corone prima ancora che fosse completato. Si trattava di un prezzo sbalorditivo per un’opera austriaca contemporanea, che rese famoso il giovane museo da un giorno all’altro."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Uno sguardo ravvicinato al Belvedere",
      "paragraphs": [
        "Da allora il dipinto è esposto al Belvedere — dal 1953 nel Belvedere Superiore, dove la collezione “Vienna 1900” è disposta attorno alla Sala di Marmo al piano superiore. Condivide la sala espositiva con «Giuditta I», diversi paesaggi dell’Attersee e il doppio ritratto di Fritza Riedler; «La morte e la fanciulla» di Egon Schiele si trova proprio accanto. Nelle riproduzioni il quadro sembra sempre di carta; dal vivo l’oro è vero metallo — lo si vede riflettere la luce e passare dal bronzo al giallo limone mentre ci si sposta lateralmente. Provate a posizionarvi a circa due o tre metri di distanza in modo che l’intero quadrato appaia come un’unica forma, poi avvicinatevi per osservare il prato e le mani."
      ],
      "visitLabel": "Trovarlo.",
      "visitBody": "Belvedere Superiore (Oberes Belvedere), Prinz-Eugen-Straße 27, 1030 Vienna. Prendere il tram D fino a Schloss Belvedere. Entrare nel palazzo, salire la scalinata d’onore fino al piano superiore, attraversare la Sala di Marmo e svoltare nella galleria dedicata a Klimt: “Il bacio” si trova sulla parete in fondo. Aperto tutti i giorni dalle 09:00 alle 18:00 (il venerdì fino alle 21:00). Andateci di prima mattina o nell’ultima ora di apertura; la sala è piccola e si riempie in fretta."
    }
  ],
  "colophonLeft": "Galleria austriaca del Belvedere · Prinz-Eugen-Straße 27, Vienna",
  "colophonRight": "N. inv. 912 · Collezione Klimt"
}
