import type { TheKissCopy } from "./theKiss"

/** Portuguese copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_PT: TheKissCopy = {
  "banner": "Saiba como funciona essa experiência",
  "eyebrowParts": [
    "Belvedere, Viena",
    "Belvedere Superior",
    "Viena, 1900"
  ],
  "title": "O Beijo",
  "titleEm": "(Amantes)",
  "subtitle": "Gustav Klimt · O apogeu do Período Dourado, 1908/09",
  "imageAlt": "Gustav Klimt, O Beijo (Os Amantes), 1908/09, óleo e folha de ouro sobre tela, Belvedere, Viena",
  "figcaption": "Dois amantes estão ajoelhados em um prado florido, envoltos em um único manto dourado; o título da exposição era *Liebespaar*, “Amantes”.",
  "credit": "Belvedere, Viena · N.º de inventário 912",
  "facts": [
    {
      "k": "Artista",
      "v": "Gustav Klimt (1862–1918)"
    },
    {
      "k": "Data",
      "v": "1908, concluído em 1909"
    },
    {
      "k": "Médio",
      "v": "Óleo, folha de ouro e prata sobre tela"
    },
    {
      "k": "Tamanho",
      "v": "180 × 180 cm (quadrado)"
    },
    {
      "k": "N.º de inventário",
      "v": "Belvedere 912"
    },
    {
      "k": "Exibido pela primeira vez",
      "v": "Kunstschau, Viena, 1908"
    },
    {
      "k": "Adquirido",
      "v": "Moderne Galerie, 1908 · 25.000 coroas"
    },
    {
      "k": "Em exibição",
      "v": "Belvedere Superior, Galeria Klimt"
    }
  ],
  "lede": "Ajoelhados em um pequeno prado de flores silvestres, à beira do que parece ser um penhasco, dois amantes estão envoltos em um único manto dourado. O homem se inclina; a mulher ergue o rosto para ser beijada, com os olhos fechados e a mão entrelaçada na dele. Atrás deles não há espaço nem paisagem — apenas um campo dourado cintilante. “O Beijo” é a pintura mais famosa do movimento de Viena de 1900 e uma das pouquíssimas obras na história da arte ocidental que consegue ser ao mesmo tempo extremamente ornamental e genuinamente terna.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "O Período Dourado de Klimt",
      "paragraphs": [
        "Em 1907, Gustav Klimt era o pintor mais célebre — e mais contestado — de Viena. Seus tetos alegóricos para a Universidade haviam sido rejeitados por serem considerados obscenos; ele havia cofundado a Secessão, da qual depois se afastou; e morava com sua companheira, Emilie Flöge, no andar de cima de seu ateliê com jardim, localizado nos subúrbios. Duas experiências o levaram a adotar o ouro. Primeiro, uma viagem em 1903 a Ravena, onde os mosaicos bizantinos de San Vitale — Justiniano e Teodora contra uma parede de ouro cintilante — lhe mostraram uma maneira de destacar figuras do espaço e transformá-las em ícones. Em segundo lugar, o ofício de seu pai: Ernst Klimt havia sido gravador de ouro. Entre 1903 e 1909, Klimt criou uma série de “quadros dourados” — o Friso de Beethoven, Judite I, o Retrato de Adele Bloch-Bauer I e, finalmente, O Beijo — aplicando folhas de ouro e prata verdadeiras diretamente sobre a tela."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Interpretando a imagem",
      "paragraphs": [
        "A composição é mais rigorosa do que parece à primeira vista. Os amantes formam uma única forma dourada — uma silhueta arredondada e fálica — que se ergue sobre uma estreita saliência de flores e flutua contra um fundo dourado fosco. Apenas a pele visível (o pescoço dele, o rosto, os braços e os pés dela) e o prado são pintados de forma ilusionista; o restante é ornamentação. Klimt divide essa ornamentação nitidamente de acordo com as diferenças de gênero, uma ideia que ele vinha desenvolvendo desde o Friso de Beethoven."
      ],
      "motifs": [
        {
          "label": "A túnica dele.",
          "text": "Retângulos e quadrados em preto, branco e prata — rígidos, arquitetônicos, “masculinos”."
        },
        {
          "label": "O roupão dela.",
          "text": "Óvalos e círculos concêntricos em dourado, rosa e violeta — suaves, orgânicos, “femininos”."
        },
        {
          "label": "O prado.",
          "text": "Flores silvestres de verdade — papoulas, margaridas, hera — a única parte naturalista da imagem."
        },
        {
          "label": "A beira do penhasco.",
          "text": "Seus dedos dos pés se curvam à beira de um pequeno precipício: o êxtase à beira do vazio."
        },
        {
          "label": "A mão dela.",
          "text": "Os dedos da mão direita dela seguram os dele; os tendões são desenhados com rigor anatômico."
        },
        {
          "label": "O fundo dourado.",
          "text": "Nem o céu, nem a parede — o campo atemporal de um pintor de ícones, inspirado em Ravena."
        }
      ],
      "quote": "Toda arte é erótica.",
      "quoteCite": "— Gustav Klimt, comentário dirigido a Berta Zuckerkandl, por volta de 1905"
    },
    {
      "id": "kunstschau-1908",
      "heading": "A Kunstschau de 1908",
      "paragraphs": [
        "Klimt apresentou a pintura na Kunstschau de 1908, em Viena, uma exposição gigantesca que ele havia organizado com um grupo dissidente de artistas em um terreno baldio onde hoje fica a Konzerthaus. A obra foi exibida como peça central da “Sala Klimt”, sob o título mais discreto de *Liebespaar* — “Amantes”. O Estado austríaco, por meio de sua recém-fundada Moderne Galerie no Belvedere Inferior, comprou a obra diretamente da parede por 25.000 coroas antes mesmo de ela estar concluída. Foi um preço surpreendente para uma obra austríaca contemporânea e consolidou a reputação do jovem museu da noite para o dia."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Um olhar mais atento ao Belvedere",
      "paragraphs": [
        "A pintura está exposta no Belvedere desde então — desde 1953 no Belvedere Superior, onde a coleção “Viena 1900” está disposta ao redor do Salão de Mármore, no andar superior. Ela divide a galeria com “Judith I”, várias paisagens de Attersee e o retrato duplo de Fritza Riedler; “A Morte e a Donzela”, de Egon Schiele, fica na sala ao lado. Nas reproduções, a pintura sempre parece papel; ao vivo, o ouro é metal de verdade — você vê ele refletir a luz e mudar de bronze para amarelo-limão conforme se move para os lados. Tente ficar a cerca de dois a três metros de distância para que o quadrado inteiro pareça uma única forma; depois, aproxime-se para observar o prado e as mãos."
      ],
      "visitLabel": "Encontrando isso.",
      "visitBody": "Belvedere Superior (Oberes Belvedere), Prinz-Eugen-Straße 27, 1030 Viena. Pegue o bonde D até Schloss Belvedere. Entre no palácio, suba a escadaria principal até o andar superior, atravesse o Salão de Mármore e entre na galeria de Klimt — “O Beijo” fica na parede do fundo. Aberto diariamente das 09h às 18h (às sextas-feiras até às 21h). Vá logo cedo ou na última hora; a sala é pequena e fica lotada rapidamente."
    }
  ],
  "colophonLeft": "Galeria Austríaca Belvedere · Prinz-Eugen-Straße 27, Viena",
  "colophonRight": "N.º de inventário 912 · Coleção Klimt"
}
