import type { TheKissCopy } from "./theKiss"

/** Turkish copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const THE_KISS_TR: TheKissCopy = {
  "banner": "Bu deneyimin nasıl işlediğini öğrenin",
  "eyebrowParts": [
    "Belvedere, Viyana",
    "Yukarı Belvedere",
    "Viyana 1900"
  ],
  "title": "Öpücük",
  "titleEm": "(Aşıklar)",
  "subtitle": "Gustav Klimt · Altın Dönem’in doruk noktası, 1908/09",
  "imageAlt": "Gustav Klimt, Öpücük (Aşıklar), 1908/09, tuval üzerine yağlı boya ve altın varak, Belvedere, Viyana",
  "figcaption": "Çiçeklerle bezeli bir çayırda, tek bir altın pelerine sarılmış iki sevgili diz çökmüş; serginin adı Liebespaar, yani “Sevgililer” idi.",
  "credit": "Belvedere, Viyana · Env. no. 912",
  "facts": [
    {
      "k": "Sanatçı",
      "v": "Gustav Klimt (1862–1918)"
    },
    {
      "k": "Tarih",
      "v": "1908, 1909'da tamamlandı"
    },
    {
      "k": "Orta",
      "v": "Tuval üzerine yağlı boya, altın ve gümüş varak"
    },
    {
      "k": "Boyut",
      "v": "180 × 180 cm (kare)"
    },
    {
      "k": "Envanter No.",
      "v": "Belvedere 912"
    },
    {
      "k": "İlk kez gösterildi",
      "v": "Kunstschau, Viyana, 1908"
    },
    {
      "k": "Satın alındı",
      "v": "Moderne Galerie, 1908 · 25.000 kron"
    },
    {
      "k": "Sergileniyor",
      "v": "Yukarı Belvedere, Klimt Galerisi"
    }
  ],
  "lede": "Bir uçurum gibi görünen yerin kenarında, yabani çiçeklerle kaplı küçük bir çayırda diz çökmüş iki sevgili, tek bir altın pelerinle sarılmış durumda. Adam öne doğru eğiliyor; kadın öpülmek için yüzünü yukarı doğru kaldırıyor, gözleri kapalı, eli adamın elini sıkıca kavrıyor. Arkalarında ne bir boşluk ne de bir manzara var — sadece parıldayan altın rengi bir alan. “Öpücük”, Viyana 1900 akımının en ünlü tablosu ve Batı sanat tarihinde hem son derece süslü hem de içten bir şefkat sergileyen çok az sayıdaki resimden biridir.",
  "sections": [
    {
      "id": "golden-period",
      "heading": "Klimt'in Altın Dönemi",
      "paragraphs": [
        "1907 yılına gelindiğinde Gustav Klimt, Viyana’nın en ünlü — ve en tartışmalı — ressamı olmuştu. Üniversite için tasarladığı alegorik tavan resimleri müstehcen olduğu gerekçesiyle reddedilmişti; Secession’u kurucularından biri olarak kurmuş, ancak daha sonra buradan ayrılmıştı; ve banliyödeki bahçeli atölyesinin üst katında hayat arkadaşı Emilie Flöge ile birlikte yaşıyordu. Onu altın rengine yönlendiren iki deneyim vardı. Birincisi, 1903’te Ravenna’ya yaptığı bir geziydi; burada San Vitale’deki Bizans mozaiklerinde — parıldayan altın bir duvarın önünde duran Justinianus ve Theodora — figürleri mekândan koparıp ikonlara dönüştürmenin yolunu keşfetti. İkincisi ise babasının mesleğiydi: Ernst Klimt bir altın oymacısıydı. 1903 ile 1909 yılları arasında Klimt, gerçek altın ve gümüş varakları doğrudan tuval üzerine yerleştirerek bir dizi “altın resim” yarattı: Beethoven Frizi, Judith I, Adele Bloch-Bauer’in Portresi I ve son olarak Öpücük."
      ]
    },
    {
      "id": "reading-picture",
      "heading": "Resmi okumak",
      "paragraphs": [
        "Kompozisyon, ilk bakışta göründüğünden daha katıdır. Aşıklar, çiçeklerden oluşan dar bir çıkıntının üzerinde duran ve mat altın bir arka planın önünde süzülen tek bir altın şekil — yuvarlak, fallik bir siluet — oluştururlar. Sadece görünen cilt kısımları (adamın boynu, kadının yüzü, kolları ve ayakları) ile çayır illüzyonist bir şekilde resmedilmiştir; geri kalan kısım ise süslemedir. Klimt, bu süslemeyi cinsiyet ayrımına göre keskin bir şekilde bölmektedir; bu, Beethoven Frizi’nden beri üzerinde çalıştığı bir fikirdir."
      ],
      "motifs": [
        {
          "label": "Cüppesi.",
          "text": "Siyah, beyaz ve gümüş renkli dikdörtgenler ve kareler — sert, mimari, “erkeksi”."
        },
        {
          "label": "Cüppesi.",
          "text": "Altın, gül rengi ve menekşe rengindeki oval şekiller ve eşmerkezli daireler — yumuşak, organik, “kadınsı”."
        },
        {
          "label": "Çayır.",
          "text": "Gerçek kır çiçekleri — gelincikler, papatyalar, sarmaşık — resimdeki tek doğal görünümlü bölüm."
        },
        {
          "label": "Uçurumun kenarı.",
          "text": "Ayak parmakları küçük bir uçurumun kenarında kıvrılıyor: boşluğun eşiğinde dengede duran coşku."
        },
        {
          "label": "Eli.",
          "text": "Sağ elinin parmakları onun elini sıkıca kavrıyor; tendonlar anatomik bir titizlikle çizilmiş."
        },
        {
          "label": "Altın zemin.",
          "text": "Ne gökyüzü, ne de duvar — bir ikon ressamının zamansız çalışma alanı, Ravenna’dan esinlenerek."
        }
      ],
      "quote": "Tüm sanat erotik.",
      "quoteCite": "— Gustav Klimt, Berta Zuckerkandl’a yaptığı bir yorum, 1905 civarı"
    },
    {
      "id": "kunstschau-1908",
      "heading": "1908 Kunstschau Sergisi",
      "paragraphs": [
        "Klimt, bu tabloyu 1908 yılında Viyana’da düzenlenen Kunstschau’da sergiledi; bu, şu anda Konzerthaus’un bulunduğu boş arazide, ayrılıkçı bir sanatçı grubuyla birlikte düzenlediği devasa bir sergiydi. Tablo, “Klimt Odası”nın en göze çarpan parçası olarak, daha mütevazı bir başlık olan Liebespaar — “Aşıklar” — altında sergilenmişti. Avusturya devleti, Aşağı Belvedere’de yeni kurulan Moderne Galerie aracılığıyla, tablo henüz tamamlanmadan duvardan indirilip 25.000 kron karşılığında satın aldı. Bu, çağdaş bir Avusturya eseri için şaşırtıcı bir fiyattı ve genç müzenin ününü bir gecede artırdı."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Belvedere’ye yakından bir bakış",
      "paragraphs": [
        "Tablo o günden beri Belvedere’de sergilenmektedir — 1953’ten beri Üst Belvedere’de; burada Viyana 1900 koleksiyonu, üst kattaki Mermer Salon’un çevresinde düzenlenmiştir. Tablo, galerisini Judith I, birkaç Attersee manzarası ve Fritza Riedler’in ikili portresiyle paylaşıyor; Egon Schiele’nin Ölüm ve Bakire adlı eseri ise hemen yanında yer alıyor. Reprodüksiyonlarda resim her zaman kağıt gibi görünür; ancak gerçekte altın gerçek metaldir — yanlara doğru hareket ettiğinizde ışığı yakalayıp bronz renginden limon sarısına dönüştüğünü görebilirsiniz. Yaklaşık iki ila üç metre geride durup tüm kareyi tek bir şekil olarak algılamaya çalışın, ardından öne doğru adım atarak çayır ve ellere bakın."
      ],
      "visitLabel": "Bunu bulmak.",
      "visitBody": "Yukarı Belvedere (Oberes Belvedere), Prinz-Eugen-Straße 27, 1030 Viyana. D numaralı tramvayla Schloss Belvedere'ye gidin. Saraya girin, devlet merdivenlerinden üst kata çıkın, Mermer Salon'u geçin ve Klimt galerisine dönün — \"Öpücük\" tablosu en son duvarda yer alıyor. Her gün 09:00–18:00 arası açık (Cuma günleri 21:00'a kadar). Sabahın ilk saatlerinde ya da kapanış saatine yakın bir zamanda gidin; salon küçük ve çabuk doluyor."
    }
  ],
  "colophonLeft": "Avusturya Belvedere Galerisi · Prinz-Eugen-Straße 27, Viyana",
  "colophonRight": "Envanter No. 912 · Klimt Koleksiyonu"
}
