import type { TwoFridasCopy } from "./twoFridas"

/** Spanish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_ES: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939, de Frida Kahlo",
  "bannerTop": "Cuando hayas consultado la página que aparece a continuación, haz clic en este banner para conocer la tecnología exclusiva en la que se basa esta solución, así como las múltiples ventajas que ofrece a los comisarios de exposiciones, museos y galerías.",
  "bannerBottom": "Haz clic en este banner para obtener más información sobre la tecnología utilizada para crear esta página.",
  "imageAlt": "«Las dos Fridas», de Frida Kahlo",
  "aboutPaintingHeading": "Acerca del cuadro.",
  "aboutPaintingParagraphs": [
    "«Las dos Fridas» es uno de los cuadros más grandes y emblemáticos de Frida Kahlo, terminado en 1939 en un momento de intensa agitación personal y emocional. La obra muestra dos versiones de la artista sentadas una al lado de la otra en un banco, cogidas de la mano, con sus cuerpos unidos por una única vena al descubierto que conecta sus corazones.",
    "Las figuras son un reflejo una de la otra, aunque difieren en la vestimenta y la expresión: una lleva un traje tradicional tehuana, propio de la cultura indígena mexicana, mientras que la otra luce un vestido blanco de estilo europeo, lo que crea un contraste visual entre la identidad mexicana y la herencia colonial.",
    "El cuadro se interpreta generalmente como un reflejo de la dualidad interior de Frida Kahlo: atrapada entre sus raíces mexicanas y su ascendencia europea, entre la fuerza y la vulnerabilidad, entre la imagen que mostraba al mundo y la persona que sufría en privado.",
    "La anatomía al descubierto, los corazones visibles y la sangre que mancha el vestido blanco aluden directamente al dolor, al desamor y a la fragilidad del cuerpo humano, temas que se repiten a lo largo de toda su obra.",
    "«Las dos Fridas» coincide además con el periodo de su divorcio del artista Diego Rivera, lo que intensificó su resonancia emocional como representación de la ruptura sentimental, la introspección y la lucha por mantenerse entera tras una gran pérdida."
  ],
  "aboutArtistHeading": "Acerca del artista.",
  "aboutArtistParagraphs": [
    "La obra «Las dos Fridas» fue pintada por Frida Kahlo (1907-1954), una artista mexicana cuya obra es reconocida por su cruda honestidad emocional, su simbolismo surrealista y su profunda reflexión sobre cuestiones relacionadas con la identidad, el género y el cuerpo.",
    "Nacida en Coyoacán, en la Ciudad de México, Kahlo desarrolló un estilo propio que fusionaba elementos del arte popular mexicano, el simbolismo indígena y el modernismo europeo, y solía recurrir a los autorretratos para explorar su sufrimiento físico, su agitación emocional y sus convicciones políticas.",
    "Un grave accidente de autobús que sufrió en su juventud le provocó un dolor crónico que la acompañará toda la vida y la obligó a someterse a numerosas operaciones quirúrgicas, experiencias que marcaron profundamente su arte y le proporcionaron una perspectiva única sobre el cuerpo, tanto como lugar de sufrimiento como lienzo para la expresión.",
    "La vida y la obra de Kahlo estuvieron estrechamente vinculadas al panorama cultural y político mexicano de principios del siglo XX. Estaba casada con el muralista Diego Rivera, cuya influencia y turbulencias marcan gran parte de su imaginería; sin embargo, desarrolló con firmeza una voz que era inconfundiblemente propia.",
    "En *Las dos Fridas*, su fusión de narrativa personal y lenguaje simbólico convierte el lienzo en una autobiografía visual, en la que las dos figuras no son solo dos versiones de Frida, sino también una reflexión sobre la naturaleza fragmentada de la identidad, el precio del amor perdido y la resiliencia necesaria para sobrevivir.",
    "A través de este cuadro y de muchos otros, Kahlo se convirtió en una figura clave del arte moderno, especialmente para las generaciones posteriores de artistas feministas y latinoamericanas, que la consideran tanto un icono cultural como una narradora profundamente humana."
  ]
}
