import type { TwoFridasCopy } from "./twoFridas"

/** German copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_DE: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939 von Frida Kahlo",
  "bannerTop": "Wenn Sie sich die untenstehende Seite angesehen haben, klicken Sie bitte auf dieses Banner, um mehr über die einzigartige Technologie zu erfahren, die dieser Lösung zugrunde liegt, sowie über die zahlreichen Vorteile, die sie für Ausstellungskuratoren, Museen und Galerien bietet.",
  "bannerBottom": "Klicken Sie auf dieses Banner, um mehr über die Technologie zu erfahren, mit der diese Seite erstellt wurde.",
  "imageAlt": "„Die beiden Fridas“ von Frida Kahlo",
  "aboutPaintingHeading": "Über das Gemälde.",
  "aboutPaintingParagraphs": [
    "„Die beiden Fridas“ ist eines der größten und bekanntesten Gemälde von Frida Kahlo, das 1939 in einer Zeit intensiver persönlicher und emotionaler Umbrüche entstand. Das Werk zeigt zwei Darstellungen der Künstlerin, die nebeneinander auf einer Bank sitzen und sich an den Händen halten; ihre Körper sind durch eine einzige sichtbare Ader verbunden, die ihre Herzen miteinander verbindet.",
    "Die Figuren spiegeln sich gegenseitig wider, unterscheiden sich jedoch in ihrer Kleidung und ihrem Gesichtsausdruck: Die eine trägt eine traditionelle Tehuana-Tracht, die mit der indigenen Kultur Mexikos in Verbindung gebracht wird, während die andere ein weißes Kleid im europäischen Stil trägt, wodurch ein visueller Kontrast zwischen mexikanischer Identität und kolonialem Erbe entsteht.",
    "Das Gemälde wird weithin als Spiegelbild von Frida Kahlos innerer Dualität interpretiert – hin- und hergerissen zwischen ihren mexikanischen Wurzeln und ihrer europäischen Abstammung, zwischen Stärke und Verletzlichkeit, zwischen dem Selbst, das sie der Welt präsentierte, und dem Selbst, das im Privaten litt.",
    "Die freiliegende Anatomie, die sichtbaren Herzen und das Blut, das das weiße Kleid befleckt, verweisen unmittelbar auf Schmerz, Herzschmerz und die Zerbrechlichkeit des menschlichen Körpers – Themen, die in ihrem gesamten künstlerischen Schaffen immer wieder auftauchen.",
    "„Die zwei Fridas“ fällt zudem mit der Zeit ihrer Scheidung vom Künstler Diego Rivera zusammen, was die emotionale Wirkung des Werks als Darstellung eines emotionalen Bruchs, der Selbstreflexion und des Kampfes, nach einem schweren Verlust die Fassung zu bewahren, noch verstärkte."
  ],
  "aboutArtistHeading": "Über den Künstler.",
  "aboutArtistParagraphs": [
    "Das Gemälde „Die beiden Fridas“ stammt von Frida Kahlo (1907–1954), einer mexikanischen Künstlerin, deren Werk für seine unverfälschte emotionale Ehrlichkeit, seine surreale Symbolik und seine intensive Auseinandersetzung mit Fragen der Identität, des Geschlechts und des Körpers bekannt ist.",
    "Kahlo, die in Coyoacán, Mexiko-Stadt, geboren wurde, entwickelte einen unverwechselbaren Stil, der Elemente der mexikanischen Volkskunst, indigene Symbolik und europäische Moderne miteinander verband. Oft nutzte sie Selbstporträts, um ihre körperlichen Leiden, ihre seelischen Turbulenzen und ihre politischen Überzeugungen zu thematisieren.",
    "Ein schwerer Busunfall in ihrer Jugend hinterließ bei ihr lebenslange chronische Schmerzen und erforderte zahlreiche Operationen – Erfahrungen, die ihre Kunst tiefgreifend geprägt und ihr eine einzigartige Perspektive auf den Körper vermittelt haben, der für sie sowohl Ort des Leidens als auch Leinwand für den Ausdruck ist.",
    "Kahlos Leben und Werk waren eng mit der kulturellen und politischen Landschaft Mexikos zu Beginn des 20. Jahrhunderts verbunden. Sie war mit dem Wandmaler Diego Rivera verheiratet, dessen Einfluss und dessen turbulentes Leben einen Großteil ihrer Bildsprache prägten; dennoch entwickelte sie beharrlich eine unverkennbar eigene künstlerische Stimme.",
    "In „The Two Fridas“ verwandelt ihre Verschmelzung von persönlicher Erzählung und symbolischer Sprache die Leinwand in eine visuelle Autobiografie, in der die beiden Figuren nicht nur zwei Versionen von Frida sind, sondern auch ein Statement über die Zerrissenheit der Identität, den Preis verlorener Liebe und die zum Überleben notwendige Widerstandsfähigkeit.",
    "Durch dieses Gemälde und viele andere wurde Kahlo zu einer zentralen Figur der modernen Kunst, insbesondere für spätere Generationen feministischer und lateinamerikanischer Künstlerinnen, die sie sowohl als kulturelle Ikone als auch als zutiefst menschliche Geschichtenerzählerin betrachten."
  ]
}
