import type { TwoFridasCopy } from "./twoFridas"

/** Portuguese copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_PT: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939, de Frida Kahlo",
  "bannerTop": "Depois de explorar a página abaixo, clique neste banner para conhecer a tecnologia exclusiva que está por trás dessa solução e os diversos benefícios que ela oferece a curadores de exposições, museus e galerias.",
  "bannerBottom": "Clique neste banner para saber mais sobre a tecnologia utilizada na criação desta página.",
  "imageAlt": "“As Duas Fridas”, de Frida Kahlo",
  "aboutPaintingHeading": "Sobre a pintura.",
  "aboutPaintingParagraphs": [
    "“As Duas Fridas” é uma das pinturas maiores e mais icônicas de Frida Kahlo, concluída em 1939, em um momento de intensa turbulência pessoal e emocional. A obra mostra duas versões da artista sentadas lado a lado em um banco, de mãos dadas, com seus corpos unidos por uma única veia à mostra que conecta seus corações.",
    "As figuras são espelhadas uma na outra, mas diferem no vestuário e na expressão: uma está vestida com um traje tradicional tehuana, associado à cultura indígena mexicana, enquanto a outra usa um vestido branco de estilo europeu, criando um contraste visual entre a identidade mexicana e a herança colonial.",
    "A pintura é amplamente interpretada como um reflexo da dualidade interior de Kahlo — dividida entre suas raízes mexicanas e sua ascendência europeia, entre força e vulnerabilidade, entre a imagem que ela apresentava ao mundo e o eu que sofria em particular.",
    "A anatomia exposta, os corações visíveis e o sangue que mancha o vestido branco remetem diretamente à dor, ao sofrimento e à fragilidade do corpo humano, temas que se repetem em toda a sua obra.",
    "A obra “As Duas Fridas” também coincide com o período de seu divórcio do artista Diego Rivera, o que aprofundou sua ressonância emocional como um retrato da ruptura afetiva, da introspecção e da luta para se manter firme após uma grande perda."
  ],
  "aboutArtistHeading": "Sobre o artista.",
  "aboutArtistParagraphs": [
    "A obra “As Duas Fridas” foi pintada por Frida Kahlo (1907-1954), uma artista mexicana cuja obra é reconhecida por sua honestidade emocional crua, seu simbolismo surreal e seu profundo envolvimento com questões de identidade, gênero e corpo.",
    "Nascida em Coyoacán, na Cidade do México, Kahlo desenvolveu um estilo característico que combinava elementos da arte popular mexicana, do simbolismo indígena e do modernismo europeu, recorrendo frequentemente a autorretratos para explorar seu sofrimento físico, seu turbilhão emocional e suas convicções políticas.",
    "Um grave acidente de ônibus ocorrido na juventude deixou-a com dores crônicas para o resto da vida e a obrigou a passar por inúmeras cirurgias — experiências que moldaram profundamente sua arte e lhe proporcionaram uma perspectiva única sobre o corpo, visto tanto como um local de sofrimento quanto como uma tela para a expressão.",
    "A vida e a obra de Kahlo estavam intimamente ligadas ao panorama cultural e político do México do início do século XX. Ela era casada com o muralista Diego Rivera, cuja influência e turbulência marcam grande parte de seu universo artístico; no entanto, ela desenvolveu com determinação uma voz que era inconfundivelmente sua.",
    "Em *As Duas Fridas*, sua fusão entre narrativa pessoal e linguagem simbólica transforma a tela em uma autobiografia visual, na qual as duas figuras não são apenas duas versões de Frida, mas também uma reflexão sobre a natureza fragmentada da identidade, os custos do amor perdido e a resiliência necessária para sobreviver.",
    "Por meio dessa pintura e de muitas outras, Kahlo tornou-se uma figura central na arte moderna, especialmente para as gerações posteriores de artistas feministas e latino-americanas, que a veem tanto como um ícone cultural quanto como uma contadora de histórias profundamente humana."
  ]
}
