import type { TwoFridasCopy } from "./twoFridas"

/** French copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_FR: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939, par Frida Kahlo",
  "bannerTop": "Une fois que vous aurez parcouru la page ci-dessous, veuillez cliquer sur cette bannière pour découvrir la technologie unique qui sous-tend cette solution, ainsi que les nombreux avantages qu'elle offre aux commissaires d'exposition, aux musées et aux galeries.",
  "bannerBottom": "Cliquez sur cette bannière pour en savoir plus sur la technologie utilisée pour créer cette page.",
  "imageAlt": "Les deux Fridas, de Frida Kahlo",
  "aboutPaintingHeading": "À propos du tableau.",
  "aboutPaintingParagraphs": [
    "« Les deux Frida » est l’un des tableaux les plus grands et les plus emblématiques de Frida Kahlo, achevé en 1939 à une période de profond bouleversement personnel et émotionnel. L’œuvre représente deux versions de l’artiste assises côte à côte sur un banc, se tenant la main, leurs corps reliés par une seule veine apparente qui relie leurs cœurs.",
    "Les personnages se font écho tout en se distinguant par leur tenue et leur expression : l'une porte un costume traditionnel tehuana, associé à la culture autochtone mexicaine, tandis que l'autre porte une robe blanche de style européen, créant ainsi un contraste visuel entre l'identité mexicaine et l'héritage colonial.",
    "Ce tableau est généralement interprété comme le reflet de la dualité intérieure de Kahlo, tiraillée entre ses racines mexicaines et son héritage européen, entre la force et la vulnérabilité, entre l'image qu'elle donnait d'elle-même au monde et celle qui souffrait en privé.",
    "L'anatomie mise à nu, les cœurs visibles et le sang qui tache la robe blanche font directement référence à la douleur, au chagrin et à la fragilité du corps humain, thèmes récurrents dans son œuvre.",
    "L'œuvre « Les deux Frida » coïncide également avec la période de son divorce avec l'artiste Diego Rivera, ce qui a renforcé sa résonance émotionnelle en tant que représentation d'une rupture affective, d'une introspection et de la lutte pour rester debout après une perte majeure."
  ],
  "aboutArtistHeading": "À propos de l'artiste.",
  "aboutArtistParagraphs": [
    "Le tableau « Les deux Fridas » a été peint par Frida Kahlo (1907-1954), une artiste mexicaine dont l'œuvre est saluée pour son authenticité émotionnelle brute, son symbolisme surréaliste et son engagement profond sur les questions d'identité, de genre et du corps.",
    "Née à Coyoacán, à Mexico, Kahlo a développé un style unique mêlant des éléments de l'art populaire mexicain, du symbolisme autochtone et du modernisme européen, recourant souvent à l'autoportrait pour explorer ses souffrances physiques, ses tourments émotionnels et ses convictions politiques.",
    "Un grave accident de bus survenu dans sa jeunesse lui a laissé des douleurs chroniques qui l'accompagnent depuis toujours et l'a contrainte à subir de nombreuses interventions chirurgicales, des expériences qui ont profondément marqué son art et lui ont donné une vision unique du corps, à la fois lieu de souffrance et support d'expression.",
    "La vie et l'œuvre de Kahlo étaient étroitement liées au paysage culturel et politique mexicain du début du XXe siècle. Elle était mariée au muraliste Diego Rivera, dont l'influence et le caractère tumultueux ont profondément marqué une grande partie de son univers pictural ; elle a néanmoins su développer avec détermination une expression artistique qui lui était propre.",
    "Dans *Les deux Frida*, sa fusion entre récit personnel et langage symbolique transforme la toile en une autobiographie visuelle, où les deux personnages ne sont pas seulement deux versions de Frida, mais constituent également une réflexion sur la nature fragmentée de l'identité, le prix de l'amour perdu et la résilience nécessaire pour survivre.",
    "Grâce à ce tableau et à bien d’autres, Kahlo est devenue une figure centrale de l’art moderne, en particulier pour les générations suivantes d’artistes féministes et latino-américaines qui la considèrent à la fois comme une icône culturelle et une conteuse profondément humaine."
  ]
}
