import type { TwoFridasCopy } from "./twoFridas"

/** Turkish copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_TR: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939, Frida Kahlo",
  "bannerTop": "Aşağıdaki sayfayı inceledikten sonra, lütfen bu başlığa tıklayarak bu çözümü mümkün kılan benzersiz teknolojiyi ve bunun sergi küratörlerine, müzelere ve galerilere sunduğu sayısız avantajı öğrenin.",
  "bannerBottom": "Bu sayfayı oluşturmak için kullanılan teknoloji hakkında daha fazla bilgi edinmek için bu başlığa tıklayın.",
  "imageAlt": "Frida Kahlo’nun “İki Frida” adlı eseri",
  "aboutPaintingHeading": "Tablonun hakkında.",
  "aboutPaintingParagraphs": [
    "“İki Frida”, Frida Kahlo’nun en büyük ve en simgesel tablolarından biridir; 1939 yılında, sanatçının yoğun kişisel ve duygusal çalkantılar yaşadığı bir dönemde tamamlanmıştır. Eserde, bir bankta yan yana oturan ve el ele tutuşan sanatçının iki versiyonu tasvir edilmiştir; bedenleri, kalplerini birbirine bağlayan tek bir açık damarla birbirine bağlanmıştır.",
    "Figürler birbirlerinin aynısı gibi görünse de kıyafetleri ve ifadeleri farklıdır: Biri Meksika yerli kültürüyle özdeşleşmiş geleneksel bir Tehuana kıyafeti giymişken, diğeri beyaz, Avrupa tarzı bir elbise giymektedir; bu da Meksika kimliği ile sömürge mirası arasında görsel bir zıtlık yaratmaktadır.",
    "Bu tablo, Kahlo’nun içsel ikileminin bir yansıması olarak yaygın bir şekilde yorumlanmaktadır: Meksikalı kökenleri ile Avrupalı ataları arasında, güç ile kırılganlık arasında, dünyaya sunduğu benliği ile özel hayatında acı çeken benliği arasında sıkışmış hali.",
    "Açığa çıkan anatomik yapılar, görünür haldeki kalpler ve beyaz elbiseyi lekeleyen kan, sanatçının eserlerinde tekrar tekrar karşımıza çıkan acı, kalp kırıklığı ve insan vücudunun kırılganlığı gibi temalara doğrudan atıfta bulunuyor.",
    "“İki Frida” eseri, sanatçı Diego Rivera’dan boşandığı döneme de denk gelmektedir; bu durum, eserin duygusal kopuşu, içsel muhasebeyi ve büyük bir kaybın ardından kendini toparlama mücadelesini yansıtan bir tasvir olarak duygusal etkisini daha da derinleştirmiştir."
  ],
  "aboutArtistHeading": "Sanatçı hakkında.",
  "aboutArtistParagraphs": [
    "“İki Frida” adlı eser, eserleri ham duygusal dürüstlüğü, sürreal sembolizmi ve kimlik, cinsiyet ve beden meseleleriyle derinlemesine ilgilenmesiyle tanınan Meksikalı sanatçı Frida Kahlo (1907-1954) tarafından resmedilmiştir.",
    "Meksiko'nun Coyoacán semtinde doğan Kahlo, Meksika halk sanatı, yerli sembolizm ve Avrupa modernizminin unsurlarını harmanlayan kendine özgü bir üslup geliştirdi; fiziksel acılarını, duygusal çalkantılarını ve siyasi inançlarını keşfetmek için sıklıkla otoportrelerine başvurdu.",
    "Gençlik yıllarında geçirdiği ciddi bir otobüs kazası, ona ömür boyu sürecek kronik ağrılar ve sayısız ameliyatla sonuçlandı; bu deneyimler, sanatını derinden şekillendirdi ve ona bedeni hem acı çekmenin bir mekanı hem de ifade için bir tuval olarak gören benzersiz bir bakış açısı kazandırdı.",
    "Kahlo’nun hayatı ve eserleri, 20. yüzyılın başlarında Meksika’nın kültürel ve siyasi ortamıyla yakından bağlantılıydı. Duvar ressamı Diego Rivera ile evliydi; Rivera’nın etkisi ve çalkantılı hayatı, Kahlo’nun imgeleminin büyük bir kısmını şekillendirse de, Kahlo kararlılıkla kendine özgü, kimsenin taklit edemeyeceği bir üslup geliştirdi.",
    "“İki Frida” adlı eserinde, kişisel anlatım ile sembolik dilin birleşimi, tuvali görsel bir otobiyografiye dönüştürür; bu eserde yer alan iki figür, sadece Frida’nın iki farklı versiyonu olmakla kalmaz, aynı zamanda kimliğin parçalanmış doğası, kaybedilen aşkın bedeli ve hayatta kalmak için gereken dayanıklılık hakkında da bir ifade niteliği taşır.",
    "Bu tablo ve diğer pek çok eseri sayesinde Kahlo, modern sanatın önde gelen isimlerinden biri haline geldi; özellikle de onu hem bir kültür ikonu hem de son derece insancıl bir hikâye anlatıcısı olarak gören sonraki nesil feminist ve Latin Amerikalı sanatçılar için."
  ]
}
