import type { TwoFridasCopy } from "./twoFridas"

/** Italian copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const TWO_FRIDAS_IT: TwoFridasCopy = {
  "title": "The Two Fridas",
  "subtitle": "1939 di Frida Kahlo",
  "bannerTop": "Dopo aver consultato la pagina qui sotto, clicca su questo banner per scoprire l’esclusiva tecnologia alla base di questa soluzione e i numerosi vantaggi che offre ai curatori di mostre, ai musei e alle gallerie.",
  "bannerBottom": "Clicca su questo banner per saperne di più sulla tecnologia utilizzata per creare questa pagina.",
  "imageAlt": "Le due Frida di Frida Kahlo",
  "aboutPaintingHeading": "Informazioni sul dipinto.",
  "aboutPaintingParagraphs": [
    "\"Le due Frida\" è uno dei dipinti più grandi e iconici di Frida Kahlo, realizzato nel 1939 in un momento di intenso sconvolgimento personale ed emotivo. L'opera raffigura due versioni dell'artista sedute fianco a fianco su una panchina, mano nella mano, con i corpi uniti da un'unica vena a vista che collega i loro cuori.",
    "Le figure sono speculari l'una all'altra, ma differiscono per l'abbigliamento e l'espressione: una indossa un abito tradizionale tehuana, tipico della cultura indigena messicana, mentre l'altra indossa un abito bianco in stile europeo, creando un contrasto visivo tra l'identità messicana e l'eredità coloniale.",
    "Il dipinto è comunemente interpretato come un riflesso della dualità interiore di Kahlo, divisa tra le sue radici messicane e le sue origini europee, tra forza e vulnerabilità, tra l’immagine di sé che mostrava al mondo e quella che soffriva in privato.",
    "L'anatomia messa a nudo, i cuori visibili e il sangue che macchia l'abito bianco rimandano direttamente al dolore, alla sofferenza e alla fragilità del corpo umano, temi ricorrenti in tutta la sua opera artistica.",
    "L’opera *Le due Frida* coincide inoltre con il periodo del suo divorzio dall’artista Diego Rivera, il che ne ha accentuato la risonanza emotiva come rappresentazione della rottura sentimentale, dell’introspezione e della lotta per non crollare dopo una grave perdita."
  ],
  "aboutArtistHeading": "Informazioni sull'artista.",
  "aboutArtistParagraphs": [
    "L'opera *Le due Frida* è stata dipinta da Frida Kahlo (1907-1954), un'artista messicana la cui opera è apprezzata per la sua cruda sincerità emotiva, il simbolismo surreale e il profondo interesse per le questioni relative all'identità, al genere e al corpo.",
    "Nata a Coyoacán, Città del Messico, Kahlo sviluppò uno stile inconfondibile che fondeva elementi dell’arte popolare messicana, del simbolismo indigeno e del modernismo europeo, ricorrendo spesso agli autoritratti per esplorare le sue sofferenze fisiche, i suoi turbamenti emotivi e le sue convinzioni politiche.",
    "Un grave incidente in autobus avvenuto durante la sua giovinezza le ha causato dolori cronici che l’hanno accompagnata per tutta la vita e l’ha costretta a sottoporsi a numerosi interventi chirurgici, esperienze che hanno profondamente influenzato la sua arte e le hanno fornito una prospettiva unica sul corpo, inteso sia come sede di sofferenza sia come tela su cui esprimersi.",
    "La vita e l’opera di Kahlo erano strettamente legate al panorama culturale e politico messicano dei primi anni del XX secolo. Era sposata con il muralista Diego Rivera, la cui influenza e il cui carattere turbolento hanno influenzato gran parte del suo immaginario, ma lei ha saputo sviluppare con determinazione uno stile inconfondibilmente proprio.",
    "In *Le due Frida*, la sua fusione tra narrazione personale e linguaggio simbolico trasforma la tela in un’autobiografia visiva, in cui le due figure non sono solo due versioni di Frida, ma rappresentano anche una riflessione sulla natura frammentata dell’identità, sul prezzo dell’amore perduto e sulla resilienza necessaria per sopravvivere.",
    "Grazie a questo dipinto e a molti altri, Kahlo è diventata una figura centrale dell’arte moderna, in particolare per le successive generazioni di artiste femministe e latinoamericane, che la considerano sia un’icona culturale sia una narratrice profondamente umana."
  ]
}
