import edmondDeBelamyImage from "../assets/edmond-de-belamy.png"
import Footer from "../components/Footer"
import "../styles/style.css"
import AudioPlayer from "../components/AudioPlayer"
import pageAudio from "../assets/Audio/ElevenLabs_Portrait_of_Edmond_de_Belamy.mp3"

export default function EdmondDeBelamyPage() {
  return (
    <>
      <main className="tma-gallery-page">
        <header className="tma-header">
          <div className="tma-header-inner">
            <h1 className="tma-page-title">Portrait of Edmond de Belamy</h1>
            <p className="tma-page-subtitle">2018 by Obvious (art collective)</p>
          </div>
        </header>

        <a
          href="/underlying-technology"
          className="tma-banner-link"
        >
          <p className="tma-banner-text">
            <strong>
              When you have explored the page below, please click on this banner to find out about the unique
              underlying technology that enables this solution, and the multiple benefits it offers an exhibition
              curator, museum, and gallery.
            </strong>
          </p>
        </a>

        <div className="tma-content">
          <AudioPlayer src={pageAudio} />

          <img
            src={edmondDeBelamyImage}
            alt="Portrait of Edmond de Belamy"
            className="tma-painting-image"
          />

          <h2>About the painting.</h2>
          <p>
            Portrait of Edmond de Belamy is a striking, deliberately "unfinished-looking" portrait that has become one
            of the most talked-about artworks of the 21st century. Created in 2018, the painting shows a man in dark,
            old-fashioned clothing with a white collar, seated in a composition that recalls 18th- or 19th-century
            European portraiture, yet rendered with a fuzzy, smeared, almost unstable presence. The face and features
            are partially blurred, as if glimpsed through a soft veil, and the figure is set against a neutral
            background that fades into nondescript tones, giving the work an uncanny, ghost-like quality.
          </p>
          <p>
            The piece is part of a series titled La Famille de Belamy, a fictional "family" of portraits generated by
            an algorithm, with Edmond de Belamy serving as the central and most famous member. The painting is not
            painted by a human hand in the traditional sense; instead, it was made by a generative adversarial network
            (GAN), a type of artificial-intelligence system trained on a dataset of roughly 15,000 historical portraits
            spanning the 14th to the 19th centuries. The AI produced the image, which was then printed on canvas and
            framed, entering the traditional art-market format despite its digital origin. The lower-right corner
            carries not a conventional signature, but a mathematical formula-"min max R(x) - Elog(D(x)) -
            Elog(1-D(G(z)))"-that codes the GAN&apos;s internal logic, turning the algorithm itself into the "artist."
          </p>
          <p>
            The work gained global attention when it was sold at Christie&apos;s in New York in 2018 for 432,500 USD, far
            exceeding its pre-sale estimate of 7,000-10,000 USD and becoming one of the first major AI-generated
            artworks to enter the high-end auction market. Beyond its price, the painting sparked intense debate about
            authorship, originality, and the boundaries of art: if an algorithm makes the image, who is the artist?
            Can a machine be creative? The blur between human input and machine output in Portrait of Edmond de Belamy
            has turned it into a symbolic landmark in the history of digital and AI-driven art.
          </p>

          <h2>About the artist.</h2>
          <p>
            Portrait of Edmond de Belamy is credited to the Paris-based art collective Obvious, a group of French
            artists and engineers-Hugo Caselles-Dupre, Pierre Fautrel, and Gauthier Vernier-who work at the
            intersection of computer science and contemporary art. The collective describes itself as developing
            collaborative projects between humans and machines, using algorithms not as replacements for painters but as
            tools that produce new visual languages. In this case, they selected and curated the training data, tuned
            the parameters of the GAN, and then chose which generated portrait to frame, sign, and present as a
            finished artwork, positioning themselves as the "directors" of the AI-driven process rather than the
            literal painters of the image.
          </p>
          <p>
            The collective drew on work in machine-learning art, including code originally shared by a teenage
            programmer, which they adapted into their own GAN system. After training the network on thousands of
            historical portraits, they initiated a cycle in which the system produced images while a "discriminator"
            part of the algorithm tried to guess whether each image was human-made or AI-made; the process continued
            until the machine could no longer reliably tell the difference. The resulting Portrait of Edmond de Belamy
            not only mimics the style and format of traditional portraiture but also deviates from it in ways that feel
            distinctly contemporary: the softness, the slight distortion, and the fugitive presence of the sitter all
            suggest a digital sensibility masked in classical dress.
          </p>
          <p>
            By pushing this AI-generated image into the institutional art world-through a major auction house,
            museum-style display, and a genealogical "family" of portraits-Obvious deliberately raised questions about
            the role of technology in creativity. They force viewers to reconsider long-standing assumptions about the
            "handmade" artwork, the uniqueness of the original, and the place of coding and data in the artistic
            process. In doing so, Portrait of Edmond de Belamy becomes not just a portrait of a fictional man, but a
            portrait of the moment when artificial intelligence formally entered the canon of art history.
          </p>
        </div>

        <a
          href="/underlying-technology"
          className="tma-banner-link"
        >
          <p className="tma-banner-text">
            <strong>Click this banner to discover more about technology used to create this page.</strong>
          </p>
        </a>
      </main>
      <Footer />
    </>
  )
}
