import type { RodinArtworkLocaleCopy } from "./rodinArtworks"

/** Turkish copy — generated by scripts/translate-locales.mjs (review before publishing). */
export const RODIN_ARTWORK_LOCALES_TR: Record<string, RodinArtworkLocaleCopy> = {
  "the-secret": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Sır",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1894 civarında tasarlanmış ve 1960'ta dökülmüştür.",
    "summary": "İki çıplak sevgili, pürüzlü bronz bir kayanın üzerinde birbirine sıkıca sarılmış durumda — adamın eli kayaya dayalı, kadının kolu adamın boynuna dolanmış, dudakları ise samimi bir öpücükle birleşmiş.",
    "aboutParagraphs": [
      "Soldan bir adam öne doğru eğilmiş, sırtı kavisli ve bir eli kayalık kaideye dayalı. Bir kadın, onun sağındaki kayaya yaslanmış, başını ona doğru kaldırmış, kolunu boynuna dolayarak onu kendine çekiyor. Dudakları, grubun ortasında birbirine değiyor. Rodin, yüzleri biraz yumuşatmış — portreden çok jesti ön plana çıkarmış — ancak vücutlar net bir şekilde okunuyor: omuz, omurga, uyluk, bir figürün diğerine yaslanırken verdiği ağırlık. Bronz, kayanın oyuklarında ve omurga boyunca yeşil renkli koyu kahverengi bir patineye sahiptir. Işık, cilalı kas çıkıntıları üzerinde kayar ve alet izleri bulunan deride yansır.",
      "Rodin bu heykel grubunu 1894 civarında tasarladı. Bu kalıp, 1960 yılında Paris’teki Georges Rudier dökümhanesinde Musée Rodin’in izniyle yapılmıştır; tabanında imza, dökümcünün damgası ve müzenin telif hakkı işareti bulunmaktadır. 27,9 santimetre boyutundaki bu eser, kasıtlı olarak küçük tutulmuştur: galerinin diğer ucundan değil, yakından bakarak izleyebileceğiniz bir kucaklaşma.",
      "Etrafında yavaşça dolaşın. Arkadan baktığınızda adamın gergin sırtını ve kadının kavisli omurgasını görürsünüz; önden baktığınızda kollarının oluşturduğu kapalı döngüyü; yandan baktığınızda ise öpüşmenin gerçekleştiği dar alanı. Eserin başlığı, yüzeysel olarak bakıldığında açıkça sergilenen bir şefkat gösterisi olan bu sahneye, mahremiyet anlamı yüklemenizi istiyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Le Secret",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/the-secret"
      },
      {
        "label": "Rodin Müzesi",
        "href": "https://www.musee-rodin.fr/en"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Le Secret. A. Rodin imzalı. Üzerinde Georges Rudier Fondeur Paris dökümhane işareti ve © Musée Rodin 1960 ibaresi bulunmaktadır. Envanter RCG0071.2-25",
    "meta": {
      "height": "27,9 cm",
      "materials": "Kahverengi patine ve yeşil vurgular içeren bronz.",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "main-crispee-droite": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Sıkılmış Büyük Sağ El",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1898'den önce tasarlanmış ve 1926 ile 1965 yılları arasında dökülmüştür.",
    "summary": "\"Cehennem Kapıları\"nın ifade dilinden esinlenerek tasarlanmış, anıtsal boyutlara ulaşmış tek başına duran bir sağ el — parmaklar, gerginlik, meydan okuma ya da içsel kargaşayı yansıtan bir tutuşla bükülmüş.",
    "aboutParagraphs": [
      "Pürüzlü, tek parça bir kaide üzerinde, bileğinden kopmuş tek bir sağ el yükseliyor. Parmaklar gergin ve bükülmüş bir tutuşla kıvrılmış durumda — kapalı bir yumruk değil, başparmak uzanmış halde dışa doğru gerilen bir kavrama. Parmak eklemleri, tendonlar ve avuç içi, neredeyse yarım metrelik bir ölçekte şekillendirilmiş; her bir alet izi açıkça görülüyor. Koyu bronz patina, parmakların arasındaki girintilerde yeşil birikintiler oluşturuyor.",
      "Rodin, bu eli “Cehennem Kapıları”ndan alınmış bağımsız bir çalışma olarak ayırıp büyütmüştür. Büyük model, bilek ve önkol kütlesinin başlı başına anıtsal parçalar olarak algılanmasını sağlar.",
      "Bu örnek, 1962 yılında Paris’teki Georges Rudier dökümhanesinde Musée Rodin’in lisansı altında dökülmüş olup, dış yüzeyinde müze onaylı baskı olduğunu teyit eden bir iç damga ile imzalanmıştır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Sağ kıvrımlı ana çubuk, büyük model",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/right-clenched-hand%2C-large-model"
      },
      {
        "label": "Rodin Müzesi",
        "href": "https://www.musee-rodin.fr/en"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Main crispée droite, grand modèle. A. Rodin imzalı. Üzerinde “Georges Rudier Fondeur Paris” ve “© Musée Rodin 1962” yazmaktadır. İç kısmında “A. Rodin” damgası bulunmaktadır. Envanter RCG0062.2-23",
    "meta": {
      "height": "46,5 cm",
      "materials": "Bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "age-of-bronze-small": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Bronz Çağı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1875 ile 1877 yılları arasında tasarlanan ve Kasım 1904’te dökülen bu versiyon, Ekim 1945’te dökülmüştür.",
    "summary": "Rodin'in yalınlaştırma tekniğindeki ilk büyük başarısı — bir elini başına koymuş, diğerini havaya kaldırmış ikonik poz, samimi bir sergilemeye uygun ölçekte korunmuş.",
    "aboutParagraphs": [
      "Koyu patine kaplı bronz bir erkek figürü, sağ elini başının üstüne koymuş, sol kolunu ise yanına indirmiş halde duruyor. Başı geriye doğru eğilmiş; gözleri ağırlaşmış, neredeyse kapanmak üzere. Ağırlığı tek bacağına vermiş; göğüs ve omuzlar, Rodin'in ilk büyük çıplak heykelinin ikinci küçültülmüş versiyonu olan bu 64 santimetrelik eserde anatomik bir hassasiyetle modellenmiştir.",
      "L'Âge d'Airain, 1877 Paris Sanat Sergisi'nde gerçekçiliğiyle büyük yankı uyandırdı; Rodin, bir süreliğine canlı modelden kalıp aldığı iddiasıyla suçlandı. Model, genç bir Belçikalı asker olan Auguste Neyt'ti.",
      "Bu bronz heykel, Ekim 1945'te Paris'teki Alexis Rudier dökümhanesinde dökülmüştür; arka yüzünde dökümcünün işareti, kaidesinde ise Rodin'in imzası bulunmaktadır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — L'Âge d'Airain, küçük model, 2. ölçek",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/l%E2%80%99%C3%A2ge-d%E2%80%99airain%2C-petit-mod%C3%A8le%2C-2%C3%A8me-reduction-%5Bage-of-bronze%2C-small-model%2C-2nd-reduction%5D"
      },
      {
        "label": "Rodin Müzesi — Bronz Çağı",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/age-bronze"
      },
      {
        "label": "Cantor Vakfı — Küçültmeler ve Genişletmeler",
        "href": "https://cantorfoundation.org/resources/reductions-and-enlargements/"
      },
      {
        "label": "Smarthistory / Khan Akademi",
        "href": "https://www.khanacademy.org/humanities/becoming-modern/avant-garde-france/avant-garde-sculpture/a/auguste-rodin-the-age-of-bronze"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), L'Âge d'Airain, petit modèle, 2ème réduction. A. Rodin imzalı. Arkada sağ tarafta Alexis Rudier / Fondeur Paris dökümcü işareti ve iç damga bulunmaktadır. Envanter RCG0063.2-23",
    "meta": {
      "height": "64,3 cm",
      "materials": "Bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "age-of-bronze": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Bronz Çağı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1875 ile 1877 yılları arasında tasarlanmış, 1918'de dökülmüştür.",
    "summary": "Bir elini başına koymuş, diğer elini havaya kaldırmış, gerçek boyutlarda bir erkek çıplak heykeli — Rodin’in ilk bağımsız başyapıtı; o kadar rahatsız edici derecede gerçekçi ki, Paris Salonu onu bu heykeli canlı bir vücuttan kalıplayarak yaptığını iddia etmişti.",
    "aboutParagraphs": [
      "Gerçek boyutta bir bronz erkek figürü, sağ kolunu başının üstüne doğru yüksekte kaldırmış, sol ön kolunu ise omzuna yakın bir konumda tutmuş halde durmaktadır. Başı geriye doğru eğilmiştir; gözleri ya kapalıdır ya da tavana doğru bakmaktadır. Göğüs, kaburgalar ve karın bölgesi, yıpranmış yeşil-siyah bir patina ile kaplıdır; bu patina, köprücük kemikleri ve kaldırılmış kol boyunca ışığı yansıtmaktadır. Duruş, uyanık ama aynı zamanda askıda kalmış gibidir — sanki uyanıyor ya da bir şeyi hatırlıyor gibi.",
      "Rodin, İtalya'dan döndükten ve Michelangelo ile ilk kez tanıştıktan sonra, bu heykeli 1875 yılının Ekim ayında Brüksel'de yapmaya başladı. Modelini, genç bir Belçikalı asker olan Auguste Neyt oluşturdu. Neyt daha sonra, Rodin'in pozunu santimetre santimetre değiştirirken saatlerce ayakta durduğunu hatırladı.",
      "Başlangıçta heykelin sol elinde uzun bir mızrak vardı ve Rodin, yenilmiş Fransızları anmak için ona Le Vaincu — Yenilen — adını vermişti. Sonra mızrağı çıkardı. Silahın yokluğunda, bu hareketin anlamı belirsizleşti: Adam uyanıyor mu, ölüyor mu, rüya mı görüyor, yoksa hiçlikten kendini mi kaldırıyor? Rodin, Hesiod'un Üçüncü İnsan Çağı'ndan esinlenerek heykele L'Âge d'Airain adını verdi ve bu belirsizlik kalıcı oldu. Heykel, uyku ile uyanıklık arasında, idealize edilmiş klasik çıplaklık ile şaşırtıcı derecede modern bir şey arasında bir yerde duruyor.",
      "Alçı heykel 1877’de Brüksel ve Paris’teki Salon sergilerine ulaştığında, eleştirmenler Rodin’i canlı modelden kalıp çıkardığı için suçladılar. Falguière, Carrier-Belleuse ve Dubois gibi bir grup meslektaşı sonunda onu kamuoyu önünde savunmak için bir bildiri imzaladı. Devlet alçı heykelini satın aldı ve 1880'de Thiébaut Frères'e bu ilk bronz heykelin yapımını sipariş etti. Rodin, Salon'da üçüncü sınıf madalya ile ödüllendirildi. Bir daha asla gerçek boyutlu bir heykel yapmadı. İhtiyacı olanı çoktan öğrenmişti."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — L'Âge d'Airain",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/l%E2%80%99%C3%A2ge-d%E2%80%99airain-%5Bage-of-bronze%5D"
      },
      {
        "label": "Orsay Müzesi — Tunç Çağı",
        "href": "https://www.musee-orsay.fr/en/artworks/lage-dairain-15624"
      },
      {
        "label": "Rodin Müzesi — Bronz Çağı",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/age-bronze"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Bronz Çağı",
        "href": "https://www.metmuseum.org/art/collection/search/189265"
      },
      {
        "label": "Cleveland Sanat Müzesi — Bronz Çağı",
        "href": "https://www.clevelandart.org/art/1918.328"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), L'Âge d'Airain. A. Rodin imzalı. Envanter RCG0002.20-05",
    "meta": {
      "height": "182,8 cm",
      "materials": "Yeşil patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "danaide": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1885 yılında tasarlanmış, 1925 civarında dökülmüştür.",
    "summary": "Bir kadın, yüzüstü pürüzlü bronz bir kayanın üzerine diz çökmüş, sırtı kavisli, saçları taşın üzerine öne doğru dökülmüş — ceza, yalnızca bedeninde somutlaşmış.",
    "aboutParagraphs": [
      "Kayalık bir kaide üzerinde kendi üzerine kıvrılmış durumda: dizleri kendine doğru çekilmiş, kalçaları yukarı kalkmış, yüzü koluna gömülmüş. Uzun saçları, altındaki taşın dokusuyla birleşen kalın bronz bukleler halinde kaya yüzeyinden aşağı dökülüyor. Sırt ve omuzlar ışığı yakalıyor; omurga boyunca ve kıvrılmış uzuvların altındaki çukurlar gölge ve yeşil patina barındırıyor. Hiçbir çömlek, başka hiçbir figür yok — sadece ağırlığa ve yorgunluğa teslim olmuş bu kompakt, kaslı vücut var. Rodin'in imzası kaidenin yan tarafında yer alıyor.",
      "Yunan mitolojisinde Danaideler, suyu tutamayan kaplarla sonsuza dek su çekmeye mahkum edilmişti. Rodin, 1885 civarında “Cehennem Kapıları” için onlardan birini modellemiş, ardından bu anıtsal kalabalığın içinden çıkardığı pek çok figürde yaptığı gibi, onu tek başına bırakmıştı. Arkın'ın bu kalıbı, zengin koyu kahverengi ve kırmızı-kahverengi patineye sahip bronzdur — Paris'teki ünlü beyaz mermerden değil, ancak aynı poz 21 santimetre boyunda korunmuştur.",
      "Heykelin etrafında dolaşın. Yukarıdan omurganın kavisini, yandan kalçanın yükselen eğriliğini ve saçların dökülüşünü, arkadan ise sanki hala göremediğiniz bir şeyi taşıyormuşçasına gerilmiş omuzları görebilirsiniz. Ceza, Rodin’in dışarıda bırakmayı tercih ettiği herhangi bir özellikte değil, duruşta yatmaktadır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Danaïde",
        "href": "https://www.thearkinrodincollection.com/"
      },
      {
        "label": "Orsay Müzesi — Danaïde",
        "href": "https://www.musee-orsay.fr/en/artworks/danaide-7694"
      },
      {
        "label": "Rodin Müzesi — Danaïd",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/danaid"
      },
      {
        "label": "Rodin Müzesi, Philadelphia — Danaid (Kaynak)",
        "href": "https://rodinmuseum.org/collection/object/96034"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Danaïde. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde © Alexis Rudier Fondeur Paris yazmaktadır. Envanter RCG0013.2-13",
    "meta": {
      "height": "21 cm",
      "materials": "Koyu ve kırmızımsı kahverengi bir patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "je-suis-belle": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Ben Güzelim",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1882 ile 1885 yılları arasında tasarlanmış, 1968'de dökülmüştür.",
    "summary": "Bronz bir kucaklaşmada birbirine sıkıca sarılmış iki figür — kadının başı geriye atılmış, erkeğin yüzü kadının göğsüne yaslanmış; eserin adı Baudelaire’den alınmış.",
    "aboutParagraphs": [
      "Yakından bakıldığında, grubun tüm üyeleri birbirine yaslanmış bedenler ve iç içe geçmiş uzuvlardan ibarettir. Bir adam, başı geriye düşmüş, gözleri kapalı, ağzı hafifçe aralık bir kadının üzerine eğilmiştir. Adamın yüzü kadının göğsüyle boynunun kıvrımlarına bastırılmıştır; kadının kolları ise adamı sarmalamıştır. Bronz, ağır, dokunsal vuruşlarla işlenmiştir — koyu kahverengi ve siyah, kasların ve saçların her kıvrımına yeşil renk yerleşmiştir. Işık, adamın omzuna ve kadının boğazına vurur; geri kalan kısım gölgeye gömülür.",
      "Je suis belle, adını Charles Baudelaire’in “Saçları ve eteği birbirine dolanmış” adlı şiirinden almaktadır. Rodin, bu heykel grubunu 1882 ile 1885 yılları arasında, ilk olarak Cehennem Kapıları için tasarladığı malzemelerden yola çıkarak geliştirmiş, ardından bağımsız bir eser olarak sergilemiştir. Bu kalıp, 1968 yılında Paris'teki Georges Rudier dökümhanesinde Musée Rodin'in lisansı altında üretilmiştir ve kaide üzerinde müzenin telif hakkı ve dökümcünün imzasını taşımaktadır.",
      "Bir adım geri çekildiğinizde, yetmiş beş santimetrelik grup tek bir karanlık kütle gibi görünür. Tekrar yaklaştığınızda ise o samimiyet geri gelir — bu bir güç gösterisi değil, yakınlığın ifadesidir; iki beden, tek bir bronz yüzeye katlanmış."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Je suis belle",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/je-suis-belle-%5Bi-am-beautiful%5D"
      },
      {
        "label": "Rodin Müzesi",
        "href": "https://www.musee-rodin.fr/en"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Je suis belle. A. Rodin imzalı. Üzerinde “© Musée Rodin 1968” ve “Georges Rudier Fondeur Paris” yazmaktadır. Envanter RCG0064.2-18",
    "meta": {
      "height": "75 cm",
      "materials": "Koyu kahverengi, siyah ve yeşil patineli bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "bust-of-jean-daire": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Jean d'Aire'nin büstü",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1886'da tasarlanmış, Aralık 1940'ta dökülmüştür.",
    "summary": "Calais'in altı vatandaşından biri olan Jean d'Aire, bronz bir heykelde tek başına duruyor — kararlı, yıpranmış yüz hatları, kahramanca bir idealizasyonu reddediyor.",
    "aboutParagraphs": [
      "Bronz baş, göğüs üstü kısmı görünen yaşlı bir adamı tasvir ediyor: derin çizgilerle kaplı alın, çukurda kalmış, yere doğru bakan gözler, yorgun bir ifadeye bürünmüş ince dudaklar. Yüzey pürüzlü ve dokunsaldır; kahverengi patina, göz çukurlarında ve boyun boyunca yeşil renktedir. Burada hiçbir şey idealize edilmemiştir — yüz kararlı, yıpranmış ve sarsılmazdır.",
      "Jean d'Aire, 1347 yılında kendilerini rehin olarak sunan altı Calaisli vatandaştan biriydi. Rodin, 1884 yılında sipariş edilen anıtta her bir adamın ruh halini ayrı ayrı işledi.",
      "Bu büst, Aralık 1940'ta Paris'teki Alexis Rudier dökümhanesinde dökülmüştür; dış yüzeyinde dökümcünün damgası, iç kısmında ise bu eserin orijinalliğini teyit eden kabartmalı bir imza bulunmaktadır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Jean d'Aire'nin Büstü",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/bust-of-jean-d%27aire"
      },
      {
        "label": "Rodin Müzesi — Calais'lılar",
        "href": "https://www.musee-rodin.fr/en/collections/sculptures/bourgeois-de-calais-monument"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Buste de Jean d'Aire. Üzerinde “Alexis Rudier Fondeur Paris” dökümhane işareti ile imzalanmış ve damgalanmış olup, iç kısmında kabartmalı “A. Rodin” imzası tekrarlanmaktadır. Envanter RCG0061.2-22",
    "meta": {
      "height": "46,9 cm",
      "materials": "Kahverengi ve yeşil patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "seated-titan": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Oturan Titan (Titanlar Vazosu'ndan)",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1878 ile 1882 yılları arasında tasarlanmıştır.",
    "summary": "Pürüzlü bir kayanın üzerinde bükülmüş tek bir beyaz mermer heykel — kolları başının arkasına kaldırılmış, bir dizi havaya kalkmış, kasları gergin, sıkı bir çömelme pozisyonunda.",
    "aboutParagraphs": [
      "Çıplak bir adam, yontulmuş bir taş bloğun üzerinde oturuyor; gövdesi bükülmüş, iki kolu başının arkasına kaldırılmış, yüzü geriye doğru eğilerek gölgeye dalmış. Yükseltilmiş bir diz silueti bozuyor; uzatılmış ayak kayaya dayanıyor. Vücut pürüzsüz bir şekilde cilalanmış; taban ise kasıtlı olarak pürüzlü bırakılmış, böylece işlenmiş ten ile işlenmemiş taş arasındaki kontrast anlamın bir parçası haline geliyor. Otuz iki santimetre boyundaki figür ele sığıyor, ancak kaburgalar ve uyluklar arasındaki uzantı onu daha büyük gösteriyor.",
      "Rodin, İtalya'dan döndükten kısa bir süre sonra, 1878–1882 yılları civarında, Albert-Ernest Carrier-Belleuse'nin \"Titanlar Vazosu\"na katkıda bulunduğu figürlerden biri olarak bu \"Oturan Titan\"ı modellemiştir. Arkın koleksiyonundaki bu eser, A. Rodin imzalı, beyaz mermerden yapılmış tek başına duran bir modeldir; dört figürlü bahçe saksısı değil, aynı Michelangelo tarzındaki çömelmiş figürün tek başına duran bir versiyonudur.",
      "Blokun etrafında bir tur atın. Arkadan bakıldığında omurga bir yay gibi kavis çiziyor; yandan bakıldığında ise yukarı kaldırılmış diz ve eğilmiş baş, tek bir çaba eğrisinde birleşiyor. Vazonun övgüsü Carrier-Belleuse’e gitti; Rodin’in “Titanlar”ın yaratıcısı olduğu ise ancak on yıllar sonra resmen kabul edildi."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Titan assis",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/seated-titan"
      },
      {
        "label": "Cleveland Sanat Müzesi",
        "href": "https://www.clevelandart.org/"
      },
      {
        "label": "Philadelphia Sanat Müzesi",
        "href": "https://www.philamuseum.org/objects/346671"
      },
      {
        "label": "Detroit Sanat Müzesi",
        "href": "https://dia.org/collection/vase-titans-94258"
      },
      {
        "label": "Houston Güzel Sanatlar Müzesi",
        "href": "https://www.mfah.org/blogs/inside-mfah/spotlight-fusion-of-forms"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Titan assis. A. Rodin imzalı, model figürü. Envanter RCG0026.2-05",
    "meta": {
      "height": "32 cm",
      "materials": "Beyaz Mermer",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "titan-iv": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Titan IV (Titanlar Vazosu'ndan)",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1878 ile 1882 yılları arasında tasarlanmıştır.",
    "summary": "Bir kayanın üzerine kamburunu çıkarmış, kollarını kaldırdığı dizine dolamış, başını eğmiş beyaz mermer bir heykel — burada tek başına tasvir edilen dördüncü Titan.",
    "aboutParagraphs": [
      "Adam, kaba yontulmuş bir mermer bloğun üzerinde çömelmiş durumda; bir dizini göğsüne çekmiş, iki kolunu da bacağına dolamış, başını dizine doğru eğmiş. Sol bacağı taşın yüzeyinden aşağı sarkıyor. Sırt ve omuzlar boyunca kaslar pürüzsüz bir şekilde şekillendirilmiş; taban ise pürüzlü ve bitmemiş kalmış. Poz kapalı, içe dönük, neredeyse kendine kapalı — üstündeki ağırlığı destekleyen bir figürden çok, kendi vücuduna katlanmış bir figür.",
      "Rodin, İtalya'dan döndükten sonra Carrier-Belleuse'nin \"Titanlar Vazosu\" için tasarladığı heykel grubunun bir parçası olarak bu \"Titan IV\" heykelini 1878 ile 1882 yılları arasında yonttu. Arkın'ın elindeki eser, otuz iki santimetre yüksekliğinde, imzalı bir beyaz mermer yorum modelidir — Carrier'ın tek başına imzaladığı dekoratif bütünlükten çıkarılmış tek figürdür.",
      "Yandan bakıldığında, omurganın uzun kıvrımı her şeyi anlatıyor. Önden bakıldığında ise sadece eğik baş ve birbirine kenetlenmiş kollar görünüyor. Dört Titan arasında en sessiz olanı ve belki de en modern olanı: bir gösteri sergilemeyen, düşünen bir beden."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Titan IV",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/titan-iv"
      },
      {
        "label": "Houston Güzel Sanatlar Müzesi",
        "href": "https://www.mfah.org/blogs/inside-mfah/spotlight-fusion-of-forms"
      },
      {
        "label": "Cleveland Sanat Müzesi",
        "href": "https://www.clevelandart.org/"
      },
      {
        "label": "Philadelphia Sanat Müzesi",
        "href": "https://www.philamuseum.org/objects/346671"
      },
      {
        "label": "Detroit Sanat Müzesi",
        "href": "https://dia.org/collection/vase-titans-94258"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Titan IV. A. Rodin imzalı, model figürü. Envanter RCG0025. 2-15",
    "meta": {
      "height": "32 cm",
      "materials": "Beyaz Mermer",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "abduction-of-hippodamia": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Hippodamia'nın Kaçırılması",
    "artist": "Albert-Ernest Carrier-Belleuse, Auguste Rodin ile birlikte (Fransız, 1840–1917)",
    "caption": "1871 civarında tasarlanmış ve dökülmüştür.",
    "summary": "Kentaur Eurytion, düğününde Lapith gelinini kaçırıyor — tanınmış bir usta ile genç Rodin arasında gerçekleştirilen şiddet dolu bir ortak çalışma; eser, yalnızca işverenin adıyla imzalanmış.",
    "aboutParagraphs": [
      "Bir centaur düğüne davetsiz misafir olarak daldı. Lapithlerin kralı Pirithous’un düğün şöleninde, yarı at konuklar şaraptan sarhoş olup gelini kaçırdılar. Kentaurların lideri Eurytion, Hippodamia'yı yerden havaya kaldırır; kadının vücudu bükülür, kolu adamın omzuna sıkışır, düğün çelenkleri hâlâ adamın toynaklarının etrafına dağılmıştır. Devrilmiş bir şarap testisi, gecenin nasıl geçtiği hakkında bilmeniz gereken her şeyi anlatır.",
      "Bu bronz heykel, 1871 ile 1879 yılları arasında Carrier-Belleuse’ün Brüksel’deki atölyesinde modellenmiştir. Genç Auguste Rodin, Komün olaylarının ardından ustasının peşinden Belçika’ya sürgüne gitmiş ve orada bir “praticien” — yani kiralık işçi — olarak çalışmıştı. Eser sadece Carrier tarafından imzalanmıştır, ancak June Hargrove'un araştırmasından bu yana yapılan akademik çalışmalar, eserin yazarlığını ikiye ayırmıştır: uluyan, kaslı centaur Rodin'e, idealize edilmiş, neredeyse neoklasik gelin ise Carrier'e aittir. Birleşim yeri görülebilir. Grubun iki yarısı, iki farklı heykeltıraşa, iki farklı on yıla aitmiş gibi görünmektedir.",
      "Konu — Centauromachy, yani medeniyetin vahşi arzuya karşı mücadelesi — eski Yunanlıların en sevdiği temalardan biriydi; Parthenon’un alınlık süslemesi için ideal bir konuydu. Washington'daki bu kalıbın etrafında dolaşın. Patina koyu fırtına yeşili, modelleme ise hareketlidir. Rodin, Bronz Çağı'na iki yıl uzaklıktadır ve şimdiden, başka bir adamın imzasında, o, kusursuz bir şekilde tanınmaktadır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Hippodamie'nin Kaçırılması",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/l%E2%80%99enl%C3%A8vement-d%E2%80%99hippodamie-%5Bthe-abduction-of-hippodamia%5D"
      },
      {
        "label": "Washington Ulusal Sanat Galerisi",
        "href": "https://www.nga.gov/artworks/56386-abduction-hippodamia-lenlevement-dhippodamie"
      }
    ],
    "plateCaption": "Albert-Ernest Carrier-Belleuse, Auguste Rodin ile birlikte (Fransız, 1840–1917), L'Enlèvement d'Hippodamie. Carrier-Belleuse imzalı. Başlık plaketi ile: L’enlèvement. Eserin bir kısmı, Carrier-Belleuse’nin rehberliğinde Auguste Rodin tarafından modellenmiştir. Envanter RCG0024.2-17",
    "meta": {
      "height": "65 cm",
      "materials": "Bronz, üzerinde zengin yeşil, orta ve koyu kahverengi bir patina.",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "minotaur": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Minotaur (Faun ve Nymph)",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1883-1885 yılları civarında tasarlanmış, 2013 yılında dökülmüştür.",
    "summary": "Yan profilden birbirine yapışmış iki bronz yüz — biri pürüzsüz ve genç, diğeri kırışık ve ağzı açık — yakın mesafeden yakalanmış bir samimiyet ve ıstırap.",
    "aboutParagraphs": [
      "Heykel, birbirine sıkıca yapışmış iki yüzle çerçeveyi dolduruyor. Sağda, gözleri kapalı, dudakları sıkı, cildi pürüzsüz bir şekilde işlenmiş, sakin bir profilden görünen genç bir kadının yüzü. Solda ise, şişkin bir gözü ve açık ağzı olan, yıpranmış, daha yaşlı bir yüz; yanağı genç kadının şakağına yaslanmış. Bronz koyu ve yansıtıcıdır, siyah-kahverengiye patine edilmiştir ve kaşlar, dudaklar ve elmacık kemikleri boyunca keskin vurgular vardır. Görüntüde bedenler ya da kaya kaide yoktur — sadece 61 santimetrelik bu yüzeylerin karşı karşıya gelmesi vardır.",
      "Rodin bu heykel grubunu pek çok farklı isimle sergiledi — Minotaur, Faun ve Nymph, Satyr ve Kadın — ve onu 1883–1885 yılları civarında, Cehennem Kapıları adlı eserine yoğunlaştığı dönemde şekillendirdi. Bu Arkın dökümü, 2013 yılında Paris'teki Susse dökümhanesinde üretildi, EA III/IV imzalı ve damgalı olup, zengin kahverengi ve yeşil patineye sahiptir.",
      "Heykelin etrafında dolaştıkça, her açıdan farklı bir izlenim ortaya çıkıyor: bir taraftan pürüzsüz hatlar göze çarparken, diğer taraftan ise açık ağız ve sabit bakan göz dikkat çekiyor. Rodin, iki yanak arasındaki dar alana bütün bir dramı sığdırıyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Minotaur",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/minotaur"
      },
      {
        "label": "Philadelphia Sanat Müzesi",
        "href": "https://www.philamuseum.org/objects/103480"
      },
      {
        "label": "Maryhill Sanat Müzesi",
        "href": "https://www.maryhillmuseum.org/inside/exhibitions/permanent-exhibitions/auguste-rodin"
      },
      {
        "label": "Rodin-Web / Tancock & Elsen katalogları",
        "href": "http://rodin-web.org/works/1886_minotaur.htm"
      },
      {
        "label": "Rodin Müzesi, Cehennem Kapıları",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/gates-hell"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Le Minotaure. A. Rodin imzalı. Üzerinde “EA III/IV Susse Fondeur Paris” dökümhane işareti yazılı ve damgalı. Envanter RCG0023.2-21",
    "meta": {
      "height": "61 cm",
      "materials": "Zengin kahverengi ve yeşil patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "camille-claudel-bonnet": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Bent giyen Camille Claudel'in büstü",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1884'te tasarlanmış, Temmuz 1971'de dökülmüştür.",
    "summary": "Gevşek şekillendirilmiş bir başlığın altındaki genç bir kadının bronz başı — gözleri aşağıya doğru bakıyor, ağzı sıkı, yüzü Rodin’in hızlı ve keskin dokunuşuyla işlenmiş.",
    "aboutParagraphs": [
      "Şapka, başın tepesinde yüksekte duruyor; yüzün daha pürüzsüz yüzeyleriyle tezat oluşturan, kaba, eskiz benzeri vuruşlarla şekillendirilmiş. Gözler açık ama aşağıya doğru bakıyor; uzun, düz burun ve kapalı ağız, dalgın bir sükûnet sergiliyor. Boyun, kare şeklinde bir tahta blok üzerinde pürüzlü bir kesikle son buluyor. Çukur kısımlarda yeşil tonlar içeren koyu kahverengi patina, elmacık kemikleri ve başlığın sırtı boyunca ışığı yansıtmaktadır.",
      "Bu, Camille Claudel’in 1884 civarında çekilmiş bir fotoğrafı; fotoğrafta, ikisinin hayatındaki en yıpratıcı ilişkinin tam başlangıcında, sevgilisi ve öğretmeni ona poz veriyor.",
      "Camille, 1883 yılında henüz yirmi yaşını doldurmamış bir öğrenci olarak Rodin’in atölyesine geldi. Rodin kırk üç yaşındaydı ve şöhretinin ilk doruk noktasındaydı. Bir yıl geçmeden Camille, onun çalışma arkadaşı, modeli, ilham perisi ve —kısa süre sonra— metresi olmuştu. Rodin, takip eden on yıl boyunca onu birçok kez heykeline dönüştürdü: La Pensée olarak, Aurora'nın başı olarak, mermeri yaran şafak tanrıçası olarak. Camille au bonnet olarak bilinen bu erken dönem baş heykeli, bu portreler arasında en doğrudan olanı, özel gözlemlere en yakın olanıdır.",
      "Etrafında yavaşça dolaşın. Burada ne bir gösteri, ne de bir alegori var. Rodin, düşüncelere dalmış genç, parlak ve son derece zor bir kadının iç dünyasını yakalamış. Aşağıya doğru bakan gözler ve kaba şapka ile ince cilalı yüz arasındaki kontrast, tam bir Rodin tarzıdır — bu, modelin henüz tamamlanmamış, hala oluşum aşamasında olması nedeniyle eserin de tamamlanmamış olduğunu ifade etmenin bir yoludur. On yıl içinde Camille ondan ayrılacaktı. Şapka ise hala duruyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Bonyeli Camille Claudel",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/camille-claudel-au-bonnet-%5Bbust-of-camille-claudel-wearing-a-bonnet%5D"
      },
      {
        "label": "Rodin Müzesi — Rodin ve Camille Claudel",
        "href": "https://www.musee-rodin.fr/en/resources/rodin-and-artists/camille-claudel"
      },
      {
        "label": "Camille Claudel Müzesi, Nogent-sur-Seine",
        "href": "https://www.museecamilleclaudel.fr/en/collections/camille-claudel-biography/1886-1893-rodin-and-camille-claudel-tumultuous-love-affair-and"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Camille Claudel au bonnet. A. Rodin imzalı; iç kısmında da aynı imza tekrarlanmaktadır. Üzerinde “No. 11 © by Musée Rodin 1971” yazısı ve Georges Rudier Fondeur Paris dökümhane işareti bulunmaktadır. Envanter RCG0022.2-05",
    "meta": {
      "height": "24,8 cm",
      "materials": "Koyu kahverengi ve yeşil patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "mme-rodin": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Rose Beuret'in Maskesi",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1882'de tasarlanmış, 1971'de dökülmüştür.",
    "summary": "Rose Beuret’in yüzü — Rodin’in elli üç yıl boyunca hayat arkadaşı olan — gözleri kapalı bir maske olarak kalıplanmış ve 1877’den beri peşini bırakmayan “canlı modelden kalıp alma” skandalından kaçınmak için kasıtlı olarak yumuşatılmıştı.",
    "aboutParagraphs": [
      "Gözler kapalı ve yüz, artık orada olmayan bir bedenden koparılmış bir maske gibi okunacak şekilde bırakılmış. Bu, Rodin'in hayatının elli üç yılını paylaştığı kadın: Lorraine kırsalından gelen bir terziyken 1864'te yirmi yaşındayken onunla tanışan, tek oğlunu doğuran, Rodin henüz tanınmıyorken atölyesini idare eden ve 1917'de ikisi de ölmeden sadece birkaç hafta önce onunla evlenen Marie-Rose Beuret.",
      "Rodin, onu ilk olarak 1880 civarında, miğferli, hırçın Bellona olarak modellemişti. 1882 civarında tasarlanan bu portrede ise görünüşü farklıdır — daha sakin, içine kapanık, eleştirmenlerin onu The Age of Bronze'u doğrudan gerçek hayattan kalıplamış olmakla suçlayarak kariyerini neredeyse sona erdirecek olan skandalı atlatmak için yüz hatları kasıtlı olarak bulanıklaştırılmıştır. Büstünü gerçek boyutundan biraz daha küçük tuttu, yüzeyleri yumuşak bıraktı, saçları ise zar zor belli olacak şekilde tasvir etti. Burada hiçbir şey suçlamaya davet etmiyor. Her şey bakmaya davet ediyor.",
      "Yakından bakın. Heykelin formlarında bu ilişkinin uzun tarihini görebilirsiniz — sevgiyi, ilgisizliği, sevgisini günlük hayatının bir parçası olarak gören bir erkeğin geç kalmış, hafif suçluluk duygusu taşıyan şefkatini. Alexis Rudier tarafından bronzdan dökülen bu baş, Madame Rodin'in Maskesi olarak da bilinir. Bu, stüdyonun tanıdığı, sessiz, başı eğik, vazgeçilmez Rose'dur; rol yapmayan Rose."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Madam Rodin",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/mme-rodin-%5Bbust-of-rose-beuret%5D"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Rose Beuret’in Maskesi",
        "href": "https://www.metmuseum.org/art/collection/search/207493"
      },
      {
        "label": "Arkın İskele’de Sanat — Mme Rodin",
        "href": "https://www.artatarkiniskele.com/import-1/mme-rodin-%5Bbust-of-rose-beuret%5D"
      },
      {
        "label": "Rose Beuret — biyografi",
        "href": "https://en.wikipedia.org/wiki/Rose_Beuret"
      },
      {
        "label": "Met — Rodin’in Çağdaşlarının Portreleri",
        "href": "https://www.metmuseum.org/perspectives/auguste-rodin-portraits"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Mme Rodin. A. Rodin imzalı. A. Rudier / Alexis Rudier Fondeur Paris yazısı. Envanter RCG0021-0X",
    "meta": {
      "height": "26,9 cm",
      "materials": "Koyu kahverengi ve orta yeşil patine kaplı bronz.",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "mask-of-hanako": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Hanako'nun Maskesi, E Tipi Çalışma",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1907 ile 1908 yılları arasında tasarlanan bu eser, 1956 yılında dökülmüştür.",
    "summary": "Hanako’nun küçük bir bronz maskesi — gözleri açık, dudakları kapalı, yüzü sakin ve maske gibi; damarlı bir taş kaide üzerinde.",
    "aboutParagraphs": [
      "Yüz, geniş burun, dolgun ve kapalı dudaklar, açık ve düz duran badem şeklindeki gözler gibi Doğu Asya özellikleriyle önden işlenmiştir. Başın arkası ve tepe kısmı, sanki daha büyük bir bloktan koparılmış gibi işlenmemiş bırakılmıştır. Koyu kahverengi patina yanakları ısıtır; çukurlarda kırmızımsı tonlar toplanır. Maske, çatlaklı taş dokulu kare bir kaide üzerinde durur. On yedi nokta sekiz santimetre boyutundaki bu eser, en temel unsurlarına indirgenmiş bir portredir.",
      "Bu Hanako — 1868'de Ohta Hisa adıyla dünyaya gelen Japon aktris, Rodin'in hayatının son on yılında en yoğun şekilde incelediği modellerinden biri oldu. Rodin, 1907 ile 1911 yılları arasında onun için elli sekiz adet büst yaptı; bu sayı, diğer hiçbir model için yaptığı sayıyı aşıyor.",
      "Rodin, Hanako’yu ilk kez 1906 yılında Marsilya’da, Amerikalı dansçı Loïe Fuller’ın yönettiği bir turne tiyatrosunda sahnede izlemişti. Oyunları, Japon tiyatrosunun Batılılaştırılmış taklitleriydi; Avrupa seyircisi için yazılmıştı ve neredeyse her zaman kanlı bir ritüel intihar sahnesiyle son buluyordu. Rodin'i etkileyen, o aşırı ıstırap dolu anda Hanako'nun gergin, bitkin ve aşkın yüzüydü. Onu Meudon'a getirdi ve kendisi heykelini yaparken Hanako'dan ölüm sahnesindeki ifadeleri taklit etmesini istedi.",
      "Bu, Rodin’in 1907’de yaptığı varyasyonlardan biri olan “Étude Type E”dir. Victoria & Albert Müzesi’nde, Jean Cros tarafından 1912’de pâte de verre tekniğiyle dökülmüş olağanüstü bir versiyon bulunmaktadır — şakakları neredeyse saydam olan, renkli camdan yapılmış Hanako. Burada sergilenen maske ise bronz versiyondur. Yakından bakın. Hareketsiz dururken bile, sanki çerçevenin hemen dışında bir şeyi dinliyormuş gibi görünüyor. Rodin daha sonra, yüzünün Donatello'nun bir Roma büstünün tüm ifade gücünü barındırdığını söyleyecekti. Rodin, Hanako'ya dokunmadan önce onun bir heykel olduğunu düşünmüştü."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Masque d'Hanako, E Tipi Etüt",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/masque-d%E2%80%99hanako%2C-%C3%A8tude-type-e-%5Bmask-of-hanako%2C-study-type-e%5D"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Hanako'nun Maskesi",
        "href": "https://www.metmuseum.org/art/collection/search/207487"
      },
      {
        "label": "Victoria ve Albert Müzesi — Hanako Maskesi, E Tipi",
        "href": "https://collections.vam.ac.uk/item/O1758562/mask-of-hanako-type-e-mask-of-hanako-rodin-auguste/"
      },
      {
        "label": "Tokyo Batı Sanatı Ulusal Müzesi",
        "href": "https://collection.nmwa.go.jp/en/S.1959-0025.html"
      },
      {
        "label": "Rodin-Web — Hanako'nun Maskeleri",
        "href": "http://www.rodin-web.org/works/1907_hanako.htm"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Masque d'Hanako, Étude Type E. A. Rodin imzalı. Üzerinde “© Musée Rodin 1956” ve “Georges Rudier Fondeur Paris” yazmaktadır. Envanter RCG0020.2-06",
    "meta": {
      "height": "17,8 cm",
      "materials": "Kahverengi ve kırmızı patine kaplı bronz.",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "head-of-lust": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Şehvetin Başı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1882'de tasarlanmış, 1917 ile 1918 yılları arasında dökülmüştür.",
    "summary": "Bir adamın bronz başı derin bir eğilimle eğilmişti — kaşları çatılmış, gözleri gölgede kalmış, ağzı hafifçe aralanmış, yüzeyindeki her çıkıntıya keder işlenmişti.",
    "aboutParagraphs": [
      "Baş aşağı doğru eğilmiş ve hafifçe bir yana dönmüş. Derin kaşlar gözlerin üzerinde gölge oluşturuyor; dudaklar, nefesini tutmuş ya da konuşmayı kesmiş olduğunu ima edecek kadar aralanmış. Kalın, dalgalı saçlar kaba yığınlar halinde şekillendirilmiş; boyun kaslı ve göğüs hizasında pürüzlü bir kesikle son buluyor. Bronz, parlak koyu kahverengi ve yeşil-siyah renktedir; alın, burun ve elmacık kemikleri boyunca parlak noktalar varken, gözler karanlıkta kalır.",
      "Rodin, 1882 yılında “Cehennem Kapıları” için “Tête de la Luxure”yi tasarladı; bu eserde, “Açgözlülük ve Şehvet” grubu içinde Şehvet’i temsil eden bir kadın figürü yer almaktadır. Bu Arkın dökümü, 1917 ile 1918 yılları arasında Alexis Rudier tarafından yapılmış olup, kaide üzerinde dökümcünün işareti ve iç kısımda tekrarlanan bir imza bulunmaktadır. 37,3 santimetre boyutundaki bu eser, ağır, içe dönük ve ilk bakışta anlaşılması zor, tek başına bir kafa çalışması olarak okunur.",
      "Yakından bakıldığında, başın aşağı doğru eğimi resmin tek konusu haline gelir. Yukarıdan bakıldığında başın tepesini ve omuzların duruşunu görürsünüz; aşağıdan bakıldığında ise açık ağzı ve kaşların ağırlığını. Rodin, bunun keder mi, yorgunluk mu yoksa içe atılmış bir duygu mu olduğuna karar vermeyi size bırakır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Şehvetin Yüzü",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/t%C3%AAte-de-la-luxure-%5Bhead-of-lust%5D"
      },
      {
        "label": "Rodin Müzesi — Açgözlülük ve Şehvet",
        "href": "https://enfer.musee-rodin.fr/fr/figure/avarice-et-la-luxure"
      },
      {
        "label": "Rodin Müzesi — Cehennem Kapıları",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/gates-hell"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Tête de la Luxure. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde “Alexis Rudier Fondeur Paris” yazmaktadır. Envanter RCG0019.2-05",
    "meta": {
      "height": "37,3 cm",
      "materials": "Zengin koyu yeşil, siyah ve kahverengi patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "mask-broken-nose": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Kırık Burunlu Adamın Maskesi",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1863 ile 1864 yılları arasında tasarlanmıştır.",
    "summary": "Sadece Bibi olarak bilinen Parisli bir tamircinin sakallı, yıpranmış yüzü — 23 yaşındaki Rodin tarafından dondurucu soğukta bir atölyede modellenmiş, Salon tarafından iki kez reddedilmiş ve Rodin tarafından ilk gerçek eseri olarak hatırlanan.",
    "aboutParagraphs": [
      "Sakallı, yüzü yara izleriyle dolu, burnu kırık, ne genç ne de klasik anlamda güzel bir yüz. Rodin daha sonra bunu ilk gerçek eseri olarak nitelendirecekti — “hayatımda yaptığım ilk heykel çalışması.” O zaman yirmi üç yaşındaydı.",
      "Modeli, 1863 yılında Rodin’in dondurucu soğuklardaki Saint-Marcel atölyesinin yakınında yaşayan ve sadece Bibi olarak bilinen yerel bir tamirciydi. Rodin bu kafa üzerinde bir yıldan fazla bir süre çalıştı. Bir kış gecesi atölyenin ısınması bozuldu, kil dondu ve başın arkası kopup düştü. Rodin bu parçayı sakladı ve ona maske adını verdi. 1864'te Salon des Beaux-Arts'a sundu; reddedildi. 1865'te tekrar sundu; yine reddedildi. Jüri üyeleri eserin bitmemiş olduğunu düşündü. Roma imparatoru kadar özenle modellenmiş, burnu kırık, yaşlanan bir işçinin portresine henüz hazır değillerdi.",
      "Yakından bakın. Yüz hatları son derece gerçekçi olsa da, saçlar geç Helenistik dönem büstlerindeki bukleler gibi işlenmiş, boş bakışlı gözler ise klasik heykellerdeki gibi. Rodin, önümüzdeki elli yıl boyunca yapacağı şeyi çoktan yapmaya başlamıştı: Antik çağın dilini sıradan, çirkin, kendine özgü insanların bedenlerine aktarmak. Maske nihayet 1875'te kabul edildi ve bronza döküldü. Modeli adının sanat tarihine geçmek üzere olduğunu hiç bilmeyen Bibi, Rodin'in ilk gerçek modeli olmuştu."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Kırık Burunlu Adam Maskesi",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/masque-de-l%E2%80%99homme-au-nez-cass%C3%A9-%5Bmask-of-a-man-with-a-broken-nose%5D"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Kırık Burunlu Adamın Maskesi",
        "href": "https://www.metmuseum.org/art/collection/search/204767"
      },
      {
        "label": "Victoria Ulusal Galerisi, Melbourne",
        "href": "https://www.ngv.vic.gov.au/explore/collection/work/3579/"
      },
      {
        "label": "Vikipedi — Burun Kırık Adam",
        "href": "https://en.wikipedia.org/wiki/Man_with_the_Broken_Nose"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Masque de l'Homme au Nez Cassé. Üzerinde \"A Rodin\" imzası ve iç kısımda kabartmalı tekrarlı imza bulunmaktadır. Üzerinde \"Alexis Rudier Fondeur Paris\" yazısı bulunmaktadır. Envanter RCG0018.2-13",
    "meta": {
      "height": "25,5 cm",
      "materials": "Kahverengi patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "torso-great-shadow": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Büyük Gölge'nin Gövdes",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1900 civarında tasarlanmış, 2000 yılında dökülmüştür.",
    "summary": "Cehennem Kapıları'ndan dışarı sarkan, başsız ve kolsuz bir gövde; bu gövde, bir zamanlar Dante'nin yazıtını işaret eden Üç Gölge'den biri olarak orada duruyordu.",
    "aboutParagraphs": [
      "Yaklaşınca göz yukarı doğru kayar, sonra bir anda durur: karşılaşacak bir kafa yoktur. Vücut, görünmez omuzlardan aşağıya doğru bastıran bir ağırlığa karşı direniyormuş gibi kavislenir, göğüs açılır, karın gerilir. Dengede tutacak kolları olmayan gövde, sanki sadece yerçekimine ve kendisine cevap veriyor gibi görünür — paradoksal bir şekilde, bir parçanın bir bütün haline dönüşmesi.",
      "Rodin, bu figürü ilk olarak Cehennem Kapıları’nı süsleyen Üç Gölge’den biri olarak modellemişti. Bu kederli nöbetçilerin her biri içe doğru eğilmiş, elleri Dante’nin yazıtına doğru uzanıyor: “Lasciate ogni speranza, voi ch’entrate.” 1900 civarında, Rodin, büyütücü Henri Lebossé ile birlikte çalışarak, başsız ve kolsuz Gölge'nin gövdesini gerçek boyutunun ötesinde büyüttü. Stüdyodan çıkan esere hayran kalan Lebossé, onu Rodin'in kariyerindeki belki de en önemli heykel olarak nitelendirdi.",
      "Antik Belvedere Torso’su — Michelangelo’nun yol göstericisi — ile olan benzerlik kasıtlıdır. Rodin uzun zamandır bir parçanın bitmiş bir heykelden daha fazla gerçeği yansıtabileceğini, eksikliğin bir tür yoğunluk olduğunu savunuyordu. Bronz heykelin etrafında yavaşça dolaşın: her açıdan kasların ve gölgelerin farklı bir dramı karşınıza çıkar, ancak bir çözüm bulunmaz. Mesele de budur. Büyük Gölge, başını ve kollarını kendine saklar."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Büyük Gölgenin Torso'su",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/torse-de-la-grande-ombre-%5Btorso-of-the-great-shadow%5D"
      },
      {
        "label": "Christie's — Rodin, Büyük Gölgenin Torso'su",
        "href": "https://www.christies.com/en/lot/lot-5766532"
      },
      {
        "label": "Rodin Müzesi, Paris",
        "href": "https://www.musee-rodin.fr/"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Torse de la Grande Ombre. A. Rodin imzalı. Üzerinde “E. GODARD Fondr © by Musée Rodin 2000” yazısı bulunmaktadır. Envanter RCG0017.2-14",
    "meta": {
      "height": "100 cm",
      "materials": "Koyu kahverengi bir patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "head-jean-de-fiennes": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Jean de Fiennes'in Başı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1886'da tasarlanmış, 1984'te dökülmüştür.",
    "summary": "Keskin bir hareketle geriye doğru eğilmiş bronz bir baş — ağzı açık, gözleri gölgelerin içinde kaybolmuş, bedeni olmayan bir yüze yoğunlaşmış ıstırap.",
    "aboutParagraphs": [
      "Sadece baş kalmıştır; iki katlı siyah bir kaideye yerleştirilmiştir. Baş geriye ve hafifçe yana doğru eğilmiştir; ağzı aralıktır, göz çukurları karanlığa gömülmüştür. Şekillendirme kaba ve acelecidir — saçlar kalın tutamlar halinde, cilt alet izleriyle pütürlüdür; alında ve elmacık kemiklerinde ışık yansımaları görülürken göz çukurları siyah kalmıştır. Gövde yok, giysi yok, uzanmış kollar yok — sadece 32,2 santimetre büyüklüğünde bu izole yüz var.",
      "Jean de Fiennes, 1347 yılında kendilerini rehin olarak sunan altı Calaisli burjuva arasında en genciydi. Rodin, anıtın yapımını 1884 yılında üstlendi ve her bir vatandaşı ayrı bir psikolojik çalışma olarak şekillendirdi. Bu baş, 1886 yılında tasarlandı; Arkın dökümü, 1984 yılında Musée Rodin'in lisansı altında Émile Godard dökümhanesinde yapıldı.",
      "Ayakları birbirine yakın durursa geriye doğru atılan kol meydan okuma olarak algılanır; ayakları birbirinden uzak durursa ise teslimiyet olarak algılanır. Rodin, genç bir adamın korkusunu tek bir açıdan gösterir ve geri kalanını ima yoluyla bırakır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Jean de Fiennes'in Kafası",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/t%C3%AAte-de-jean-de-fiennes-%5Bhead-of-jean-de-fiennes%5D"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Jean de Fiennes, Giysili",
        "href": "https://www.metmuseum.org/art/collection/search/207553"
      },
      {
        "label": "Vikipedi — Jean de Fiennes (Rodin)",
        "href": "https://en.wikipedia.org/wiki/Jean_de_Fiennes"
      },
      {
        "label": "Maryhill Sanat Müzesi — Rodin Koleksiyonu",
        "href": "https://www.maryhillmuseum.org/"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Tête de Jean de Fiennes. Üzerinde \"A. Rodin\" yazısı ve \"E. Godard Fondr\" dökümhane işareti bulunmakta olup, Musée Rodin tarafından 1984 tarihli ve Émile Godard dökümhanesi tarafından da tarihlenmiştir. Envanter RCG0016-0X",
    "meta": {
      "height": "32,2 cm",
      "materials": "Bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "head-pierre-de-wiessant": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Pierre de Wissant'ın heykeli",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1885 civarında tasarlanmış, 1960'ta dökülmüştür.",
    "summary": "Calais'lılar'dan birinin gerçek boyutundan daha büyük bir baş heykeli; uzun bir korku anında donmuş gibi duruyor — gözleri çukurlaşmış, ağzı yarı açık, yüzeyinde hâlâ Rodin’in işleme izleri görülüyor.",
    "aboutParagraphs": [
      "Pierre de Wissant, 1347 yılında kuşatma altındaki Calais kentinin kurtulabilmesi için kendilerini İngiltere Kralı III. Edward’a rehin olarak sunan altı varlıklı vatandaştan biriydi. Beş yüzyıl sonra anıtını tasarlayan Rodin, vatanseverlik klişesini reddetti ve bunun yerine her bir adamı kişisel dehşetine sürükledi. Bu, sanki heykeltıraş, tıpkı sahnede olduğu gibi ağız ve göz kapaklarındaki en ufak bir hareketi bile okumanızı istemişçesine, gerçek boyutunun ötesinde büyütülmüş Pierre'in yüzüdür.",
      "Yüzeye bir bakın. Rodin alçıyı doğrudan işledi — şakaklarda grafit çizgiler beliriyor, gözlerin altındaki çukurlara renk tonları yerleşmiş, deride hâlâ parmak izleri görünüyor. Hiçbir şey düzeltilmemiş ya da cilalanmamış. Baş, akademik anlamda bitmemiş olsa da, diğer her açıdan tamamlanmış durumda.",
      "Anıt grubu üzerinde çalışmaya devam ederken, her bir burjuva figürünün kendi başına tam bir dram barındırdığına inanarak, Pierre’in gerçek boyutlu heykelini anıt grubundan ayrı olarak sergiledi. Bu başın önüne dikildiğinizde nedenini anlarsınız. Ağız hafifçe aralanmış; bir söz düşünülmüş ama söylenmemiş. Yavaşça yana doğru yürüyün ve tüm yüz bir parça daha çökmüş gibi görünecektir. O parça, konunun tamamıdır."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Wiessant Taş Kafası",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/t%C3%AAte-de-pierre-de-wiessant%2C-type-b-%5Bhead-of-pierre-de-wiessant%2C-type-b%5D"
      },
      {
        "label": "Cleveland Sanat Müzesi — Pierre de Wissant’ın Büstü (1917.722)",
        "href": "https://www.clevelandart.org/art/1917.722"
      },
      {
        "label": "Cleveland Sanat Müzesi — Pierre de Wissant'ın Büstü (bronz, 1920.120)",
        "href": "https://www.clevelandart.org/art/1920.120"
      },
      {
        "label": "Arkın Koleksiyonu — Wiessant Taş Kafası, B Tipi",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/t%C3%AAte-de-pierre-de-wiessant,-type-b-%5Bhead-of-pierre-de-wiessant,-type-b%5D"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Tête de Pierre de Wiessant. A. Rodin imzalı; iç kısmında kabartmalı imza bulunmaktadır. Musée Rodin tarafından © işareti ile imzalanmış olup, üzerinde Georges Rudier Fondeur Paris 1960 dökümhane işareti bulunmaktadır. Envanter RCG0015.2-05",
    "meta": {
      "height": "43,3 cm",
      "materials": "Koyu kahverengi bir patineye ve yeşil tonlara sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "head-eustache-de-saint-pierre": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Eustache de Saint-Pierre'in Başı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1886'da tasarlanmış, 1974'te dökülmüştür.",
    "summary": "Sakallı, çukur gözlü en yaşlı kasaba sakininin başı — tüm tarih kayıtlarına göre Calais için canını feda etmeye ilk gönüllü olan adam.",
    "aboutParagraphs": [
      "Sakallı bronz bir baş öne doğru bakıyor: alında derin çizgiler, çukurlaşmış gözler, kalın bıyık ve girintilerinde yeşil patina birikmiş gür sakal. Yüz zayıf, yıpranmış ve hüzünlü — ahşap iki katlı bir kaidenin üstüne yerleştirilmiş metal bir direğe monte edilmiş. Otuz beş santimetre boyundaki bu eser, en temel unsurlarına indirgenmiş bir portre olarak algılanıyor.",
      "Eustache de Saint-Pierre, 1347 yılında kuşatma altındaki Calais kentinden sadece gömlekleriyle ve boyunlarına ipler asılı halde çıkıp III. Edward’a teslim olan altı vatandaştan en büyüğüydü. Tarih kayıtları, onun öne çıkan ilk kişi olduğunu belirtmektedir.",
      "Rodin, 1886 yılında Eustache heykelini, Pas-de-Calais doğumlu ressam Jean-Charles Cazin’den esinlenerek yaptı; sanatçı, Cazin’in yüz hatlarının aradığı mirası taşıdığını düşünüyordu. Rodin, bu burjuva karakterine kahramanca bir duruş vermedi. Elmacık kemikleri şakaklara doğru sivrilir; ağız sıkı ama yorgundur; alın hafifçe öne doğru eğimlidir, sanki kafa reddedemeyeceği yürüyüşe çoktan başlamış gibidir.",
      "Bir kenara çekilince önce kaşlar ışığı yakalar — elmacık kemikleri belirginleşir, ağız sertleşir, gözler gölgenin derinliklerine gömülür. Bedenin bütününden koparıldığında, baş, bir erkeğin kendini feda etmesinin bedelini anlatan bir denemeye dönüşür."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Aziz Petrus'un Kulak Kapağı",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/t%C3%AAte-d%E2%80%99eustache-de-saint-pierre%2C-%C3%A8tude-type-a%2C-grand-mod%C3%A8le--%5Bhead-of-d%E2%80%99eustache-de-saint-pierre%2C-study-type-a%2C-large-model%5D"
      },
      {
        "label": "Rodin Müzesi — Calais Vatandaşları Anıtı",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/monument-burghers-calais"
      },
      {
        "label": "Kreeger Müzesi — Calais'lılar tablosundan Eustache de Saint-Pierre",
        "href": "https://www.kreegermuseum.org/about-us/collection/sculpture/Auguste-Rodin_Eustache-de-Saint-Pierre-from-The-Burghers-of-Calais-1884-95-reduction"
      },
      {
        "label": "Wikimedia Commons — Eustache de Saint-Pierre’in Son Portresi, Rodin Müzesi, Dört Kalıptan İkincisi",
        "href": "https://commons.wikimedia.org/wiki/File:Final_Head_of_Eustache_de_Saint_Pierre_by_Auguste_Rodin,_Mus%C3%A9e_Rodin_cast_II_of_IV.JPG"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Tête d'Eustache de Saint Pierre. A. Rodin imzalı. Üzerinde “© Musée Rodin 1974” ve “Georges Rudier Fondeur Paris” yazmaktadır. Envanter RCG0014.2-05",
    "meta": {
      "height": "35 cm",
      "materials": "Yeşil ve kahverengi patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "eve-small-model": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Eve, küçük model",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1881'de tasarlanmış, Nisan 1947'de dökülmüştür.",
    "summary": "Kendi utancının içine kapanmış minik bir Eve — kollarını yüzüne ve vücuduna dolamış, başını kollarının oluşturduğu gölgenin içine gömmüş.",
    "aboutParagraphs": [
      "Rodin, 1881 yılında Havva heykeline, Adem heykelinin eş parçası olarak başladı; her ikisi de Cehennem Kapısı’nın iki yanını süsleyecekti. İtalyan bir model, Abruzzesi kardeşlerden biri üzerinde çalışırken, modelin vücudunda bir değişiklik olduğunu fark etti — model ona söylememişti, ama hamileydi. Sonunda modellemeye başladığı figür, bu gizli yükü taşıyordu: karnında bir kalınlık, artık birbiriyle tam olarak uyuşmayan bir uyluk, artık saklayamadığı şeye karşı içe doğru eğilmeye başlayan bir vücut.",
      "Kare tabanlı ve düz ayaklı küçük model — petit modèle — 1883 yılına kadar tamamlanarak sergilendi. Sonunda François Rudier, Griffoul & Lorge, Perzinka, Alexis Rudier ve en son olarak 1967 yılına kadar Georges Rudier tarafından yaklaşık kırk adet bronz döküm yapıldı. İlk sahipleri, bu eseri, anıtsal Havva'yı ahlaki gücünden hiçbir şey kaybetmeden ev ortamına taşıdığı için çok sevdiler.",
      "Rilke onu en iyi şekilde tarif etmişti: \"Havva, başını kollarının gölgesine derinlemesine gömmüş bir şekilde duruyor.\" Ona sessizce yaklaş. Kollar göğüsleri ve yüzü sarmış; omuzlar öne doğru eğilmiş; beden, cennetten çıkacak uzun yolculuğuna çoktan başlamış. Elmayı yedikten hemen sonraki anı izliyorsun."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Ève, küçük model",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/eve%2C-petit-mod%C3%A8le-(mod%C3%A8le-%C3%A0-la-base-carr%C3%A9e-et-aux-pieds-plats)-%5Beve%2C-small-model-(model-with-a-square-base-and-flat-feet)%5D"
      },
      {
        "label": "Rodin Müzesi — Havva",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/eve"
      },
      {
        "label": "Arkın Koleksiyonu — Ève, küçük model (kare tabanlı ve düz ayaklı)",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/eve,-petit-mod%C3%A8le-(mod%C3%A8le-%C3%A0-la-base-carr%C3%A9e-et-aux-pieds-plats)-%5Beve,-small-model-(model-with-a-square-base-and-flat-feet)%5D"
      },
      {
        "label": "Vikipedi — Havva (Rodin)",
        "href": "https://en.wikipedia.org/wiki/Eve_(Rodin)"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Ève, petit modèle. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde © Alexis Rudier Fondeur Paris yazmaktadır. Envanter RCG0012.2-07",
    "meta": {
      "height": "76 cm",
      "materials": "Hafif kahverengi bir patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "meditation": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Meditasyon ya da İç Ses",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1885'te tasarlanmış, 1930'da dökülmüştür.",
    "summary": "Victor Hugo’nun terk edilmiş Pantheon anıtı için tasarlanan, kıvrımlı ve bükülmüş bir figür — daha sonra bağımsız bir eser olarak ortaya çıkarılmış ve genellikle kolları olmadan sergilenmiştir.",
    "aboutParagraphs": [
      "Ayakta duran çıplak bir kadın, S şeklinde kıvrılmış: başı katlanmış sağ koluna yaslanmış, sol kolu havada, bacakları uyluk hizasında çaprazlanmış, sağ ayağı kayalık bronz bir kaideye basmış. Yüzeyi koyu kahverengi, elle şekillendirilmiş; kalça ve göğüs kafesi boyunca kaslar ışığı yansıtıyor. Sanki kendi göğsünün içinden gelen bir sesi dinliyor gibi görünüyor.",
      "\"La Méditation\", Rodin'in 1885 yılında tasarladığı, ancak Panthéon için yapılan ve sonradan terk edilen Victor Hugo anıtındaki bir ilham perisi figürü olarak ortaya çıktı.",
      "Panthéon projesi suya düştü ve Rodin, bu figürü kaybetmeyi reddettiği için onu heykel grubundan ayırdı. 1896’da onu neredeyse gerçek boyutuna yakın bir şekilde büyüttü. Kadın dönüyor. Kalçası dışarı doğru çıkmış, göğsü omuzlarına doğru dönmüş, başı diğer göğsüne doğru eğilmiş — tüm bedeni içe doğru dinliyor. Birçok kalıpta kadının kolları yoktur; bazılarında ise diz altından itibaren bacakları yoktur. Rodin pişman değildi. \"Kolsuz heykellerim,\" dedi Rilke'ye, \"onlar için gerekli olan hiçbir şeyden yoksun değiller.\"",
      "Alexis Rudier, 1921 ile 1943 yılları arasında on üç adet kalıp çıkardı; ana alçı kalıp Meudon’daki Rodin Müzesi’nde bulunurken, diğer kalıplar ise Stockholm, Tokyo ve Londra’da yer almaktadır. Onun önünde hareketsiz durun. Figür sizin için poz vermiyor. Kendi zihninde bir cümlenin ortasında ve duyduklarını tutabilecek kadar kalın olan tek şey bronz."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — La Méditation",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/la-m%C3%A9ditation-%5Bmeditation%5D-"
      },
      {
        "label": "Rodin Müzesi — Meditasyon ya da İç Ses",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/meditation-or-inner-voice"
      },
      {
        "label": "Rodin-Web — Düşünce (1885)",
        "href": "http://rodin-web.org/works/1885_meditation.htm"
      },
      {
        "label": "Victoria & Albert Müzesi — İç Ses (İlham Perisi)",
        "href": "https://collections.vam.ac.uk/item/O135947/inner-voice-the-muse-figure-rodin-auguste/"
      },
      {
        "label": "Vikipedi — Meditasyon (Rodin)",
        "href": "https://en.wikipedia.org/wiki/Meditation_(Rodin)"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), La Méditation. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde “Alexis Rudier Fondeur, Paris” yazmaktadır. Envanter RCG0011.2-07",
    "meta": {
      "height": "74,1 cm",
      "materials": "Kahverengi ve koyu kahverengi patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "triumphant-youth": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Zafer Kazanan Gençlik",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1894 yılında tasarlanmış, 1906 ile 1918 yılları arasında dökülmüştür.",
    "summary": "Kayalık bir kaide üzerinde bronz bir öpüşüşe dalmış bir adam ve bir kadın — kadının başı geriye atılmış, adamın kolu kadının omuzlarında, heykel grubu altın kahverengi bir patina ile parıldıyor.",
    "aboutParagraphs": [
      "Çıplak bir adam pürüzlü bir kayanın üzerinde oturmuş, geriye yaslanmış; bir kadın ise kucağına uzanmış durumda. Kadının sağ kolu adamın boynuna dolanmış; adamın eli ise kadının uyluğunda. Dudakları, kompozisyonun merkezinde birleşiyor. Bronz, zengin altın kahverengi bir patineye sahiptir; bu patine, kayanın çatlaklarında ve vücutlarının arasındaki kıvrımlarda daha koyu renktedir. Kas yapısı, Rodin'in karakteristik cilalı ve pürüzlü karışımıyla modellenmiştir — kadının kavisli sırtında pürüzsüz, altlarındaki taşta ise hareketlidir.",
      "Rodin bu heykel grubunu 1896 Paris Salonu’nda “Zafer Kazanan Gençlik” adıyla sergilemiş olsa da, “Sonsuz Gençlik”, “Büyükannenin Öpücüğü”, “Yaşlılık ve Ergenlik” gibi başka başlıklar altında da sergilemiştir. Eser 1894 yılında tasarlandı. Arkın tarafından dökülen bu heykel, Thiébault Frères dökümhanesinin imzasını taşıyor ve yüksekliği elli iki santimetredir.",
      "Heykelin etrafında dolaştıkça kucaklaşma sürekli yeni bir şekil alıyor: arkadan bakıldığında erkeğin geniş sırtı; önden bakıldığında kadının geriye atılmış başı; yandan bakıldığında ise öpüşmenin dar köprüsü. Rodin bu heykel grubuna pek çok isim verdi, çünkü heykel tek bir hikâyeye sığmayı reddediyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Zafer Kazanan Gençlik",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/la-jeunesse-triomphante-%5Btriumphant-youth%5D"
      },
      {
        "label": "Vikipedi — Zafer Kazanan Gençlik",
        "href": "https://en.wikipedia.org/wiki/Youth_Triumphant"
      },
      {
        "label": "Philadelphia Sanat Müzesi — Zafer Kazanan Gençlik",
        "href": "https://press.philamuseum.org/asset/331894/image4-youthtriumphant-2"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), La Jeunesse Triomphante. A. Rodin imzalı. Üzerinde “Thiebault Fres Paris et Cie. Suc.” yazıyor. Envanter RCG0005.2-05",
    "meta": {
      "height": "52 cm",
      "materials": "Zengin altın kahverengi ve koyu kahverengi bir patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "iris-study-with-head": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Iris, Başlı Portre",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1890 ile 1891 yılları arasında tasarlanmış, 1970 yılında dökülmüştür.",
    "summary": "Tek ayağı üzerinde dengede duran, diğer bacağını yana doğru uzatmış, bir kolu omuzdan itibaren eksik olan başsız bir bronz heykel — karanlık patine kaplı metal üzerinde donmuş akrobatik bir hareket.",
    "aboutParagraphs": [
      "Figür, sağ bacağını bükmüş, sol bacağını ise yatay olarak uzatmış bir şekilde durmaktadır. Başı yoktur — boyun kısmında kaba bir kütük kalmıştır — ve sol kol omuzdan kesilmiştir. Sağ kol, uzanmış ayağı kavramak için gövdenin üzerinden uzanmaktadır. Karın ve uyluk kasları belirgindir; yüzey koyu kahverengi-yeşil renktedir, göğüs ve uzanmış uzuv boyunca parlak noktalar bulunmaktadır. Elli üç santimetre uzunluğundaki bu poz, ayaktan kalçaya ve kütüğe kadar tek bir gerilim çizgisi olarak algılanmaktadır.",
      "Rodin, “Tanrıların Habercisi İris” adlı eserini 1890 ile 1891 yılları arasında, başlangıçta Victor Hugo Anıtı için tasarladı. Daha sonra birçok versiyondan baş ve kolu çıkardı; böylece ortaya çıkan başsız, bacakları yana açılmış figür, sanatçının en çok tartışılan eserlerinden biri haline geldi. Bu Arkın dökümü, 1969 ile 1972 yılları arasında Susse Fondeurs tarafından Musée Rodin için üretildi.",
      "Figürün etrafında dolaştıkça denge sürekli değişiyor — önden bakıldığında uzanan kol, bakışları vücudun diğer tarafına çekiyor; yandan bakıldığında ise yatay pozisyondaki bacak bir kaldıraç gibi dışarı doğru uzanıyor. Uçuyormuş gibi görünen bu duruş, sadece yere basan ayak sayesinde ayakta kalıyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Iris, Kafalı Etüt",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/iris%2C-%C3%A9tude-avec-t%C3%A9te-%5Biris%2C-study-with-head%5D"
      },
      {
        "label": "Rodin Müzesi — Tanrıların habercisi İris",
        "href": "https://www.musee-rodin.fr/en/musee/collections/oeuvres/iris-messenger-gods"
      },
      {
        "label": "Metropolitan Sanat Müzesi — Tanrılar Elçisi Iris",
        "href": "https://www.metmuseum.org/art/collection/search/207490"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Iris, Étude avec Tête. A. Rodin imzalı. Üzerinde “© Musée Rodin 1971” ve “Susse Fondeurs, Paris” ibareleri yer almaktadır. 1969 ile 1972 yılları arasında Musée Rodin için Susse Dökümhanesi tarafından dökülmüştür. Envanter RCG0010.2-13",
    "meta": {
      "height": "53 cm",
      "materials": "Yeşil ve koyu kahverengi patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "falling-man": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Düşen Adam",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1885 civarında tasarlanmış, 1973'te dökülmüştür.",
    "summary": "Cehennem Kapıları’nın üst eşiğinden geriye doğru fırlatılan bir lanetlinin silueti, karşı konulamaz bir güçten kaçar gibi bükülüyordu.",
    "aboutParagraphs": [
      "Rodin’in “Cehennem Kapıları”na sıkıştırdığı kıvranan kalabalığın içinde, “Düşen Adam” özel bir yere sahiptir: O, hiçbir şeyden kaçamayan figürdür. 1880'lerin başında Rodin'in büyük kapı üzerinde çalıştığı sırada tasarlanan bu figür, kapının sol üst köşesine, timpanumu alt panellerden ayıran lento üzerine yarıya kadar bacaklarını uzatmış şekilde yerleştirilmiştir. Geriye doğru devrilmeye başlamıştır ve bronz heykel, düşüşün geri dönüşü olmayan hale gelmesinden hemen önceki anı tam olarak yakalamaktadır.",
      "Rodin hayattayken bu heykelin hiçbir kalıbı alınmamıştı. Susse dökümhanesi, 1972 ile 1982 yılları arasında Musée Rodin için on iki bronz heykel üretti ve bu da onlardan biri. Kapıdan uzakta, bağımsız bir eser olarak Düşen Adam, kalabalığın içine kaynaştığında gizlenen özelliklerini ortaya çıkarır: sırtının derin kavisi, göğsünün ileriye doğru büyük itişi, sanki kendisine doğru koşan şeyi şimdiden görmüşçesine sağ omzunun üzerine atılmış başı.",
      "Onun etrafında yavaşça dolaşın. Kompozisyonda dinlenme noktası yok. Her bir çizgi — kol, göğüs kafesi, uyluk — bir diğerine yaslanıyor. Rodin bir keresinde, figürlerinin yüzün ifade edemediğini bedenle ifade etmesini istediğini söylemişti. İşte karşınızda, cevapsız bir duaya dalmış beden."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Düşen Adam",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/l%E2%80%99homme-qui-tombe-%5Bthe-falling-man%5D"
      },
      {
        "label": "Vikipedi — Düşen Adam (Rodin)",
        "href": "https://en.wikipedia.org/wiki/The_Falling_Man_(Rodin)"
      },
      {
        "label": "Rodin Müzesi — Cehennem Kapısı: Düşen Adam",
        "href": "https://enfer.musee-rodin.fr/fr/figure/homme-qui-tombe"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), L'Homme Qui Tombe. A. Rodin imzalı. Üzerinde “© Musée Rodin 1973” ve “Susse Fondeurs, Paris” yazmaktadır. Envanter RCG0009.2-04",
    "meta": {
      "height": "58,5 cm",
      "materials": "Zengin koyu yeşil bir patineye ve kahverengi vurgular içeren bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "monumental-torso": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Anıtsal Torso",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1904'te tasarlanmış, 1970'te dökülmüştür.",
    "summary": "\"Düşen Adam\"dan alınmış, başsız ve kolsuz, büyütülmüş bir gövde — kurtarılmanın ve kaçmanın imkânsız olduğu bir noktaya kadar büyütülmüş bir parça.",
    "aboutParagraphs": [
      "1904 yılına gelindiğinde Rodin, yirmi yılını “Cehennem Kapıları” adlı dev kabartma üzerinde figürleri söküp takarak, onları yeni ölçeklerde işleyerek ve bu kalabalık içinde isimsiz kalmalarına izin vermeyerek geçirmişti. \"Anıtsal Torso\", bu kurtarılan eserlerden biridir. Eser, \"Düşen Adam\" ile başlar — Kapı'nın sol üst lentosunun üzerine yarı devrilmiş, kıvranan figür — ve tamamen kendine özgü bir varlık olarak son bulur: başı yok, kolları omuzlarından kesilmiş, bacakları uyluk ortasında bitiyor.",
      "Bu heykel, Rodin hayattayken hiçbir zaman kalıba dökülmedi. 1970 yılında Georges Rudier dökümhanesi, Rodin Müzesi’nin siparişi üzerine bu versiyonu, yüksekliği bir metreden biraz fazla olacak şekilde üretti. Gövde, Rodin’in parmağının her bir dokunuşunu koruyor. Göğsün gökyüzüne doğru açılma şekline, derinin altında kavis çizen kaburgalara, düşmeye başlamış olmasına rağmen hala gergin duran karın bölgesine bakın. Harekete yön verecek uzuvlar olmadan, vücut saf bir baskı haline gelir.",
      "Rodin, gençlik yıllarından beri, doğru seçilmiş bir parçanın tam bir figürden daha fazla gerçeği yansıtabileceğini savunmuştu. Bu eserin etrafında yavaşça dolaşın, bu iddia kendiliğinden ortaya çıkacaktır. Gözün durup bakabileceği hiçbir yer yok: Her açı, kas ve gölgelerin farklı bir dramını ortaya koyuyor ve hiçbiri bir sonuca varmıyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Büyük Erkek Büstü",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/grande-torse-de-l%E2%80%99homme-%5Bmonumental-torso%5D"
      },
      {
        "label": "Kuzey Carolina Sanat Müzesi — Yürüyen Adamın Anıtsal Torso'su",
        "href": "https://collection.ncartmuseum.org/objects/4746/monumental-torso-of-the-walking-man"
      },
      {
        "label": "Kamu Sanat Arşivi — Düşen Adamın Büyük Torso Heykeli",
        "href": "https://publicartarchive.org/art/Grand-Torse-de-L-homme-qui-Tombe/382dc281"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Grande Torse de l'Homme. Üzerinde “© Musée Rodin 1970” yazısı ve Georges Rudier Fondeur dökümhane işareti bulunmaktadır. Paris. Envanter RCG0008.2-14",
    "meta": {
      "height": "102 cm",
      "materials": "Zengin koyu kahverengi bir patineye sahip bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "eternal-spring-first-state": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Sonsuz Bahar, İlk Baskı",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1884'te tasarlanmış, 1969'da dökülmüştür.",
    "summary": "Rodin’in “Sonsuz Bahar” adlı eserinin ilk taslağı — bir kayanın üzerine geriye doğru eğilmiş, kucağına doğru eğilen bir kızı öpmeye çalışan genç bir adam. Çoğu sanatsever için, tüm versiyonların en güzeli.",
    "aboutParagraphs": [
      "Bir adam pürüzlü kayaya sırtını dayamış, bir kolunu yatay olarak uzatmış; bir kadın ise kucağına uzanmış, başını geriye atarak onun öpücüğüne karşılık veriyor. Vücutları, dokusu oldukça belirgin, engebeli bir zemin üzerinde beliriyor; koyu kahverengi-yeşil bir patina, huzursuz taşın üzerinde sevgililerin pürüzsüz tenini öne çıkarıyor.",
      "L'Éternel Printemps, 1884 yılında \"Öpücük\" ile birlikte tasarlandı; bu eser, Rodin onu bağımsız bir kompozisyon olarak yayınlamadan önce aslında \"Cehennem Kapıları\" için düşünülmüştü.",
      "Premier État'ı nadir ve değerli kılan şey, işlenmemiş haliyle kalmış olmasıdır. Bu en erken versiyonun sadece beş bronz dökümü bulunmaktadır: ikisi Alexis Rudier tarafından 1930 ile 1952 yılları arasında, diğer üçü ise Georges Rudier tarafından 1966 ile 1969 yılları arasında yapılmıştır. Musée Rodin'in sözleşme listesi bu örnekle sona ermektedir. Daha sonraki versiyonlarda Rodin ve işbirlikçileri kompozisyonu yumuşatmışlardır, ancak burada genç adam hala kayanın üzerine aşırı derecede geriye doğru eğilmiş ve kız hala onun üzerine atlamış durumdadır — dizleri açık, saçları dağınık, tüm vücudu kendini sunmaktadır.",
      "Yakından bakın. Sevgililerin yüzleri henüz tam olarak birleşmemiş. “Sonsuz Bahar”, Rodin’in ticari açıdan en başarılı romantizm simgelerinden biri haline geldi; ancak bu ilk versiyonda, sanki çift o sabah tanışmış gibi bir his uyandırıyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — L'Éternel Printemps, İlk Baskı",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/l%E2%80%99%C3%A9ternel-printemps%2C-premier-%C3%A9tat-%5Beternal-spring%2C-first-state%5D"
      },
      {
        "label": "Vikipedi — Ebedi Bahar",
        "href": "https://en.wikipedia.org/wiki/Eternal_Springtime"
      },
      {
        "label": "Basil &amp; Elise Goulandris Vakfı — L'Éternel Printemps",
        "href": "https://goulandris.gr/en/artwork/rodin-auguste-eternal-springtime"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), L'Éternel Printemps, Premier État. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde © Musée Rodin 1969 ve Georges Rudier Fondeur Paris ibareleri yer almaktadır. Envanter RCG0006.2-08",
    "meta": {
      "height": "51,4 cm",
      "materials": "Koyu kahverengi ve siyah patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "the-kiss-3rd-reduction": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Öpücük, 3. Küçültme",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1886 yılında tasarlanan bu eser, 1901 yılında küçültülmüş bir versiyonu olarak hazırlanmış ve 1910 ile 1918 yılları arasında bronzdan dökülmüştür.",
    "summary": "Rodin’in en ünlü kucaklaşma sahnesinin küçük ölçekli, oda tiyatrosu versiyonu — Dante’nin eserinde sonsuzluğu kaybetmelerine neden olacak öpüşüş anında yakalanan Paolo ve Francesca.",
    "aboutParagraphs": [
      "Oda ölçeğinde, bir adam kayanın üzerine oturmuş bir kadına doğru eğilmiş; kadının başı, adamın dudaklarına ulaşmak için yukarı doğru eğilmiş, adamın kolu kadının omzuna dolanmış, kadının kolu ise adamın boynuna sarılmış. Koyu, parlak patina kahverengi ve siyah tonlarda uzanırken, saçlarda ve omuz çukurlarında yeşil tonlar görülüyor. Kucaklaşma sıkı, sessiz ve neredeyse tamamen üst vücutla gerçekleşiyor.",
      "Çift, Dante’nin “Cehennem”inden Paolo ve Francesca da Rimini olarak “Cehennem Kapıları”nda yer almıştı; daha sonra Rodin onları buradan ayırarak bağımsız bir eser haline getirdi.",
      "\"Le Baiser\", bağımsız bir eser olarak 1887 yılında Brüksel'de alçıdan, aynı yılın ilerleyen aylarında ise Paris'te bronzdan sergilenmiştir. 1898'de Rodin, Barbedienne dökümhanesiyle on yıllık bir sözleşme imzalayarak 72 cm, 60 cm, 40 cm ve 25 cm olmak üzere dört farklı küçültülmüş ölçekte sınırsız sayıda döküm yapılmasını sağladı. 39,5 cm'lik 3ème Réduction, bu boyutların üçüncüsüne karşılık gelir ve 1910 ile 1918 yılları arasında oldukça fazla sayıda dökülmüştür.",
      "Bu sadeleştirmeden geriye kalan, hareketin sessizliğidir. Francesca, Paolo’ya doğru eğilir; dudakları birleşir; Dante’nin bahsettiği Paolo’nun kitabı, Francesca’nın kalçasının yanındaki kayanın üzerinde unutulmuş halde durmaktadır. Yakından bakarsanız, o anın nabzını okuyabilirsiniz. Bunun sonsuza dek sürmeyeceğini henüz bilmiyorlar."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Le Baiser, 3. İndirim",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/le-baiser%2C-3%C3%A8me-r%C3%A9duction-%5Bthe-kiss%2C-2nd-reduction%5D"
      },
      {
        "label": "Ulusal Sanat Galerisi — Öpücük (Le Baiser)",
        "href": "https://www.nga.gov/artworks/1008-kiss-le-baiser"
      },
      {
        "label": "Christie's — Öpücük, 3. baskı",
        "href": "https://www.christies.com/en/lot/lot-5839227"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Le Baiser, 3ème Réduction. A. Rodin imzalı. Üzerinde \"F. Barbedienne Fondeur\" yazısı bulunmaktadır. Envanter RCG0007.2-21",
    "meta": {
      "height": "39,5 cm",
      "materials": "Siyah ve kahverengi patine kaplı bronz, yeşil vurgularla",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "death-of-adonis": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Adonis'in Ölümü",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1885 ile 1887 yılları arasında tasarlanmış, 1956 yılında dökülmüştür.",
    "summary": "Yaban domuzu tarafından ölümcül şekilde yaralanan genç güzellik tanrısı Adonis, Afrodit’in bedeninin üzerinde yatıyor — Baudelaire’in şiirlerinden birinin kenarına çizilmiş bir eskizden doğan, özlü ve derinden hissedilen bir ağıt.",
    "aboutParagraphs": [
      "Heykel grubu büyük değil — neredeyse bir önkol kadar — ama Rodin ona bir mezarın ağırlığını yüklemiş. Adonis ölmüş. Yüzüstü, Afrodit’in bedeninin üzerinde yatıyor; Afrodit ise onun altında yarı diz çökmüş, yarı yere yığılmış halde, sanki onu yeniden ısıtabiliyormuş gibi Adonis’ten geriye kalanları kucaklıyor. İki beden o kadar sıkı bir şekilde birbirine sarılmış ki, bronz heykelin etrafında dolaşırken bazen bir figürün nerede bittiği, diğerinin nerede başladığı belli olmuyor.",
      "Rodin, bu kompozisyonun ilk taslağını 1887 yılında, yayıncı Paul Gallimard’ın resimlemesini istediği *Les Fleurs du Mal* kitabının içindeki Baudelaire’in *Le Poison* şiirinin kenar boşluğuna çizdi. Heykeli üç farklı şehirde üç farklı isimle sergiledi: Brüksel'de \"Venüs ve Adonis\", Londra'da \"Hero ve Leander\" ve son olarak \"Mort d'Adonis\" — her seferinde başka bir mitolojik ölümün adını alan aynı yas tutan sevgililer grubu.",
      "Adonis figürü aslında Cehennem Kapıları'ndan yeniden kullanılmış bir figürdür; orada kadın olarak, “İnsan ve Düşüncesi”nin bir parçası olarak üst eşikte yer almaktadır. Rodin, figürlerinin cinsiyetlerini ve hikâyelerini özgürce değiştirmeyi severdi; önemli olan duruşudur. Yakından bakın: sırtın kıvrımı, gevşek el, Afrodit'in yanağını onun omzuna dayama şekli. Arzunun kedere dönüştüğü tam o anı izliyorsunuz."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Adonis'in Ölümü",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/mort-d%27adonis-%5Bdeath-of-adonis%5D"
      },
      {
        "label": "Walters Sanat Müzesi — Adonis'in Ölümü",
        "href": "https://art.thewalters.org/object/27.491/"
      },
      {
        "label": "Christie's — Adonis'in Uyanışı (eşlik eden eser)",
        "href": "https://www.christies.com/en/lot/lot-3905784"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Mort d'Adonis. A. Rodin imzalı; iç kısmında kabartmalı imza tekrarlanmaktadır. Üzerinde © Musée Rodin 1956 ve Georges Rudier Fondeur Paris ibareleri bulunmaktadır. Envanter RCG0004.2-05",
    "meta": {
      "height": "27 cm",
      "materials": "Kahverengi ve koyu yeşil patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "jardiniere-of-the-titans": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Titanlar'ın Çiçeklik",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1877 civarında tasarlanmış, 1887'den önce dökülmüştür.",
    "summary": "Dört çabalayan çıplak figürün taşıdığı sade bir terrakotta kase — mat, sırsız; her yüzeyinde ellerin ve aletlerin izleri belirgin.",
    "aboutParagraphs": [
      "Dört kaslı erkek, ortadaki bir direğin etrafında çömelmiş durumda; omuzları ve yukarı kaldırılmış kollarıyla başlarının üzerinde sığ bir kaseyi tutuyorlar. Eser, açık bej renkli, sırsız terrakottadan yapılmış olup, figürlerin vücutlarında ve kasenin üzerinde parmak izleri ile alet izleri görülüyor. Figürler ile ortadaki sütun arasında kumaş kıvrımları uzanıyor. Bir adam başı eğik bir şekilde öne doğru eğilmiş; bir diğeri ise düz avucunu kaseye doğru uzatmış. Eserin tamamı, uzun ve koyu renkli ahşap bir kaide üzerinde duruyor.",
      "Rodin, bu figürleri 1877 civarında, saksıyı tasarlayan ve üzerine imzasını atan Albert Carrier-Belleuse için çalışırken şekillendirdi. Arkın'daki bu örnek, 39,1 santimetre yüksekliğinde, A. Carrier Belleuse imzalı bir terrakotta eserdir — Paris, Cleveland veya Detroit'teki çok renkli sırlı versiyonların aksine, sırsız bir kalıptır.",
      "Tabanın etrafında dolaştığınızda, her bir Titan farklı bir gerilim açısı sunuyor — geriye eğilmiş sırt, havaya kaldırılmış kol, öne eğilmiş baş. Çanak sade; tüm heyecan, onun altındaki bedenlerde yatıyor."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Titanlı Saksı",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/jardini%C3%A8re-aux-titans"
      },
      {
        "label": "Petit Palais — Titanlar Saksı",
        "href": "https://www.petitpalais.paris.fr/en/oeuvre/titans-jardiniere"
      },
      {
        "label": "Detroit Sanat Müzesi — Titanların Vazosu",
        "href": "https://dia.org/collection/vase-titans-94258"
      },
      {
        "label": "Philadelphia Sanat Müzesi — Titanların Vazosu",
        "href": "https://www.philamuseum.org/objects/346671"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Jardinière aux Titans. İmza: A. Carrier Belleuse. Envanter RCG0001.20-13",
    "meta": {
      "height": "39,1 cm",
      "materials": "Terrakotta",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  },
  "eternal-idol-small-model": {
    "aboutHeading": "Eser hakkında",
    "sourcesLabel": "Kaynaklar:",
    "exhibitionEyebrow": "Arkın Rodin Koleksiyonu — Heykel",
    "subtitle": "Sonsuz İdol, Küçük Model",
    "artist": "Auguste Rodin (Fransız, 1840–1917)",
    "caption": "1889'da tasarlanmış, 1927'de dökülmüştür.",
    "summary": "Bir adam, ellerini arkasında birleştirerek diz çökmüş ve ayakta duran bir kadının göğsüne dudaklarını bastırıyor — Rodin'in en yoğun hayranlık, güvensizlik ve tapınma temalı küçük grubu, Cehennem Kapıları henüz atölyesindeyken modellenmiştir.",
    "aboutParagraphs": [
      "Rodin bu grubu 1889'da, hala Cehennem Kapıları ile uğraşırken yaptı. Her iki figür de sağ kapıda ayrı ayrı başladı, daha sonra onları çıkarıp birbirine yapıştırdı. Adam diz çökmüş, elleri sanki bağlanmış gibi arkasında birleştirilmiş. Kadın onun üzerinde duruyor, bir bacağını yukarı kaldırmış, neredeyse ifadesiz bir yüzle aşağıya bakıyor. Adam, dua, teslimiyet ya da yüksek sesle söyleyemediği bir itiraf gibi görünen bir hareketle ağzını kadının göğsüne gömmüş.",
      "Rodin, hayatı boyunca bu esere üç farklı isim verdi. Komünyondaki ekmek parçasını çağrıştıran L'Hostie — Host — adını verdi. Le Sacrifice adını verdi. Sonunda L'Éternelle Idole adını seçti. Bu isimlerin ortak bir noktası var: Kadın ilahi, erkek ise ne kadar sefil olursa olsun, bir şekilde ibadet etme özgürlüğüne sahip.",
      "Bu 17 santimetrelik versiyonun ilk kalıbı, 1891'de koleksiyoncu Antoni Roux'ya gitti. Roux, Rodin'i eseri büyütmeye ikna etti ve 1893'te Jean Escoula tarafından mermerden bir heykel oyuldu. Ancak küçük bronz heykel, daha büyük versiyonların yumuşattığı bir şeyi koruyor. Kompozisyon kapalı ve yoğun, elinde tutulan bir nesnenin boyutunda. Kısa bir süre Rodin'in sekreteri olarak görev yapan romancı Rainer Maria Rilke, heykel hakkında şöyle demiştir: ‘Cennet yakındır, ama henüz ulaşılmamıştır; Cehennem yakındır, ama henüz unutulmamıştır.’ Adamın ellerine bakın. Tamamen bağlı değiller, ama tamamen özgür de değiller."
    ],
    "sources": [
      {
        "label": "Arkın Rodin Koleksiyonu — Éternelle Idole, Petit Modèle",
        "href": "https://www.thearkinrodincollection.com/our-exhibitions/%C3%A9ternelle-idole%2C-petit-modele-%5Beternal-idol%2C-small-model%5D-"
      },
      {
        "label": "Montreal Güzel Sanatlar Müzesi — The Eternal Idol",
        "href": "https://www.mbam.qc.ca/en/works/71552/"
      },
      {
        "label": "Christie's — Éternelle idole, grand modèle",
        "href": "https://www.christies.com/en/lot/lot-6414756"
      }
    ],
    "plateCaption": "Auguste Rodin (Fransız, 1840–1917), Éternelle Idole, Petit Modèle. A. Rodin imzalı. 1 numara ile numaralandırılmış ve Alexis Rudier Fondeur, Paris dökümhane damgası ile damgalanmış. Envanter RCG0003.20-05",
    "meta": {
      "height": "17,14 cm",
      "materials": "Siyah ve yeşil patine kaplı bronz",
      "location": "Arkın Saat Kulesi - Arkın Grubu Genel Merkezi"
    }
  }
}
