import type { TempleOfDendurCopy } from "./templeOfDendur"

/** Spanish copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const TEMPLE_OF_DENDUR_ES: TempleOfDendurCopy = {
  "banner": "Descubre cómo funciona esta experiencia",
  "eyebrow": "El Met de la Quinta Avenida · Arte egipcio · Sala 131",
  "eyebrowParts": [
    "El Met de la Quinta Avenida",
    "Arte egipcio",
    "Galería 131"
  ],
  "title": "El templo de Dendur",
  "subtitle": "Un templo nubio dedicado a Isis, donado por Egipto al pueblo estadounidense",
  "imageAlt": "El Templo de Dendur, reconstruido en la Galería 131 del Museo Metropolitano de Arte",
  "figcaption": "El templo y su puerta, reconstruidos junto a un estanque reflectante en el ala norte acristalada.",
  "credit": "Imagen: Museo Metropolitano de Arte, n.º de referencia 68.154",
  "facts": [
    {
      "k": "Fecha",
      "v": "terminada en el año 10 a. C."
    },
    {
      "k": "Reino",
      "v": "César Augusto"
    },
    {
      "k": "De",
      "v": "Dendur, Baja Nubia"
    },
    {
      "k": "Material",
      "v": "Arenisca eólica"
    },
    {
      "k": "Templo",
      "v": "6,4 × 6,4 × 12,5 m"
    },
    {
      "k": "Puerta",
      "v": "8,1 × 3,7 × 3,4 m"
    },
    {
      "k": "Adquirido",
      "v": "«Regalo de Egipto», 1965"
    },
    {
      "k": "En exposición desde",
      "v": "1978, Galería 131"
    }
  ],
  "lede": "El templo de Dendur es el único templo egipcio completo del hemisferio occidental. Construido en la orilla occidental del Nilo, en la Baja Nubia, alrededor del año 15 a. C., fue encargado por el primer emperador romano de Egipto, Augusto, y dedicado a la diosa Isis y a dos héroes locales —dos hermanos llamados Pediese y Pihor— que fueron venerados como semidioses tras ahogarse en el río.",
  "sections": [
    {
      "id": "political-temple",
      "heading": "Un templo político en una provincia romana",
      "paragraphs": [
        "Tras derrotar a Cleopatra VII y a Marco Antonio en el año 31 a. C., Augusto confiscó los bienes de los templos egipcios y centralizó su administración. Para facilitar el cambio de régimen, encargó al menos diecisiete proyectos de construcción dedicados a dioses regionales; el pequeño santuario de arenisca de Tutzis, conocido hoy como Dendur, fue uno de ellos. En sus paredes, Augusto aparece como faraón con las vestiduras tradicionales egipcias, realizando ofrendas a los dioses: una puesta en escena imperial dirigida a los súbditos nubios que aún practicaban el culto a la antigua usanza."
      ]
    },
    {
      "id": "reading-walls",
      "heading": "Leer entre líneas",
      "paragraphs": [
        "Los templos egipcios se interpretaban como representaciones del mundo natural: el santuario era el montículo primigenio, las columnas, los juncos y los lotos de los pantanos del Nilo, y el techo, el cielo. La decoración de Dendur sigue ese esquema casi como si se tratara de una cosmología ilustrada."
      ],
      "motifs": [
        {
          "label": "Base del templo",
          "text": "El papiro y las plantas de loto parecen brotar del agua, representada por las figuras de Hapy, dios de la crecida del Nilo."
        },
        {
          "label": "Columnas del porche",
          "text": "Se alzan como altos manojos de tallos de papiro atados con flores de loto."
        },
        {
          "label": "Dintel de la puerta",
          "text": "Un disco solar flanqueado por las alas extendidas de Horus, el dios del cielo."
        },
        {
          "label": "Techo del porche",
          "text": "Los buitres con las alas extendidas simbolizan la bóveda celeste."
        },
        {
          "label": "Paredes exteriores",
          "text": "Dos registros horizontales de relieve hundido muestran al rey haciendo ofrendas a unas deidades que sostienen cetros y el ankh, el símbolo de la vida."
        },
        {
          "label": "Pared trasera del santuario",
          "text": "En Pihor se rinde culto a Isis; más abajo, en Pediese —actualmente en mal estado—, se rinde culto a Osiris. Este es el corazón ritual del edificio."
        }
      ],
      "afterNote": "Fíjate en los cartuchos que hay junto a la cabeza del rey. En muchos de ellos solo figura la inscripción «faraón», en lugar de un nombre propio: una forma de abreviar que los albañiles de la época romana podían reutilizar independientemente de quién ocupara el trono."
    },
    {
      "id": "rescued-from-nile",
      "heading": "Rescatado del Nilo",
      "paragraphs": [
        "Cuando Egipto comenzó a construir la Gran Presa de Asuán en la década de 1960, se preveía que un enorme lago artificial —el lago Nasser— acabaría sumergiendo decenas de monumentos antiguos. La UNESCO lideró una operación internacional de rescate y Estados Unidos aportó fondos sustanciales. En señal de agradecimiento, Egipto regaló cuatro de los monumentos rescatados a los países que habían colaborado; el Templo de Dendur fue donado al pueblo estadounidense en 1965 y, tras un concurso nacional, se le adjudicó al Museo Metropolitano en 1967.",
        "El templo llegó en unas 640 cajas que pesaban más de 800 toneladas. Se volvió a montar bloque a bloque en el interior del ala norte, construida expresamente para ello, que se inauguró en 1978. La pared norte acristalada da a un estanque reflectante que simula el Nilo, y la luz cambia a lo largo del día de forma muy similar a como lo hacía antaño en Dendur."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Fijándonos bien",
      "paragraphs": [
        "Acércate primero por la puerta, para entrar en el templo tal y como lo habría hecho un devoto de la antigüedad. En el interior, atravesarás tres espacios de santidad creciente: un pronaos con dos columnas; una sala de ofrendas cuyos relieves están tallados en relieve elevado, en lugar de en relieve hundido; y, al fondo, el pequeño santuario de Isis. En el exterior, busca los grafitis griegos y coptos: nombres de peregrinos grabados en la piedra a lo largo de casi dos milenios, incluida una dedicatoria en demótico de un viajero del siglo XIX. Ahora forman parte de la historia del lugar."
      ],
      "visitLabel": "Encontrarlo.",
      "visitBody": "La Galería 131, situada en la planta baja, en el extremo norte del museo. Entra por el Gran Salón, recorre las galerías egipcias en orden cronológico (Antiguo Imperio → Imperio Medio → Imperio Nuevo → Período Tardío → Época Ptolemaica) y Dendur es el punto culminante. Calcula unos veinte minutos; más si la luz es buena."
    }
  ],
  "colophonLeft": "El Museo Metropolitano de Arte · 1000 Fifth Avenue, Nueva York",
  "colophonRight": "N.º de objeto 68.154 · Arte egipcio"
}
