import type { TempleOfDendurCopy } from "./templeOfDendur"

/** Portuguese copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const TEMPLE_OF_DENDUR_PT: TempleOfDendurCopy = {
  "banner": "Saiba como funciona essa experiência",
  "eyebrow": "The Met Fifth Avenue · Arte Egípcia · Galeria 131",
  "eyebrowParts": [
    "The Met Fifth Avenue",
    "Arte egípcia",
    "Galeria 131"
  ],
  "title": "O Templo de Dendur",
  "subtitle": "Um templo núbio dedicado a Ísis, doado pelo Egito ao povo americano",
  "imageAlt": "O Templo de Dendur, remontado na Galeria 131 do Museu Metropolitano de Arte",
  "figcaption": "O templo e seu portão, remontados ao lado de um espelho d’água na ala norte envidraçada.",
  "credit": "Imagem: Museu Metropolitano de Arte, nº de acervo 68.154",
  "facts": [
    {
      "k": "Data",
      "v": "concluída em 10 a.C."
    },
    {
      "k": "Reinado",
      "v": "César Augusto"
    },
    {
      "k": "De",
      "v": "Dendur, Baixa Núbia"
    },
    {
      "k": "Material",
      "v": "Arenito eólico"
    },
    {
      "k": "Templo",
      "v": "6,4 × 6,4 × 12,5 m"
    },
    {
      "k": "Portão",
      "v": "8,1 × 3,7 × 3,4 m"
    },
    {
      "k": "Adquirido",
      "v": "Presente do Egito, 1965"
    },
    {
      "k": "Em exibição desde",
      "v": "1978, Galeria 131"
    }
  ],
  "lede": "O Templo de Dendur é o único templo egípcio completo no Hemisfério Ocidental. Construído na margem oeste do Nilo, na Baixa Núbia, por volta de 15 a.C., foi encomendado pelo primeiro imperador romano do Egito, Augusto, e dedicado à deusa Ísis e a dois heróis locais — os irmãos Pediese e Pihor — que passaram a ser reverenciados como semideuses após se afogarem no rio.",
  "sections": [
    {
      "id": "political-temple",
      "heading": "Um templo político em uma província romana",
      "paragraphs": [
        "Depois que Augusto derrotou Cleópatra VII e Marco Antônio em 31 a.C., ele confiscou os bens dos templos do Egito e centralizou sua administração. Para facilitar a transição de regime, ele encomendou pelo menos dezessete projetos de construção dedicados a deuses regionais; o pequeno santuário de arenito em Tutzis, hoje conhecido como Dendur, foi um deles. Em suas paredes, Augusto aparece como faraó com as vestes tradicionais egípcias, fazendo oferendas aos deuses — uma encenação imperial destinada aos súditos núbios que ainda praticavam o culto à maneira antiga."
      ]
    },
    {
      "id": "reading-walls",
      "heading": "Interpretando as mensagens nas paredes",
      "paragraphs": [
        "Os templos egípcios eram interpretados como representações do mundo natural: o santuário era o monte primitivo, as colunas eram os juncos e as flores de lótus dos pântanos do Nilo, e o teto era o céu. A decoração de Dendur segue esse conceito quase como uma cosmologia ilustrada."
      ],
      "motifs": [
        {
          "label": "Base do templo",
          "text": "O papiro e as plantas de lótus parecem brotar da água, representada pelas figuras de Hapy, deus da cheia do Nilo."
        },
        {
          "label": "Colunas da varanda",
          "text": "Erguem-se como altos feixes de talos de papiro amarrados com flores de lótus."
        },
        {
          "label": "Viga do portão",
          "text": "Um disco solar ladeado pelas asas abertas de Hórus, o deus do céu."
        },
        {
          "label": "Teto da varanda",
          "text": "Os abutres com as asas abertas simbolizam a abóbada celeste."
        },
        {
          "label": "Paredes externas",
          "text": "Dois registros horizontais em relevo recuado mostram o rei fazendo oferendas às divindades, que seguram cetros e o ankh, o símbolo da vida."
        },
        {
          "label": "Parede traseira do santuário",
          "text": "Pihor é dedicado a Ísis; abaixo, Pediese — hoje em ruínas — é dedicado a Osíris. Este é o coração ritualístico do edifício."
        }
      ],
      "afterNote": "Observe os cartuchos ao lado da cabeça do rei. Muitos trazem simplesmente a inscrição “faraó”, em vez de um nome próprio — um atalho que os pedreiros da era romana podiam reutilizar independentemente de quem ocupasse o trono."
    },
    {
      "id": "rescued-from-nile",
      "heading": "Resgatado do Nilo",
      "paragraphs": [
        "Quando o Egito começou a construir a Barragem Alta de Assuã na década de 1960, um vasto lago artificial — o Lago Nasser — estava prestes a engolir dezenas de monumentos antigos. A UNESCO liderou uma operação internacional de resgate, e os Estados Unidos contribuíram com fundos substanciais. Em sinal de gratidão, o Egito presenteou quatro dos monumentos resgatados aos países que haviam ajudado; o Templo de Dendur foi doado ao povo americano em 1965 e concedido ao Museu Metropolitano em 1967, após um concurso nacional.",
        "O templo chegou em cerca de 640 caixotes, pesando mais de 800 toneladas. Foi remontado bloco por bloco dentro da ala norte, construída especificamente para esse fim, que foi inaugurada em 1978. A parede norte envidraçada dá de frente para um espelho d’água que representa o Nilo, e a luz muda ao longo do dia da mesma forma que costumava fazer em Dendur."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Olhando com atenção",
      "paragraphs": [
        "Aproxime-se primeiro pelo portão, para entrar no templo como um fiel da antiguidade faria. No interior, você atravessa três espaços de santidade crescente: um pronaos com duas colunas; uma sala de oferendas cujos relevos são esculpidos em relevo saliente, e não em relevo côncavo; e, ao fundo, o pequeno santuário de Ísis. No exterior, procure grafites gregos e coptas — nomes de peregrinos gravados na pedra ao longo de quase dois milênios, incluindo uma dedicatória em demótico feita por um viajante do século XIX. Eles agora fazem parte da história do local."
      ],
      "visitLabel": "Encontrando isso.",
      "visitBody": "Galeria 131, no térreo, na extremidade norte do museu. Entre pelo Grande Salão, percorra as galerias egípcias em ordem cronológica (Antigo Império → Império Médio → Império Novo → Período Tardio → Período Ptolomaico) e a estátua de Dendur será o ponto alto da visita. Reserve vinte minutos; um pouco mais se a iluminação estiver boa."
    }
  ],
  "colophonLeft": "Museu Metropolitano de Arte · 1000 Fifth Avenue, Nova York",
  "colophonRight": "Objeto nº 68.154 · Arte egípcia"
}
