import type { TempleOfDendurCopy } from "./templeOfDendur"

/** Italian copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const TEMPLE_OF_DENDUR_IT: TempleOfDendurCopy = {
  "banner": "Scopri come funziona questa esperienza",
  "eyebrow": "Il Met sulla Fifth Avenue · Arte egizia · Sala 131",
  "eyebrowParts": [
    "Il Met sulla Fifth Avenue",
    "Arte egizia",
    "Galleria 131"
  ],
  "title": "Il Tempio di Dendur",
  "subtitle": "Un tempio nubiano dedicato a Iside, donato dall’Egitto al popolo americano",
  "imageAlt": "Il Tempio di Dendur, ricostruito nella Galleria 131 del Metropolitan Museum of Art",
  "figcaption": "Il tempio e il suo portone, ricostruiti accanto a uno specchio d’acqua nell’ala nord vetrata.",
  "credit": "Immagine: The Metropolitan Museum of Art, n. di inventario 68.154",
  "facts": [
    {
      "k": "Data",
      "v": "completato nel 10 a.C."
    },
    {
      "k": "Regno",
      "v": "Cesare Augusto"
    },
    {
      "k": "Da",
      "v": "Dendur, Bassa Nubia"
    },
    {
      "k": "Materiale",
      "v": "Arenaria eolica"
    },
    {
      "k": "Tempio",
      "v": "6,4 × 6,4 × 12,5 m"
    },
    {
      "k": "Cancello",
      "v": "8,1 × 3,7 × 3,4 m"
    },
    {
      "k": "Acquisito",
      "v": "Dono dell’Egitto, 1965"
    },
    {
      "k": "In mostra dal",
      "v": "1978, Galleria 131"
    }
  ],
  "lede": "Il Tempio di Dendur è l’unico tempio egizio completo presente nell’emisfero occidentale. Costruito sulla riva occidentale del Nilo nella Bassa Nubia intorno al 15 a.C., fu commissionato dal primo imperatore romano d'Egitto, Augusto, e dedicato alla dea Iside e a due eroi locali — i fratelli Pediese e Pihor — che furono venerati come semidei dopo essere annegati nel fiume.",
  "sections": [
    {
      "id": "political-temple",
      "heading": "Un tempio politico in una provincia romana",
      "paragraphs": [
        "Dopo aver sconfitto Cleopatra VII e Marco Antonio nel 31 a.C., Augusto confiscò i beni dei templi egizi e ne centralizzò l’amministrazione. Per facilitare il cambio di regime, commissionò almeno diciassette progetti edilizi dedicati alle divinità regionali; il piccolo santuario in arenaria di Tutzis, oggi noto come Dendur, era uno di questi. Sulle sue pareti Augusto appare come faraone nei tradizionali abiti regali egizi, mentre offre doni agli dei: una rappresentazione imperiale rivolta ai sudditi nubiani che continuavano a praticare il culto secondo le antiche usanze."
      ]
    },
    {
      "id": "reading-walls",
      "heading": "Leggere le pareti",
      "paragraphs": [
        "I templi egizi erano interpretati come rappresentazioni del mondo naturale: il santuario era il tumulo primordiale, le colonne le canne e i fiori di loto delle paludi del Nilo, il soffitto il cielo. La decorazione di Dendur segue tale schema quasi come una cosmologia illustrata."
      ],
      "motifs": [
        {
          "label": "Base del tempio",
          "text": "Il papiro e le piante di loto sembrano spuntare dall’acqua, rappresentata dalle figure di Hapy, dio della piena del Nilo."
        },
        {
          "label": "Colonne del portico",
          "text": "Si ergono come alti fasci di steli di papiro legati con fiori di loto."
        },
        {
          "label": "Architrave del cancello",
          "text": "Un disco solare affiancato dalle ali spiegate di Horus, il dio del cielo."
        },
        {
          "label": "Soffitto del portico",
          "text": "Gli avvoltoi con le ali spiegate simboleggiano la volta celeste."
        },
        {
          "label": "Pareti esterne",
          "text": "Due registri orizzontali a rilievo incassato raffigurano il re mentre offre doni alle divinità che impugnano scettri e l’ankh, il simbolo della vita."
        },
        {
          "label": "Parete posteriore del santuario",
          "text": "A Pihor si venera Iside; più in basso, a Pediese — oggi in stato di degrado — si venera Osiride. Questo è il cuore rituale dell’edificio."
        }
      ],
      "afterNote": "Cercate i cartigli accanto alla testa del re. Molti recano semplicemente la scritta “faraone” anziché un nome proprio: una soluzione che i muratori dell’epoca romana potevano riutilizzare indipendentemente da chi occupasse il trono."
    },
    {
      "id": "rescued-from-nile",
      "heading": "Salvato dal Nilo",
      "paragraphs": [
        "Quando l’Egitto iniziò a costruire la Grande Diga di Assuan negli anni ’60, un vasto lago artificiale — il Lago Nasser — stava per sommergere decine di monumenti antichi. L’UNESCO guidò un’operazione internazionale di salvataggio e gli Stati Uniti contribuirono con ingenti fondi. In segno di gratitudine, l’Egitto donò quattro dei monumenti salvati ai paesi che avevano prestato aiuto; il Tempio di Dendur fu donato al popolo americano nel 1965 e assegnato al Metropolitan Museum nel 1967 a seguito di un concorso nazionale.",
        "Il tempio è giunto in circa 640 casse per un peso complessivo di oltre 800 tonnellate. È stato ricostruito blocco per blocco all’interno dell’ala nord, realizzata appositamente a tale scopo e inaugurata nel 1978. La parete nord, rivestita di vetro, si affaccia su uno specchio d’acqua che simboleggia il Nilo, e la luce cambia nel corso della giornata proprio come un tempo a Dendur."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Osservando attentamente",
      "paragraphs": [
        "Avvicinatevi prima dal portone, in modo da entrare nel tempio come avrebbe fatto un antico fedele. All’interno attraverserete tre spazi di santità crescente: un pronao con due colonne; una sala delle offerte i cui rilievi sono scolpiti in rilievo piuttosto che in bassorilievo; e, in fondo, il piccolo santuario di Iside. All’esterno, cercate i graffiti greci e copti: nomi di pellegrini incisi nella pietra nel corso di quasi due millenni, tra cui una dedica in demotico lasciata da un viaggiatore del XIX secolo. Ormai fanno parte della storia di questo luogo."
      ],
      "visitLabel": "Trovarlo.",
      "visitBody": "Galleria 131, al piano terra, all’estremità nord del Museo. Entrate dalla Sala Grande, percorrete le gallerie egizie in ordine cronologico (Antico Regno → Medio Regno → Nuovo Regno → Periodo Tardo → Periodo tolemaico) e la statua di Dendur rappresenta il culmine del percorso. Prevedete una ventina di minuti; di più se la luce è buona."
    }
  ],
  "colophonLeft": "Il Metropolitan Museum of Art · 1000 Fifth Avenue, New York",
  "colophonRight": "N. 68.154 · Arte egizia"
}
