import type { TempleOfDendurCopy } from "./templeOfDendur"

/** Turkish copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const TEMPLE_OF_DENDUR_TR: TempleOfDendurCopy = {
  "banner": "Bu deneyimin nasıl işlediğini öğrenin",
  "eyebrow": "Met Fifth Avenue · Mısır Sanatı · Galeri 131",
  "eyebrowParts": [
    "The Met Fifth Avenue",
    "Mısır Sanatı",
    "Galeri 131"
  ],
  "title": "Dendur Tapınağı",
  "subtitle": "Mısır tarafından Amerikan halkına hediye edilen, İsis’e adanmış bir Nubya tapınağı",
  "imageAlt": "Metropolitan Sanat Müzesi’nin 131 numaralı galerisinde yeniden bir araya getirilen Dendur Tapınağı",
  "figcaption": "Tapınak ve kapısı, camla kaplı kuzey kanadındaki yansıtıcı havuzun yanında yeniden bir araya getirildi.",
  "credit": "Resim: Metropolitan Sanat Müzesi, Eser No. 68.154",
  "facts": [
    {
      "k": "Tarih",
      "v": "MÖ 10 yılına kadar tamamlandı"
    },
    {
      "k": "Hükümdarlık",
      "v": "Sezar Augustus"
    },
    {
      "k": "Kaynak:",
      "v": "Dendur, Aşağı Nubia"
    },
    {
      "k": "Malzeme",
      "v": "Eol kumtaşı"
    },
    {
      "k": "Tapınak",
      "v": "6,4 × 6,4 × 12,5 m"
    },
    {
      "k": "Kapı",
      "v": "8,1 × 3,7 × 3,4 m"
    },
    {
      "k": "Satın alındı",
      "v": "Mısır'dan Bir Hediye, 1965"
    },
    {
      "k": "Sergilenmeye başlandığı tarih:",
      "v": "1978, Galeri 131"
    }
  ],
  "lede": "Dendur Tapınağı, Batı Yarımküre’deki tek eksiksiz Mısır tapınağıdır. MÖ 15 civarında Aşağı Nubia'da Nil'in batı yakasında inşa edilen tapınak, Mısır'ın ilk Roma imparatoru Augustus tarafından yaptırılmış ve tanrıça İsis ile nehirde boğulduktan sonra yarı tanrı olarak saygı gören iki yerel kahraman — Pediese ve Pihor adlı kardeşler — adanmıştır.",
  "sections": [
    {
      "id": "political-temple",
      "heading": "Bir Roma eyaletindeki siyasi tapınak",
      "paragraphs": [
        "MÖ 31 yılında Kleopatra VII ve Mark Antony’yi mağlup ettikten sonra Augustus, Mısır tapınaklarının mallarına el koydu ve bunların idaresini merkezileştirdi. Rejim değişikliğini sorunsuz hale getirmek amacıyla bölgesel tanrılar için en az on yedi inşaat projesini başlatmıştı; Tutzis’te bulunan ve günümüzde Dendur olarak bilinen küçük kumtaşı tapınak da bunlardan biriydi. Tapınağın duvarlarında Augustus, geleneksel Mısır kraliyet kıyafetleri içinde firavun olarak tasvir edilmiş ve tanrılara adaklar sunarken resmedilmiştir — bu, hâlâ eski geleneklere göre ibadet eden Nubyalı tebaaya yönelik bir imparatorluk tiyatrosu niteliğindeydi."
      ]
    },
    {
      "id": "reading-walls",
      "heading": "Duvarlardan okuma",
      "paragraphs": [
        "Mısır tapınakları, doğa dünyasının simgeleri olarak algılanırdı: kutsal alan ilkel bir höyük, sütunlar Nil bataklıklarının sazlıklarını ve nilüferlerini, tavan ise gökyüzünü temsil ediyordu. Dendur’daki süslemeler, bu yaklaşımı adeta resimli bir kozmoloji gibi yansıtmaktadır."
      ],
      "motifs": [
        {
          "label": "Tapınağın kaidesi",
          "text": "Papirüs ve lotus bitkileri, Nil nehrinin taşkınlarının tanrısı Hapy’nin figürleriyle temsil edilen sudan filizleniyor gibi görünmektedir."
        },
        {
          "label": "Veranda sütunları",
          "text": "Lotus çiçekleriyle bağlanmış uzun papirüs sapı demetleri gibi yüksel."
        },
        {
          "label": "Kapı üst eşiği",
          "text": "Gök tanrısı Horus’un iki yana açılmış kanatlarıyla çevrelenmiş bir güneş diski."
        },
        {
          "label": "Veranda tavanı",
          "text": "Kanatlarını açmış akbabalar, gök kubbesini simgeliyor."
        },
        {
          "label": "Dış duvarlar",
          "text": "İki yatay sıraya yerleştirilmiş çukur kabartma, kralın asalarını ve yaşam sembolü olan ankh'ı tutan tanrılara adak sunduğunu göstermektedir."
        },
        {
          "label": "Sığınak arka duvarı",
          "text": "Pihor, İsis’e tapınır; aşağıda ise — günümüzde hasar görmüş olan — Pediese, Osiris’e tapınır. Burası, yapının ritüel merkezidir."
        }
      ],
      "afterNote": "Kralın başının yanındaki kartuşlara dikkat edin. Birçoğunda kişisel bir isim yerine sadece “firavun” yazmaktadır — bu, Roma dönemindeki taş ustalarının tahtta kim oturursa otursun yeniden kullanabilecekleri bir kısayoldu."
    },
    {
      "id": "rescued-from-nile",
      "heading": "Nil Nehri’nden kurtarıldı",
      "paragraphs": [
        "1960’larda Mısır, Asvan Yüksek Barajı’nın inşasına başladığında, devasa bir yapay göl — Nasır Gölü — düzinelerce antik anıtı yutmak üzereydi. UNESCO, uluslararası bir kurtarma çalışmasına öncülük etti ve ABD bu çalışmaya önemli miktarda fon sağladı. Mısır, minnettarlığını göstermek amacıyla kurtarılan anıtlardan dördünü yardım eden ülkelere hediye etti; Dendur Tapınağı 1965 yılında Amerikan halkına bağışlandı ve 1967 yılında ulusal bir yarışmanın ardından Metropolitan Müzesi’ne verildi.",
        "Tapınak, 800 metrik tondan fazla ağırlığa sahip yaklaşık 640 sandık halinde getirildi. Tapınak, 1978 yılında açılan ve bu amaçla inşa edilen kuzey kanadının içinde blok blok yeniden birleştirildi. Camla kaplı kuzey duvarı, Nil Nehri'ni simgeleyen yansıtıcı bir havuza bakmaktadır ve gün boyunca ışık, tıpkı bir zamanlar Dendur'da olduğu gibi değişmektedir."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Yakından bakıldığında",
      "paragraphs": [
        "Önce kapıdan yaklaşın; böylece tapınağa tıpkı eski zamanlardaki bir ibadetçinin yapacağı gibi girmiş olursunuz. İçeride, kutsallığı giderek artan üç mekândan geçersiniz: iki sütunlu bir pronaos; kabartmalarının çukur değil, yükseltilmiş olarak oyulduğu bir adak odası; ve en arkada, İsis’in küçük kutsal alanı. Dış cephede Yunan ve Kıpti grafitilerini arayın — neredeyse iki bin yıl boyunca taşa kazınmış hacıların isimleri, aralarında on dokuzuncu yüzyıldan bir gezginin demotik dilde yazdığı adak yazısı da bulunmaktadır. Bunlar artık bu eserin tarihinin bir parçasıdır."
      ],
      "visitLabel": "Bunu bulmak.",
      "visitBody": "Müzenin kuzey ucundaki zemin katta yer alan 131 numaralı galeri. Büyük Salon’dan girin, Mısır galerilerini kronolojik sırayla (Eski Krallık → Orta → Yeni → Geç Dönem → Ptolemaik) gezip Dendur’u son olarak ziyaret edin. Yirmi dakika ayırın; ışık koşulları uygunsa daha fazla zaman ayırabilirsiniz."
    }
  ],
  "colophonLeft": "Metropolitan Sanat Müzesi · 1000 Fifth Avenue, New York",
  "colophonRight": "Esin No. 68.154 · Mısır Sanatı"
}
