import type { TempleOfDendurCopy } from "./templeOfDendur"

/** German copy — generated by scripts/translate-essay-artwork.mjs (review before publishing). */
export const TEMPLE_OF_DENDUR_DE: TempleOfDendurCopy = {
  "banner": "Erfahren Sie, wie dieses Erlebnis funktioniert",
  "eyebrow": "The Met Fifth Avenue · Ägyptische Kunst · Galerie 131",
  "eyebrowParts": [
    "Das Met an der Fifth Avenue",
    "Ägyptische Kunst",
    "Galerie 131"
  ],
  "title": "Der Tempel von Dendur",
  "subtitle": "Ein nubischer Isis-Tempel, eine Schenkung Ägyptens an das amerikanische Volk",
  "imageAlt": "Der Tempel von Dendur, der in Galerie 131 des Metropolitan Museum of Art wieder aufgebaut wurde",
  "figcaption": "Der Tempel und sein Tor, die neben einem Spiegelteich im verglasten Nordflügel wieder aufgebaut wurden.",
  "credit": "Bild: The Metropolitan Museum of Art, Objektsignatur 68.154",
  "facts": [
    {
      "k": "Datum",
      "v": "fertiggestellt um 10 v. Chr."
    },
    {
      "k": "Regierungszeit",
      "v": "Caesar Augustus"
    },
    {
      "k": "Von",
      "v": "Dendur, Unter-Nubien"
    },
    {
      "k": "Material",
      "v": "Äolischer Sandstein"
    },
    {
      "k": "Tempel",
      "v": "6,4 × 6,4 × 12,5 m"
    },
    {
      "k": "Tor",
      "v": "8,1 × 3,7 × 3,4 m"
    },
    {
      "k": "Erworben",
      "v": "„Gift of Egypt“, 1965"
    },
    {
      "k": "Zu sehen seit",
      "v": "1978, Galerie 131"
    }
  ],
  "lede": "Der Tempel von Dendur ist der einzige vollständig erhaltene ägyptische Tempel auf der westlichen Hemisphäre. Er wurde um 15 v. Chr. am Westufer des Nils in Unter-Nubien erbaut, im Auftrag des ersten römischen Kaisers von Ägypten, Augustus, und der Göttin Isis sowie zwei lokalen Helden gewidmet – den Brüdern Pediese und Pihor –, die nach ihrem Ertrinken im Fluss als Halbgötter verehrt wurden.",
  "sections": [
    {
      "id": "political-temple",
      "heading": "Ein politischer Tempel in einer römischen Provinz",
      "paragraphs": [
        "Nachdem Augustus im Jahr 31 v. Chr. Kleopatra VII. und Marcus Antonius besiegt hatte, beschlagnahmte er den Besitz der ägyptischen Tempel und zentralisierte deren Verwaltung. Um den Regimewechsel reibungslos zu gestalten, gab er mindestens siebzehn Bauprojekte für regionale Gottheiten in Auftrag; der kleine Sandsteinschrein in Tutzis, heute bekannt als Dendur, war einer davon. An dessen Wänden erscheint Augustus als Pharao in traditioneller ägyptischer Insignien, der den Göttern Opfer darbringt – ein Stück kaiserliches Theater, das sich an die nubischen Untertanen richtete, die noch nach alter Sitte verehrten."
      ]
    },
    {
      "id": "reading-walls",
      "heading": "Die Wände lesen",
      "paragraphs": [
        "Ägyptische Tempel wurden als Abbilder der Natur verstanden: Der Tempelraum war der Urhügel, die Säulen das Schilf und die Lotusblumen der Nilsümpfe, die Decke der Himmel. Die Verzierungen von Dendur folgen diesem Konzept fast wie eine illustrierte Kosmologie."
      ],
      "motifs": [
        {
          "label": "Sockel des Tempels",
          "text": "Papyrus- und Lotuspflanzen scheinen aus dem Wasser zu wachsen, das durch Figuren von Hapy, dem Gott der Nilflut, dargestellt wird."
        },
        {
          "label": "Verandasäulen",
          "text": "Erhebe dich wie hohe Bündel aus Papyrusstängeln, die mit Lotusblüten zusammengebunden sind."
        },
        {
          "label": "Torbalken",
          "text": "Eine Sonnenscheibe, flankiert von den ausgebreiteten Flügeln des Himmelsgottes Horus."
        },
        {
          "label": "Verandadecke",
          "text": "Geier mit ausgebreiteten Flügeln symbolisieren das Himmelsgewölbe."
        },
        {
          "label": "Außenwände",
          "text": "Zwei horizontale Register mit vertieften Reliefs zeigen den König bei Opfergaben an Gottheiten, die Zepter und das Ankh, das Zeichen des Lebens, in den Händen halten."
        },
        {
          "label": "Rückwand des Altarraums",
          "text": "In Pihor wird Isis verehrt; darunter, in Pediese – das mittlerweile beschädigt ist –, wird Osiris verehrt. Dies ist das rituelle Herzstück des Gebäudes."
        }
      ],
      "afterNote": "Achten Sie auf die Kartuschen neben dem Kopf des Königs. Auf vielen steht lediglich „Pharao“ statt eines persönlichen Namens – eine Abkürzung, die die Steinmetze der römischen Zeit immer wieder verwenden konnten, ganz gleich, wer gerade auf dem Thron saß."
    },
    {
      "id": "rescued-from-nile",
      "heading": "Aus dem Nil gerettet",
      "paragraphs": [
        "Als Ägypten in den 1960er Jahren mit dem Bau des Assuan-Staudamms begann, drohte ein riesiger Stausee – der Nassersee – Dutzende antiker Denkmäler zu verschlingen. Die UNESCO leitete eine internationale Rettungsaktion, und die Vereinigten Staaten stellten erhebliche Mittel zur Verfügung. Aus Dankbarkeit schenkte Ägypten vier der geretteten Denkmäler an Länder, die geholfen hatten; der Tempel von Dendur wurde 1965 dem amerikanischen Volk übergeben und 1967 nach einem nationalen Wettbewerb dem Metropolitan Museum zugesprochen.",
        "Der Tempel wurde in rund 640 Kisten mit einem Gesamtgewicht von über 800 Tonnen angeliefert. Er wurde Stein für Stein im eigens dafür errichteten Nordflügel, der 1978 eröffnet wurde, wieder zusammengebaut. Die verglaste Nordwand blickt auf ein Spiegelbecken, das den Nil symbolisiert, und das Licht verändert sich im Laufe des Tages ähnlich wie einst in Dendur."
      ]
    },
    {
      "id": "looking-closely",
      "heading": "Genau hinschauen",
      "paragraphs": [
        "Nähern Sie sich zunächst vom Tor aus, damit Sie den Tempel so betreten, wie es ein Gläubiger in der Antike getan hätte. Im Inneren durchqueren Sie drei Räume mit zunehmender Heiligkeit: einen Pronaos mit zwei Säulen; einen Opferraum, dessen Reliefs als Hochreliefs und nicht als Flachreliefs gemeißelt sind; und ganz hinten das kleine Heiligtum der Isis. Achten Sie an der Außenseite auf griechische und koptische Graffiti – Namen von Pilgern, die über fast zwei Jahrtausende hinweg in den Stein geritzt wurden, darunter eine Widmung in demotischer Schrift von einem Reisenden aus dem 19. Jahrhundert. Sie sind nun Teil der Geschichte dieses Objekts."
      ],
      "visitLabel": "Es finden.",
      "visitBody": "Galerie 131, im Erdgeschoss am nördlichen Ende des Museums. Betreten Sie die Galerie von der Großen Halle aus und durchschreiten Sie die ägyptischen Ausstellungsräume in chronologischer Reihenfolge (Altes Reich → Mittlere Zeit → Neues Reich → Spätzeit → Ptolemäerzeit) – Dendur bildet den Höhepunkt. Planen Sie zwanzig Minuten ein; bei gutem Licht auch etwas mehr."
    }
  ],
  "colophonLeft": "Das Metropolitan Museum of Art · 1000 Fifth Avenue, New York",
  "colophonRight": "Objekt-Nr. 68.154 · Ägyptische Kunst"
}
