#!/usr/bin/env node
/**
 * Translate Hoa Hakananaiʻa page copy EN → FR / JA via DeepL API.
 *
 * Usage:
 *   node scripts/translate-hoa.mjs
 *   node scripts/translate-hoa.mjs --lang fr
 *   node scripts/translate-hoa.mjs --dry-run
 *
 * Requires DEEPL_API_KEY in .env.local (museum or arkin_museum).
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { countCharacters, getDeepLUsage, translateTexts } from "./lib/deepl.mjs"
import { loadEnvLocal } from "./lib/load-env.mjs"

loadEnvLocal()

const __dirname = dirname(fileURLToPath(import.meta.url))
const museumRoot = join(__dirname, "..")
const galleryRoot = join(museumRoot, "../gallery")
const sourcePath = join(museumRoot, "src/data/hoaHakananai.en.json")

const args = process.argv.slice(2)
const dryRun = args.includes("--dry-run")
const onlyLang = args.includes("--lang") ? args[args.indexOf("--lang") + 1]?.toUpperCase() : null

const apiKey = process.env.DEEPL_API_KEY
const apiUrl = process.env.DEEPL_API_URL ?? "https://api-free.deepl.com"

const TARGETS = [
  { code: "FR", exportName: "HOA_HAKANANAI_FR", fileName: "hoaHakananai.fr.ts" },
  { code: "JA", exportName: "HOA_HAKANANAI_JA", fileName: "hoaHakananai.ja.ts" },
]

function flattenCopy(copy) {
  const jobs = []
  const keys = []

  const push = (key, value) => {
    if (!value) return
    keys.push(key)
    jobs.push(value)
  }

  push("subtitle", copy.subtitle)
  push("bannerTop", copy.bannerTop)
  push("bannerBottom", copy.bannerBottom)
  push("imageAlt", copy.imageAlt)
  push("aboutHoaHeading", copy.aboutHoaHeading)
  for (let i = 0; i < copy.aboutHoaParagraphs.length; i++) {
    push(`aboutHoa:${i}`, copy.aboutHoaParagraphs[i])
  }
  push("aboutRapaNuiHeading", copy.aboutRapaNuiHeading)
  for (let i = 0; i < copy.aboutRapaNuiParagraphs.length; i++) {
    push(`aboutRapaNui:${i}`, copy.aboutRapaNuiParagraphs[i])
  }

  return { jobs, keys }
}

function rebuildCopy(source, keys, translated) {
  const map = Object.fromEntries(keys.map((key, index) => [key, translated[index]]))

  return {
    title: source.title,
    subtitle: map.subtitle ?? source.subtitle,
    bannerTop: map.bannerTop ?? source.bannerTop,
    bannerBottom: map.bannerBottom ?? source.bannerBottom,
    imageAlt: map.imageAlt ?? source.imageAlt,
    aboutHoaHeading: map.aboutHoaHeading ?? source.aboutHoaHeading,
    aboutHoaParagraphs: source.aboutHoaParagraphs.map((_, i) => map[`aboutHoa:${i}`]).filter(Boolean),
    aboutRapaNuiHeading: map.aboutRapaNuiHeading ?? source.aboutRapaNuiHeading,
    aboutRapaNuiParagraphs: source.aboutRapaNuiParagraphs
      .map((_, i) => map[`aboutRapaNui:${i}`])
      .filter(Boolean),
  }
}

function toTsFile(exportName, copy, langLabel) {
  return `import type { HoaHakananaiCopy } from "./hoaHakananai"

/** ${langLabel} copy — generated by scripts/translate-hoa.mjs (review before publishing). */
export const ${exportName}: HoaHakananaiCopy = ${JSON.stringify(copy, null, 2)}
`
}

if (!dryRun && !apiKey) {
  console.error("Set DEEPL_API_KEY in apps/museum/.env.local or apps/arkin_museum/.env.local")
  process.exit(1)
}

const source = JSON.parse(readFileSync(sourcePath, "utf8"))
const { jobs, keys } = flattenCopy(source)

const targets = onlyLang ? TARGETS.filter((t) => t.code === onlyLang) : TARGETS
if (targets.length === 0) {
  console.error(`Unknown --lang ${onlyLang}; use fr or ja`)
  process.exit(1)
}

console.log(`Translating Hoa Hakananaiʻa, ~${countCharacters(jobs)} characters → ${targets.map((t) => t.code).join(", ")}`)

if (dryRun) {
  process.exit(0)
}

try {
  const usage = await getDeepLUsage(apiKey, apiUrl)
  console.log(
    `DeepL usage: ${usage.character_count} / ${usage.character_limit} characters this billing period`,
  )
} catch (error) {
  console.warn(`Could not fetch usage: ${error.message}`)
}

for (const target of targets) {
  console.log(`translate → ${target.code}...`)
  const translated = await translateTexts(jobs, {
    apiKey,
    apiUrl,
    targetLang: target.code,
  })
  const copy = rebuildCopy(source, keys, translated)
  const contents = toTsFile(target.exportName, copy, target.code === "FR" ? "French" : "Japanese")

  for (const appRoot of [museumRoot, galleryRoot]) {
    const outPath = join(appRoot, "src/data", target.fileName)
    writeFileSync(outPath, contents)
    console.log(`  wrote ${outPath}`)
  }

  await new Promise((r) => setTimeout(r, 300))
}

console.log("\nReview French and Japanese copy, then commit the generated locale files.")
