#!/usr/bin/env node
/**
 * Translate artwork page copy via DeepL API.
 *
 * Usage:
 *   node scripts/translate-artwork.mjs --artwork two-fridas
 *   node scripts/translate-artwork.mjs --artwork hoa-hakananai --lang de
 *   node scripts/translate-artwork.mjs --artwork two-fridas --langs ar,de,es
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { ARTWORK_LOCALE_TARGETS } from "./artwork-locales.config.mjs"
import { ARTWORKS } from "./artworks.config.mjs"
import { countCharacters, getDeepLUsage, translateTexts } from "./lib/deepl.mjs"
import { loadEnvLocal } from "./lib/load-env.mjs"

loadEnvLocal()

const __dirname = dirname(fileURLToPath(import.meta.url))
const museumRoot = join(__dirname, "..")
const galleryRoot = join(museumRoot, "../gallery")

const args = process.argv.slice(2)
const dryRun = args.includes("--dry-run")
const artworkSlug = args.includes("--artwork") ? args[args.indexOf("--artwork") + 1] : null
const onlyLang = args.includes("--lang") ? args[args.indexOf("--lang") + 1] : null
const onlyLangs = args.includes("--langs") ? args[args.indexOf("--langs") + 1] : null

const apiKey = process.env.DEEPL_API_KEY
const apiUrl = process.env.DEEPL_API_URL ?? "https://api-free.deepl.com"

const artwork = artworkSlug ? ARTWORKS[artworkSlug] : null
if (!artwork) {
  console.error(`Pass --artwork ${Object.keys(ARTWORKS).join(" | ")}`)
  process.exit(1)
}

const appRoot = artwork.app === "gallery" ? galleryRoot : museumRoot
const sourcePath = join(appRoot, "src/data", `${artwork.dataBase}.en.json`)
const TARGETS = ARTWORK_LOCALE_TARGETS.map((entry) => ({
  code: entry.deepl,
  locale: entry.locale,
  exportName: `${artwork.exportPrefix}_${entry.locale.toUpperCase()}`,
  fileName: `${artwork.dataBase}.${entry.locale}.ts`,
  label: entry.label,
}))

function flattenCopy(copy, sections) {
  const jobs = []
  const keys = []

  const push = (key, value) => {
    if (!value) return
    keys.push(key)
    jobs.push(value)
  }

  push("subtitle", copy.subtitle)
  push("bannerTop", copy.bannerTop)
  push("bannerBottom", copy.bannerBottom)
  push("imageAlt", copy.imageAlt)

  for (const [sectionIndex, section] of sections.entries()) {
    push(`section:${sectionIndex}:heading`, copy[section.headingKey])
    const paragraphs = copy[section.paragraphsKey] ?? []
    for (let i = 0; i < paragraphs.length; i++) {
      push(`section:${sectionIndex}:${i}`, paragraphs[i])
    }
  }

  return { jobs, keys }
}

function rebuildCopy(source, keys, translated, sections) {
  const map = Object.fromEntries(keys.map((key, index) => [key, translated[index]]))
  const next = {
    title: source.title,
    subtitle: map.subtitle ?? source.subtitle,
    bannerTop: map.bannerTop ?? source.bannerTop,
    bannerBottom: map.bannerBottom ?? source.bannerBottom,
    imageAlt: map.imageAlt ?? source.imageAlt,
  }

  for (const [sectionIndex, section] of sections.entries()) {
    const sourceParagraphs = source[section.paragraphsKey] ?? []
    next[section.headingKey] = map[`section:${sectionIndex}:heading`] ?? source[section.headingKey]
    next[section.paragraphsKey] = sourceParagraphs
      .map((_, i) => map[`section:${sectionIndex}:${i}`])
      .filter(Boolean)
  }

  return next
}

function toTsFile(artworkConfig, exportName, copy, langLabel) {
  return `import type { ${artworkConfig.copyTypeName} } from "./${artworkConfig.dataBase}"

/** ${langLabel} copy — generated by scripts/translate-artwork.mjs (review before publishing). */
export const ${exportName}: ${artworkConfig.copyTypeName} = ${JSON.stringify(copy, null, 2)}
`
}

function filterTargets() {
  if (onlyLangs) {
    const wanted = new Set(onlyLangs.split(",").map((value) => value.trim().toLowerCase()))
    return TARGETS.filter(
      (target) => wanted.has(target.locale) || wanted.has(target.code.toLowerCase()),
    )
  }

  if (onlyLang) {
    const wanted = onlyLang.trim().toLowerCase()
    return TARGETS.filter(
      (target) => target.locale === wanted || target.code.toLowerCase() === wanted,
    )
  }

  return TARGETS
}

if (!dryRun && !apiKey) {
  console.error("Set DEEPL_API_KEY in apps/museum/.env.local or apps/arkin_museum/.env.local")
  process.exit(1)
}

const source = JSON.parse(readFileSync(sourcePath, "utf8"))
const { jobs, keys } = flattenCopy(source, artwork.sections)
const targets = filterTargets()

if (targets.length === 0) {
  console.error(`Unknown language filter; use --lang de or --langs ar,de,es`)
  process.exit(1)
}

console.log(
  `Translating ${artwork.slug}, ~${countCharacters(jobs)} characters → ${targets.map((t) => t.code).join(", ")}`,
)

if (dryRun) {
  process.exit(0)
}

try {
  const usage = await getDeepLUsage(apiKey, apiUrl)
  console.log(
    `DeepL usage: ${usage.character_count} / ${usage.character_limit} characters this billing period`,
  )
} catch (error) {
  console.warn(`Could not fetch usage: ${error.message}`)
}

for (const target of targets) {
  console.log(`translate → ${target.code}...`)
  const translated = await translateTexts(jobs, {
    apiKey,
    apiUrl,
    targetLang: target.code,
  })
  const copy = rebuildCopy(source, keys, translated, artwork.sections)
  const contents = toTsFile(artwork, target.exportName, copy, target.label)
  const outPath = join(appRoot, "src/data", target.fileName)
  writeFileSync(outPath, contents)
  console.log(`  wrote ${outPath}`)

  await new Promise((r) => setTimeout(r, 300))
}

console.log("\nReview translated copy, then commit the generated locale files.")
