export const TRACKED_ARKIN_ARTWORKS = [
  { title: "The Secret", path: "/the-secret" },
  { title: "Large Clenched Right Hand", path: "/main-crispee-droite" },
  { title: "The Age of Bronze", path: "/age-of-bronze-small" },
  { title: "The Age of Bronze", path: "/age-of-bronze" },
  { title: "Danaïde", path: "/danaide" },
  { title: "I Am Beautiful", path: "/je-suis-belle" },
  { title: "Bust of Jean d'Aire", path: "/bust-of-jean-daire" },
  { title: "Seated Titan (from the Vase of the Titans)", path: "/seated-titan" },
  { title: "Titan IV (from the Vase of the Titans)", path: "/titan-iv" },
  { title: "The Abduction of Hippodamia", path: "/abduction-of-hippodamia" },
  { title: "The Minotaur (Faun and Nymph)", path: "/minotaur" },
  { title: "Bust of Camille Claudel Wearing a Bonnet", path: "/camille-claudel-bonnet" },
  { title: "Mask of Rose Beuret", path: "/mme-rodin" },
  { title: "Mask of Hanako, Study Type E", path: "/mask-of-hanako" },
  { title: "Head of Lust", path: "/head-of-lust" },
  { title: "Mask of the Man with the Broken Nose", path: "/mask-broken-nose" },
  { title: "Torso of the Great Shadow", path: "/torso-great-shadow" },
  { title: "Head of Jean de Fiennes", path: "/head-jean-de-fiennes" },
  { title: "Head of Pierre de Wissant", path: "/head-pierre-de-wiessant" },
  { title: "Head of Eustache de Saint-Pierre", path: "/head-eustache-de-saint-pierre" },
  { title: "Eve, small model", path: "/eve-small-model" },
  { title: "Meditation, or The Inner Voice", path: "/meditation" },
  { title: "Triumphant Youth", path: "/triumphant-youth" },
  { title: "Iris, Study with Head", path: "/iris-study-with-head" },
  { title: "The Falling Man", path: "/falling-man" },
  { title: "Monumental Torso", path: "/monumental-torso" },
  { title: "Eternal Spring, First State", path: "/eternal-spring-first-state" },
  { title: "The Kiss, 3rd Reduction", path: "/the-kiss-3rd-reduction" },
  { title: "Death of Adonis", path: "/death-of-adonis" },
  { title: "The Titans' Jardinière", path: "/jardiniere-of-the-titans" },
  { title: "Eternal Idol, Small Model", path: "/eternal-idol-small-model" },
] as const

export type TrackedArtwork = (typeof TRACKED_ARKIN_ARTWORKS)[number]
