/** NFC tag labels and artwork titles → canonical path (from rodinArtworks). */
export const TRACKED_ARKIN_NAME_TO_PATH = new Map<string, string>([
  ["/abduction-of-hippodamia", "/abduction-of-hippodamia"],
  ["/age-of-bronze", "/age-of-bronze"],
  ["/age-of-bronze-small", "/age-of-bronze-small"],
  ["/bust-of-jean-daire", "/bust-of-jean-daire"],
  ["/camille-claudel-bonnet", "/camille-claudel-bonnet"],
  ["/danaide", "/danaide"],
  ["/death-of-adonis", "/death-of-adonis"],
  ["/eternal-idol-small-model", "/eternal-idol-small-model"],
  ["/eternal-spring-first-state", "/eternal-spring-first-state"],
  ["/eve-small-model", "/eve-small-model"],
  ["/falling-man", "/falling-man"],
  ["/head-eustache-de-saint-pierre", "/head-eustache-de-saint-pierre"],
  ["/head-jean-de-fiennes", "/head-jean-de-fiennes"],
  ["/head-of-lust", "/head-of-lust"],
  ["/head-pierre-de-wiessant", "/head-pierre-de-wiessant"],
  ["/iris-study-with-head", "/iris-study-with-head"],
  ["/jardiniere-of-the-titans", "/jardiniere-of-the-titans"],
  ["/je-suis-belle", "/je-suis-belle"],
  ["/main-crispee-droite", "/main-crispee-droite"],
  ["/mask-broken-nose", "/mask-broken-nose"],
  ["/mask-of-hanako", "/mask-of-hanako"],
  ["/meditation", "/meditation"],
  ["/minotaur", "/minotaur"],
  ["/mme-rodin", "/mme-rodin"],
  ["/monumental-torso", "/monumental-torso"],
  ["/seated-titan", "/seated-titan"],
  ["/the-kiss-3rd-reduction", "/the-kiss-3rd-reduction"],
  ["/the-secret", "/the-secret"],
  ["/titan-iv", "/titan-iv"],
  ["/torso-great-shadow", "/torso-great-shadow"],
  ["/triumphant-youth", "/triumphant-youth"],
  ["abduction-of-hippodamia", "/abduction-of-hippodamia"],
  ["age-of-bronze", "/age-of-bronze"],
  ["age-of-bronze-small", "/age-of-bronze-small"],
  ["bust of camille claudel wearing a bonnet", "/camille-claudel-bonnet"],
  ["bust of jean d'aire", "/bust-of-jean-daire"],
  ["bust-of-jean-daire", "/bust-of-jean-daire"],
  ["buste de jean d'aire", "/bust-of-jean-daire"],
  ["buste de jean d'aire (bust of jean d'aire)", "/bust-of-jean-daire"],
  ["camille claudel au bonnet", "/camille-claudel-bonnet"],
  ["camille claudel au bonnet (bust of camille claudel wearing a bonnet)", "/camille-claudel-bonnet"],
  ["camille-claudel-bonnet", "/camille-claudel-bonnet"],
  ["danaide", "/danaide"],
  ["danaïde", "/danaide"],
  ["death of adonis", "/death-of-adonis"],
  ["death-of-adonis", "/death-of-adonis"],
  ["eternal idol, small model", "/eternal-idol-small-model"],
  ["eternal spring, first state", "/eternal-spring-first-state"],
  ["eternal-idol-small-model", "/eternal-idol-small-model"],
  ["eternal-spring-first-state", "/eternal-spring-first-state"],
  ["éternelle idole, petit modèle", "/eternal-idol-small-model"],
  ["éternelle idole, petit modèle (eternal idol, small model)", "/eternal-idol-small-model"],
  ["eve-small-model", "/eve-small-model"],
  ["ève, petit modèle", "/eve-small-model"],
  ["ève, petit modèle (eve, small model)", "/eve-small-model"],
  ["eve, small model", "/eve-small-model"],
  ["falling-man", "/falling-man"],
  ["grande torse de l'homme", "/monumental-torso"],
  ["grande torse de l'homme (monumental torso)", "/monumental-torso"],
  ["head of eustache de saint-pierre", "/head-eustache-de-saint-pierre"],
  ["head of jean de fiennes", "/head-jean-de-fiennes"],
  ["head of lust", "/head-of-lust"],
  ["head of pierre de wissant", "/head-pierre-de-wiessant"],
  ["head-eustache-de-saint-pierre", "/head-eustache-de-saint-pierre"],
  ["head-jean-de-fiennes", "/head-jean-de-fiennes"],
  ["head-of-lust", "/head-of-lust"],
  ["head-pierre-de-wiessant", "/head-pierre-de-wiessant"],
  ["i am beautiful", "/je-suis-belle"],
  ["iris-study-with-head", "/iris-study-with-head"],
  ["iris, étude avec tête", "/iris-study-with-head"],
  ["iris, étude avec tête (iris, study with head)", "/iris-study-with-head"],
  ["iris, study with head", "/iris-study-with-head"],
  ["jardinière aux titans", "/jardiniere-of-the-titans"],
  ["jardinière aux titans (the titans' jardinière)", "/jardiniere-of-the-titans"],
  ["jardiniere-of-the-titans", "/jardiniere-of-the-titans"],
  ["je suis belle", "/je-suis-belle"],
  ["je suis belle (i am beautiful)", "/je-suis-belle"],
  ["je-suis-belle", "/je-suis-belle"],
  ["l'âge d'airain", "/age-of-bronze"],
  ["l'âge d'airain (the age of bronze)", "/age-of-bronze"],
  ["l'âge d'airain, petit modèle, 2ème réduction", "/age-of-bronze-small"],
  ["l'âge d'airain, petit modèle, 2ème réduction (the age of bronze)", "/age-of-bronze-small"],
  ["l'enlèvement d'hippodamie", "/abduction-of-hippodamia"],
  ["l'enlèvement d'hippodamie (the abduction of hippodamia)", "/abduction-of-hippodamia"],
  ["l'éternel printemps, premier état", "/eternal-spring-first-state"],
  ["l'éternel printemps, premier état (eternal spring, first state)", "/eternal-spring-first-state"],
  ["l'homme qui tombe", "/falling-man"],
  ["l'homme qui tombe (the falling man)", "/falling-man"],
  ["la jeunesse triomphante", "/triumphant-youth"],
  ["la jeunesse triomphante (triumphant youth)", "/triumphant-youth"],
  ["la méditation", "/meditation"],
  ["la méditation (meditation, or the inner voice)", "/meditation"],
  ["large clenched right hand", "/main-crispee-droite"],
  ["le baiser, 3ème réduction", "/the-kiss-3rd-reduction"],
  ["le baiser, 3ème réduction (the kiss, 3rd reduction)", "/the-kiss-3rd-reduction"],
  ["le minotaure", "/minotaur"],
  ["le minotaure (the minotaur (faun and nymph))", "/minotaur"],
  ["le secret", "/the-secret"],
  ["le secret (the secret)", "/the-secret"],
  ["main crispée droite, grand modèle", "/main-crispee-droite"],
  ["main crispée droite, grand modèle (large clenched right hand)", "/main-crispee-droite"],
  ["main-crispee-droite", "/main-crispee-droite"],
  ["mask of hanako, study type e", "/mask-of-hanako"],
  ["mask of rose beuret", "/mme-rodin"],
  ["mask of the man with the broken nose", "/mask-broken-nose"],
  ["mask-broken-nose", "/mask-broken-nose"],
  ["mask-of-hanako", "/mask-of-hanako"],
  ["masque d'hanako, étude type e", "/mask-of-hanako"],
  ["masque d'hanako, étude type e (mask of hanako, study type e)", "/mask-of-hanako"],
  ["masque de l'homme au nez cassé", "/mask-broken-nose"],
  ["masque de l'homme au nez cassé (mask of the man with the broken nose)", "/mask-broken-nose"],
  ["meditation", "/meditation"],
  ["meditation, or the inner voice", "/meditation"],
  ["minotaur", "/minotaur"],
  ["mme rodin", "/mme-rodin"],
  ["mme rodin (mask of rose beuret)", "/mme-rodin"],
  ["mme-rodin", "/mme-rodin"],
  ["monumental torso", "/monumental-torso"],
  ["monumental-torso", "/monumental-torso"],
  ["mort d'adonis", "/death-of-adonis"],
  ["mort d'adonis (death of adonis)", "/death-of-adonis"],
  ["seated titan (from the vase of the titans)", "/seated-titan"],
  ["seated-titan", "/seated-titan"],
  ["tête d'eustache de saint pierre", "/head-eustache-de-saint-pierre"],
  ["tête d'eustache de saint pierre (head of eustache de saint-pierre)", "/head-eustache-de-saint-pierre"],
  ["tête de jean de fiennes", "/head-jean-de-fiennes"],
  ["tête de jean de fiennes (head of jean de fiennes)", "/head-jean-de-fiennes"],
  ["tête de la luxure", "/head-of-lust"],
  ["tête de la luxure (head of lust)", "/head-of-lust"],
  ["tête de pierre de wiessant", "/head-pierre-de-wiessant"],
  ["tête de pierre de wiessant (head of pierre de wissant)", "/head-pierre-de-wiessant"],
  ["the abduction of hippodamia", "/abduction-of-hippodamia"],
  ["the age of bronze", "/age-of-bronze"],
  ["the falling man", "/falling-man"],
  ["the kiss, 3rd reduction", "/the-kiss-3rd-reduction"],
  ["the minotaur (faun and nymph)", "/minotaur"],
  ["the secret", "/the-secret"],
  ["the titans' jardinière", "/jardiniere-of-the-titans"],
  ["the-kiss-3rd-reduction", "/the-kiss-3rd-reduction"],
  ["the-secret", "/the-secret"],
  ["titan assis", "/seated-titan"],
  ["titan assis (seated titan (from the vase of the titans))", "/seated-titan"],
  ["titan iv", "/titan-iv"],
  ["titan iv (from the vase of the titans)", "/titan-iv"],
  ["titan iv (titan iv (from the vase of the titans))", "/titan-iv"],
  ["titan-iv", "/titan-iv"],
  ["torse de la grande ombre", "/torso-great-shadow"],
  ["torse de la grande ombre (torso of the great shadow)", "/torso-great-shadow"],
  ["torso of the great shadow", "/torso-great-shadow"],
  ["torso-great-shadow", "/torso-great-shadow"],
  ["triumphant youth", "/triumphant-youth"],
  ["triumphant-youth", "/triumphant-youth"],
])
